const en = {
  inbox: 'Inbox', discardPrompt: 'Discard the message you have not sent?', discard: 'Discard', keepWriting: 'Keep writing',
  title: 'Messages', care: 'Customer care', team: 'My team', support: 'Indice support', distributor: 'My consultant',
  subtitle: 'Conversations and support requests', newMessage: 'New conversation', search: 'Search', all: 'All',
  unassigned: 'Unassigned', mine: 'Assigned to me', OPEN: 'Waiting for care', WAITING_CUSTOMER: 'Waiting for customer', RESOLVED: 'Resolved',
  subject: 'Subject', body: 'Message', recipient: 'Colleague', topic: 'Reason', module: 'Related module (optional)',
  CONSULTATION: 'Question', FAILURE: 'Problem report', IMPROVEMENT: 'Suggestion',
  send: 'Send', sending: 'Sending…', sent: 'Sent', cancel: 'Cancel', back: 'Back', retry: 'Retry',
  empty: 'No conversations here yet.', choose: 'Choose a conversation or start a new one.',
  loading: 'Loading…', older: 'Earlier messages', more: 'Load more', internal: 'Internal note', public: 'Reply to customer',
  error: 'Could not complete the request. Your message is still here; retry when connected.',
  denied: 'This conversation is no longer available to your account.', conflict: 'This conversation changed. Review the latest information and retry.',
  limited: 'You are sending too quickly. Please wait a minute before retrying.',
  take: 'Assign to me', assignee: 'Responsible', transfer: 'Transfer to Indice', transferConfirm: 'Transfer this case and its public history to Indice support?',
  resolve: 'Resolve', reopen: 'Reopen', priority: 'Priority', LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', CRITICAL: 'Critical',
  audit: 'Activity', close: 'Close', legacy: 'Previous system tickets', queue: 'Customer conversations',
  overdue: 'Waiting over 24 h', firstResponse: 'Average first response (min)', resolution: 'Average resolution (min)',
  pendingNotifications: 'Pending notifications', asynchronous: 'We will reply here. Response times depend on service hours.',
  noPeople: 'No active colleagues match your search.', refresh: 'Refresh', language: 'Language',
};
type Copy = typeof en;
const es: Copy = {
  inbox: 'Bandeja', discardPrompt: '¿Descartar el mensaje que todavía no enviaste?', discard: 'Descartar', keepWriting: 'Seguir escribiendo',
  title: 'Mensajes', care: 'Centro de atención', team: 'Mi equipo', support: 'Soporte Índice', distributor: 'Mi consultor',
  subtitle: 'Conversaciones y solicitudes de atención', newMessage: 'Nueva conversación', search: 'Buscar', all: 'Todas',
  unassigned: 'Sin asignar', mine: 'Asignadas a mí', OPEN: 'Esperando atención', WAITING_CUSTOMER: 'Esperando al cliente', RESOLVED: 'Resueltas',
  subject: 'Asunto', body: 'Mensaje', recipient: 'Compañero', topic: 'Motivo', module: 'Módulo relacionado (opcional)',
  CONSULTATION: 'Consulta', FAILURE: 'Reportar un problema', IMPROVEMENT: 'Sugerencia',
  send: 'Enviar', sending: 'Enviando…', sent: 'Enviado', cancel: 'Cancelar', back: 'Volver', retry: 'Reintentar',
  empty: 'Todavía no hay conversaciones aquí.', choose: 'Selecciona una conversación o inicia una nueva.',
  loading: 'Cargando…', older: 'Mensajes anteriores', more: 'Cargar más', internal: 'Nota interna', public: 'Respuesta al cliente',
  error: 'No se pudo completar la solicitud. Tu mensaje sigue aquí; reintenta cuando tengas conexión.',
  denied: 'Esta conversación ya no está disponible para tu cuenta.', conflict: 'La conversación cambió. Revisa la información actualizada y reintenta.',
  limited: 'Estás enviando muy rápido. Espera un minuto antes de reintentar.',
  take: 'Asignarme', assignee: 'Responsable', transfer: 'Transferir a Índice', transferConfirm: '¿Transferir el caso y su historial público a Soporte Índice?',
  resolve: 'Resolver', reopen: 'Reabrir', priority: 'Prioridad', LOW: 'Baja', MEDIUM: 'Media', HIGH: 'Alta', CRITICAL: 'Crítica',
  audit: 'Actividad', close: 'Cerrar', legacy: 'Tickets de sistema anteriores', queue: 'Conversaciones de clientes',
  overdue: 'Sin respuesta por más de 24 h', firstResponse: 'Primera respuesta promedio (min)', resolution: 'Resolución promedio (min)',
  pendingNotifications: 'Avisos pendientes', asynchronous: 'Te responderemos aquí. El tiempo de respuesta depende del horario de atención.',
  noPeople: 'No hay compañeros activos que coincidan.', refresh: 'Actualizar', language: 'Idioma',
};
const fr: Copy = {
  inbox: 'Boîte de réception', discardPrompt: 'Abandonner le message non envoyé ?', discard: 'Abandonner', keepWriting: 'Continuer à écrire',
  title: 'Messages', care: 'Centre de service', team: 'Mon équipe', support: 'Assistance Indice', distributor: 'Mon conseiller',
  subtitle: 'Conversations et demandes de service', newMessage: 'Nouvelle conversation', search: 'Rechercher', all: 'Toutes',
  unassigned: 'Non attribuées', mine: 'Mes demandes', OPEN: 'En attente de réponse', WAITING_CUSTOMER: 'En attente du client', RESOLVED: 'Résolues',
  subject: 'Objet', body: 'Message', recipient: 'Collègue', topic: 'Motif', module: 'Module concerné (facultatif)',
  CONSULTATION: 'Question', FAILURE: 'Signaler un problème', IMPROVEMENT: 'Suggestion',
  send: 'Envoyer', sending: 'Envoi…', sent: 'Envoyé', cancel: 'Annuler', back: 'Retour', retry: 'Réessayer',
  empty: 'Aucune conversation pour le moment.', choose: 'Sélectionnez une conversation ou commencez-en une.',
  loading: 'Chargement…', older: 'Messages précédents', more: 'Afficher plus', internal: 'Note interne', public: 'Réponse au client',
  error: 'Impossible de terminer. Votre message est conservé; réessayez après la reconnexion.',
  denied: 'Cette conversation n’est plus accessible à votre compte.', conflict: 'La conversation a changé. Consultez les informations et réessayez.',
  limited: 'Envoi trop rapide. Patientez une minute avant de réessayer.',
  take: 'Me l’attribuer', assignee: 'Responsable', transfer: 'Transférer à Indice', transferConfirm: 'Transférer cette demande et son historique public à Indice?',
  resolve: 'Résoudre', reopen: 'Rouvrir', priority: 'Priorité', LOW: 'Faible', MEDIUM: 'Moyenne', HIGH: 'Élevée', CRITICAL: 'Critique',
  audit: 'Activité', close: 'Fermer', legacy: 'Anciens tickets système', queue: 'Conversations clients',
  overdue: 'En attente depuis plus de 24 h', firstResponse: 'Première réponse moyenne (min)', resolution: 'Résolution moyenne (min)',
  pendingNotifications: 'Notifications en attente', asynchronous: 'Nous répondrons ici selon les heures de service.',
  noPeople: 'Aucun collègue actif ne correspond.', refresh: 'Actualiser', language: 'Langue',
};
const pt: Copy = {
  inbox: 'Caixa de entrada', discardPrompt: 'Descartar a mensagem ainda não enviada?', discard: 'Descartar', keepWriting: 'Continuar escrevendo',
  title:'Mensagens',care:'Central de atendimento',team:'Minha equipe',support:'Suporte Índice',distributor:'Meu consultor',subtitle:'Conversas e solicitações de atendimento',
  newMessage:'Nova conversa',search:'Buscar',all:'Todas',unassigned:'Sem responsável',mine:'Atribuídas a mim',OPEN:'Aguardando atendimento',WAITING_CUSTOMER:'Aguardando cliente',RESOLVED:'Resolvidas',
  subject:'Assunto',body:'Mensagem',recipient:'Colega',topic:'Motivo',module:'Módulo relacionado (opcional)',CONSULTATION:'Consulta',FAILURE:'Relatar problema',IMPROVEMENT:'Sugestão',
  send:'Enviar',sending:'Enviando…',sent:'Enviada',cancel:'Cancelar',back:'Voltar',retry:'Tentar novamente',empty:'Nenhuma conversa ainda.',choose:'Selecione uma conversa ou inicie uma nova.',
  loading:'Carregando…',older:'Mensagens anteriores',more:'Carregar mais',internal:'Nota interna',public:'Resposta ao cliente',error:'Não foi possível concluir. Sua mensagem foi preservada; tente novamente quando houver conexão.',
  denied:'Esta conversa não está mais disponível para sua conta.',conflict:'A conversa mudou. Confira as informações atualizadas e tente novamente.',limited:'Envio muito rápido. Aguarde um minuto.',
  take:'Atribuir a mim',assignee:'Responsável',transfer:'Transferir para Índice',transferConfirm:'Transferir este caso e seu histórico público para o suporte Índice?',resolve:'Resolver',reopen:'Reabrir',priority:'Prioridade',
  LOW:'Baixa',MEDIUM:'Média',HIGH:'Alta',CRITICAL:'Crítica',audit:'Atividade',close:'Fechar',legacy:'Chamados de sistema anteriores',queue:'Conversas de clientes',overdue:'Aguardando há mais de 24 h',
  firstResponse:'Primeira resposta média (min)',resolution:'Resolução média (min)',pendingNotifications:'Avisos pendentes',asynchronous:'Responderemos aqui conforme o horário de atendimento.',noPeople:'Nenhum colega ativo encontrado.',refresh:'Atualizar',language:'Idioma',
};
const ko: Copy = {
  inbox: '받은 편지함', discardPrompt: '아직 보내지 않은 메시지를 삭제할까요?', discard: '삭제', keepWriting: '계속 작성',
  title:'메시지',care:'고객 지원 센터',team:'내 팀',support:'Indice 지원',distributor:'내 컨설턴트',subtitle:'대화 및 지원 요청',newMessage:'새 대화',search:'검색',all:'전체',
  unassigned:'미배정',mine:'내 담당 요청',OPEN:'지원 응답 대기',WAITING_CUSTOMER:'고객 응답 대기',RESOLVED:'해결됨',subject:'제목',body:'메시지',recipient:'동료',topic:'유형',module:'관련 모듈 (선택)',
  CONSULTATION:'문의',FAILURE:'문제 신고',IMPROVEMENT:'제안',send:'보내기',sending:'보내는 중…',sent:'전송됨',cancel:'취소',back:'뒤로',retry:'다시 시도',empty:'아직 대화가 없습니다.',choose:'대화를 선택하거나 새로 시작하세요.',
  loading:'불러오는 중…',older:'이전 메시지',more:'더 보기',internal:'내부 메모',public:'고객에게 답장',error:'요청을 완료하지 못했습니다. 메시지는 유지됩니다. 연결 후 다시 시도하세요.',
  denied:'이 계정으로 대화에 접근할 수 없습니다.',conflict:'대화가 변경되었습니다. 최신 정보를 확인한 후 다시 시도하세요.',limited:'전송이 너무 빠릅니다. 1분 후 다시 시도하세요.',
  take:'내게 배정',assignee:'담당자',transfer:'Indice로 전달',transferConfirm:'이 요청과 공개 대화 내역을 Indice 지원팀으로 전달할까요?',resolve:'해결 처리',reopen:'다시 열기',priority:'우선순위',
  LOW:'낮음',MEDIUM:'보통',HIGH:'높음',CRITICAL:'긴급',audit:'활동',close:'닫기',legacy:'기존 시스템 요청',queue:'고객 대화',overdue:'24시간 이상 대기',firstResponse:'평균 첫 응답 (분)',resolution:'평균 해결 시간 (분)',
  pendingNotifications:'대기 중인 알림',asynchronous:'지원 운영 시간에 따라 여기에서 답변드립니다.',noPeople:'검색에 일치하는 활성 동료가 없습니다.',refresh:'새로고침',language:'언어',
};
const zh: Copy = {
  inbox: '收件箱', discardPrompt: '放弃尚未发送的消息？', discard: '放弃', keepWriting: '继续编写',
  title:'消息',care:'客户服务中心',team:'我的团队',support:'Indice 支持',distributor:'我的顾问',subtitle:'对话和服务请求',newMessage:'新建对话',search:'搜索',all:'全部',unassigned:'未分配',mine:'分配给我',
  OPEN:'等待客服回复',WAITING_CUSTOMER:'等待客户回复',RESOLVED:'已解决',subject:'主题',body:'消息',recipient:'同事',topic:'原因',module:'相关模块（可选）',CONSULTATION:'咨询',FAILURE:'报告问题',IMPROVEMENT:'建议',
  send:'发送',sending:'发送中…',sent:'已发送',cancel:'取消',back:'返回',retry:'重试',empty:'暂无对话。',choose:'选择对话或开始新对话。',loading:'加载中…',older:'较早的消息',more:'加载更多',internal:'内部备注',public:'回复客户',
  error:'无法完成请求。消息已保留，请在连接恢复后重试。',denied:'此账户已无法访问该对话。',conflict:'对话已更新，请查看最新信息后重试。',limited:'发送过快，请等待一分钟再重试。',
  take:'分配给我',assignee:'负责人',transfer:'转交 Indice',transferConfirm:'将此请求及其公开对话记录转交给 Indice 支持团队？',resolve:'标记为已解决',reopen:'重新打开',priority:'优先级',LOW:'低',MEDIUM:'中',HIGH:'高',CRITICAL:'紧急',
  audit:'活动',close:'关闭',legacy:'原有系统工单',queue:'客户对话',overdue:'等待超过24小时',firstResponse:'平均首次回复（分钟）',resolution:'平均解决时间（分钟）',pendingNotifications:'待发送通知',
  asynchronous:'我们将在这里回复，回复时间取决于服务时间。',noPeople:'没有匹配的活跃同事。',refresh:'刷新',language:'语言',
};
export const messagingCopy = (locale: string): Copy => locale.startsWith('es') ? es : locale.startsWith('fr') ? fr
  : locale.startsWith('pt') ? pt : locale.startsWith('ko') ? ko : locale.startsWith('zh') ? zh : en;
export const messagingLabel = (copy: Copy, value: string) => copy[value as keyof Copy] ?? value;
