import type { SalesRecordsTranslations } from './types';

type CommissionWorkspaceCopy = SalesRecordsTranslations['commissionWorkspace'];

export const frCACommissionWorkspace: CommissionWorkspaceCopy = {
  loadError: 'Impossible de charger les paramètres de commission.', title: 'Commissions', subtitle: 'Définissez comment les commissions sont gagnées, révisez les montants générés et contrôlez leur transfert vers les primes et la paie.', generated: 'Commissions générées', cuts: 'Clôtures', generateCut: 'Générer une clôture', managePolicies: 'Gérer les politiques', sectionsLabel: 'Sections des commissions',
  common: { back: 'Retour', continue: 'Continuer', saving: 'Enregistrement…', delete: 'Supprimer', pause: 'Suspendre', selected: (count) => `${count} sélectionnés`, selectAll: 'Tout sélectionner', applyAll: 'Appliquer à tous', noMatches: 'Aucun résultat.', resultsPage: (count, page, pages) => `${count} résultats · page ${page} sur ${pages}`, selectFiltered: (count) => `Sélectionner les ${count} résultats filtrés`, calculating: 'Calcul…', unavailable: 'Non disponible' },
  rules: {
    steps: ['Participants et produits', 'Calcul', 'Révision'], policyHelp: 'Définissez clairement qui peut gagner la commission et quels produits la génèrent. Sans sélection, la politique s’applique à tous.', participants: 'Employés participants', allEmployees: 'Tous les employés', searchEmployees: 'Rechercher par nom ou courriel', categoryFilter: 'Filtrer le catalogue par catégorie', allCategories: 'Toutes les catégories', productsInCategory: (count, category) => `${count} produits dans ${category}`, applyCategory: 'Appliquer la catégorie entière', fullCategory: (name) => `Catégorie entière : ${name}`, commissionProducts: 'Produits qui génèrent une commission', allProducts: 'Tous les produits', searchProducts: 'Rechercher par nom, code ou catégorie', specificity: 'La règle la plus précise s’applique d’abord : vendeur + produit, produit, catégorie, vendeur, puis règle générale. La priorité ne départage que les règles de même portée.',
    typeHelpers: { fixed_per_product: 'Le montant est versé pour chaque unité vendue.', percentage_of_product: 'Le pourcentage s’applique au sous-total de chaque ligne.', fixed_per_sale: 'Le montant est versé une fois par vente.', percentage_of_sale: 'Le pourcentage s’applique au total de la vente.' },
    saleOrLineAmount: 'Montant de vente ou de ligne', quantity: 'Quantité', result: 'Résultat de la règle', participantsSummary: (count) => count ? `${count} employés` : 'Tous les employés', productsSummary: (count) => count ? `${count} produits sélectionnés` : 'Tous les produits', futureEffect: 'Les ventes futures de chaque employé sélectionné généreront automatiquement leur commission lorsqu’elles correspondent à cette politique.', validity: 'Validité', noStart: 'Aucun début', noEnd: 'Aucune fin', conflicts: (count, names) => `Correspond à ${count} règle(s) : ${names}. La priorité départagera.`, noConflicts: 'Aucun conflit trouvé pour la même portée et la même validité.', duplicate: 'Dupliquer comme inactive', deleteRule: 'Supprimer la règle', copiedSuffix: '(copie)',
    validation: { name: 'Donnez un nom à la règle.', positive: 'La valeur de commission doit être supérieure à zéro.', percentage: 'Le pourcentage ne peut pas dépasser 100 %.', dates: 'La date de fin ne peut pas précéder la date de début.', priority: 'La priorité doit être comprise entre 0 et 999.' }, saveError: 'Impossible d’enregistrer la règle. Vérifiez votre connexion et réessayez.', deleteError: 'Impossible de supprimer la règle.',
  },
  cutsPanel: {
    loadError: 'Impossible de charger l’historique des clôtures.', created: 'La clôture a été envoyée aux primes RH. Les applications seront disponibles pour la prochaine paie compatible.', filters: 'Filtres des clôtures', summary: (visible, total) => `${visible} clôtures sur ${total}`, search: 'Rechercher', searchPlaceholder: 'Référence de clôture', status: 'Statut', allStatuses: 'Tous les statuts', inHr: 'Dans les Ressources humaines', consumed: 'Consommée dans la paie', periodFrom: 'Période depuis', periodTo: 'Période jusqu’à', title: 'Clôtures de commissions', description: 'Historique envoyé aux primes et suivi de la consommation en paie.', count: (count) => `${count} clôtures`, columns: { code: 'Référence', period: 'Période', commissions: 'Commissions', employees: 'Employés', total: 'Total', status: 'Statut' }, applied: (applied, total) => `Dans RH · ${applied}/${total} appliquées`, noMatch: 'Aucune clôture ne correspond aux filtres.', empty: 'Aucune clôture de commissions n’a encore été générée.',
    modalTitle: 'Clôtures de commissions', modalDescription: 'Exécutez une clôture maintenant ou gérez les clôtures récurrentes depuis le serveur.', saveError: 'Impossible d’enregistrer la clôture.', scheduleLoadError: 'Impossible de charger l’automatisation actuelle.', pauseError: 'Impossible de suspendre l’automatisation.', removeError: 'Impossible de supprimer l’automatisation.', closeAndSend: 'Clôturer et envoyer aux RH', saveChanges: 'Enregistrer les modifications', createAutomation: 'Créer l’automatisation', manual: 'Clôture manuelle', manualDescription: 'Choisissez les dates, révisez la portée et exécutez-la immédiatement.', automatic: 'Clôture automatique', automaticDescription: 'Le serveur clôture chaque période et l’envoie automatiquement aux RH.', start: 'Début de clôture', end: 'Fin de clôture', amount: 'Montant', saved: 'Automatisations enregistrées', configured: (count) => `${count} configurées`, new: 'Nouvelle', active: 'Active', paused: 'Suspendue', none: 'Aucune automatisation. Configurez la première.', automationName: 'Nom de l’automatisation', automationPlaceholder: 'Ex. Commissions mensuelles des ventes', frequency: 'Fréquence de clôture', currentStatus: 'Statut actuel', notConfigured: 'Non configurée', nextRun: 'Prochaine exécution', emptyRun: 'Si une période ne contient aucune commission admissible, l’exécution est enregistrée et l’échéancier avance sans créer de clôture vide.', audit: 'Chaque clôture est figée et chaque prime ne peut être incluse qu’une seule fois dans la paie, avec sa référence conservée pour l’audit.', cadence: { weekly: { title: 'Hebdomadaire', detail: 'Chaque lundi clôture la période du lundi au dimanche précédent.' }, semimonthly: { title: 'Bimensuelle', detail: 'Le 16 et le 1er, clôture chaque moitié du mois.' }, monthly: { title: 'Mensuelle', detail: 'Le 1er, clôture le mois civil précédent.' } },
  },
};

export const ptBRCommissionWorkspace: CommissionWorkspaceCopy = {
  loadError: 'Não foi possível carregar as configurações de comissão.', title: 'Comissões', subtitle: 'Defina como as comissões são ganhas, revise os valores gerados e controle o envio para Incentivos e Folha.', generated: 'Comissões geradas', cuts: 'Fechamentos', generateCut: 'Gerar fechamento', managePolicies: 'Gerenciar políticas', sectionsLabel: 'Seções de comissões',
  common: { back: 'Voltar', continue: 'Continuar', saving: 'Salvando…', delete: 'Excluir', pause: 'Pausar', selected: (count) => `${count} selecionados`, selectAll: 'Selecionar todos', applyAll: 'Aplicar a todos', noMatches: 'Nenhum resultado.', resultsPage: (count, page, pages) => `${count} resultados · página ${page} de ${pages}`, selectFiltered: (count) => `Selecionar os ${count} resultados filtrados`, calculating: 'Calculando…', unavailable: 'Indisponível' },
  rules: {
    steps: ['Participantes e produtos', 'Cálculo', 'Revisão'], policyHelp: 'Defina claramente quem pode ganhar a comissão e quais produtos a geram. Sem seleção, a política se aplica a todos.', participants: 'Colaboradores participantes', allEmployees: 'Todos os colaboradores', searchEmployees: 'Buscar por nome ou e-mail', categoryFilter: 'Filtrar catálogo por categoria', allCategories: 'Todas as categorias', productsInCategory: (count, category) => `${count} produtos em ${category}`, applyCategory: 'Aplicar categoria completa', fullCategory: (name) => `Categoria completa: ${name}`, commissionProducts: 'Produtos que geram comissão', allProducts: 'Todos os produtos', searchProducts: 'Buscar por nome, código ou categoria', specificity: 'A regra mais específica é aplicada primeiro: vendedor + produto, produto, categoria, vendedor e depois regra geral. A prioridade só desempata regras do mesmo escopo.',
    typeHelpers: { fixed_per_product: 'O valor é pago por cada unidade vendida.', percentage_of_product: 'O percentual é aplicado ao subtotal de cada linha.', fixed_per_sale: 'O valor é pago uma vez por venda.', percentage_of_sale: 'O percentual é aplicado ao total da venda.' },
    saleOrLineAmount: 'Valor da venda ou da linha', quantity: 'Quantidade', result: 'Resultado da regra', participantsSummary: (count) => count ? `${count} colaboradores` : 'Todos os colaboradores', productsSummary: (count) => count ? `${count} produtos selecionados` : 'Todos os produtos', futureEffect: 'As vendas futuras de cada colaborador selecionado gerarão a comissão automaticamente quando corresponderem a esta política.', validity: 'Vigência', noStart: 'Sem início', noEnd: 'Sem fim', conflicts: (count, names) => `Coincide com ${count} regra(s): ${names}. A prioridade resolverá o empate.`, noConflicts: 'Nenhum conflito foi encontrado para o mesmo escopo e vigência.', duplicate: 'Duplicar como inativa', deleteRule: 'Excluir regra', copiedSuffix: '(cópia)',
    validation: { name: 'Dê um nome à regra.', positive: 'O valor da comissão deve ser maior que zero.', percentage: 'O percentual não pode exceder 100%.', dates: 'A data final não pode ser anterior à inicial.', priority: 'A prioridade deve ficar entre 0 e 999.' }, saveError: 'Não foi possível salvar a regra. Verifique a conexão e tente novamente.', deleteError: 'Não foi possível excluir a regra.',
  },
  cutsPanel: {
    loadError: 'Não foi possível carregar o histórico de fechamentos.', created: 'O fechamento foi enviado aos Incentivos de RH. Os lançamentos estarão disponíveis para a próxima folha compatível.', filters: 'Filtros de fechamento', summary: (visible, total) => `${visible} de ${total} fechamentos`, search: 'Buscar', searchPlaceholder: 'Referência do fechamento', status: 'Status', allStatuses: 'Todos os status', inHr: 'Em Recursos Humanos', consumed: 'Consumido na folha', periodFrom: 'Período desde', periodTo: 'Período até', title: 'Fechamentos de comissão', description: 'Histórico enviado aos Incentivos e acompanhamento do consumo na folha.', count: (count) => `${count} fechamentos`, columns: { code: 'Referência', period: 'Período', commissions: 'Comissões', employees: 'Colaboradores', total: 'Total', status: 'Status' }, applied: (applied, total) => `Em RH · ${applied}/${total} aplicadas`, noMatch: 'Nenhum fechamento corresponde aos filtros.', empty: 'Nenhum fechamento de comissão foi gerado.',
    modalTitle: 'Fechamentos de comissão', modalDescription: 'Execute um fechamento agora ou gerencie fechamentos recorrentes no servidor.', saveError: 'Não foi possível salvar o fechamento.', scheduleLoadError: 'Não foi possível carregar a automação atual.', pauseError: 'Não foi possível pausar a automação.', removeError: 'Não foi possível excluir a automação.', closeAndSend: 'Fechar e enviar ao RH', saveChanges: 'Salvar alterações', createAutomation: 'Criar automação', manual: 'Fechamento manual', manualDescription: 'Escolha as datas, revise o escopo e execute imediatamente.', automatic: 'Fechamento automático', automaticDescription: 'O servidor fecha cada período e envia automaticamente ao RH.', start: 'Início do fechamento', end: 'Fim do fechamento', amount: 'Valor', saved: 'Automações salvas', configured: (count) => `${count} configuradas`, new: 'Nova', active: 'Ativa', paused: 'Pausada', none: 'Ainda não há automações. Configure a primeira.', automationName: 'Nome da automação', automationPlaceholder: 'Ex.: Comissões mensais de vendas', frequency: 'Frequência de fechamento', currentStatus: 'Status atual', notConfigured: 'Não configurada', nextRun: 'Próxima execução', emptyRun: 'Se um período não tiver comissões elegíveis, a execução será registrada e a agenda avançará sem criar um fechamento vazio.', audit: 'Cada fechamento fica congelado e cada incentivo só pode entrar uma vez na Folha, preservando a referência para auditoria.', cadence: { weekly: { title: 'Semanal', detail: 'Toda segunda-feira fecha a segunda a domingo anteriores.' }, semimonthly: { title: 'Quinzenal', detail: 'Nos dias 16 e 1, fecha cada metade do mês.' }, monthly: { title: 'Mensal', detail: 'No dia 1, fecha o mês calendário anterior.' } },
  },
};

export const koCACommissionWorkspace: CommissionWorkspaceCopy = {
  loadError: '커미션 설정을 불러올 수 없습니다.', title: '커미션', subtitle: '커미션 적립 방식을 정의하고 생성 금액과 인센티브·급여 전달을 관리합니다.', generated: '생성된 커미션', cuts: '마감', generateCut: '마감 생성', managePolicies: '정책 관리', sectionsLabel: '커미션 섹션',
  common: { back: '뒤로', continue: '계속', saving: '저장 중…', delete: '삭제', pause: '일시 중지', selected: (count) => `${count}개 선택됨`, selectAll: '모두 선택', applyAll: '모두에게 적용', noMatches: '검색 결과가 없습니다.', resultsPage: (count, page, pages) => `${count}개 결과 · ${pages}페이지 중 ${page}`, selectFiltered: (count) => `필터 결과 ${count}개 모두 선택`, calculating: '계산 중…', unavailable: '사용할 수 없음' },
  rules: {
    steps: ['참여자와 제품', '계산', '검토'], policyHelp: '커미션을 받을 직원과 대상 제품을 명확히 정하세요. 선택하지 않으면 모두에게 적용됩니다.', participants: '참여 직원', allEmployees: '모든 직원', searchEmployees: '이름 또는 이메일 검색', categoryFilter: '카테고리별 카탈로그 필터', allCategories: '모든 카테고리', productsInCategory: (count, category) => `${category} 제품 ${count}개`, applyCategory: '전체 카테고리 적용', fullCategory: (name) => `전체 카테고리: ${name}`, commissionProducts: '커미션 대상 제품', allProducts: '모든 제품', searchProducts: '이름, 코드 또는 카테고리 검색', specificity: '가장 구체적인 규칙이 우선합니다: 판매자+제품, 제품, 카테고리, 판매자, 일반 규칙. 우선순위는 같은 범위에서만 동률을 결정합니다.',
    typeHelpers: { fixed_per_product: '판매된 단위마다 금액이 지급됩니다.', percentage_of_product: '각 품목 소계에 비율이 적용됩니다.', fixed_per_sale: '판매당 한 번 금액이 지급됩니다.', percentage_of_sale: '판매 총액에 비율이 적용됩니다.' },
    saleOrLineAmount: '판매 또는 품목 금액', quantity: '수량', result: '규칙 결과', participantsSummary: (count) => count ? `직원 ${count}명` : '모든 직원', productsSummary: (count) => count ? `제품 ${count}개 선택됨` : '모든 제품', futureEffect: '선택한 직원의 향후 판매가 이 정책과 일치하면 커미션이 자동으로 생성됩니다.', validity: '유효 기간', noStart: '시작일 없음', noEnd: '종료일 없음', conflicts: (count, names) => `${count}개 규칙과 일치: ${names}. 우선순위가 동률을 결정합니다.`, noConflicts: '같은 범위와 유효 기간에서 충돌이 없습니다.', duplicate: '비활성 상태로 복제', deleteRule: '규칙 삭제', copiedSuffix: '(사본)',
    validation: { name: '규칙 이름을 입력하세요.', positive: '커미션 값은 0보다 커야 합니다.', percentage: '비율은 100%를 초과할 수 없습니다.', dates: '종료일은 시작일보다 빠를 수 없습니다.', priority: '우선순위는 0에서 999 사이여야 합니다.' }, saveError: '규칙을 저장할 수 없습니다. 연결을 확인하고 다시 시도하세요.', deleteError: '규칙을 삭제할 수 없습니다.',
  },
  cutsPanel: {
    loadError: '마감 기록을 불러올 수 없습니다.', created: '마감이 인사 인센티브로 전송되었습니다. 다음 호환 급여에서 사용할 수 있습니다.', filters: '마감 필터', summary: (visible, total) => `마감 ${total}개 중 ${visible}개`, search: '검색', searchPlaceholder: '마감 참조', status: '상태', allStatuses: '모든 상태', inHr: '인사에 있음', consumed: '급여에서 사용됨', periodFrom: '기간 시작', periodTo: '기간 종료', title: '커미션 마감', description: '인센티브로 전송된 기록과 급여 사용 현황입니다.', count: (count) => `마감 ${count}개`, columns: { code: '참조', period: '기간', commissions: '커미션', employees: '직원', total: '합계', status: '상태' }, applied: (applied, total) => `인사 · ${applied}/${total} 적용`, noMatch: '필터와 일치하는 마감이 없습니다.', empty: '아직 생성된 커미션 마감이 없습니다.',
    modalTitle: '커미션 마감', modalDescription: '지금 마감을 실행하거나 서버에서 반복 마감을 관리하세요.', saveError: '마감을 저장할 수 없습니다.', scheduleLoadError: '현재 자동화를 불러올 수 없습니다.', pauseError: '자동화를 일시 중지할 수 없습니다.', removeError: '자동화를 삭제할 수 없습니다.', closeAndSend: '마감 후 인사로 전송', saveChanges: '변경 사항 저장', createAutomation: '자동화 생성', manual: '수동 마감', manualDescription: '날짜와 범위를 검토한 후 즉시 실행합니다.', automatic: '자동 마감', automaticDescription: '서버가 각 기간을 마감하고 인사로 자동 전송합니다.', start: '마감 시작', end: '마감 종료', amount: '금액', saved: '저장된 자동화', configured: (count) => `${count}개 설정됨`, new: '새로 만들기', active: '활성', paused: '일시 중지됨', none: '자동화가 없습니다. 첫 자동화를 설정하세요.', automationName: '자동화 이름', automationPlaceholder: '예: 월간 판매 커미션', frequency: '마감 주기', currentStatus: '현재 상태', notConfigured: '설정되지 않음', nextRun: '다음 실행', emptyRun: '적격 커미션이 없는 기간은 실행 기록만 남기고 빈 마감을 만들지 않은 채 일정이 진행됩니다.', audit: '각 마감은 고정되며 인센티브는 급여에 한 번만 포함되어 감사 참조가 유지됩니다.', cadence: { weekly: { title: '매주', detail: '매주 월요일에 이전 월요일부터 일요일까지 마감합니다.' }, semimonthly: { title: '월 2회', detail: '16일과 1일에 각 반월을 마감합니다.' }, monthly: { title: '매월', detail: '매월 1일에 이전 달을 마감합니다.' } },
  },
};

export const zhCACommissionWorkspace: CommissionWorkspaceCopy = {
  loadError: '无法加载佣金设置。', title: '佣金', subtitle: '定义佣金赚取方式，审核生成金额，并管理向激励和工资的交接。', generated: '已生成佣金', cuts: '结算批次', generateCut: '生成结算批次', managePolicies: '管理政策', sectionsLabel: '佣金区段',
  common: { back: '返回', continue: '继续', saving: '正在保存…', delete: '删除', pause: '暂停', selected: (count) => `已选择 ${count} 项`, selectAll: '全选', applyAll: '应用于全部', noMatches: '没有匹配结果。', resultsPage: (count, page, pages) => `${count} 个结果 · 第 ${page}/${pages} 页`, selectFiltered: (count) => `选择全部 ${count} 个筛选结果`, calculating: '正在计算…', unavailable: '不可用' },
  rules: {
    steps: ['参与者与产品', '计算', '审核'], policyHelp: '明确谁可以赚取佣金及哪些产品产生佣金。未选择时，政策适用于所有人。', participants: '参与员工', allEmployees: '所有员工', searchEmployees: '按姓名或邮箱搜索', categoryFilter: '按类别筛选目录', allCategories: '所有类别', productsInCategory: (count, category) => `${category} 中有 ${count} 个产品`, applyCategory: '应用整个类别', fullCategory: (name) => `整个类别：${name}`, commissionProducts: '产生佣金的产品', allProducts: '所有产品', searchProducts: '按名称、代码或类别搜索', specificity: '优先应用更具体的规则：销售员+产品、产品、类别、销售员，最后是通用规则。优先级只解决相同范围内的冲突。',
    typeHelpers: { fixed_per_product: '每售出一件产品支付固定金额。', percentage_of_product: '百分比应用于每个明细小计。', fixed_per_sale: '每笔销售支付一次固定金额。', percentage_of_sale: '百分比应用于销售总额。' },
    saleOrLineAmount: '销售或明细金额', quantity: '数量', result: '规则结果', participantsSummary: (count) => count ? `${count} 名员工` : '所有员工', productsSummary: (count) => count ? `已选择 ${count} 个产品` : '所有产品', futureEffect: '所选员工的未来销售符合此政策时将自动生成佣金。', validity: '有效期', noStart: '无开始日期', noEnd: '无结束日期', conflicts: (count, names) => `与 ${count} 条规则匹配：${names}。将按优先级处理。`, noConflicts: '相同范围和有效期内没有发现冲突。', duplicate: '复制为停用状态', deleteRule: '删除规则', copiedSuffix: '（副本）',
    validation: { name: '请为规则命名。', positive: '佣金值必须大于零。', percentage: '百分比不能超过 100%。', dates: '结束日期不能早于开始日期。', priority: '优先级必须在 0 到 999 之间。' }, saveError: '无法保存规则。请检查连接后重试。', deleteError: '无法删除规则。',
  },
  cutsPanel: {
    loadError: '无法加载结算历史。', created: '结算批次已发送到人力资源激励，可用于下一次兼容工资结算。', filters: '结算筛选', summary: (visible, total) => `显示 ${visible}/${total} 个批次`, search: '搜索', searchPlaceholder: '结算批次编号', status: '状态', allStatuses: '所有状态', inHr: '已进入人力资源', consumed: '已用于工资', periodFrom: '期间从', periodTo: '期间至', title: '佣金结算批次', description: '已发送到激励的历史记录及工资使用跟踪。', count: (count) => `${count} 个批次`, columns: { code: '编号', period: '期间', commissions: '佣金', employees: '员工', total: '总额', status: '状态' }, applied: (applied, total) => `人力资源 · 已应用 ${applied}/${total}`, noMatch: '没有符合筛选条件的批次。', empty: '尚未生成佣金结算批次。',
    modalTitle: '佣金结算', modalDescription: '立即运行结算，或在服务器中管理周期性结算。', saveError: '无法保存结算批次。', scheduleLoadError: '无法加载当前自动化。', pauseError: '无法暂停自动化。', removeError: '无法删除自动化。', closeAndSend: '结算并发送到人力资源', saveChanges: '保存更改', createAutomation: '创建自动化', manual: '手动结算', manualDescription: '选择日期、审核范围并立即运行。', automatic: '自动结算', automaticDescription: '服务器按期结算并自动发送到人力资源。', start: '结算开始', end: '结算结束', amount: '金额', saved: '已保存自动化', configured: (count) => `已配置 ${count} 个`, new: '新建', active: '启用', paused: '已暂停', none: '尚无自动化，请配置第一个。', automationName: '自动化名称', automationPlaceholder: '例如：每月销售佣金', frequency: '结算频率', currentStatus: '当前状态', notConfigured: '未配置', nextRun: '下次运行', emptyRun: '如果某期间没有符合条件的佣金，系统会记录执行并推进计划，但不会创建空批次。', audit: '每个批次都会冻结，每项激励只能计入工资一次，并保留引用以便审计。', cadence: { weekly: { title: '每周', detail: '每周一结算上一周周一至周日。' }, semimonthly: { title: '每半月', detail: '每月 16 日和 1 日分别结算半个月。' }, monthly: { title: '每月', detail: '每月 1 日结算上一个自然月。' } },
  },
};
