export type AccountingReportCopy = {
  title: string; subtitle: string;
  actions: Record<'synchronize' | 'syncing' | 'export' | 'print' | 'close' | 'reopen' | 'retry' | 'setup' | 'cancel' | 'confirm' | 'save' | 'columns' | 'previous' | 'next' | 'closeModal', string>;
  filters: Record<'title' | 'subtitle' | 'period' | 'from' | 'to' | 'unit' | 'business' | 'allUnits' | 'allBusinesses' | 'clear', string>;
  periods: Record<'current' | 'previous' | 'quarter' | 'year' | 'custom', string>;
  views: Record<'aria' | 'overview' | 'statements' | 'trial' | 'quality', string>;
  common: Record<'concept' | 'framework' | 'currency' | 'status' | 'severity' | 'finding' | 'detail', string>;
  modules: Record<string, string>; accountTypes: Record<string, string>; readiness: Record<string, string>;
  workflow: Record<string, string>;
  statement: Record<'current' | 'comparative' | 'variance' | 'consistent' | 'inconsistent' | 'openDetail', string>;
  trial: Record<string, string>; quality: Record<string, string>; metrics: Record<string, string>;
  overview: Record<string, string>; bridge: Record<string, string>; insightCodes: Record<string, string>;
  actionCodes: Record<string, string>; drilldown: Record<string, string>; modals: Record<string, string>;
  setup: Record<string, string>; messages: Record<string, string>;
};

const es: AccountingReportCopy = {
  title: 'Centro de estados financieros', subtitle: 'Del dato operativo al cierre: evidencia auditable, comparativos y control contable.',
  actions: { synchronize: 'Sincronizar', syncing: 'Sincronizando', export: 'Exportar', print: 'Imprimir', close: 'Cerrar periodo', reopen: 'Reabrir periodo', retry: 'Reintentar', setup: 'Preparar motor contable', cancel: 'Cancelar', confirm: 'Confirmar cierre', save: 'Reabrir periodo', columns: 'Columnas', previous: 'Anterior', next: 'Siguiente', closeModal: 'Cerrar' },
  filters: { title: 'Alcance del reporte', subtitle: 'El mismo periodo y alcance se aplica a todas las vistas.', period: 'Periodo', from: 'Desde', to: 'Hasta', unit: 'Unidad', business: 'Negocio', allUnits: 'Todas las unidades', allBusinesses: 'Todos los negocios', clear: 'Limpiar filtros' },
  periods: { current: 'Mes actual', previous: 'Mes anterior', quarter: 'Trimestre actual', year: 'Año actual', custom: 'Personalizado' },
  views: { aria: 'Vistas de estados financieros', overview: 'Pulso financiero', statements: 'Estados', trial: 'Balanza', quality: 'Cierre y calidad' },
  common: { concept: 'Concepto', framework: 'Marco', currency: 'Moneda', status: 'Estado', severity: 'Severidad', finding: 'Hallazgo', detail: 'Detalle' },
  modules: { sales: 'Ventas', expenses: 'Gastos', receivables: 'Cuentas por cobrar', payroll: 'Nómina', ledger: 'Mayor contable', inventory: 'Inventario' },
  accountTypes: { ASSET: 'Activo', LIABILITY: 'Pasivo', EQUITY: 'Patrimonio', REVENUE: 'Ingreso', EXPENSE: 'Gasto', OCI: 'Otro resultado integral' },
  readiness: { PRELIMINARY: 'Preliminar', READY: 'Listo para revisión', CLOSED: 'Periodo cerrado', coverage: 'Cobertura contable', entries: 'Asientos publicados', pending: 'Fuentes pendientes', blocking: 'Bloqueos' },
  workflow: { synchronize: '1. Sincroniza', reconcile: '2. Concilia', review: '3. Revisa', close: '4. Cierra', source: 'Trae operaciones elegibles', balance: 'Comprueba mayor y auxiliares', compare: 'Lee estados y comparativos', protect: 'Protege el periodo' },
  statement: { current: 'Periodo actual', comparative: 'Comparativo', variance: 'Variación', consistent: 'Cuadra internamente', inconsistent: 'Requiere conciliación', openDetail: 'Abrir evidencia contable' },
  trial: { code: 'Cuenta', name: 'Nombre', type: 'Tipo', debit: 'Débito', credit: 'Crédito', balance: 'Saldo', journals: 'Asientos', empty: 'No hay movimientos contabilizados para este alcance.', search: 'Buscar cuenta', rowsPerPage: 'Filas por página', page: 'Página', of: 'de', openDetail: 'Abrir detalle contable', resize: 'Redimensionar columna', visibleColumns: 'Columnas visibles' },
  quality: { title: 'Control antes de decidir', subtitle: 'Los bloqueos impiden declarar las cifras como definitivas.', affected: 'registros afectados', action: 'Siguiente acción', noFindings: 'No hay hallazgos bloqueantes en este periodo.', sources: 'Cobertura por módulo' },
  metrics: { REVENUE: 'Ingresos', GROSS_PROFIT: 'Utilidad bruta', OPERATING_PROFIT: 'Utilidad operativa', NET_PROFIT: 'Utilidad neta', NET_MARGIN: 'Margen neto', CLOSING_CASH: 'Efectivo al cierre', WORKING_CAPITAL: 'Capital de trabajo', CURRENT_RATIO: 'Razón corriente', ACCOUNTING_COVERAGE: 'Cobertura contable', revenue: 'Ingresos', grossProfit: 'Utilidad bruta', operatingProfit: 'Utilidad operativa', netProfit: 'Utilidad neta', assets: 'Activos', liabilities: 'Pasivos', equity: 'Patrimonio', cash: 'Cambio en efectivo' },
  overview: { title: 'Pulso financiero', subtitle: 'Lectura ejecutiva del periodo, comparativo y evidencia contable.', comparative: 'vs. periodo comparable', unavailable: 'No disponible', targetNotConfigured: 'Meta no configurada', profitBridge: 'Puente de utilidad', profitBridgeHelp: 'Explica cómo los ingresos se convierten en utilidad neta.', cashBridge: 'Puente de efectivo', cashBridgeHelp: 'Conecta el efectivo inicial con el saldo final del periodo.', trend: 'Tendencia de 12 meses', trendHelp: 'Compara ingresos, utilidad operativa y utilidad neta.', organization: 'Comparación por unidad', organizationHelp: 'Muestra contribución y resultado por unidad con evidencia dimensionada.', noOrganization: 'No hay asientos dimensionados por unidad para este alcance.', insights: 'Lecturas ejecutivas', insightsHelp: 'Señales deterministas; no sustituyen metas ni juicio profesional.' },
  bridge: { REVENUE: 'Ingresos', COST_OF_SALES: 'Costo de ventas', OPERATING_EXPENSES: 'Gastos operativos', OTHER_INCOME: 'Otros ingresos', FINANCE_EXPENSE: 'Costos financieros', INCOME_TAX: 'Impuesto', NET_PROFIT: 'Utilidad neta', OPENING_CASH: 'Efectivo inicial', OPERATING_CASH: 'Operación', INVESTING_CASH: 'Inversión', FINANCING_CASH: 'Financiamiento', CLOSING_CASH: 'Efectivo final' },
  insightCodes: { ACCOUNTING_BLOCKERS: 'El periodo conserva bloqueos contables', NEGATIVE_WORKING_CAPITAL: 'El capital de trabajo es negativo', NEGATIVE_OPERATING_PROFIT: 'La operación genera pérdida', REVENUE_CONTRACTION: 'Los ingresos bajaron frente al comparativo', NO_AUTOMATIC_EXCEPTION: 'No se detectaron excepciones automáticas' },
  actionCodes: { OPEN_CLOSE_QUALITY: 'Revisar cierre y calidad', OPEN_FINANCIAL_POSITION: 'Abrir situación financiera', OPEN_PROFIT_LOSS: 'Abrir estado de resultados', OPEN_REVENUE_DETAIL: 'Abrir detalle de ingresos', REVIEW_STATEMENTS: 'Revisar estados' },
  drilldown: { title: 'Evidencia contable', description: 'Asientos publicados que explican la cifra seleccionada.', debit: 'Débitos', credit: 'Créditos', net: 'Saldo natural', entries: 'Asientos', accounts: 'Cuentas', date: 'Fecha', journal: 'Asiento', source: 'Fuente', document: 'Documento', organization: 'Unidad / negocio', empty: 'No hay partidas publicadas para este concepto y alcance.', loadError: 'No fue posible cargar el detalle contable.' },
  modals: { closeTitle: 'Cerrar periodo contable', closeDescription: 'Confirma que revisaste los estados y que no existen hallazgos bloqueantes.', closeItem: 'Los asientos publicados quedarán protegidos contra nuevas contabilizaciones.', reopenTitle: 'Reabrir periodo contable', reopenDescription: 'La reapertura es auditable. Explica el motivo antes de continuar.', reason: 'Motivo de reapertura', reasonHelp: 'Entre 10 y 500 caracteres.', reasonRequired: 'Escribe un motivo de al menos 10 caracteres.', columnsTitle: 'Columnas de la balanza' },
  setup: { title: 'Activa el mayor contable', description: 'La primera sincronización crea el catálogo estándar, identifica operaciones elegibles y publica únicamente partidas completas.', note: 'No se generan cifras ficticias: faltantes de costo, moneda o clasificación se muestran como hallazgos.' },
  messages: { loadError: 'No fue posible cargar los estados financieros.', syncSuccess: 'Sincronización terminada.', closeSuccess: 'El periodo quedó cerrado.', reopenSuccess: 'El periodo quedó reabierto.' },
};

const en: AccountingReportCopy = {
  ...es,
  title: 'Financial statements centre', subtitle: 'From operational data to close: auditable evidence, comparatives, and accounting control.',
  actions: { synchronize: 'Synchronize', syncing: 'Synchronizing', export: 'Export', print: 'Print', close: 'Close period', reopen: 'Reopen period', retry: 'Retry', setup: 'Prepare accounting engine', cancel: 'Cancel', confirm: 'Confirm close', save: 'Reopen period', columns: 'Columns', previous: 'Previous', next: 'Next', closeModal: 'Close' },
  filters: { title: 'Report scope', subtitle: 'The same period and scope applies to every view.', period: 'Period', from: 'From', to: 'To', unit: 'Unit', business: 'Business', allUnits: 'All units', allBusinesses: 'All businesses', clear: 'Clear filters' },
  periods: { current: 'Current month', previous: 'Previous month', quarter: 'Current quarter', year: 'Current year', custom: 'Custom' },
  views: { aria: 'Financial reporting views', overview: 'Financial pulse', statements: 'Statements', trial: 'Trial balance', quality: 'Close and quality' },
  common: { concept: 'Concept', framework: 'Framework', currency: 'Currency', status: 'Status', severity: 'Severity', finding: 'Finding', detail: 'Detail' },
  modules: { sales: 'Sales', expenses: 'Expenses', receivables: 'Receivables', payroll: 'Payroll', ledger: 'Ledger', inventory: 'Inventory' },
  accountTypes: { ASSET: 'Asset', LIABILITY: 'Liability', EQUITY: 'Equity', REVENUE: 'Revenue', EXPENSE: 'Expense', OCI: 'Other comprehensive income' },
  readiness: { PRELIMINARY: 'Preliminary', READY: 'Ready for review', CLOSED: 'Closed period', coverage: 'Accounting coverage', entries: 'Posted journals', pending: 'Pending sources', blocking: 'Blocks' },
  workflow: { synchronize: '1. Synchronize', reconcile: '2. Reconcile', review: '3. Review', close: '4. Close', source: 'Bring eligible operations', balance: 'Check ledger and subledgers', compare: 'Read statements and comparatives', protect: 'Protect the period' },
  statement: { current: 'Current period', comparative: 'Comparative', variance: 'Variance', consistent: 'Internally consistent', inconsistent: 'Needs reconciliation', openDetail: 'Open accounting evidence' },
  trial: { code: 'Account', name: 'Name', type: 'Type', debit: 'Debit', credit: 'Credit', balance: 'Balance', journals: 'Journals', empty: 'No posted activity for this scope.', search: 'Search accounts', rowsPerPage: 'Rows per page', page: 'Page', of: 'of', openDetail: 'Open accounting detail', resize: 'Resize column', visibleColumns: 'Visible columns' },
  quality: { title: 'Control before deciding', subtitle: 'Blocking findings prevent the figures from being final.', affected: 'affected records', action: 'Next action', noFindings: 'There are no blocking findings for this period.', sources: 'Coverage by module' },
  metrics: { REVENUE: 'Revenue', GROSS_PROFIT: 'Gross profit', OPERATING_PROFIT: 'Operating profit', NET_PROFIT: 'Net profit', NET_MARGIN: 'Net margin', CLOSING_CASH: 'Closing cash', WORKING_CAPITAL: 'Working capital', CURRENT_RATIO: 'Current ratio', ACCOUNTING_COVERAGE: 'Accounting coverage', revenue: 'Revenue', grossProfit: 'Gross profit', operatingProfit: 'Operating profit', netProfit: 'Net profit', assets: 'Assets', liabilities: 'Liabilities', equity: 'Equity', cash: 'Cash change' },
  overview: { title: 'Financial pulse', subtitle: 'Executive reading of the period, comparative, and accounting evidence.', comparative: 'vs. comparable period', unavailable: 'Unavailable', targetNotConfigured: 'Target not configured', profitBridge: 'Profit bridge', profitBridgeHelp: 'Explains how revenue becomes net profit.', cashBridge: 'Cash bridge', cashBridgeHelp: 'Connects opening cash to the period-end balance.', trend: '12-month trend', trendHelp: 'Compares revenue, operating profit, and net profit.', organization: 'Unit comparison', organizationHelp: 'Shows contribution and result by unit when dimensional evidence exists.', noOrganization: 'There are no journals dimensioned by unit for this scope.', insights: 'Executive readings', insightsHelp: 'Deterministic signals; they do not replace targets or professional judgement.' },
  bridge: { REVENUE: 'Revenue', COST_OF_SALES: 'Cost of sales', OPERATING_EXPENSES: 'Operating expenses', OTHER_INCOME: 'Other income', FINANCE_EXPENSE: 'Finance costs', INCOME_TAX: 'Tax', NET_PROFIT: 'Net profit', OPENING_CASH: 'Opening cash', OPERATING_CASH: 'Operations', INVESTING_CASH: 'Investing', FINANCING_CASH: 'Financing', CLOSING_CASH: 'Closing cash' },
  insightCodes: { ACCOUNTING_BLOCKERS: 'The period still has accounting blocks', NEGATIVE_WORKING_CAPITAL: 'Working capital is negative', NEGATIVE_OPERATING_PROFIT: 'Operations are generating a loss', REVENUE_CONTRACTION: 'Revenue declined against the comparative', NO_AUTOMATIC_EXCEPTION: 'No automatic exceptions were detected' },
  actionCodes: { OPEN_CLOSE_QUALITY: 'Review close and quality', OPEN_FINANCIAL_POSITION: 'Open financial position', OPEN_PROFIT_LOSS: 'Open profit or loss', OPEN_REVENUE_DETAIL: 'Open revenue detail', REVIEW_STATEMENTS: 'Review statements' },
  drilldown: { title: 'Accounting evidence', description: 'Posted journals that explain the selected figure.', debit: 'Debits', credit: 'Credits', net: 'Natural balance', entries: 'Journals', accounts: 'Accounts', date: 'Date', journal: 'Journal', source: 'Source', document: 'Document', organization: 'Unit / business', empty: 'No posted lines exist for this concept and scope.', loadError: 'Accounting detail could not be loaded.' },
  modals: { closeTitle: 'Close accounting period', closeDescription: 'Confirm that the statements were reviewed and no blocking findings remain.', closeItem: 'Posted journals will be protected from new postings.', reopenTitle: 'Reopen accounting period', reopenDescription: 'Reopening is audited. Explain the reason before continuing.', reason: 'Reopening reason', reasonHelp: 'Between 10 and 500 characters.', reasonRequired: 'Enter a reason of at least 10 characters.', columnsTitle: 'Trial balance columns' },
  setup: { title: 'Activate the accounting ledger', description: 'The first synchronization creates the standard chart, discovers eligible operations, and posts only complete entries.', note: 'No fictional figures are generated: missing cost, currency, or classification appears as a finding.' },
  messages: { loadError: 'Financial statements could not be loaded.', syncSuccess: 'Synchronization completed.', closeSuccess: 'The period is closed.', reopenSuccess: 'The period was reopened.' },
};

const translations: Record<string, AccountingReportCopy> = {
  'es-MX': es, 'es-CO': es, 'en-US': en, 'en-CA': en,
  'fr-CA': { ...en, title: 'Centre des états financiers', subtitle: 'Des données opérationnelles à la clôture : preuves auditables, comparatifs et contrôle comptable.', views: { ...en.views, overview: 'Pouls financier', statements: 'États', trial: 'Balance de vérification', quality: 'Clôture et qualité' } },
  'pt-BR': { ...en, title: 'Central de demonstrações financeiras', subtitle: 'Dos dados operacionais ao fechamento: evidências auditáveis, comparativos e controle contábil.', views: { ...en.views, overview: 'Pulso financeiro', statements: 'Demonstrações', trial: 'Balancete', quality: 'Fechamento e qualidade' } },
  'ko-CA': { ...en, title: '재무제표 센터', subtitle: '운영 데이터부터 마감까지: 감사 가능한 근거, 비교 정보 및 회계 통제.', views: { ...en.views, overview: '재무 현황', statements: '재무제표', trial: '시산표', quality: '마감 및 품질' } },
  'zh-CA': { ...en, title: '财务报表中心', subtitle: '从运营数据到结账：可审计证据、比较信息与会计控制。', views: { ...en.views, overview: '财务脉搏', statements: '报表', trial: '试算表', quality: '结账与质量' } },
};

export function getAccountingReportCopy(locale: string): AccountingReportCopy {
  return translations[locale] ?? es;
}
