import {
  BudgetHealthStatus,
  BudgetStatus,
  ExpenseStatus,
  PaymentStatus,
  PettyCashStatus,
  PurchaseOrderStatus,
} from '../types/finance-status.types';
import type { FinanceTabAlignment, FinanceTabKey, FinanceUiTabMigration } from '../types/finance-tab-alignment.types';

const expenseStatuses = [
  ExpenseStatus.DRAFT,
  ExpenseStatus.PENDING_APPROVAL,
  ExpenseStatus.APPROVED,
  ExpenseStatus.PARTIALLY_PAID,
  ExpenseStatus.PAID,
  ExpenseStatus.CLOSED,
  ExpenseStatus.CANCELLED,
  ExpenseStatus.REJECTED,
] as const;

const budgetStatuses = [
  BudgetStatus.DRAFT,
  BudgetStatus.ACTIVE,
  BudgetStatus.CLOSED,
  BudgetStatus.ARCHIVED,
  BudgetHealthStatus.ON_TRACK,
  BudgetHealthStatus.WARNING,
  BudgetHealthStatus.EXCEEDED,
] as const;

const lifecycleStatuses = ['ACTIVE', 'INACTIVE'] as const;
const paymentStatuses = [PaymentStatus.UNPAID, PaymentStatus.PARTIALLY_PAID, PaymentStatus.PAID, PaymentStatus.OVERDUE] as const;
const pettyCashStatuses = [PettyCashStatus.ISSUED, PettyCashStatus.PARTIALLY_SETTLED, PettyCashStatus.SETTLED, PettyCashStatus.OVERDUE, PettyCashStatus.CANCELLED] as const;
const purchaseOrderStatuses = [
  PurchaseOrderStatus.DRAFT,
  PurchaseOrderStatus.PENDING_APPROVAL,
  PurchaseOrderStatus.APPROVED,
  PurchaseOrderStatus.ISSUED,
  PurchaseOrderStatus.PARTIALLY_RECEIVED,
  PurchaseOrderStatus.RECEIVED,
  PurchaseOrderStatus.CANCELLED,
  PurchaseOrderStatus.REJECTED,
  PurchaseOrderStatus.CLOSED,
] as const;

export const FINANCE_TAB_ALIGNMENT = {
  expenses: {
    tabKey: 'expenses',
    currentUiTab: 'expenses',
    tabName: 'Expenses',
    purpose: 'record_real_business_expenses',
    mainEntity: 'Expense',
    secondaryEntities: ['Provider', 'BudgetLine', 'PaymentAccount', 'AccountingAccount', 'FinanceAttachment'],
    sourceOfTruth: 'frontend_mock_until_api',
    defaultTableColumns: ['folio', 'provider', 'concept', 'accountingAccount', 'paymentAccount', 'total', 'paidAmount', 'balance', 'currency', 'expenseDate', 'dueDate', 'paymentDate', 'status', 'paymentStatus', 'attachments', 'actions'],
    optionalTableColumns: ['description', 'expenseType', 'budgetLine', 'purchaseOrder', 'subtotal', 'tax', 'closeDate', 'requestedBy', 'approvedBy', 'performedBy', 'auditStatus'],
    statusesUsed: [...expenseStatuses, ...paymentStatuses],
    createsExpense: true,
    consumesBudget: true,
    budgetEffect: 'actual_budget_consumption',
    affectsPaymentAccount: true,
    cashEffect: 'expense_payment',
    affectsCashFlow: true,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'direct_source',
    requiresApproval: true,
    requiresAttachment: true,
    backendReadinessLevel: 'contract_ready',
    frontendReadinessLevel: 'current_frontend_ready',
    isImplementedInCurrentUi: true,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'total', budgetSource: 'budgetLine', paymentAccountSource: 'paymentAccount', auditSource: 'entity_audit_fields', attachmentSource: 'attachments', rowNature: 'real_expense' },
    openQuestions: ['Which approved or paid statuses consume budget in the backend ledger?', 'Are receipts mandatory for every expense type or only for audited closure?'],
  },
  budgets: {
    tabKey: 'budgets',
    currentUiTab: 'budgets',
    tabName: 'Budgets',
    purpose: 'plan_and_control_budget',
    mainEntity: 'BudgetLine',
    secondaryEntities: ['Expense', 'PurchaseOrder', 'PettyCashMovement'],
    sourceOfTruth: 'frontend_mock_until_api',
    defaultTableColumns: ['name', 'period', 'plannedAmount', 'committedAmount', 'actualExpenseAmount', 'pettyCashIssuedAmount', 'pettyCashSettledAmount', 'availableAmount', 'healthStatus', 'status', 'actions'],
    optionalTableColumns: ['id', 'createdAt', 'updatedAt', 'rowNature'],
    statusesUsed: budgetStatuses,
    createsExpense: false,
    consumesBudget: false,
    budgetEffect: 'planned_budget',
    affectsPaymentAccount: false,
    cashEffect: 'none',
    affectsCashFlow: false,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'direct_source',
    requiresApproval: false,
    requiresAttachment: false,
    backendReadinessLevel: 'contract_ready',
    frontendReadinessLevel: 'current_frontend_ready',
    isImplementedInCurrentUi: true,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'plannedAmount', budgetSource: 'budget_line_rollup', paymentAccountSource: 'not_applicable', auditSource: 'entity_audit_fields', attachmentSource: 'not_applicable', rowNature: 'planned_budget' },
    openQuestions: ['Is BudgetLine or Budget the backend aggregate root?', 'What period granularity is required for monthly, quarterly, and project budgets?'],
  },
  providers: {
    tabKey: 'providers',
    currentUiTab: 'providers',
    tabName: 'Providers',
    purpose: 'manage_provider_catalog',
    mainEntity: 'Provider',
    secondaryEntities: ['Expense', 'PurchaseOrder', 'FinanceAttachment'],
    sourceOfTruth: 'frontend_mock_until_api',
    defaultTableColumns: ['name', 'taxId', 'email', 'phone', 'paymentTerms', 'status', 'totalSpent', 'openBalance', 'actions'],
    optionalTableColumns: ['id', 'attachments', 'createdAt', 'updatedAt'],
    statusesUsed: lifecycleStatuses,
    createsExpense: false,
    consumesBudget: false,
    budgetEffect: 'none',
    affectsPaymentAccount: false,
    cashEffect: 'indirect_reference',
    affectsCashFlow: false,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'indirect_dimension',
    requiresApproval: false,
    requiresAttachment: false,
    backendReadinessLevel: 'backend_contract_required',
    frontendReadinessLevel: 'current_frontend_ready',
    isImplementedInCurrentUi: true,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'totalSpent', budgetSource: 'not_applicable', paymentAccountSource: 'not_applicable', auditSource: 'entity_audit_fields', attachmentSource: 'attachments', rowNature: 'reference_catalog' },
    openQuestions: ['Do provider attachments belong to Provider or compliance documents?', 'Is taxId unique inside company scope?'],
  },
  paymentAccounts: {
    tabKey: 'paymentAccounts',
    currentUiTab: 'payment_accounts',
    tabName: 'Payment Accounts',
    purpose: 'manage_payment_accounts',
    mainEntity: 'PaymentAccount',
    secondaryEntities: ['Expense', 'PettyCashMovement', 'FinanceFundMovement'],
    sourceOfTruth: 'frontend_mock_until_api',
    defaultTableColumns: ['name', 'type', 'balance', 'currency', 'status', 'source', 'lastMovementDate', 'actions'],
    optionalTableColumns: ['id', 'createdAt', 'updatedAt'],
    statusesUsed: lifecycleStatuses,
    createsExpense: false,
    consumesBudget: false,
    budgetEffect: 'none',
    affectsPaymentAccount: true,
    cashEffect: 'payment_account_balance',
    affectsCashFlow: true,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'direct_source',
    requiresApproval: false,
    requiresAttachment: false,
    backendReadinessLevel: 'backend_contract_required',
    frontendReadinessLevel: 'current_frontend_ready',
    isImplementedInCurrentUi: true,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'balance', budgetSource: 'not_applicable', paymentAccountSource: 'payment_account_movements', auditSource: 'entity_audit_fields', attachmentSource: 'not_applicable', rowNature: 'payment_account_balance' },
    openQuestions: ['What reconciliation model is required for bank and credit card accounts?', 'Should account balances be ledger-derived or stored with periodic reconciliation?'],
  },
  accountingAccounts: {
    tabKey: 'accountingAccounts',
    currentUiTab: 'accounting',
    tabName: 'Accounting Accounts',
    purpose: 'manage_accounting_classification',
    mainEntity: 'AccountingAccount',
    secondaryEntities: ['Expense'],
    sourceOfTruth: 'frontend_mock_until_api',
    defaultTableColumns: ['code', 'name', 'group', 'status', 'actions'],
    optionalTableColumns: ['id', 'createdAt', 'updatedAt'],
    statusesUsed: lifecycleStatuses,
    createsExpense: false,
    consumesBudget: false,
    budgetEffect: 'none',
    affectsPaymentAccount: false,
    cashEffect: 'none',
    affectsCashFlow: false,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'indirect_dimension',
    requiresApproval: false,
    requiresAttachment: false,
    backendReadinessLevel: 'backend_contract_required',
    frontendReadinessLevel: 'current_frontend_ready',
    isImplementedInCurrentUi: true,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'not_applicable', budgetSource: 'not_applicable', paymentAccountSource: 'not_applicable', auditSource: 'entity_audit_fields', attachmentSource: 'not_applicable', rowNature: 'accounting_classification' },
    openQuestions: ['Is group a fixed backend enum or company-configurable catalog?', 'Must accounting accounts map to an external chart of accounts?'],
  },
  pettyCash: {
    tabKey: 'pettyCash',
    currentUiTab: 'petty_cash',
    tabName: 'Petty Cash',
    purpose: 'manage_petty_cash_issuance_and_settlement',
    mainEntity: 'PettyCashMovement',
    secondaryEntities: ['PaymentAccount', 'BudgetLine', 'Expense', 'FinanceFundMovement', 'FinanceAttachment'],
    sourceOfTruth: 'future_finance_api',
    defaultTableColumns: ['custodian', 'paymentAccount', 'issuedAmount', 'settledAmount', 'settlementBalance', 'currency', 'issuedDate', 'settlementDueDate', 'settledDate', 'status', 'attachments', 'actions'],
    optionalTableColumns: ['id', 'movementType', 'budgetLine', 'createdAt', 'updatedAt'],
    statusesUsed: pettyCashStatuses,
    createsExpense: true,
    consumesBudget: true,
    budgetEffect: 'temporary_issue_and_actual_settlement',
    affectsPaymentAccount: true,
    cashEffect: 'fund_movement',
    affectsCashFlow: true,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'direct_source',
    requiresApproval: true,
    requiresAttachment: true,
    backendReadinessLevel: 'backend_contract_required',
    frontendReadinessLevel: 'planned_not_implemented',
    isImplementedInCurrentUi: false,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'issuedAmount', budgetSource: 'budgetLine', paymentAccountSource: 'paymentAccount', auditSource: 'entity_audit_fields', attachmentSource: 'attachments', rowNature: 'fund_movement' },
    openQuestions: ['Should each settlement line create an Expense immediately or only after final settlement approval?', 'Should overdue status be calculated dynamically or persisted by a scheduled job?'],
  },
  purchaseOrders: {
    tabKey: 'purchaseOrders',
    currentUiTab: 'purchase_orders',
    tabName: 'Purchase Orders',
    purpose: 'commit_purchase_orders',
    mainEntity: 'PurchaseOrder',
    secondaryEntities: ['Provider', 'BudgetLine', 'Expense', 'FinanceAttachment'],
    sourceOfTruth: 'future_finance_api',
    defaultTableColumns: ['folio', 'provider', 'budgetLine', 'description', 'subtotal', 'tax', 'total', 'currency', 'status', 'requestedBy', 'approvedBy', 'issuedDate', 'actions'],
    optionalTableColumns: ['id', 'receivedDate', 'attachments', 'createdAt', 'updatedAt'],
    statusesUsed: purchaseOrderStatuses,
    createsExpense: false,
    consumesBudget: true,
    budgetEffect: 'committed_budget',
    affectsPaymentAccount: false,
    cashEffect: 'none',
    affectsCashFlow: false,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'direct_source',
    requiresApproval: true,
    requiresAttachment: false,
    backendReadinessLevel: 'backend_contract_required',
    frontendReadinessLevel: 'planned_not_implemented',
    isImplementedInCurrentUi: false,
    tableCoherence: { primaryEntityIdentifier: 'id', statusSource: 'status', monetarySource: 'total', budgetSource: 'budgetLine', paymentAccountSource: 'not_applicable', auditSource: 'entity_audit_fields', attachmentSource: 'attachments', rowNature: 'committed_order' },
    openQuestions: ['When does a purchase order convert or link to Expense?', 'Are receiving events required before expense creation?'],
  },
  financialOverview: {
    tabKey: 'financialOverview',
    currentUiTab: 'kpis',
    tabName: 'Financial Overview',
    purpose: 'report_financial_overview',
    mainEntity: 'FinancialOverview',
    secondaryEntities: ['Expense', 'BudgetLine', 'PaymentAccount', 'PettyCashMovement', 'PurchaseOrder', 'Provider', 'AccountingAccount'],
    sourceOfTruth: 'derived_finance_projection',
    defaultTableColumns: ['metric', 'period', 'plannedAmount', 'committedAmount', 'actualAmount', 'issuedBudgetAmount', 'settledBudgetAmount', 'cashFlowAmount', 'variance', 'status'],
    optionalTableColumns: ['provider', 'accountingAccount', 'paymentAccount', 'rowNature'],
    statusesUsed: ['DERIVED'],
    createsExpense: false,
    consumesBudget: false,
    budgetEffect: 'reporting_output',
    affectsPaymentAccount: false,
    cashEffect: 'derived_reporting',
    affectsCashFlow: false,
    affectsFinancialOverview: true,
    financialOverviewEffect: 'reporting_output',
    requiresApproval: false,
    requiresAttachment: false,
    backendReadinessLevel: 'contract_ready',
    frontendReadinessLevel: 'current_frontend_ready',
    isImplementedInCurrentUi: true,
    tableCoherence: { primaryEntityIdentifier: 'metric', statusSource: 'derived_metrics', monetarySource: 'derived_metrics', budgetSource: 'budget_line_rollup', paymentAccountSource: 'payment_account_movements', auditSource: 'not_applicable', attachmentSource: 'not_applicable', rowNature: 'reporting_output' },
    openQuestions: ['Is overview calculated synchronously from ledgers or stored as snapshots?', 'What are the exact definitions for committed, actual, issued, and settled totals?'],
  },
} satisfies Record<FinanceTabKey, FinanceTabAlignment>;

export const FINANCE_TAB_ALIGNMENT_LIST = Object.values(FINANCE_TAB_ALIGNMENT);

export const FINANCE_CURRENT_UI_TAB_MIGRATION = [
  { currentUiTab: 'expenses', targetTabKey: 'expenses', targetEntity: 'Expense', implementationState: 'current_frontend_ready', notes: 'Current Expenses tab maps directly to real expense records.' },
  { currentUiTab: 'budgets', targetTabKey: 'budgets', targetEntity: 'BudgetLine', implementationState: 'current_frontend_ready', notes: 'Current Budgets UI should evolve toward BudgetLine rollups.' },
  { currentUiTab: 'providers', targetTabKey: 'providers', targetEntity: 'Provider', implementationState: 'current_frontend_ready', notes: 'Current Providers tab remains a provider catalog.' },
  { currentUiTab: 'accounting', targetTabKey: 'accountingAccounts', targetEntity: 'AccountingAccount', implementationState: 'current_frontend_ready', notes: 'Current accounting tab maps to accounting classifications.' },
  { currentUiTab: 'payment_accounts', targetTabKey: 'paymentAccounts', targetEntity: 'PaymentAccount', implementationState: 'current_frontend_ready', notes: 'Current payment accounts tab maps to cash, bank, credit card, and petty cash accounts.' },
  { currentUiTab: 'kpis', targetTabKey: 'financialOverview', targetEntity: 'FinancialOverview', implementationState: 'current_frontend_ready', notes: 'Current KPIs tab becomes Financial Overview reporting.' },
  { currentUiTab: 'petty_cash', targetTabKey: 'pettyCash', targetEntity: 'PettyCashMovement', implementationState: 'planned_not_implemented', notes: 'Petty Cash is required before backend completeness but is not a tab in this module yet.' },
  { currentUiTab: 'purchase_orders', targetTabKey: 'purchaseOrders', targetEntity: 'PurchaseOrder', implementationState: 'planned_not_implemented', notes: 'Purchase Orders are required before backend completeness but are not a tab in this module yet.' },
] satisfies readonly FinanceUiTabMigration[];
