export const getNotificationCenterCopy = (locale: string) => {
  if (locale.toLowerCase().startsWith('es')) {
    return {
      title: 'Centro de notificaciones',
      subtitle: 'Prioriza alertas, tareas y comunicados que requieren atención.',
      inbox: 'Bandeja',
      settings: 'Configuración',
      unread: 'Sin leer',
      urgent: 'Urgentes',
      actionable: 'Por atender',
      total: 'Total',
      searchPlaceholder: 'Buscar notificaciones…',
      allModules: 'Todos los módulos',
      allPriorities: 'Todas las prioridades',
      highPriority: 'Alta',
      mediumPriority: 'Media',
      lowPriority: 'Baja',
      all: 'Todas',
      read: 'Leídas',
      markAllRead: 'Marcar todo leído',
      refresh: 'Actualizar',
      close: 'Cerrar',
      retry: 'Reintentar',
      emptyTitle: 'No hay notificaciones para estos filtros',
      emptyDescription: 'Cuando algo requiera atención aparecerá aquí.',
      loading: 'Cargando notificaciones...',
      showing: 'Mostrando',
      of: 'de',
      attentionInsight: 'Revisa primero las alertas urgentes y las tareas vencidas.',
      calmInsight: 'No hay alertas criticas pendientes en este momento.',
      open: 'Abrir',
      markRead: 'Leida',
      dismiss: 'Descartar',
      preferencesTitle: 'Preferencias por módulo',
      preferencesSubtitle: 'Elige qué señales debe mostrar Índice en tu centro operativo.',
      preferencesNotice: 'Vista preparada para preferencias reales; la persistencia se conectará cuando exista el endpoint.',
      channelSystem: 'Sistema',
      frequencyImmediate: 'Inmediata',
      enabled: 'Activo',
      disabled: 'Silenciado',
      backToInbox: 'Volver a la bandeja',
      previewTitle: 'Notificaciones',
      previewEmpty: 'No hay notificaciones.',
      previewAll: 'Abrir centro de notificaciones',
      newSingular: 'nueva',
      newPlural: 'nuevas',
      quietMode: 'Modo silencioso',
      quietModeDescription: 'Reduce senales de baja prioridad y conserva alertas criticas.',
      settingsSummary: 'Configuración local de la vista',
      settingsSummaryDescription: 'Estos controles preparan las preferencias por módulo.',
      noPersistence: 'Sin cambios de backend en esta fase.',
    };
  }

  return {
    title: 'Notification center',
    subtitle: 'Prioritize alerts, tasks, and announcements that need attention.',
    inbox: 'Inbox',
    settings: 'Settings',
    unread: 'Unread',
    urgent: 'Urgent',
    actionable: 'Actionable',
    total: 'Total',
    searchPlaceholder: 'Search notifications...',
    allModules: 'All modules',
    allPriorities: 'All priorities',
    highPriority: 'High',
    mediumPriority: 'Medium',
    lowPriority: 'Low',
    all: 'All',
    read: 'Read',
    markAllRead: 'Mark all read',
    refresh: 'Refresh',
    close: 'Close',
    retry: 'Retry',
    emptyTitle: 'No notifications match these filters',
    emptyDescription: 'Anything that needs attention will appear here.',
    loading: 'Loading notifications...',
    showing: 'Showing',
    of: 'of',
    attentionInsight: 'Review urgent alerts and overdue tasks first.',
    calmInsight: 'No critical alerts are pending right now.',
    open: 'Open',
    markRead: 'Read',
    dismiss: 'Dismiss',
    preferencesTitle: 'Preferences by module',
    preferencesSubtitle: 'Choose which signals Indice should show in your operational center.',
    preferencesNotice: 'Prepared for real preferences; persistence will connect when the endpoint exists.',
    channelSystem: 'System',
    frequencyImmediate: 'Immediate',
    enabled: 'Enabled',
    disabled: 'Muted',
    backToInbox: 'Back to inbox',
    previewTitle: 'Notifications',
    previewEmpty: 'No notifications.',
    previewAll: 'Open notification center',
    newSingular: 'new',
    newPlural: 'new',
    quietMode: 'Quiet mode',
    quietModeDescription: 'Reduce low-priority signals while keeping critical alerts visible.',
    settingsSummary: 'Local view configuration',
    settingsSummaryDescription: 'These controls prepare the module preference contract.',
    noPersistence: 'No backend changes in this phase.',
  };
};

export type NotificationCenterCopy = ReturnType<typeof getNotificationCenterCopy>;
