export type DocumentPrintCategory =
  | 'executive-report'
  | 'operational-report'
  | 'tab-print'
  | 'transaction-document'
  | 'legal-document'
  | 'thermal-document';

export type DocumentPrintModifier =
  | 'approval-required'
  | 'confidential'
  | 'customer-facing'
  | 'employee-facing'
  | 'fiscal'
  | 'internal'
  | 'legal'
  | 'multi-currency'
  | 'signature-required'
  | 'thermal'
  | 'white-label';

export type DocumentPageSize = 'a4' | 'letter' | '58mm' | '80mm';
export type DocumentPageOrientation = 'portrait' | 'landscape';

export interface DocumentPrintContract {
  category: DocumentPrintCategory;
  modifiers: DocumentPrintModifier[];
  orientation: DocumentPageOrientation;
  pageSize: DocumentPageSize;
  version: string;
}

export const documentPrintAttribution = 'Generated by Indice';
