import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { resolve } from 'node:path';
const { chromium } = await import(process.env.INDICE_PLAYWRIGHT_MODULE || 'playwright');
const server = await createServer({ root: resolve(import.meta.dirname, '..'), server: { host: '127.0.0.1', port: 5191, strictPort: true }, define: { 'import.meta.env.VITE_API_BASE_URL': '""' } });
let browser;
try {
  await server.listen();
  browser = await chromium.launch({ headless: true, ...(process.env.INDICE_CHROME_PATH ? { executablePath: process.env.INDICE_CHROME_PATH } : {}) });
  const page = await browser.newPage();
  const errors = [], saved = new Map();
  let identity = '9001:9001', failSave = false, failLoad = false, delayLoad = 0, delaySave = 0, writes = 0;
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', async route => {
    const request = route.request(), url = new URL(request.url());
    if (url.origin !== 'http://127.0.0.1:5191') return route.abort();
    if (!url.pathname.startsWith('/api/')) return route.continue();
    if (url.pathname.endsWith('/workspace-state/system/learning-mode')) {
      const scope = identity;
      if (request.method() === 'PUT') {
        if (failSave) { failSave = false; return route.fulfill({ status: 503, json: { message: 'Synthetic failure' } }); }
        await new Promise(resolve => setTimeout(resolve, delaySave));
        saved.set(scope, request.postDataJSON().state); writes++;
      } else {
        if (failLoad) return route.fulfill({ status: 503, json: { message: 'Synthetic failure' } });
        const snapshot = saved.get(scope) ?? {};
        await new Promise(resolve => setTimeout(resolve, delayLoad));
        return route.fulfill({ json: { state: snapshot, schemaVersion: 1 } });
      }
      return route.fulfill({ json: { state: saved.get(scope) ?? {}, schemaVersion: 1 } });
    }
    return route.fulfill({ status: 500, json: { message: `Unexpected ${url.pathname}` } });
  });
  await page.addInitScript(() => localStorage.setItem('frontend-indice-language', new URL(location.href).searchParams.get('language') ?? 'en-US'));
  const active = expected => page.waitForFunction(value => document.querySelector('[data-testid="active"]')?.textContent === String(value), expected);
  await page.goto('http://127.0.0.1:5191/tests/browser/preferences.html');
  await active(true);
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Guidance throughout Índice' }).locator('..').click();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await active(false);
  await page.evaluate(() => window.preferenceFixture.logout());
  await page.reload();
  await page.waitForTimeout(300);
  await active(false);
  assert.equal(saved.get(identity)?.active, false, 'disabled mode must survive logout/local storage cleanup');
  console.log('PASS: English settings, durable opt-out after logout');
  const openSettings = () => page.getByRole('button', { name: 'Settings', exact: true }).click();
  const toggleLearning = () => page.getByRole('checkbox', { name: 'Guidance throughout Índice' }).locator('..').click();
  const saveButton = () => page.getByRole('button', { name: 'Save changes', exact: true });
  const ready = () => page.waitForFunction(() => document.querySelector('[data-testid="ready"]')?.textContent === 'true');
  await openSettings(); await toggleLearning();
  failSave = true;
  await saveButton().click();
  await page.getByRole('alert').waitFor();
  await active(false);
  assert.equal(saved.get(identity).active, false);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.evaluate(() => window.preferenceFixture.preferences.setLearningStep(3));
  await page.waitForFunction(() => document.querySelector('[data-testid="step"]').textContent === '3');
  assert.equal(saved.get(identity).active, false, 'cancelled failed drafts must not leak into a later save');
  await openSettings(); await toggleLearning();
  failSave = true;
  await saveButton().click();
  await page.getByRole('alert').waitFor();
  await saveButton().click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await active(true);
  console.log('PASS: failed saves retain the draft, retry succeeds, cancellation cannot leak unsaved settings');
  await page.evaluate(() => {
    const p = window.preferenceFixture.preferences;
    p.setLearningStep(1); p.setLearningModeVisible(false); p.setLearningStep(v => v + 1);
  });
  await page.waitForFunction(() => document.querySelector('[data-testid="step"]').textContent === '2');
  assert.deepEqual(saved.get(identity), { version: 1, active: true, visible: false, step: 2 });
  failSave = true;
  await page.evaluate(() => window.preferenceFixture.preferences.setLearningStep(4));
  await page.waitForFunction(() => window.preferenceFixture.preferences.preferenceError === 'save');
  await page.evaluate(() => window.preferenceFixture.preferences.retryPreferences());
  await page.waitForFunction(() => document.querySelector('[data-testid="step"]').textContent === '4');
  console.log('PASS: sequential field edits and background save retries');
  saved.set('9002:9001', { version: 1, active: false, visible: true, step: 1 });
  identity = '9002:9001';
  await page.evaluate(() => window.preferenceFixture.switchUser(9002));
  await ready(); await active(false);
  assert.equal(await page.getByTestId('step').innerText(), '1');
  saved.set('9002:9002', { version: 1, active: true, visible: true, step: 2 });
  identity = '9002:9002';
  await page.evaluate(() => window.preferenceFixture.switchUser(9002, 9002));
  await ready(); await active(true);
  assert.equal(await page.getByTestId('step').innerText(), '2');
  delayLoad = 600; identity = '9003:9001';
  await page.evaluate(() => window.preferenceFixture.switchUser(9003));
  await page.waitForTimeout(100);
  identity = '9002:9001'; delayLoad = 0;
  await page.evaluate(() => window.preferenceFixture.switchUser(9002));
  await ready(); await active(false); await page.waitForTimeout(650); await active(false);
  assert.equal(saved.has('9003:9001'), false, 'obsolete loads must not seed preferences');
  console.log('PASS: user/company isolation and stale load protection');
  identity = '9001:9001'; failLoad = true;
  const beforeFailure = writes;
  await page.reload();
  await page.waitForFunction(() => window.preferenceFixture.preferences.preferenceError === 'load');
  await active(false); await openSettings();
  assert.equal(await saveButton().isDisabled(), true);
  assert.equal(writes, beforeFailure, 'a failed read must never overwrite the account with defaults');
  failLoad = false;
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await ready();
  assert.equal(await page.getByRole('checkbox', { name: 'Guidance throughout Índice' }).isChecked(), true);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  console.log('PASS: load failures block changes and preserve the account preference');
  const confirmed = saved.get(identity);
  saved.set(identity, { version: 2, active: false });
  const beforeInvalid = writes;
  await page.reload();
  await page.waitForFunction(() => window.preferenceFixture.preferences.preferenceError === 'load');
  assert.equal(writes, beforeInvalid, 'unsupported remote data must not be overwritten with a default opt-in');
  saved.set(identity, confirmed);
  await page.evaluate(() => window.preferenceFixture.preferences.retryPreferences());
  await ready();
  await page.getByRole('button', { name: 'Theme', exact: true }).click();
  await page.getByRole('button', { name: 'Split', exact: true }).click();
  const frame = page.frameLocator('iframe');
  await frame.getByRole('button', { name: 'Theme', exact: true }).waitFor();
  await frame.locator('html.dark').waitFor();
  await page.getByRole('button', { name: 'Theme', exact: true }).click();
  await frame.locator('html:not(.dark)').waitFor();
  await page.getByRole('button', { name: 'Theme', exact: true }).click();
  await frame.locator('html.dark').waitFor();
  await frame.getByRole('button', { name: 'Theme', exact: true }).click();
  await page.locator('html:not(.dark)').waitFor();
  for (let cycle = 0; cycle < 30; cycle++) {
    await page.getByRole('button', { name: 'Theme', exact: true }).click();
    await frame.locator(cycle % 2 === 0 ? 'html.dark' : 'html:not(.dark)').waitFor();
  }
  await openSettings(); await toggleLearning(); await saveButton().click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await frame.getByTestId('active').filter({ hasText: 'false' }).waitFor();
  await page.getByRole('button', { name: 'Split', exact: true }).click();
  await page.getByRole('button', { name: 'Guides', exact: true }).click();
  const expenses = page.getByTestId('expenses-guide');
  await expenses.getByRole('button', { name: 'Learn more', exact: true }).click();
  await expenses.getByRole('button', { name: 'Step 2, Budgets: To review' }).click();
  await expenses.getByRole('heading', { name: 'Budgets', exact: true }).waitFor();
  await expenses.getByRole('button', { name: 'I understand', exact: true }).click();
  assert.doesNotMatch(await expenses.innerText(), /Modo aprendiz|Presupuestos|Por revisar|Ir a las funciones/);
  const hr = page.getByTestId('hr-guide');
  await hr.getByRole('button', { name: 'Step 2, Attendance: To review' }).click();
  await hr.getByRole('button', { name: 'Learn more', exact: true }).click();
  await hr.getByRole('button', { name: 'Review attendance', exact: true }).waitFor();
  assert.doesNotMatch(await hr.innerText(), /Paso |Por revisar|Recorrido lógico/);
  assert.ok((await page.getByTestId('dashboard-guide').innerText()).includes('Session'));
  console.log('PASS: English module flow, HR area navigation, understood state and six-stage dashboard');
  await page.addInitScript(() => {
    const get = Storage.prototype.getItem, set = Storage.prototype.setItem;
    Storage.prototype.getItem = function(key) { if (key.startsWith('indice.app.learningMode.')) throw new DOMException('Blocked', 'SecurityError'); return get.call(this, key); };
    Storage.prototype.setItem = function(key, value) { if (key.startsWith('indice.app.learningMode.')) throw new DOMException('Blocked', 'SecurityError'); return set.call(this, key, value); };
  });
  await page.reload(); await ready(); await active(false);
  await openSettings(); await toggleLearning(); await saveButton().click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.reload(); await ready(); await active(true);
  await page.goto('http://127.0.0.1:5191/tests/browser/preferences.html?language=en-CA');
  await ready(); await openSettings();
  await page.getByRole('dialog', { name: 'Learning mode', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Guides', exact: true }).click();
  await page.getByTestId('expenses-guide').getByRole('button', { name: 'Step 2, Budgets: Understood' }).waitFor();
  console.log('PASS: Canadian English settings and guide navigation');
  const idleWrites = writes;
  await page.waitForTimeout(800);
  assert.equal(writes, idleWrites, 'idle panes must not keep saving');
  assert.deepEqual(errors, []);
  console.log('PASS: remote persistence without browser storage and no idle write loop');
  console.log('PASS: theme changes synchronize in both directions');
} finally { await browser?.close(); await server.close(); }
