import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { printModules, quotationFixture } from './helpers/quotation-print-fixtures.mjs';

const load = printModules();
const render = load('shared/print/standardDocumentHtml.ts');
const source = path => readFileSync(resolve(import.meta.dirname, '../src/app/BasicModules', path), 'utf8');

test('web document retains every row, native currency, scope, snapshot, signature and version', () => {
  const fixture = quotationFixture(125);
  fixture.metadata.push({ label: 'Activo histórico', value: 'Unidad vendida en 2025' });
  fixture.tables[0].rows.push(['USD aislado', '1', '20.00 USD', '20.00 USD']);
  fixture.sections[0].paragraphs.push('Texto extenso '.repeat(400));
  const html = render.buildStandardDocumentHtml(fixture);
  assert.equal((html.match(/<tr>/g) ?? []).length, 127);
  for (const text of ['galvanizado 125', '20.00 USD', '435.00 MXN', 'Unidad vendida en 2025', 'v1.0', 'Recibió', 'Texto extenso '.repeat(400)]) assert.ok(html.includes(text));
  assert.match(html, /<thead>/);
  assert.match(html, /scope="col" class="numeric"/);
});

test('all document content is escaped and active image schemes are rejected', () => {
  const fixture = quotationFixture();
  fixture.title = '<img src=x onerror=alert(1)>';
  fixture.metadata[0].value = '</dd><script>attack()</script>';
  fixture.logoUrl = 'javascript:alert(1)';
  const html = render.buildStandardDocumentHtml(fixture);
  assert.doesNotMatch(html, /<script>|onerror=alert\(1\)>|src="javascript:/);
  assert.match(html, /&lt;script&gt;/);
  assert.equal(render.safeDocumentImageUrl('data:text/html;base64,WA=='), '');
  assert.equal(render.safeDocumentImageUrl('data:image/svg+xml,<svg onload="attack()"/>'), '');
  assert.equal(render.safeDocumentImageUrl('data:image/png;base64,WA=='), 'data:image/png;base64,WA==');
});

test('empty and localized documents remain complete without invented issuer identity', () => {
  for (const locale of ['es-MX', 'es-CO', 'en-CA', 'en-US', 'fr-CA', 'pt-BR', 'ko-CA', 'zh-CA']) {
    const fixture = quotationFixture(0, locale);
    fixture.issuer = undefined;
    fixture.tables[0].emptyMessage = 'Sin registros / 空 / 없음';
    const html = render.buildStandardDocumentHtml(fixture);
    assert.match(html, /Sin registros \/ 空 \/ 없음/);
    assert.doesNotMatch(html, /document-identity">Indice/);
    assert.ok(load('shared/print/webPrintCopy.ts').getWebPrintCopy(locale).help);
  }
});

test('company-only documents use true gray tokens and preserve the colored logo boundary', () => {
  const fixture = quotationFixture();
  fixture.logoUrl = 'https://example.invalid/company-logo.png';
  const html = render.buildStandardDocumentHtml(fixture);
  assert.doesNotMatch(html, /Powered by|indiceapp\.com|Generated by Indice/);
  assert.match(html, /<img data-company-logo/);
  const theme = source('shared/print/quotationPrintTheme.ts');
  for (const [color] of theme.matchAll(/#[0-9a-f]{6}/gi)) assert.ok(color.slice(1, 3) === color.slice(3, 5) && color.slice(3, 5) === color.slice(5, 7), color);
  assert.match(theme, /break-inside: avoid-page/);
  assert.match(theme, /data-print-oversized/);
  const { grayscaleColor } = load('shared/print/documentGrayscale.ts');
  assert.equal(grayscaleColor('rgb(255, 0, 0)'), 'rgb(54, 54, 54)');
  assert.equal(grayscaleColor('rgba(255, 0, 0, 0.5)'), 'rgba(54, 54, 54, 0.5)');
  assert.equal(grayscaleColor('oklch(0.7 0.2 35)'), 'oklch(0.7 0 35)');
  assert.equal(grayscaleColor('none'), 'none');
});

test('print engine rejects blank documents and reports blocked popups without leaking the blob', () => {
  const failures = [], revoked = [], blobs = [];
  const engine = printModules({ './documentPrintFeedback': { notifyDocumentPrintFailure: (...args) => failures.push(args) } })('shared/print/documentHtmlPrintEngine.ts');
  const originalWindow = globalThis.window;
  const create = URL.createObjectURL, revoke = URL.revokeObjectURL;
  try {
    globalThis.window = { open: () => null };
    URL.createObjectURL = blob => { blobs.push(blob); return 'blob:fixture'; };
    URL.revokeObjectURL = url => revoked.push(url);
    assert.equal(engine.printDocumentHtml({ bodyHtml: ' ', documentTitle: 'Empty', locale: 'es-MX' }), false);
    assert.equal(blobs.length, 0);
    assert.equal(engine.printDocumentHtml({ bodyHtml: '<p>Contenido</p>', documentTitle: 'Report', locale: 'es-MX' }), false);
    assert.deepEqual(failures, [['es-MX', 'popup-blocked']]);
    assert.deepEqual(revoked, ['blob:fixture']);
    assert.equal(blobs[0].type, 'text/html;charset=utf-8');
  } finally { globalThis.window = originalWindow; URL.createObjectURL = create; URL.revokeObjectURL = revoke; }
});

test('reserved windows print once after font readiness, with thermal paper preserved', async () => {
  const engine = load('shared/print/documentHtmlPrintEngine.ts');
  const originalWindow = globalThis.window;
  const create = URL.createObjectURL, revoke = URL.revokeObjectURL;
  let listener, resolveFonts, count = 0, blob;
  const target = { closed: false, location: { href: 'about:blank', replace(url) { this.href = url; } }, document: { readyState: 'complete', images: [], fonts: { ready: new Promise(resolve => { resolveFonts = resolve; }) } }, addEventListener: (_, callback) => { listener = callback; }, focus() {}, print() { count++; } };
  try {
    globalThis.window = { open: () => { throw new Error('must reuse reserved window'); }, setInterval: () => 1, clearInterval() {}, setTimeout: () => 2 };
    URL.createObjectURL = value => { blob = value; return 'blob:thermal-fixture'; };
    URL.revokeObjectURL = () => {};
    assert.equal(engine.printDocumentHtml({ bodyHtml: '<p>Ticket</p>', documentTitle: 'Ticket', locale: 'es-MX', pageSize: '80mm', targetWindow: target }), true);
    const printing = listener();
    assert.equal(count, 0);
    resolveFonts(); await printing; await listener();
    assert.equal(count, 1);
    assert.match(await blob.text(), /size: 80mm auto/);
    assert.doesNotMatch(await blob.text(), /grid-template-columns: 1fr 1.4fr 1fr/);
  } finally { globalThis.window = originalWindow; URL.createObjectURL = create; URL.revokeObjectURL = revoke; }
});

test('IME opt-out remains explicit and binary quotation sharing remains available', () => {
  assert.match(source('Kpis/KPIs/KPIs.tsx'), /quotationStyle=\{activeView !== 'overview' && activeView !== 'sectors'\}/);
  assert.match(source('Kpis/components/AnalyticsDocumentPreviewModal.tsx'), /quotationStyle = false/);
  assert.match(source('Kpis/components/visualDocumentExport.ts'), /if \(quotationStyle\) return printDocumentHtml/);
  assert.doesNotMatch(source('Dashboard/BusinessProfile/BusinessDiagnosisPdf/businessDiagnosisPdf.tsx'), /quotationPrintTheme|standardDocumentHtml/);
  assert.match(source('Sales/Cotizacion/quotePdf.ts'), /export async function getQuotePdfBlob/);
  assert.match(source('Sales/Cotizacion/components/QuotePreviewModal.tsx'), /getQuotePdfBlob/);
  assert.match(source('shared/print/standardDocumentPdf.ts'), /return printStandardDocumentHtml\(definition\)/);
  assert.doesNotMatch(source('PointOfSale/Sale/components/TicketModal.tsx'), /La descarga PDF quedo preparada/);
});

test('selected HR acts open a single print job without losing folios, detail or signatures', () => {
  const jobs = [];
  const records = printModules({ '../../../shared/print/documentHtmlPrintEngine': { printDocumentHtml: input => { jobs.push(input); return true; } } })('HumanResources/Records/utils/records.pdf.ts');
  const copy = { pdfDocument: { title: 'Acta', followUp: 'Seguimiento', employeeSignature: 'Firma empleado', reportedBySignature: 'Firma responsable' },
    pdf: { recordNumber: id => `RH-${id}`, employee: 'Empleado', reportedBy: 'Reportó', eventDate: 'Fecha', type: 'Tipo', severity: 'Severidad', status: 'Estado', description: 'Descripción', actionsTaken: 'Acciones', witnesses: 'Testigos', attachments: 'Evidencias', notAvailable: '—' },
    types: { warning: 'Advertencia' }, severity: { low: 'Baja' }, status: { open: 'Abierto' } };
  const first = { id: '1', recordNumber: 'ACT-1', title: 'Primer acto', user: { name: 'Persona A', position: 'Puesto' }, reportedBy: { name: 'Responsable' }, eventDate: '2026-09-17T12:00:00Z', type: 'warning', severity: 'low', status: 'open', description: 'Hechos registrados', actionsTaken: 'Seguimiento registrado', witnesses: ['Testigo'], attachments: [{ name: 'Evidencia.pdf' }] };
  const second = { ...first, id: '2', recordNumber: 'ACT-2', title: 'Segundo acto' };
  const before = structuredClone([first, second]);
  assert.equal(records.printRecordsWeb([], copy, 'es-MX'), false);
  assert.equal(records.printRecordsWeb([first, second], copy, 'es-MX'), true);
  assert.equal(jobs.length, 1);
  assert.equal(jobs[0].pageSize, 'letter');
  assert.match(jobs[0].contentStyles, /break-before: page/);
  for (const value of ['ACT-1', 'ACT-2', 'Hechos registrados', 'Seguimiento registrado', 'Testigo', 'Evidencia.pdf', 'Firma empleado', 'Firma responsable', 'Confidencial']) assert.ok(jobs[0].bodyHtml.includes(value));
  assert.deepEqual([first, second], before);
});
