app.storage.provider=minio
app.storage.minio.endpoint=http://127.0.0.1:9000
app.storage.minio.public-endpoint=http://127.0.0.1:9000
app.storage.minio.service-public-endpoint=http://host.docker.internal:9000
app.storage.minio.access-key=minioadmin
app.storage.minio.secret-key=minioadmin
app.storage.minio.region=us-east-1
app.storage.minio.bucket-attendance=indice-hr-attendance
app.storage.minio.bucket-biometric=indice-hr-biometric
app.storage.minio.bucket-documents=indice-hr-documents
app.storage.minio.presign-expiry-seconds=900

app.hr.attendance.enforce-location-radius=false
app.hr.face.enabled=true
app.hr.face.service-base-url=http://127.0.0.1:8091
app.hr.face.session-expiry-seconds=600
