import type { ConsultingTranslations } from './types';

export const enCA: ConsultingTranslations = {
  title: 'Consulting', subtitle: 'Schedule and track sessions with the Indice team.',
  loading: 'Preparing the consulting schedule…', errorDescription: 'Try again to load your sessions and availability.', requestError: 'We could not send your request. Your details are still on screen; please try again.', retry: 'Try again',
  benefitIncluded: 'Your first virtual session is included', benefitAdditional: 'Additional session', duration: '50 minutes', pendingNotice: 'Choose the day and time that work best for you. An Indice consultant will contact you to understand your needs and confirm the session with you.',
  brandPromiseTitle: 'You are never alone while growing your company', brandPromiseDescription: 'Indice accompanies you through every stage of your company’s growth. Whenever you need support, we will review your business situation with you, help you make decisions, and implement Indice as efficiently as possible.', consultantChangeNote: 'We want you to feel supported and at ease. If needed, you may request a different consultant for your next session.',
  scheduleTitle: 'Request your session', scheduleDescription: 'First tell us when works for you; then we will choose the best way to help together.', stepSession: '2 · Format', stepTime: '1 · Date and time', stepContext: '3 · Topic and contact', includedBadge: 'Included with your account', additionalBadge: 'Separate payment required',
  preferredDate: 'Preferred date', preferredTime: 'Preferred time', alternativeTitle: 'Second time', addAlternative: 'Add an alternative time', removeAlternative: 'Remove alternative time', timezone: 'Time zone',
  consultationMode: 'How would you prefer to meet?', virtualMode: 'Virtual', virtualDescription: 'Join from any country. The link will appear shortly before the confirmed time.', inPersonMode: 'In person', inPersonDescription: 'Currently available in selected cities in Mexico and Canada.', inPersonCost: 'In-person consulting has an additional cost. We will send a quote before confirming.', inPersonQuoteBadge: 'In-person quote pending',
  country: 'Country for the in-person session', city: 'City', cityPlaceholder: 'Select a city', otherCity: 'None of these cities', unsupportedCountry: 'We do not have in-person consultants available in this country yet.', useVirtualInstead: 'You can select virtual consulting to receive support from anywhere.',
  topic: 'What would you like to work on?', topics: { ONBOARDING: 'Initial Indice implementation', BUSINESS_CONSULTING: 'Business consulting', OPERATIONS: 'Processes and operations', PEOPLE: 'People and organization', SALES: 'Sales and commercial offer', FINANCE: 'Finance and indicators', OTHER: 'Another business challenge' },
  notes: 'Share the context', notesPlaceholder: 'Briefly describe the challenge, decision you need to make, or result you want.', attendeeName: 'Attendee name', attendeeEmail: 'Contact email', attendeePhone: 'Contact phone', submit: 'Send request', submitting: 'Sending request…', confirmationNote: 'The request will remain pending confirmation. A consultant will contact you to coordinate it.',
  upcomingTitle: 'Your next consulting session', requested: 'Pending confirmation', confirmed: 'Confirmed', paymentRequired: 'Payment or quote pending', cancelled: 'Cancelled', completed: 'Completed', preferredLabel: 'Preferred time', alternativeLabel: 'Alternative', meetingLink: 'Join consulting session', meetingPending: 'The link will be available 15 minutes before the session.', meetingAvailableAt: 'Access available from', consultantLabel: 'Assigned consultant',
  requestFlow: 'Request progress', flowRequested: 'Request sent', flowConfirmed: 'Appointment confirmed', flowSession: 'Consulting session', cancelAction: 'Cancel request', cancelling: 'Cancelling…', historyTitle: 'Consulting history', historyEmpty: 'You have not requested a session yet.', successTitle: 'Request sent', successDescription: 'Your request is now pending confirmation. A consultant will contact you to coordinate the session.',
  requiredMessage: 'Complete the required fields before continuing.', invalidDateMessage: 'Choose a business-hour time with at least 24 hours notice.', locationRequiredMessage: 'Select a city with in-person service or change to virtual consulting.', notificationWarning: 'The request was saved, but the email notification failed. The team can still see it in Root.',
  countries: { MX: '🇲🇽 Mexico', CA: '🇨🇦 Canada', US: '🇺🇸 United States', BR: '🇧🇷 Brazil', CO: '🇨🇴 Colombia' },
};
