import type { ConsultingTranslations } from './types';

export const esMX: ConsultingTranslations = {
  title: 'Consultoría', subtitle: 'Agenda y da seguimiento a tus sesiones con el equipo de Índice.',
  loading: 'Preparando la agenda de consultoría…', errorDescription: 'Intenta nuevamente para consultar tus sesiones y disponibilidad.', requestError: 'No pudimos enviar tu solicitud. Tus datos siguen en pantalla; inténtalo nuevamente.', retry: 'Intentar nuevamente',
  benefitIncluded: 'Una sesión virtual al mes está incluida y no es acumulable', benefitAdditional: 'Sesión adicional', duration: '60 minutos', pendingNotice: 'Elige el día y el horario que te convengan. Un consultor de Índice te contactará para conocer tus necesidades y confirmar contigo la sesión.',
  brandPromiseTitle: 'Nunca estás solo mientras haces crecer tu empresa', brandPromiseDescription: 'Índice te acompaña en cada etapa del crecimiento de tu empresa. Cuando necesites apoyo, analizaremos contigo la situación de tu negocio y te ayudaremos a tomar decisiones e implementar Índice de la manera más eficiente posible.', consultantChangeNote: 'Queremos que te sientas acompañado y en confianza. Si lo necesitas, puedes solicitar otro consultor para tu próxima sesión.',
  scheduleTitle: 'Solicita tu sesión', scheduleDescription: 'Primero dinos cuándo te conviene; después elegiremos contigo la mejor forma de ayudarte.', stepSession: '3 · Modalidad', stepTime: '1 · Día y horario', stepConsultant: '2 · Consultor', stepContext: '4 · Tema y contacto', includedBadge: 'Incluida con tu cuenta', additionalBadge: 'Requiere pago por separado',
  preferredDate: 'Fecha preferente', preferredTime: 'Hora preferente', alternativeTitle: 'Segundo horario', addAlternative: 'Agregar un horario alternativo', removeAlternative: 'Quitar horario alternativo', timezone: 'Zona horaria',
  consultantPreference: '¿Con quién prefieres atenderte?', consultantPreferenceDescription: 'Tu preferencia orientará la asignación. El equipo de Índice confirmará disponibilidad y podrás solicitar un cambio.', distributorPreferenceTitle: 'Mi distribuidor', distributorPreferenceDescription: 'Solicita que te atienda tu distribuidor o una persona consultora de su equipo.', indiceTeamPreferenceTitle: 'Otro consultor de Índice', indiceTeamPreferenceDescription: 'Permite que Índice seleccione otra persona consultora de acuerdo con el tema y la disponibilidad.', requestedWith: 'Preferencia solicitada',
  consultationMode: '¿Cómo prefieres la consultoría?', virtualMode: 'Virtual', virtualDescription: 'Conéctate desde cualquier país. El enlace aparecerá cerca de la hora confirmada.', inPersonMode: 'Presencial', inPersonDescription: 'Disponible por ahora en ciudades seleccionadas de México y Canadá.', inPersonCost: 'La consultoría presencial tiene un costo adicional. Te enviaremos la cotización antes de confirmar.', inPersonQuoteBadge: 'Cotización presencial pendiente',
  country: 'País de la sesión presencial', city: 'Ciudad', cityPlaceholder: 'Selecciona una ciudad', otherCity: 'Ninguna de estas ciudades', unsupportedCountry: 'Aún no contamos con consultores presenciales disponibles en este país.', useVirtualInstead: 'Puedes seleccionar consultoría virtual para recibir acompañamiento desde cualquier lugar.',
  topic: '¿Qué quieres trabajar?', topics: { ONBOARDING: 'Implementación inicial de Índice', BUSINESS_CONSULTING: 'Consultoría de negocios', OPERATIONS: 'Procesos y operación', PEOPLE: 'Personas y organización', SALES: 'Ventas y oferta comercial', FINANCE: 'Finanzas e indicadores', OTHER: 'Otro reto de tu empresa' },
  notes: 'Cuéntanos el contexto', notesPlaceholder: 'Describe brevemente el reto, la decisión que necesitas tomar o el resultado que buscas.', attendeeName: 'Nombre de quien asistirá', attendeeEmail: 'Correo de contacto', attendeePhone: 'Teléfono de contacto', submit: 'Enviar solicitud', submitting: 'Enviando solicitud…', confirmationNote: 'La solicitud quedará “Por confirmar”. Un consultor se pondrá en contacto contigo para cuadrar la cita.',
  upcomingTitle: 'Tu próxima consultoría', requested: 'Por confirmar', confirmed: 'Confirmada', paymentRequired: 'Pago o cotización pendiente', cancelled: 'Cancelada', completed: 'Completada', preferredLabel: 'Horario preferente', alternativeLabel: 'Alternativa', meetingLink: 'Ingresar a la consultoría', meetingPending: 'El enlace estará disponible 15 minutos antes de la sesión.', meetingAvailableAt: 'Acceso disponible desde', consultantLabel: 'Consultor asignado',
  requestFlow: 'Seguimiento de tu solicitud', flowRequested: 'Solicitud enviada', flowConfirmed: 'Cita confirmada', flowSession: 'Consultoría', cancelAction: 'Cancelar solicitud', cancelling: 'Cancelando…', historyTitle: 'Historial de consultoría', historyEmpty: 'Todavía no has solicitado una sesión.', successTitle: 'Solicitud enviada', successDescription: 'Tu solicitud aparece ahora como “Por confirmar”. Un consultor te contactará para acordar la sesión.',
  requiredMessage: 'Completa los datos obligatorios antes de continuar.', preferenceRequiredMessage: 'Selecciona si prefieres atenderte con tu distribuidor o con otro consultor de Índice.', invalidDateMessage: 'Elige un horario hábil con al menos 24 horas de anticipación.', locationRequiredMessage: 'Selecciona una ciudad con servicio presencial o cambia la modalidad a virtual.', notificationWarning: 'La solicitud quedó guardada, pero el aviso por correo no pudo enviarse. El equipo podrá verla en Root.',
  countries: { MX: '🇲🇽 México', CA: '🇨🇦 Canadá', US: '🇺🇸 Estados Unidos', BR: '🇧🇷 Brasil', CO: '🇨🇴 Colombia' },
};
