import type { ConsultingTranslations } from './types';

export const frCA: ConsultingTranslations = {
  title: 'Services-conseils', subtitle: 'Planifiez vos séances avec l’équipe Indice et suivez leur progression.',
  loading: 'Préparation du calendrier de consultation…', errorDescription: 'Réessayez pour charger vos séances et les disponibilités.', requestError: 'Nous n’avons pas pu envoyer votre demande. Vos renseignements sont toujours affichés; veuillez réessayer.', retry: 'Réessayer',
  benefitIncluded: 'Une séance virtuelle par mois est incluse et non cumulable', benefitAdditional: 'Séance supplémentaire', duration: '60 minutes', pendingNotice: 'Choisissez le jour et l’heure qui vous conviennent. Une personne de l’équipe-conseil Indice communiquera avec vous pour comprendre vos besoins et confirmer la séance.',
  brandPromiseTitle: 'Vous n’êtes jamais seul pour faire croître votre entreprise', brandPromiseDescription: 'Indice vous accompagne à chaque étape de la croissance de votre entreprise. Lorsque vous avez besoin d’aide, nous analysons la situation avec vous pour prendre de meilleures décisions et implanter Indice efficacement.', consultantChangeNote: 'Nous voulons que vous vous sentiez soutenu et en confiance. Au besoin, vous pouvez demander une autre personne-conseil pour la prochaine séance.',
  scheduleTitle: 'Demander une séance', scheduleDescription: 'Indiquez d’abord vos disponibilités; nous choisirons ensuite ensemble la meilleure façon de vous aider.', stepSession: '3 · Formule', stepTime: '1 · Date et heure', stepConsultant: '2 · Personne-conseil', stepContext: '4 · Sujet et coordonnées', includedBadge: 'Incluse avec votre compte', additionalBadge: 'Paiement distinct requis',
  preferredDate: 'Date souhaitée', preferredTime: 'Heure souhaitée', alternativeTitle: 'Deuxième plage horaire', addAlternative: 'Ajouter une plage horaire', removeAlternative: 'Retirer la plage horaire', timezone: 'Fuseau horaire',
  consultantPreference: 'Avec qui souhaitez-vous échanger?', consultantPreferenceDescription: 'Votre préférence guidera l’assignation. L’équipe Indice confirmera la disponibilité et vous pourrez demander un changement.', distributorPreferenceTitle: 'Mon distributeur', distributorPreferenceDescription: 'Demandez votre distributeur ou une personne-conseil de son équipe.', indiceTeamPreferenceTitle: 'Une autre personne-conseil Indice', indiceTeamPreferenceDescription: 'Laissez Indice choisir une autre personne selon le sujet et les disponibilités.', requestedWith: 'Préférence demandée',
  consultationMode: 'Quelle formule préférez-vous?', virtualMode: 'Virtuelle', virtualDescription: 'Connectez-vous depuis n’importe quel pays. Le lien s’affichera peu avant l’heure confirmée.', inPersonMode: 'En personne', inPersonDescription: 'Offerte actuellement dans certaines villes du Mexique et du Canada.', inPersonCost: 'La consultation en personne entraîne des frais supplémentaires. Nous vous transmettrons une estimation avant de confirmer.', inPersonQuoteBadge: 'Estimation en personne en attente',
  country: 'Pays de la séance en personne', city: 'Ville', cityPlaceholder: 'Sélectionner une ville', otherCity: 'Aucune de ces villes', unsupportedCountry: 'Nous n’avons pas encore de personnes-conseils disponibles en personne dans ce pays.', useVirtualInstead: 'Choisissez la consultation virtuelle pour recevoir de l’aide où que vous soyez.',
  topic: 'Sur quoi souhaitez-vous travailler?', topics: { ONBOARDING: 'Implantation initiale d’Indice', BUSINESS_CONSULTING: 'Conseils d’affaires', OPERATIONS: 'Processus et opérations', PEOPLE: 'Personnes et organisation', SALES: 'Ventes et offre commerciale', FINANCE: 'Finances et indicateurs', OTHER: 'Autre défi d’entreprise' },
  notes: 'Décrivez le contexte', notesPlaceholder: 'Décrivez brièvement le défi, la décision à prendre ou le résultat recherché.', attendeeName: 'Nom de la personne participante', attendeeEmail: 'Adresse courriel', attendeePhone: 'Numéro de téléphone', submit: 'Envoyer la demande', submitting: 'Envoi de la demande…', confirmationNote: 'La demande restera en attente de confirmation. Une personne-conseil communiquera avec vous pour la coordonner.',
  upcomingTitle: 'Votre prochaine séance', requested: 'Confirmation en attente', confirmed: 'Confirmée', paymentRequired: 'Paiement ou estimation en attente', cancelled: 'Annulée', completed: 'Terminée', preferredLabel: 'Plage souhaitée', alternativeLabel: 'Autre possibilité', meetingLink: 'Accéder à la séance', meetingPending: 'Le lien sera accessible 15 minutes avant la séance.', meetingAvailableAt: 'Accès offert à compter de', consultantLabel: 'Personne-conseil assignée',
  requestFlow: 'Suivi de la demande', flowRequested: 'Demande envoyée', flowConfirmed: 'Rendez-vous confirmé', flowSession: 'Séance de consultation', cancelAction: 'Annuler la demande', cancelling: 'Annulation…', historyTitle: 'Historique des consultations', historyEmpty: 'Vous n’avez pas encore demandé de séance.', successTitle: 'Demande envoyée', successDescription: 'Votre demande est en attente de confirmation. Une personne-conseil communiquera avec vous pour fixer la séance.',
  requiredMessage: 'Remplissez les champs obligatoires avant de continuer.', preferenceRequiredMessage: 'Choisissez votre distributeur ou une autre personne-conseil Indice.', invalidDateMessage: 'Choisissez une heure ouvrable avec un préavis d’au moins 24 heures.', locationRequiredMessage: 'Choisissez une ville desservie en personne ou passez à la consultation virtuelle.', notificationWarning: 'La demande a été enregistrée, mais le courriel n’a pas pu être envoyé. L’équipe peut tout de même la consulter dans Root.',
  countries: { MX: '🇲🇽 Mexique', CA: '🇨🇦 Canada', US: '🇺🇸 États-Unis', BR: '🇧🇷 Brésil', CO: '🇨🇴 Colombie' },
};
