import type { ConsultingTranslations } from './types';

export const ptBR: ConsultingTranslations = {
  title: 'Consultoria', subtitle: 'Agende e acompanhe suas sessões com a equipe Índice.',
  loading: 'Preparando a agenda de consultoria…', errorDescription: 'Tente novamente para carregar suas sessões e disponibilidades.', requestError: 'Não foi possível enviar sua solicitação. Seus dados continuam na tela; tente novamente.', retry: 'Tentar novamente',
  benefitIncluded: 'Sua primeira sessão virtual está incluída', benefitAdditional: 'Sessão adicional', duration: '50 minutos', pendingNotice: 'Escolha o dia e o horário mais convenientes. Um consultor da Índice entrará em contato para entender suas necessidades e confirmar a sessão.',
  brandPromiseTitle: 'Você nunca está só ao fazer sua empresa crescer', brandPromiseDescription: 'A Índice acompanha cada etapa do crescimento da sua empresa. Quando precisar de apoio, analisaremos a situação com você para tomar decisões e implementar a Índice da forma mais eficiente possível.', consultantChangeNote: 'Queremos que você se sinta acompanhado e à vontade. Se precisar, solicite outro consultor para a próxima sessão.',
  scheduleTitle: 'Solicite sua sessão', scheduleDescription: 'Primeiro informe quando é melhor; depois escolheremos juntos a melhor forma de ajudar.', stepSession: '3 · Modalidade', stepTime: '1 · Data e horário', stepConsultant: '2 · Consultor', stepContext: '4 · Tema e contato', includedBadge: 'Incluída na sua conta', additionalBadge: 'Pagamento separado necessário',
  preferredDate: 'Data preferida', preferredTime: 'Horário preferido', alternativeTitle: 'Segundo horário', addAlternative: 'Adicionar horário alternativo', removeAlternative: 'Remover horário alternativo', timezone: 'Fuso horário',
  consultantPreference: 'Com quem prefere ser atendido?', consultantPreferenceDescription: 'Sua preferência orientará a atribuição. A equipe Índice confirmará a disponibilidade e você poderá solicitar uma troca.', distributorPreferenceTitle: 'Meu distribuidor', distributorPreferenceDescription: 'Solicite seu distribuidor ou um consultor da equipe dele.', indiceTeamPreferenceTitle: 'Outro consultor da Índice', indiceTeamPreferenceDescription: 'Permita que a Índice escolha outro consultor conforme o tema e a disponibilidade.', requestedWith: 'Preferência solicitada',
  consultationMode: 'Como prefere a consultoria?', virtualMode: 'Virtual', virtualDescription: 'Conecte-se de qualquer país. O link aparecerá pouco antes do horário confirmado.', inPersonMode: 'Presencial', inPersonDescription: 'Disponível no momento em cidades selecionadas do México e do Canadá.', inPersonCost: 'A consultoria presencial tem custo adicional. Enviaremos o orçamento antes da confirmação.', inPersonQuoteBadge: 'Orçamento presencial pendente',
  country: 'País da sessão presencial', city: 'Cidade', cityPlaceholder: 'Selecione uma cidade', otherCity: 'Nenhuma dessas cidades', unsupportedCountry: 'Ainda não temos consultores presenciais disponíveis neste país.', useVirtualInstead: 'Escolha a consultoria virtual para receber apoio de qualquer lugar.',
  topic: 'Em que você quer trabalhar?', topics: { ONBOARDING: 'Implementação inicial da Índice', BUSINESS_CONSULTING: 'Consultoria de negócios', OPERATIONS: 'Processos e operações', PEOPLE: 'Pessoas e organização', SALES: 'Vendas e oferta comercial', FINANCE: 'Finanças e indicadores', OTHER: 'Outro desafio da empresa' },
  notes: 'Conte o contexto', notesPlaceholder: 'Descreva brevemente o desafio, a decisão que precisa tomar ou o resultado que busca.', attendeeName: 'Nome de quem participará', attendeeEmail: 'E-mail para contato', attendeePhone: 'Telefone para contato', submit: 'Enviar solicitação', submitting: 'Enviando solicitação…', confirmationNote: 'A solicitação ficará aguardando confirmação. Um consultor entrará em contato para combinar a sessão.',
  upcomingTitle: 'Sua próxima consultoria', requested: 'Aguardando confirmação', confirmed: 'Confirmada', paymentRequired: 'Pagamento ou orçamento pendente', cancelled: 'Cancelada', completed: 'Concluída', preferredLabel: 'Horário preferido', alternativeLabel: 'Alternativa', meetingLink: 'Entrar na consultoria', meetingPending: 'O link ficará disponível 15 minutos antes da sessão.', meetingAvailableAt: 'Acesso disponível a partir de', consultantLabel: 'Consultor responsável',
  requestFlow: 'Acompanhamento da solicitação', flowRequested: 'Solicitação enviada', flowConfirmed: 'Sessão confirmada', flowSession: 'Consultoria', cancelAction: 'Cancelar solicitação', cancelling: 'Cancelando…', historyTitle: 'Histórico de consultorias', historyEmpty: 'Você ainda não solicitou uma sessão.', successTitle: 'Solicitação enviada', successDescription: 'Sua solicitação aguarda confirmação. Um consultor entrará em contato para combinar a sessão.',
  requiredMessage: 'Preencha os campos obrigatórios antes de continuar.', preferenceRequiredMessage: 'Escolha seu distribuidor ou outro consultor da Índice.', invalidDateMessage: 'Escolha um horário comercial com pelo menos 24 horas de antecedência.', locationRequiredMessage: 'Selecione uma cidade com atendimento presencial ou altere para consultoria virtual.', notificationWarning: 'A solicitação foi salva, mas o e-mail não pôde ser enviado. A equipe ainda poderá vê-la no Root.',
  countries: { MX: '🇲🇽 México', CA: '🇨🇦 Canadá', US: '🇺🇸 Estados Unidos', BR: '🇧🇷 Brasil', CO: '🇨🇴 Colômbia' },
};
