package com.indice.erp.finance.pettycash;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

record PettyCashStatementRecord(
    Long id,
    Long companyId,
    Long pettyCashFundId,
    PettyCashFundType fundTypeSnapshot,
    String folio,
    String periodKey,
    LocalDate periodStart,
    LocalDate periodEnd,
    LocalDate cutOffDate,
    BigDecimal openingBalanceAmount,
    BigDecimal assignedAmount,
    BigDecimal additionalDepositAmount,
    BigDecimal declaredClosingBalanceAmount,
    BigDecimal estimatedUsageAmount,
    BigDecimal verifiedExpenseAmount,
    BigDecimal returnedAmount,
    BigDecimal shortageAmount,
    BigDecimal carryForwardAmount,
    String currencyCode,
    PettyCashStatementStatus status,
    Long responsibleUserId,
    String externalOwnerTypeSnapshot,
    String externalOwnerNameSnapshot,
    String externalOwnerRelationshipSnapshot,
    String externalOwnerReferenceSnapshot,
    String statementRecipientEmailSnapshot,
    String managedAssetTypeSnapshot,
    String managedAssetNameSnapshot,
    String managedAssetReferenceSnapshot,
    Long reviewedByUserId,
    Integer attachmentCount,
    Long createdByUserId,
    Long updatedByUserId,
    Instant createdAt,
    Instant updatedAt,
    Instant deletedAt,
    Long version,
    String customFieldsJson,
    String metadataJson
) {
}
