import { getCustomerAccountCopy } from "./customerAccountTranslations";
export type CustomerTableCopy = {
  account: string;
  userType: string;
  commercialOrigin: string;
  status: string;
  access: string;
  billing: string;
  users: string;
  nextEvent: string;
  actions: string;
  columns: string;
  more: string;
  manage: string;
  editType: string;
  noAccounts: string;
  noPlan: string;
  noContract: string;
  monthly: string;
  annual: string;
  currentCharge: string;
  nextInvoiceCharge: string;
  afterTrial: string;
  estimatedCharge: string;
  stripeScheduled: string;
  pendingStripeActivation: string;
  pricePending: string;
  configureRate: string;
  activeUsers: string;
  availableUsers: string;
  manageUsers: string;
  noActivity: string;
  trialEnd: string;
  trialExpired: string;
  daysRemaining: (days: number) => string;
  extendTrial: string;
  permanentTrial: string;
  renewal: string;
  noDate: string;
  sort: string;
  directWithIndice: string;
  distributorAccount: string;
  assignedDistributor: string;
  assignDistributor: string;
  changeDistributor: string;
  deleteAccount: string;
  createdByDistributor: string;
  createdByIndice: string;
  webRegistration: string;
  originNotRegistered: string;
  traceabilityUnavailable: string;
  currentDistributor: string;
  noCurrentDistributor: string;
  currentPortfolio: string;
};

export function getCustomerTableCopy(language?: string | boolean): CustomerTableCopy {
  const { locale, t } = getCustomerAccountCopy(language);
  return {
    account: t("account"),
    userType: t("accountType"),
    commercialOrigin: t("origin"),
    status: t("status"),
    access: t("plan"),
    billing: t("billing"),
    users: t("users"),
    nextEvent: t("nextEvent"),
    actions: t("actions"),
    columns: t("columns"),
    more: t("more"),
    manage: t("manage"),
    editType: t("editType"),
    noAccounts: t("noAccounts"),
    noPlan: t("noPlan"),
    noContract: t("noContract"),
    monthly: t("monthly"),
    annual: t("annual"),
    currentCharge: t("currentCharge"),
    nextInvoiceCharge: t("nextInvoiceCharge"),
    afterTrial: t("afterTrial"),
    estimatedCharge: t("estimatedCharge"),
    stripeScheduled: t("stripeScheduled"),
    pendingStripeActivation: t("pendingStripeActivation"),
    pricePending: t("pricePending"),
    configureRate: t("configureRate"),
    activeUsers: t("activeUsers"),
    availableUsers: t("availableLower"),
    manageUsers: t("manageUsers"),
    noActivity: t("noActivity"),
    trialEnd: t("trialEnd"),
    trialExpired: t("trialExpired"),
    extendTrial: t("extendTrial"),
    permanentTrial: t("permanentTrial"),
    renewal: t("renewal"),
    noDate: t("noScheduledDate"),
    sort: t("sort"),
    directWithIndice: t("directWithIndice"),
    distributorAccount: t("distributorAccount"),
    assignedDistributor: t("assignedDistributor"),
    assignDistributor: t("assignDistributor"),
    changeDistributor: t("changeDistributor"),
    deleteAccount: t("deleteAccount"),
    createdByDistributor: t("createdByDistributor"),
    createdByIndice: t("createdByIndice"),
    webRegistration: t("webRegistration"),
    originNotRegistered: t("historicalOrigin"),
    traceabilityUnavailable: t("traceabilityUnavailable"),
    currentDistributor: t("currentDistributor"),
    noCurrentDistributor: t("noCurrentDistributor"),
    currentPortfolio: t("currentPortfolio"),
    daysRemaining: (days: number) => t(new Intl.PluralRules(locale).select(days) === "one" ? "dayLeftOne" : "dayLeftOther", { count: days }),
  };
}
