import type { PointOfSaleLocale } from '../translations';

const en = {
  chargeUnavailable: 'Card payments are unavailable for this Mercado Pago connection. Check the merchant setup or production approval.',
  closeRequest: 'Check and close unsubmitted request',
  notSubmitted: 'Payment was not submitted. Check the terminal setup or sale details before retrying.',
  configure: 'Configure Mercado Pago', title: 'Configure Mercado Pago Point', description: 'Connect your Mexico merchant account, discover a Point device, and assign it to a POS register. Payments use MXN.',
  connection: 'Connection', terminal: 'Point terminal', register: 'POS register', connected: 'Connected', disconnected: 'Not connected', unavailable: 'Mercado Pago is unavailable in this environment.',
  connect: 'Connect Mercado Pago', refresh: 'Refresh', discover: 'Discover terminals', configureMode: 'Enable POS mode', modeHelp: 'Associate the terminal with your merchant account, store and POS in the Mercado Pago app. Enable POS mode, restart the terminal, and refresh before assigning it.',
  restart: 'POS mode requested. Restart the terminal and refresh before accepting payments.', assign: 'Assign to register', assigned: 'Terminal assigned.', unassign: 'Unassign', confirmUnassign: 'Remove this register’s Mercado Pago terminal?', keep: 'Keep assignment', confirm: 'Confirm',
  empty: 'No terminals found. Check the merchant account and discover again.', noRegister: 'No active registers available.', ready: 'Ready', pending: 'Needs configuration', disabled: 'Disabled', providerVerification: 'Provider verification', providerVerified: 'Provider verified', stale: 'Verification expired', terminalUnavailable: 'Unavailable at provider', reconfigure: 'Binding changed; reconfigure', environment: 'Environment', merchant: 'Merchant account', mode: 'Operating mode', assignment: 'Register assignment', unassigned: 'Unassigned',
  error: 'The operation could not be completed. Refresh and try again.', oauthError: 'Mercado Pago authorization was not completed. Connect again.', oauthSuccess: 'Mercado Pago connected. Discover your terminals.', oneProvider: 'Both provider accounts can be connected. Each register uses one terminal provider. Unassign its current terminal before switching providers.',
  recovery: 'Mercado Pago payment recovery', recoveryHelp: 'Verify this payment before charging again or choosing another method.', waiting: 'Payment sent to Point. Waiting for the customer.', uncertain: 'Payment result is unknown. Check the terminal and recover before charging again.', approved: 'Payment verified. Completing the POS receipt.', cancel: 'Cancel payment', deviceCancel: 'Cancel on the terminal, then recover the payment.', recover: 'Recover payment', retryDelivery: 'Recover original request', mxnOnly: 'Mercado Pago Point supports one full card payment in MXN.', noProvider: 'Assign a payment terminal to this register before charging a card.', loading: 'Verifying terminal payments…', intent: 'Payment', receiptPending: 'Payment approved. Recover the persisted POS receipt before charging again.',
};
type MercadoPagoTerminalBaseCopy = { [K in keyof typeof en]: string };
const es: MercadoPagoTerminalBaseCopy = {
  chargeUnavailable: 'Los pagos con tarjeta no están disponibles para esta conexión Mercado Pago. Revisa la cuenta comercial o la aprobación de producción.',
  closeRequest: 'Verificar y cerrar solicitud no enviada',
  notSubmitted: 'El pago no fue enviado. Revisa la configuración de la terminal o los datos de la venta antes de reintentar.',
  configure: 'Configurar Mercado Pago', title: 'Configurar Mercado Pago Point', description: 'Conecta tu cuenta comercial de México, descubre un dispositivo Point y asígnalo a una caja POS. Los pagos usan MXN.',
  connection: 'Conexión', terminal: 'Terminal Point', register: 'Caja POS', connected: 'Conectada', disconnected: 'Sin conectar', unavailable: 'Mercado Pago no está disponible en este entorno.',
  connect: 'Conectar Mercado Pago', refresh: 'Actualizar', discover: 'Descubrir terminales', configureMode: 'Activar modo POS', modeHelp: 'Asocia la terminal a tu cuenta, tienda y POS en la app de Mercado Pago. Activa el modo POS, reinicia la terminal y actualiza antes de asignarla.',
  restart: 'Modo POS solicitado. Reinicia la terminal y actualiza antes de aceptar pagos.', assign: 'Asignar a caja', assigned: 'Terminal asignada.', unassign: 'Desasignar', confirmUnassign: '¿Quitar la terminal Mercado Pago de esta caja?', keep: 'Conservar asignación', confirm: 'Confirmar',
  empty: 'No se encontraron terminales. Revisa la cuenta comercial y vuelve a descubrir.', noRegister: 'No hay cajas activas disponibles.', ready: 'Lista', pending: 'Requiere configuración', disabled: 'Desactivada', providerVerification: 'Verificación del proveedor', providerVerified: 'Verificada por el proveedor', stale: 'Verificación vencida', terminalUnavailable: 'No disponible en el proveedor', reconfigure: 'Cambió la vinculación; reconfigura', environment: 'Entorno', merchant: 'Cuenta comercial', mode: 'Modo de operación', assignment: 'Caja asignada', unassigned: 'Sin asignar',
  error: 'No se pudo completar la operación. Actualiza e inténtalo de nuevo.', oauthError: 'No se completó la autorización de Mercado Pago. Conecta de nuevo.', oauthSuccess: 'Mercado Pago conectado. Descubre tus terminales.', oneProvider: 'Puedes conectar ambas cuentas. Cada caja usa un solo proveedor de terminal. Quita su terminal actual antes de cambiar de proveedor.',
  recovery: 'Recuperación de pagos Mercado Pago', recoveryHelp: 'Verifica este pago antes de volver a cobrar o elegir otro método.', waiting: 'Pago enviado a Point. Esperando al cliente.', uncertain: 'Resultado del pago desconocido. Revisa la terminal y recupera antes de volver a cobrar.', approved: 'Pago verificado. Completando el comprobante POS.', cancel: 'Cancelar pago', deviceCancel: 'Cancela en la terminal y después recupera el pago.', recover: 'Recuperar pago', retryDelivery: 'Recuperar solicitud original', mxnOnly: 'Mercado Pago Point admite un solo pago completo con tarjeta en MXN.', noProvider: 'Asigna una terminal de pago a esta caja antes de cobrar con tarjeta.', loading: 'Verificando pagos de terminal…', intent: 'Pago', receiptPending: 'Pago aprobado. Recupera el comprobante POS guardado antes de volver a cobrar.',
};
const fr: MercadoPagoTerminalBaseCopy = {
  chargeUnavailable: 'Les paiements par carte sont indisponibles pour cette connexion Mercado Pago. Vérifiez le compte marchand ou l’autorisation de production.',
  closeRequest: 'Vérifier et fermer la demande non envoyée',
  notSubmitted: 'Le paiement n’a pas été envoyé. Vérifiez le terminal ou la vente avant de réessayer.',
  configure: 'Configurer Mercado Pago', title: 'Configurer Mercado Pago Point', description: 'Connectez votre compte marchand mexicain, trouvez un appareil Point et attribuez-le à une caisse POS. Les paiements utilisent MXN.', connection: 'Connexion', terminal: 'Terminal Point', register: 'Caisse POS', connected: 'Connecté', disconnected: 'Non connecté', unavailable: 'Mercado Pago est indisponible dans cet environnement.', connect: 'Connecter Mercado Pago', refresh: 'Actualiser', discover: 'Rechercher les terminaux', configureMode: 'Activer le mode POS', modeHelp: 'Associez le terminal à votre compte, magasin et POS dans l’application Mercado Pago. Activez le mode POS, redémarrez et actualisez avant l’attribution.', restart: 'Mode POS demandé. Redémarrez le terminal et actualisez avant les paiements.', assign: 'Attribuer à une caisse', assigned: 'Terminal attribué.', unassign: 'Retirer l’attribution', confirmUnassign: 'Retirer le terminal Mercado Pago de cette caisse ?', keep: 'Conserver', confirm: 'Confirmer', empty: 'Aucun terminal trouvé. Vérifiez le compte et relancez la recherche.', noRegister: 'Aucune caisse active.', ready: 'Prêt', pending: 'Configuration nécessaire', disabled: 'Désactivé', providerVerification: 'Vérification du fournisseur', providerVerified: 'Vérifié par le fournisseur', stale: 'Vérification expirée', terminalUnavailable: 'Indisponible chez le fournisseur', reconfigure: 'Association modifiée; reconfigurez', environment: 'Environnement', merchant: 'Compte marchand', mode: 'Mode de fonctionnement', assignment: 'Caisse attribuée', unassigned: 'Non attribué', error: 'L’opération a échoué. Actualisez et réessayez.', oauthError: 'Autorisation Mercado Pago incomplète. Reconnectez-vous.', oauthSuccess: 'Mercado Pago connecté. Recherchez vos terminaux.', oneProvider: 'Les deux comptes peuvent être connectés. Chaque caisse utilise un fournisseur. Retirez le terminal actuel avant de changer.', recovery: 'Récupération des paiements Mercado Pago', recoveryHelp: 'Vérifiez ce paiement avant de facturer à nouveau ou de changer de méthode.', waiting: 'Paiement envoyé à Point. En attente du client.', uncertain: 'Résultat inconnu. Vérifiez le terminal et récupérez le paiement avant de facturer à nouveau.', approved: 'Paiement vérifié. Finalisation du reçu POS.', cancel: 'Annuler le paiement', deviceCancel: 'Annulez sur le terminal, puis récupérez le paiement.', recover: 'Récupérer le paiement', retryDelivery: 'Récupérer la demande initiale', mxnOnly: 'Mercado Pago Point accepte un paiement intégral par carte en MXN.', noProvider: 'Attribuez un terminal à cette caisse avant un paiement par carte.', loading: 'Vérification des paiements…', intent: 'Paiement', receiptPending: 'Paiement approuvé. Récupérez le reçu POS enregistré avant de facturer à nouveau.',
};
const pt: MercadoPagoTerminalBaseCopy = {
  chargeUnavailable: 'Pagamentos com cartão indisponíveis nesta conexão Mercado Pago. Confira a conta comercial ou a aprovação de produção.',
  closeRequest: 'Verificar e encerrar solicitação não enviada',
  notSubmitted: 'O pagamento não foi enviado. Confira o terminal ou os dados da venda antes de tentar novamente.',
  configure: 'Configurar Mercado Pago', title: 'Configurar Mercado Pago Point', description: 'Conecte sua conta comercial do México, descubra um Point e associe-o a um caixa POS. Pagamentos em MXN.', connection: 'Conexão', terminal: 'Terminal Point', register: 'Caixa POS', connected: 'Conectado', disconnected: 'Não conectado', unavailable: 'Mercado Pago indisponível neste ambiente.', connect: 'Conectar Mercado Pago', refresh: 'Atualizar', discover: 'Descobrir terminais', configureMode: 'Ativar modo POS', modeHelp: 'Associe o terminal à conta, loja e POS no aplicativo Mercado Pago. Ative o modo POS, reinicie e atualize antes de associar.', restart: 'Modo POS solicitado. Reinicie o terminal e atualize antes de receber pagamentos.', assign: 'Associar ao caixa', assigned: 'Terminal associado.', unassign: 'Remover associação', confirmUnassign: 'Remover o terminal Mercado Pago deste caixa?', keep: 'Manter associação', confirm: 'Confirmar', empty: 'Nenhum terminal encontrado. Verifique a conta e descubra novamente.', noRegister: 'Nenhum caixa ativo.', ready: 'Pronto', pending: 'Requer configuração', disabled: 'Desativado', providerVerification: 'Verificação do provedor', providerVerified: 'Verificado pelo provedor', stale: 'Verificação expirada', terminalUnavailable: 'Indisponível no provedor', reconfigure: 'Vínculo alterado; reconfigure', environment: 'Ambiente', merchant: 'Conta comercial', mode: 'Modo de operação', assignment: 'Caixa associado', unassigned: 'Não associado', error: 'Não foi possível concluir. Atualize e tente novamente.', oauthError: 'Autorização Mercado Pago incompleta. Conecte novamente.', oauthSuccess: 'Mercado Pago conectado. Descubra seus terminais.', oneProvider: 'Ambas as contas podem estar conectadas. Cada caixa usa um fornecedor. Remova o terminal atual antes de trocar.', recovery: 'Recuperação de pagamentos Mercado Pago', recoveryHelp: 'Verifique este pagamento antes de cobrar novamente ou escolher outro método.', waiting: 'Pagamento enviado ao Point. Aguardando o cliente.', uncertain: 'Resultado desconhecido. Verifique o terminal e recupere antes de cobrar novamente.', approved: 'Pagamento verificado. Concluindo o recibo POS.', cancel: 'Cancelar pagamento', deviceCancel: 'Cancele no terminal e depois recupere o pagamento.', recover: 'Recuperar pagamento', retryDelivery: 'Recuperar solicitação original', mxnOnly: 'Mercado Pago Point aceita um pagamento integral com cartão em MXN.', noProvider: 'Associe uma terminal ao caixa antes de cobrar com cartão.', loading: 'Verificando pagamentos…', intent: 'Pagamento', receiptPending: 'Pagamento aprovado. Recupere o recibo POS salvo antes de cobrar novamente.',
};
const ko: MercadoPagoTerminalBaseCopy = {
  chargeUnavailable: '이 Mercado Pago 연결에서는 카드 결제를 사용할 수 없습니다. 판매자 설정이나 운영 승인을 확인하세요.',
  closeRequest: '미전송 요청 확인 및 종료',
  notSubmitted: '결제가 전송되지 않았습니다. 다시 시도하기 전에 단말기 설정이나 판매 정보를 확인하세요.',
  configure: 'Mercado Pago 설정', title: 'Mercado Pago Point 설정', description: '멕시코 판매자 계정을 연결하고 Point 기기를 검색하여 POS 계산대에 연결하세요. 결제 통화는 MXN입니다.', connection: '연결', terminal: 'Point 단말기', register: 'POS 계산대', connected: '연결됨', disconnected: '연결 안 됨', unavailable: '이 환경에서는 Mercado Pago를 사용할 수 없습니다.', connect: 'Mercado Pago 연결', refresh: '새로 고침', discover: '단말기 검색', configureMode: 'POS 모드 활성화', modeHelp: 'Mercado Pago 앱에서 단말기를 계정, 매장 및 POS에 연결하세요. POS 모드를 켜고 단말기를 재시작한 후 새로 고침하세요.', restart: 'POS 모드를 요청했습니다. 결제 전에 단말기를 재시작하고 새로 고침하세요.', assign: '계산대에 연결', assigned: '단말기가 연결되었습니다.', unassign: '연결 해제', confirmUnassign: '이 계산대의 Mercado Pago 단말기를 해제할까요?', keep: '연결 유지', confirm: '확인', empty: '단말기가 없습니다. 계정을 확인하고 다시 검색하세요.', noRegister: '활성 계산대가 없습니다.', ready: '준비됨', pending: '설정 필요', disabled: '비활성', providerVerification: '공급자 확인', providerVerified: '공급자 확인 완료', stale: '확인 만료됨', terminalUnavailable: '공급자에서 사용할 수 없음', reconfigure: '연결 변경됨; 다시 설정하세요', environment: '환경', merchant: '판매자 계정', mode: '작동 모드', assignment: '연결된 계산대', unassigned: '미연결', error: '작업을 완료하지 못했습니다. 새로 고침 후 다시 시도하세요.', oauthError: 'Mercado Pago 인증을 완료하지 못했습니다. 다시 연결하세요.', oauthSuccess: 'Mercado Pago가 연결되었습니다. 단말기를 검색하세요.', oneProvider: '두 계정을 모두 연결할 수 있습니다. 계산대마다 공급자 하나를 사용합니다. 변경 전에 기존 단말기를 해제하세요.', recovery: 'Mercado Pago 결제 복구', recoveryHelp: '다시 결제하거나 다른 방법을 선택하기 전에 이 결제를 확인하세요.', waiting: 'Point에 결제를 보냈습니다. 고객을 기다리는 중입니다.', uncertain: '결제 결과를 알 수 없습니다. 단말기를 확인하고 복구한 후 다시 결제하세요.', approved: '결제가 확인되었습니다. POS 영수증을 완료하는 중입니다.', cancel: '결제 취소', deviceCancel: '단말기에서 취소한 후 결제를 복구하세요.', recover: '결제 복구', retryDelivery: '원래 요청 복구', mxnOnly: 'Mercado Pago Point는 MXN 전액 카드 결제 하나를 지원합니다.', noProvider: '카드 결제 전에 계산대에 결제 단말기를 연결하세요.', loading: '단말기 결제 확인 중…', intent: '결제', receiptPending: '결제가 승인되었습니다. 다시 결제하기 전에 저장된 POS 영수증을 복구하세요.',
};
const zh: MercadoPagoTerminalBaseCopy = {
  chargeUnavailable: '此 Mercado Pago 连接无法接受银行卡付款。请检查商户设置或生产环境批准。',
  closeRequest: '检查并关闭未提交的请求',
  notSubmitted: '付款未提交。重试前请检查终端设置或销售详情。',
  configure: '配置 Mercado Pago', title: '配置 Mercado Pago Point', description: '连接墨西哥商户账户，发现 Point 设备并分配到 POS 收银台。付款使用 MXN。', connection: '连接', terminal: 'Point 终端', register: 'POS 收银台', connected: '已连接', disconnected: '未连接', unavailable: '此环境中无法使用 Mercado Pago。', connect: '连接 Mercado Pago', refresh: '刷新', discover: '发现终端', configureMode: '启用 POS 模式', modeHelp: '在 Mercado Pago 应用中将终端关联到账户、商店和 POS。启用 POS 模式，重启终端并刷新后再分配。', restart: '已请求 POS 模式。接受付款前请重启终端并刷新。', assign: '分配到收银台', assigned: '终端已分配。', unassign: '取消分配', confirmUnassign: '移除此收银台的 Mercado Pago 终端？', keep: '保留分配', confirm: '确认', empty: '未找到终端。请检查账户并重新发现。', noRegister: '没有启用的收银台。', ready: '就绪', pending: '需要配置', disabled: '已停用', providerVerification: '提供商验证', providerVerified: '提供商已验证', stale: '验证已过期', terminalUnavailable: '提供商处不可用', reconfigure: '绑定已更改；请重新配置', environment: '环境', merchant: '商户账户', mode: '操作模式', assignment: '已分配的收银台', unassigned: '未分配', error: '无法完成操作。请刷新后重试。', oauthError: '未完成 Mercado Pago 授权。请重新连接。', oauthSuccess: 'Mercado Pago 已连接。请发现终端。', oneProvider: '可以连接两个账户。每个收银台使用一个提供商。更换前请取消当前终端的分配。', recovery: 'Mercado Pago 付款恢复', recoveryHelp: '再次收费或选择其他方式前，请核实此付款。', waiting: '付款已发送到 Point。正在等待客户。', uncertain: '付款结果未知。再次收费前请检查终端并恢复付款。', approved: '付款已核实。正在完成 POS 收据。', cancel: '取消付款', deviceCancel: '在终端上取消，然后恢复付款。', recover: '恢复付款', retryDelivery: '恢复原始请求', mxnOnly: 'Mercado Pago Point 支持一笔 MXN 全额银行卡付款。', noProvider: '银行卡收费前，请为此收银台分配付款终端。', loading: '正在核实终端付款…', intent: '付款', receiptPending: '付款已批准。再次收费前请恢复已保存的 POS 收据。',
};
const reviewEn = {
  reviewTitle: 'Authenticated merchant review', reviewHelp: 'Use the Mercado Pago order ID only after locating this exact charge in the merchant account. The server verifies ownership, amount, and currency.',
  reviewOrder: 'Mercado Pago order ID', reviewOrderPlaceholder: 'ORD…', reviewReason: 'Review reason', reviewReasonPlaceholder: 'Explain how the provider order was located',
  reviewSubmit: 'Verify provider order', reviewInvalid: 'Enter a valid ORD order ID and a reason between 8 and 500 characters.', reviewConflict: 'The payment changed. Current details were reloaded; review them before trying again.', reviewError: 'The provider order could not be verified.',
};
type MercadoPagoReviewCopy = { [K in keyof typeof reviewEn]: string };
export type MercadoPagoTerminalCopy = MercadoPagoTerminalBaseCopy & MercadoPagoReviewCopy;
const reviewEs: MercadoPagoReviewCopy = { reviewTitle: 'Revisión autenticada del comercio', reviewHelp: 'Usa el ID de orden de Mercado Pago solo después de localizar este cargo exacto en la cuenta comercial. El servidor verifica titularidad, importe y moneda.', reviewOrder: 'ID de orden de Mercado Pago', reviewOrderPlaceholder: 'ORD…', reviewReason: 'Motivo de la revisión', reviewReasonPlaceholder: 'Explica cómo se localizó la orden del proveedor', reviewSubmit: 'Verificar orden del proveedor', reviewInvalid: 'Ingresa un ID de orden ORD válido y un motivo de 8 a 500 caracteres.', reviewConflict: 'El pago cambió. Se cargaron los datos actuales; revísalos antes de intentarlo de nuevo.', reviewError: 'No se pudo verificar la orden del proveedor.' };
const reviews: Record<PointOfSaleLocale, MercadoPagoReviewCopy> = {
  'en-CA': reviewEn, 'en-US': reviewEn, 'es-MX': reviewEs, 'es-CO': reviewEs,
  'fr-CA': { reviewTitle: 'Vérification authentifiée du marchand', reviewHelp: 'Utilisez l’identifiant de commande Mercado Pago seulement après avoir retrouvé ce débit exact dans le compte marchand. Le serveur vérifie le titulaire, le montant et la devise.', reviewOrder: 'Identifiant de commande Mercado Pago', reviewOrderPlaceholder: 'ORD…', reviewReason: 'Motif de la vérification', reviewReasonPlaceholder: 'Expliquez comment la commande a été retrouvée', reviewSubmit: 'Vérifier la commande', reviewInvalid: 'Saisissez un identifiant ORD valide et un motif de 8 à 500 caractères.', reviewConflict: 'Le paiement a changé. Les données actuelles ont été rechargées; vérifiez-les avant de réessayer.', reviewError: 'La commande du fournisseur n’a pas pu être vérifiée.' },
  'pt-BR': { reviewTitle: 'Verificação autenticada do comerciante', reviewHelp: 'Use o ID do pedido Mercado Pago somente após localizar esta cobrança exata na conta comercial. O servidor verifica titularidade, valor e moeda.', reviewOrder: 'ID do pedido Mercado Pago', reviewOrderPlaceholder: 'ORD…', reviewReason: 'Motivo da verificação', reviewReasonPlaceholder: 'Explique como o pedido foi localizado', reviewSubmit: 'Verificar pedido do provedor', reviewInvalid: 'Informe um ID ORD válido e um motivo de 8 a 500 caracteres.', reviewConflict: 'O pagamento mudou. Os dados atuais foram recarregados; revise-os antes de tentar novamente.', reviewError: 'Não foi possível verificar o pedido do provedor.' },
  'ko-CA': { reviewTitle: '인증된 판매자 검토', reviewHelp: '판매자 계정에서 이 결제를 정확히 찾은 경우에만 Mercado Pago 주문 ID를 사용하세요. 서버가 소유권, 금액 및 통화를 확인합니다.', reviewOrder: 'Mercado Pago 주문 ID', reviewOrderPlaceholder: 'ORD…', reviewReason: '검토 사유', reviewReasonPlaceholder: '공급자 주문을 찾은 방법을 설명하세요', reviewSubmit: '공급자 주문 확인', reviewInvalid: '유효한 ORD 주문 ID와 8~500자의 사유를 입력하세요.', reviewConflict: '결제 정보가 변경되었습니다. 최신 정보를 다시 불러왔으니 확인 후 다시 시도하세요.', reviewError: '공급자 주문을 확인하지 못했습니다.' },
  'zh-CA': { reviewTitle: '商户身份验证审核', reviewHelp: '只有在商户账户中找到完全对应的扣款后，才可使用 Mercado Pago 订单 ID。服务器会核验归属、金额和币种。', reviewOrder: 'Mercado Pago 订单 ID', reviewOrderPlaceholder: 'ORD…', reviewReason: '审核原因', reviewReasonPlaceholder: '说明如何找到服务商订单', reviewSubmit: '核验服务商订单', reviewInvalid: '请输入有效的 ORD 订单 ID 和 8–500 个字符的原因。', reviewConflict: '付款已发生变化。已重新加载当前详情；请检查后重试。', reviewError: '无法核验服务商订单。' },
};
const bases: Record<PointOfSaleLocale, MercadoPagoTerminalBaseCopy> = {
  'en-CA': en, 'en-US': en, 'es-MX': es, 'es-CO': es, 'fr-CA': fr, 'pt-BR': pt, 'ko-CA': ko, 'zh-CA': zh,
};
export const mercadoPagoTerminalCopyByLocale = Object.fromEntries(
  Object.entries(bases).map(([locale, copy]) => [locale, { ...copy, ...reviews[locale as PointOfSaleLocale] }]),
) as Record<PointOfSaleLocale, MercadoPagoTerminalCopy>;
