import type { PlatformAdminLocale } from '../translations';

const en = { title: 'Mercado Pago production', description: 'Platform Root controls whether this company may create live Point charges. Recovery, cancellation, webhooks, and refunds remain available while suspended.', missing: 'This company has no production Mercado Pago connection yet.', state: 'Activation state', gate: 'Effective charge gate', allowed: 'Live charges allowed', blocked: 'Live charges blocked', reason: 'Operational reason', placeholder: 'Record the rollout, incident, or suspension reason', save: 'Save activation', refresh: 'Refresh', saved: 'Activation updated.', conflict: 'Another administrator changed this decision. The latest version has been loaded; review it before saving.', error: 'Activation could not be loaded or updated.', version: 'Decision version' };
type Copy = typeof en;
const es: Copy = { title: 'Producción de Mercado Pago', description: 'Platform Root controla si esta empresa puede crear cobros Point reales. La recuperación, cancelación, webhooks y reembolsos siguen disponibles durante una suspensión.', missing: 'Esta empresa todavía no tiene una conexión de producción de Mercado Pago.', state: 'Estado de activación', gate: 'Permiso efectivo de cobro', allowed: 'Cobros reales permitidos', blocked: 'Cobros reales bloqueados', reason: 'Motivo operativo', placeholder: 'Registra el motivo del despliegue, incidente o suspensión', save: 'Guardar activación', refresh: 'Actualizar', saved: 'Activación actualizada.', conflict: 'Otro administrador cambió esta decisión. Se cargó la versión más reciente; revísala antes de guardar.', error: 'No se pudo cargar o actualizar la activación.', version: 'Versión de decisión' };
const fr: Copy = { title: 'Production Mercado Pago', description: 'Platform Root contrôle les paiements Point réels de cette entreprise. La récupération, l’annulation, les webhooks et les remboursements restent disponibles pendant une suspension.', missing: 'Cette entreprise n’a pas encore de connexion Mercado Pago de production.', state: 'État d’activation', gate: 'Autorisation effective', allowed: 'Paiements réels autorisés', blocked: 'Paiements réels bloqués', reason: 'Motif opérationnel', placeholder: 'Indiquez le motif du déploiement, incident ou suspension', save: 'Enregistrer', refresh: 'Actualiser', saved: 'Activation mise à jour.', conflict: 'Un autre administrateur a modifié cette décision. La dernière version a été chargée.', error: 'Impossible de charger ou modifier l’activation.', version: 'Version de décision' };
const pt: Copy = { title: 'Produção Mercado Pago', description: 'Platform Root controla se esta empresa pode criar cobranças Point reais. Recuperação, cancelamento, webhooks e reembolsos continuam disponíveis durante suspensão.', missing: 'Esta empresa ainda não tem conexão Mercado Pago de produção.', state: 'Estado de ativação', gate: 'Permissão efetiva', allowed: 'Cobranças reais permitidas', blocked: 'Cobranças reais bloqueadas', reason: 'Motivo operacional', placeholder: 'Registre o motivo da implantação, incidente ou suspensão', save: 'Salvar ativação', refresh: 'Atualizar', saved: 'Ativação atualizada.', conflict: 'Outro administrador alterou esta decisão. A versão mais recente foi carregada.', error: 'Não foi possível carregar ou atualizar a ativação.', version: 'Versão da decisão' };
const ko: Copy = { title: 'Mercado Pago 운영', description: 'Platform Root가 이 회사의 실제 Point 결제 허용 여부를 관리합니다. 중지 중에도 복구, 취소, 웹훅 및 환불은 계속 사용할 수 있습니다.', missing: '이 회사에는 아직 Mercado Pago 운영 연결이 없습니다.', state: '활성화 상태', gate: '실제 결제 권한', allowed: '실제 결제 허용', blocked: '실제 결제 차단', reason: '운영 사유', placeholder: '출시, 사고 또는 중지 사유를 기록하세요', save: '활성화 저장', refresh: '새로 고침', saved: '활성화가 업데이트되었습니다.', conflict: '다른 관리자가 이 결정을 변경했습니다. 저장하기 전에 최신 버전을 검토하세요.', error: '활성화를 불러오거나 업데이트하지 못했습니다.', version: '결정 버전' };
const zh: Copy = { title: 'Mercado Pago 生产环境', description: 'Platform Root 控制该公司能否创建真实 Point 收款。暂停期间仍可使用恢复、取消、Webhook 和退款。', missing: '该公司尚无 Mercado Pago 生产环境连接。', state: '激活状态', gate: '实际收款权限', allowed: '允许真实收款', blocked: '阻止真实收款', reason: '操作原因', placeholder: '记录上线、事件或暂停原因', save: '保存激活状态', refresh: '刷新', saved: '激活状态已更新。', conflict: '另一位管理员已更改此决定。已加载最新版本，请在保存前检查。', error: '无法加载或更新激活状态。', version: '决策版本' };
export const mercadoPagoActivationCopy: Record<PlatformAdminLocale, Copy> = { 'en-CA': en, 'en-US': en, 'es-MX': es, 'es-CO': es, 'fr-CA': fr, 'pt-BR': pt, 'ko-CA': ko, 'zh-CA': zh };
