import type { LearningModeControl } from '../../../learningMode';

export const collaboratorsLearningControls: readonly LearningModeControl[] = [
  {
    id: 'add-collaborator',
    emoji: '➕',
    kind: 'Botón de acción',
    title: 'Agregar colaborador',
    purpose: 'Crea el expediente laboral de una persona y la incorpora formalmente a la operación.',
    behavior: 'Abre un formulario para registrar datos personales, puesto, unidad, negocio, documentos y horario inicial.',
    whenToUse: 'Úsalo desde el ingreso del colaborador, antes de asignarle responsabilidades o accesos.',
    tipByCharacter: {
      emily: 'Registra la sucursal y el puesto desde el primer día para conservar los mismos estándares al crecer.',
      juanito: 'No dejes datos en mensajes o libretas: un expediente completo también es una forma de control.',
      camila: 'Incluye también a familiares que trabajan en el negocio; tener confianza no sustituye definir su función.',
    },
    storyByCharacter: {
      emily: 'Emily es estratégica y cuida mucho la experiencia del cliente. Cuando contrata a un barista, lo registra desde el primer día con sucursal, puesto y horario; así puede abrir nuevas cafeterías sin perder claridad sobre quién fue preparado para cada función.',
      juanito: 'Juanito es muy bueno con los números, pero usa RH para asegurarse de que lo que no cabe en una hoja de cálculo también esté bajo control. Registra a cada colaborador con su expediente completo porque ya aprendió que, si no tiene los datos, después se le olvidan y no sabe dónde encontrarlos.',
      camila: 'Camila es trabajadora y confía mucho en su familia. Al agregar formalmente a cada persona, convierte acuerdos de palabra en puestos y responsabilidades visibles sin perder la cercanía del negocio familiar.',
    },
  },
  {
    id: 'columns',
    emoji: '🧩',
    kind: 'Botón de configuración',
    title: 'Columnas',
    purpose: 'Define qué información aparece en la tabla y en qué orden se consulta.',
    behavior: 'Abre el configurador para mostrar, ocultar, ordenar y fijar columnas del expediente.',
    whenToUse: 'Úsalo para adaptar la vista a la revisión que realizarás: documentos, puestos, horarios o nómina.',
    tipByCharacter: {
      emily: 'Crea una vista enfocada en sucursal, puesto y horario para revisar rápidamente la cobertura.',
      juanito: 'Muestra solo las columnas que responden la pregunta que estás analizando para no perderte entre datos.',
      camila: 'Coloca primero puesto, departamento y estado para que las responsabilidades sean visibles de inmediato.',
    },
    storyByCharacter: {
      emily: 'Emily organiza las columnas por sucursal, puesto y horario. Su disciplina le permite revisar en minutos si una cafetería está preparada para operar antes de una apertura.',
      juanito: 'Juanito tiende a querer ver todos los números al mismo tiempo. Configurar columnas le ayuda a concentrarse: cuando revisa personal, deja visibles tienda, puesto, estado y costo laboral, y oculta lo que no necesita en ese momento.',
      camila: 'Camila antes buscaba la información preguntando a cada familiar. Ahora configura una vista con área, puesto y estado para consultar responsabilidades sin depender de conversaciones dispersas.',
    },
  },
  {
    id: 'search',
    emoji: '🔎',
    kind: 'Herramienta de búsqueda',
    title: 'Buscar colaborador',
    purpose: 'Localiza rápidamente una persona por nombre, código o puesto.',
    behavior: 'Reduce la tabla mientras escribes y muestra únicamente las coincidencias.',
    whenToUse: 'Úsalo antes de editar, consultar documentos o realizar una acción sobre una persona específica.',
    tipByCharacter: {
      emily: 'Busca por puesto cuando necesites localizar perfiles similares entre distintas sucursales.',
      juanito: 'Usa códigos consistentes para encontrar personas aunque existan nombres repetidos.',
      camila: 'Asigna códigos incluso a familiares para que el expediente sea tan claro como el de cualquier colaborador.',
    },
    storyByCharacter: {
      emily: 'Emily recibe una duda sobre una gerente y la encuentra por nombre sin recorrer listas de todas las sucursales. Responde rápido y evita interrumpir a otros responsables.',
      juanito: 'Cuando una tienda reporta un problema, Juanito busca al encargado por código o puesto. Así encuentra el expediente correcto sin confiar en que recordará apellidos o teléfonos.',
      camila: 'Camila localiza a un vendedor por nombre antes de revisar sus documentos. Ya no necesita buscar entre carpetas físicas ni preguntar quién guardó la información.',
    },
  },
  {
    id: 'unit-filter',
    emoji: '🏢',
    kind: 'Filtro operativo',
    title: 'Filtrar por unidad',
    purpose: 'Separa al personal según la unidad organizacional a la que pertenece.',
    behavior: 'Muestra únicamente colaboradores vinculados con la unidad seleccionada.',
    whenToUse: 'Úsalo para revisar oficinas, regiones o estructuras administrativas por separado.',
    tipByCharacter: {
      emily: 'Compara unidades con la misma regla para detectar diferencias de estructura.',
      juanito: 'Separa oficinas y operación de tiendas para no mezclar costos ni responsabilidades.',
      camila: 'Distingue administración, mostrador y almacén aunque hoy compartan el mismo espacio.',
    },
    storyByCharacter: {
      emily: 'Emily filtra la unidad regional antes de revisar nuevas contrataciones. Su visión estratégica le ayuda a crecer por zonas sin mezclar estructuras distintas.',
      juanito: 'Juanito separa la oficina corporativa de la operación de tiendas. El filtro le evita comparar funciones administrativas con puestos de piso de venta.',
      camila: 'Camila crea unidades para administración y operación. Aunque todos se conocen, el filtro le muestra dónde está concentrando realmente al equipo.',
    },
  },
  {
    id: 'business-filter',
    emoji: '🏪',
    kind: 'Filtro operativo',
    title: 'Filtrar por empresa o negocio',
    purpose: 'Permite revisar colaboradores de una empresa, sucursal o línea operativa concreta.',
    behavior: 'Limita la tabla al negocio seleccionado dentro de la unidad correspondiente.',
    whenToUse: 'Úsalo para analizar cobertura, expedientes o responsables de una operación específica.',
    tipByCharacter: {
      emily: 'Revisa cada cafetería por separado antes de comparar resultados entre sucursales.',
      juanito: 'Filtra una tienda antes de tomar decisiones de contratación basadas en sus números.',
      camila: 'Separa mostrador, almacén o futuras sucursales para saber qué operación necesita apoyo.',
    },
    storyByCharacter: {
      emily: 'Emily selecciona una cafetería y revisa solamente a su equipo. Así confirma cobertura y expedientes sin distraerse con las demás ubicaciones.',
      juanito: 'Juanito analiza una tienda con ventas bajas y filtra a su personal. Descubre si el problema es falta de cobertura, puestos mal asignados o información incompleta, no solo un número de venta.',
      camila: 'Camila filtra la refaccionaria principal para revisar quién atiende mostrador y quién opera almacén. Esto le ayuda a dejar de resolver cada ausencia personalmente.',
    },
  },
  {
    id: 'department-filter',
    emoji: '🧭',
    kind: 'Filtro organizacional',
    title: 'Filtrar por departamento',
    purpose: 'Agrupa a las personas según la función que cumplen dentro de la empresa.',
    behavior: 'Muestra únicamente integrantes del departamento seleccionado.',
    whenToUse: 'Úsalo para revisar equipos como ventas, almacén, administración u operaciones.',
    tipByCharacter: {
      emily: 'Usa departamentos consistentes en todas las sucursales para comparar equipos equivalentes.',
      juanito: 'No confundas ubicación con función: una misma tienda puede tener varios departamentos.',
      camila: 'Nombrar departamentos ayuda a separar relaciones familiares de responsabilidades laborales.',
    },
    storyByCharacter: {
      emily: 'Emily filtra Operaciones para verificar que cada cafetería tenga responsables preparados. Su organización transforma los estándares en una estructura repetible.',
      juanito: 'Juanito revisa solo Inventarios cuando aparecen diferencias de existencias. El filtro le ayuda a identificar responsables y conversar con el equipo adecuado, no con toda la tienda.',
      camila: 'Camila filtra Almacén para revisar funciones y documentos. Así puede pedir resultados por área sin convertir cada conversación en un asunto familiar.',
    },
  },
  {
    id: 'status-filter',
    emoji: '🚦',
    kind: 'Filtro de seguimiento',
    title: 'Filtrar por estado',
    purpose: 'Distingue colaboradores activos, inactivos o con relación terminada.',
    behavior: 'Actualiza la tabla para mostrar únicamente el estado laboral seleccionado.',
    whenToUse: 'Úsalo antes de nómina, auditorías de acceso o limpieza de expedientes.',
    tipByCharacter: {
      emily: 'Revisa inactivos antes de abrir una sucursal para evitar asignaciones equivocadas.',
      juanito: 'Compara activos contra nómina y accesos; las listas deben contar la misma historia.',
      camila: 'Actualiza el estado aunque la salida haya sido informal para conservar un historial confiable.',
    },
    storyByCharacter: {
      emily: 'Emily filtra colaboradores activos antes de planear horarios. Evita contar con alguien que ya no participa en la operación de una sucursal.',
      juanito: 'Juanito compara activos con sus cálculos de nómina. Como confía en los números, el filtro le permite detectar rápidamente personas que no deberían seguir generando pagos o accesos.',
      camila: 'Camila marca y filtra correctamente las salidas, incluso cuando se trata de conocidos. Así profesionaliza el historial sin borrar lo que ocurrió.',
    },
  },
  {
    id: 'edit-record',
    emoji: '✏️',
    kind: 'Acción del expediente',
    title: 'Editar colaborador',
    purpose: 'Actualiza información personal, laboral, salarial, documental o de asignación.',
    behavior: 'Abre el expediente existente y guarda los cambios sin crear un registro duplicado.',
    whenToUse: 'Úsalo cuando cambie un puesto, contacto, salario, documento, unidad o responsabilidad.',
    tipByCharacter: {
      emily: 'Actualiza los movimientos en cuanto ocurren para que todas las sucursales trabajen con información vigente.',
      juanito: 'No crees otro registro por cada cambio; conserva la continuidad del expediente.',
      camila: 'Formaliza los cambios de responsabilidad aunque se hayan acordado verbalmente.',
    },
    storyByCharacter: {
      emily: 'Emily promueve a una barista y edita su puesto y sucursal. El historial sigue concentrado y la nueva responsabilidad queda visible para todo el equipo.',
      juanito: 'Juanito cambia a un colaborador de tienda y actualiza el mismo expediente. Evita duplicarlo y mantiene consistentes los datos que después utilizará en sus reportes.',
      camila: 'Camila deja de asumir que todos saben quién cambió de función. Edita el puesto de su familiar y convierte el acuerdo verbal en información operativa.',
    },
  },
  {
    id: 'access',
    emoji: '🔐',
    kind: 'Acción de seguridad',
    title: 'Administrar acceso y PIN',
    purpose: 'Controla las credenciales que el colaborador utiliza en herramientas de asistencia y operación.',
    behavior: 'Permite crear, revisar o actualizar el acceso asociado con la persona.',
    whenToUse: 'Úsalo al incorporar personal, cambiar responsabilidades o resolver un acceso comprometido.',
    tipByCharacter: {
      emily: 'Entrega accesos según el puesto, no por comodidad ni antigüedad.',
      juanito: 'Revisa que cada acceso pertenezca a una sola persona para conservar trazabilidad.',
      camila: 'Evita compartir claves entre familiares; la confianza funciona mejor con responsabilidades identificables.',
    },
    storyByCharacter: {
      emily: 'Emily asigna accesos según el rol de cada gerente y barista. Protege la operación sin frenar el trabajo de las sucursales.',
      juanito: 'Juanito quiere que cada movimiento pueda explicarse. Por eso asigna un PIN individual: si aparece una diferencia, sabe qué registro revisar y con quién conversar.',
      camila: 'Camila reemplaza la contraseña compartida por accesos individuales. No se trata de desconfiar de su familia, sino de cuidar el negocio y aclarar responsabilidades.',
    },
  },
  {
    id: 'termination',
    emoji: '🚪',
    kind: 'Acción laboral',
    title: 'Terminar contrato o eliminar',
    purpose: 'Registra la salida de una persona y conserva el estado correcto de su expediente.',
    behavior: 'Termina la relación laboral; si el expediente ya está terminado y corresponde, permite eliminarlo definitivamente.',
    whenToUse: 'Úsalo al concluir una relación laboral y después de asegurar documentos, pagos y devolución de activos.',
    tipByCharacter: {
      emily: 'Cierra accesos, activos y responsabilidades como parte del mismo proceso de salida.',
      juanito: 'No borres primero: termina la relación para conservar datos útiles para nómina y análisis.',
      camila: 'Documenta la salida aunque exista cercanía personal; claridad no significa falta de empatía.',
    },
    storyByCharacter: {
      emily: 'Emily registra una salida y coordina accesos, activos y cobertura. Su disciplina evita que una sucursal quede con responsabilidades abandonadas.',
      juanito: 'Juanito antes quitaba nombres de sus listas y después sus números dejaban de cuadrar. Ahora termina el contrato, conserva el historial y cierra pendientes antes de eliminar cualquier dato.',
      camila: 'Camila documenta una salida familiar con respeto y claridad. Así protege la relación personal y evita que el negocio quede con acuerdos ambiguos.',
    },
  },
  {
    id: 'selection',
    emoji: '☑️',
    kind: 'Control de tabla',
    title: 'Seleccionar colaboradores',
    purpose: 'Marca una o varias filas para ejecutar acciones sobre un grupo.',
    behavior: 'Activa la barra de acciones masivas y conserva visible cuántas personas están seleccionadas.',
    whenToUse: 'Úsalo cuando el mismo cambio debe aplicarse a varias personas.',
    tipByCharacter: {
      emily: 'Filtra primero y selecciona después para evitar mezclar equipos de distintas sucursales.',
      juanito: 'Verifica el contador antes de aplicar un cambio masivo; ese número es tu control de seguridad.',
      camila: 'Selecciona por función para formalizar grupos completos sin editar persona por persona.',
    },
    storyByCharacter: {
      emily: 'Emily filtra una sucursal y selecciona a todo el equipo que cambiará de horario. Reduce trabajo repetido sin afectar otras ubicaciones.',
      juanito: 'Juanito revisa el contador de seleccionados antes de cambiar asignaciones. Su atención a los números se convierte en una salvaguarda para no modificar personas equivocadas.',
      camila: 'Camila selecciona a todo el equipo de almacén para ordenar sus asignaciones. Avanza más rápido y aplica el mismo criterio a todos.',
    },
  },
  {
    id: 'bulk-actions',
    emoji: '👥',
    kind: 'Barra de acciones masivas',
    title: 'Asignaciones masivas',
    purpose: 'Actualiza unidad, negocio, departamento o puesto para varios colaboradores a la vez.',
    behavior: 'Aplica el cambio seleccionado a todas las filas marcadas y actualiza sus expedientes.',
    whenToUse: 'Úsalo durante reorganizaciones, aperturas, movimientos de equipo o correcciones compartidas.',
    tipByCharacter: {
      emily: 'Haz un cambio por vez y confirma el grupo antes de continuar con la siguiente asignación.',
      juanito: 'Filtra, cuenta, selecciona y aplica: sigue siempre el mismo orden para reducir errores.',
      camila: 'Define primero la nueva estructura y después actualiza al grupo completo.',
    },
    storyByCharacter: {
      emily: 'Emily prepara una nueva cafetería y asigna al equipo completo a la sucursal. La acción masiva mantiene consistencia y evita capturas distintas para personas que comparten destino.',
      juanito: 'Juanito reorganiza una tienda siguiendo cuatro pasos: filtra, cuenta, selecciona y asigna. Su método numérico le permite mover al equipo sin perder a nadie en el proceso.',
      camila: 'Camila formaliza el departamento de Almacén y asigna al grupo completo. La estructura deja de existir solo en su cabeza y comienza a verse en el sistema.',
    },
  },
  {
    id: 'clear-selection',
    emoji: '🧹',
    kind: 'Botón de control',
    title: 'Limpiar selección',
    purpose: 'Desmarca el grupo actual y evita que una acción posterior se aplique a personas equivocadas.',
    behavior: 'Quita todas las marcas de la tabla y cierra la barra de acciones masivas.',
    whenToUse: 'Úsalo al terminar una acción grupal o cuando necesites construir una selección diferente.',
    tipByCharacter: {
      emily: 'Limpia la selección antes de cambiar de sucursal o comenzar una revisión nueva.',
      juanito: 'Confirma que el contador vuelva a cero; así sabes que el siguiente análisis inicia limpio.',
      camila: 'Cierra cada cambio masivo antes de pasar a otro equipo para no mezclar responsabilidades.',
    },
    storyByCharacter: {
      emily: 'Emily termina de actualizar al equipo de una cafetería y limpia la selección antes de abrir otra sucursal. Su disciplina evita que una acción cruce operaciones distintas.',
      juanito: 'Juanito verifica que el contador regrese a cero después de cada movimiento. Ese pequeño control le da la certeza numérica de que no arrastrará colaboradores a la siguiente acción.',
      camila: 'Camila limpia la selección después de organizar Almacén y luego comienza con Mostrador. Así profesionaliza un área a la vez sin mezclar personas.',
    },
  },
  {
    id: 'export',
    emoji: '📤',
    kind: 'Acción masiva',
    title: 'Exportar seleccionados',
    purpose: 'Genera un archivo con la información de los colaboradores seleccionados.',
    behavior: 'Descarga un CSV que puede revisarse, compartirse o utilizarse como respaldo de trabajo.',
    whenToUse: 'Úsalo para revisiones autorizadas, conciliaciones o análisis fuera del sistema.',
    tipByCharacter: {
      emily: 'Exporta solo la información necesaria y protege los datos personales del equipo.',
      juanito: 'Usa el archivo para analizar, pero conserva el sistema como fuente principal y actualizada.',
      camila: 'Evita crear nuevas listas manuales que después compitan con el expediente oficial.',
    },
    storyByCharacter: {
      emily: 'Emily exporta el equipo de una región para una revisión autorizada. Comparte únicamente lo necesario y mantiene el sistema como fuente oficial.',
      juanito: 'Juanito disfruta analizar datos en hojas de cálculo. Exporta una selección concreta, hace sus cálculos y recuerda que cualquier corrección debe volver al expediente, no quedarse aislada en el archivo.',
      camila: 'Camila entrega a su contador una selección ordenada en lugar de fotografías de libretas. Reduce aclaraciones y protege la consistencia de la información.',
    },
  },
  {
    id: 'table-navigation',
    emoji: '📊',
    kind: 'Controles de tabla',
    title: 'Ordenar y navegar la tabla',
    purpose: 'Organiza los registros y permite recorrerlos por páginas sin perder contexto.',
    behavior: 'Ordena al pulsar encabezados y cambia página o cantidad de filas desde los controles inferiores.',
    whenToUse: 'Úsalo para revisar listas extensas, detectar faltantes y trabajar en bloques manejables.',
    tipByCharacter: {
      emily: 'Ordena por sucursal o puesto para revisar la estructura siguiendo un criterio constante.',
      juanito: 'El orden cambia la lectura, no los datos; define primero qué pregunta quieres responder.',
      camila: 'Revisa por bloques pequeños y corrige un tipo de información cada vez.',
    },
    storyByCharacter: {
      emily: 'Emily ordena por puesto para comparar responsables entre sucursales. Su pensamiento estratégico detecta vacíos de estructura antes de que afecten el servicio.',
      juanito: 'Juanito ordena por estado o costo según la pregunta que analiza. Sabe que una tabla desordenada puede esconder señales aunque los números estén correctos.',
      camila: 'Camila recorre el equipo por páginas y revisa un bloque a la vez. El trabajo deja de sentirse interminable y puede completar la información con constancia.',
    },
  },
  {
    id: 'documents',
    emoji: '📁',
    kind: 'Función del expediente',
    title: 'Documentos del colaborador',
    purpose: 'Concentra la evidencia y documentación relacionada con cada persona.',
    behavior: 'Permite consultar, cargar, reemplazar o retirar archivos desde el expediente correspondiente.',
    whenToUse: 'Úsalo al contratar, actualizar documentos o completar información pendiente.',
    tipByCharacter: {
      emily: 'Define el mismo estándar documental para todas las sucursales y revísalo periódicamente.',
      juanito: 'Un dato sin evidencia puede fallar cuando más lo necesitas; completa el expediente antes de cerrar la revisión.',
      camila: 'Digitaliza los documentos aunque antes se guardaran en carpetas familiares o personales.',
    },
    storyByCharacter: {
      emily: 'Emily exige el mismo expediente documental en cada cafetería. Su disciplina permite crecer sin que cada gerente invente una forma distinta de guardar información.',
      juanito: 'Juanito aprendió que no todo se resuelve con un total correcto. Si falta un documento, el dato puede no servir cuando llega una revisión; por eso verifica que cada expediente tenga evidencia completa.',
      camila: 'Camila reúne documentos que antes estaban en carpetas, teléfonos y casas distintas. Digitalizarlos le da continuidad al negocio y evita depender de quién recuerda dónde se guardaron.',
    },
  },
] as const;
