const messages = {
  filters: ["Filtros", "Filters", "Filtres", "Filtros", "필터", "筛选"],
  search: ["Buscar", "Search", "Rechercher", "Buscar", "검색", "搜索"],
  clear: ["Limpiar filtros", "Clear filters", "Effacer les filtres", "Limpar filtros", "필터 지우기", "清除筛选"],
  periodToday: ["Hoy", "Today", "Aujourd’hui", "Hoje", "오늘", "今天"],
  periodWeek: ["Esta semana", "This week", "Cette semaine", "Esta semana", "이번 주", "本周"],
  periodMonth: ["Este mes", "This month", "Ce mois-ci", "Este mês", "이번 달", "本月"],
  periodLastMonth: ["Mes pasado", "Last month", "Mois dernier", "Mês passado", "지난달", "上月"],
  statusOnTime: ["Al corriente", "On time", "À jour", "Em dia", "정상", "正常"],
  statusDueSoon: ["Próximo a vencer", "Due soon", "Échéance proche", "Próximo do vencimento", "만기 임박", "即将到期"],
  statusOverdue: ["Vencido", "Overdue", "En retard", "Vencido", "연체", "逾期"],
  statusPartial: ["Pago parcial", "Partial payment", "Paiement partiel", "Pagamento parcial", "부분 지급", "部分付款"],
  statusPaid: ["Liquidado", "Paid", "Soldé", "Quitado", "완납", "已结清"],
  statusRestructured: ["Reestructurado", "Restructured", "Restructuré", "Reestruturado", "재조정", "已重组"],
  statusCancelled: ["Cancelado", "Cancelled", "Annulé", "Cancelado", "취소", "已取消"],

  title: ['Indicadores de Cartera','Receivables indicators','Indicateurs des créances','Indicadores de carteira','매출채권 지표','应收账款指标'],
  subtitle: ['Saldos, vencimientos y cobranza con el detalle que explica cada cifra.','Balances, due dates and collections with supporting detail.','Soldes, échéances et encaissements avec leurs détails.','Saldos, vencimentos e cobranças com seus detalhes.','잔액, 만기 및 수금의 근거 내역.','余额、到期与收款及其明细。'],
  overview: ['Resumen','Overview','Résumé','Resumo','요약','概览'],
  analysis: ['Análisis','Analysis','Analyse','Análise','분석','分析'],
  units: ['Por unidad','By unit','Par unité','Por unidade','사업부별','按部门'],
  details: ['Cuentas y cobros','Accounts and collections','Comptes et encaissements','Contas e recebimentos','계정 및 수금','账户与收款'],
  views: ['Vistas de indicadores','Indicator views','Vues des indicateurs','Vistas dos indicadores','지표 보기','指标视图'],
  refresh: ['Actualizar datos','Refresh data','Actualiser','Atualizar dados','새로 고침','刷新数据'],
  print: ['Imprimir reporte','Print report','Imprimer le rapport','Imprimir relatório','보고서 인쇄','打印报告'],
  context: ['Los saldos y atrasos son actuales. El periodo filtra únicamente los cobros por fecha de pago; no reconstruye saldos históricos.','Balances and arrears are current. The period filters collections by payment date only; it does not reconstruct historical balances.','Soldes et retards actuels. La période filtre uniquement les encaissements par date de paiement, sans reconstituer les soldes historiques.','Saldos e atrasos são atuais. O período filtra apenas recebimentos por data de pagamento, sem reconstruir saldos históricos.','잔액과 연체는 현재 기준입니다. 기간은 지급일별 수금에만 적용되며 과거 잔액을 재구성하지 않습니다.','余额和逾期均为当前值。期间仅按付款日期筛选收款，不重建历史余额。'],
  asOf: ['Fecha de corte','As of','Date de référence','Data de referência','기준일','截至日期'],
  period: ['Periodo de cobros','Collection period','Période des encaissements','Período de recebimentos','수금 기간','收款期间'],
  searchHelp: ['Cliente o folio de la cuenta','Customer or account reference','Client ou référence du compte','Cliente ou referência da conta','고객 또는 계정 번호','客户或账户编号'],
  unavailable: ['No disponible','Unavailable','Indisponible','Indisponível','사용 불가','不可用'],
  empty: ['No hay registros con estos filtros.','No records match these filters.','Aucun résultat pour ces filtres.','Nenhum registro com estes filtros.','필터에 해당하는 기록이 없습니다.','此筛选条件下没有记录。'],
  loading: ['Cargando indicadores…','Loading indicators…','Chargement des indicateurs…','Carregando indicadores…','지표 불러오는 중…','正在加载指标…'],
  sourceError: ['No se pudieron cargar los datos. Usa Actualizar datos para reintentar.','Data could not be loaded. Use Refresh data to retry.','Chargement impossible. Utilisez Actualiser pour réessayer.','Não foi possível carregar os dados. Use Atualizar dados para tentar novamente.','데이터를 불러오지 못했습니다. 새로 고침하세요.','无法加载数据，请刷新重试。'],
  moneyError: ['Hay importes sin conversión completa. Se muestran como no disponibles, nunca como cero.','Some amounts lack complete conversion. They are unavailable, never replaced with zero.','Certains montants ne sont pas entièrement convertis. Ils sont indisponibles, jamais remplacés par zéro.','Alguns valores não têm conversão completa. São indisponíveis, nunca substituídos por zero.','일부 금액의 환산이 불완전하여 0 대신 사용 불가로 표시됩니다.','部分金额换算不完整，显示不可用而非零。'],
  scheduleError: ['Cuentas sin calendario completo; los totales de atraso y próximos vencimientos no están disponibles','Accounts with incomplete schedules; overdue and upcoming totals are unavailable','Comptes sans échéancier complet; totaux en retard et à venir indisponibles','Contas com calendário incompleto; totais vencidos e próximos indisponíveis','일정이 불완전한 계정으로 연체 및 만기 합계를 표시할 수 없음','账户还款计划不完整，逾期和即将到期合计不可用'],
  dateError: ['Cobros con fecha inválida o futura excluidos','Collections with invalid or future dates excluded','Encaissements avec date invalide ou future exclus','Recebimentos com data inválida ou futura excluídos','유효하지 않거나 미래 날짜의 수금 제외','已排除日期无效或未来的收款'],
  balance: ['Saldo por cobrar','Outstanding balance','Solde à recouvrer','Saldo a receber','미수 잔액','应收余额'],
  balanceHelp: ['Saldo actual de cuentas vigentes con deuda, incluido el interés contratado.','Current debt on non-cancelled accounts, including contracted interest.','Dette actuelle des comptes non annulés, intérêts contractuels inclus.','Dívida atual de contas não canceladas, incluindo juros contratados.','취소되지 않은 계정의 현재 잔액이며 약정 이자를 포함합니다.','非取消账户的当前债务，包含约定利息。'],
  overdue: ['Cuotas vencidas','Overdue instalments','Échéances en retard','Parcelas vencidas','연체 할부금','逾期分期款'],
  overdueHelp: ['Saldo pendiente de cuotas con fecha anterior al corte; no usa el vencimiento final de la cuenta.','Unpaid instalments due before the cutoff, not the final account maturity.','Solde des échéances antérieures à la date de référence, pas à la maturité finale du compte.','Saldo de parcelas anteriores à data de referência, não ao vencimento final da conta.','계정 최종 만기가 아닌 기준일 이전 미납 할부금입니다.','按分期到期日早于截止日的未付款计算，不使用账户最终到期日。'],
  delinquency: ['Saldo en atraso','Overdue share','Part en retard','Parcela em atraso','연체 비중','逾期占比'],
  delinquencyHelp: ['Cuotas vencidas / saldo por cobrar, en la misma moneda de comparación.','Overdue instalments / outstanding balance in the same comparison currency.','Échéances en retard / solde à recouvrer, dans la même devise.','Parcelas vencidas / saldo a receber, na mesma moeda.','동일 통화 기준 연체 할부금 / 미수 잔액.','逾期分期款 / 应收余额，以同一比较货币计算。'],
  upcoming: ['Por vencer en 30 días','Due within 30 days','À échéance sous 30 jours','A vencer em 30 dias','30일 이내 만기','30天内到期'],
  upcomingHelp: ['Cuotas pendientes desde hoy hasta 30 días después, ambas fechas incluidas.','Unpaid instalments from today through 30 days ahead, inclusive.','Échéances impayées entre aujourd’hui et dans 30 jours, bornes incluses.','Parcelas pendentes de hoje até 30 dias depois, inclusive.','오늘부터 30일 후까지의 미납 할부금으로 양 끝 날짜를 포함합니다.','今天至30天后的待付分期款，包含首尾日期。'],
  collected: ['Cobrado en el periodo','Collected in period','Encaissé sur la période','Recebido no período','기간 내 수금','期间已收款'],
  collectedHelp: ['Pagos registrados por fecha de pago, incluidas cuentas ya liquidadas. No equivale a ventas del periodo.','Recorded payments by payment date, including settled accounts. Not period sales.','Paiements par date de paiement, comptes soldés inclus. Ce ne sont pas les ventes de la période.','Pagamentos por data de pagamento, incluindo contas liquidadas. Não equivale às vendas do período.','완납 계정도 포함한 지급일별 등록 수금이며 기간 매출과 다릅니다.','按付款日期记录的付款，包含已结清账户，不等于期间销售额。'],
  accounts: ['Cuentas con saldo','Accounts with debt','Comptes débiteurs','Contas com saldo','잔액 보유 계정','有余额账户'],
  accountsHelp: ['Cuentas no canceladas con saldo mayor a cero; un cliente puede tener varias.','Non-cancelled accounts with a positive balance; one customer may have several.','Comptes non annulés à solde positif; un client peut en avoir plusieurs.','Contas não canceladas com saldo positivo; um cliente pode ter várias.','잔액이 양수인 비취소 계정이며 고객 한 명이 여러 계정을 가질 수 있습니다.','余额大于零的非取消账户，同一客户可有多个账户。'],
  customers: ['Clientes identificados con deuda','Identified customers with debt','Clients identifiés débiteurs','Clientes identificados com dívida','식별된 채무 고객','已识别欠款客户'],
  customersHelp: ['Contactos únicos vinculados a cuentas con saldo. Las cuentas sin contacto se indican por separado.','Unique contacts linked to open accounts. Accounts without a contact are shown separately.','Contacts uniques liés aux comptes débiteurs. Comptes sans contact indiqués séparément.','Contatos únicos ligados a contas com saldo. Contas sem contato são indicadas separadamente.','잔액 계정에 연결된 고유 연락처 수이며 연락처 없는 계정은 별도 표시합니다.','关联欠款账户的唯一联系人，未关联联系人的账户单独标示。'],
  unlinked: ['Cuentas sin contacto vinculado','Accounts without a linked contact','Comptes sans contact lié','Contas sem contato vinculado','연결된 연락처 없는 계정','未关联联系人的账户'],
  evidence: ['Cobros con comprobante','Collections with receipts','Encaissements avec justificatif','Recebimentos com comprovante','증빙 있는 수금','附凭证收款'],
  evidenceHelp: ['Pagos con archivo / pagos del periodo. Un adjunto no significa conciliación bancaria.','Payments with a file / period payments. An attachment does not mean bank reconciliation.','Paiements avec fichier / paiements de la période. Une pièce jointe ne signifie pas rapprochement bancaire.','Pagamentos com arquivo / pagamentos do período. Um anexo não significa conciliação bancária.','파일 있는 지급 / 기간 지급. 첨부가 은행 대사를 의미하지는 않습니다.','附文件付款 / 期间付款。附件并不代表已完成银行对账。'],
  noSample: ['Sin base para medir','No measurement base','Aucune base de mesure','Sem base para medir','측정 기준 없음','无可测量基数'],
  aging: ['Antigüedad de cuotas pendientes','Ageing of unpaid instalments','Ancienneté des échéances impayées','Antiguidade das parcelas pendentes','미납 할부금 경과 기간','未付分期款账龄'],
  agingHelp: ['Saldo restante de cada cuota al corte. No es una reconstrucción histórica del saldo.','Remaining instalment balance at cutoff. Not a reconstruction of historical balances.','Solde restant par échéance à la date de référence, sans reconstitution historique.','Saldo restante por parcela na data de referência, sem reconstrução histórica.','기준일의 남은 할부 잔액으로 과거 잔액 재구성이 아닙니다.','截止日各期剩余余额，并非历史余额重建。'],
  current: ['Vigente y por vencer','Current and upcoming','Courant et à venir','Em dia e a vencer','현재 및 만기 예정','未到期'],
  days1to30: ['1–30 días','1–30 days','1–30 jours','1–30 dias','1–30일','1–30天'],
  days31to60: ['31–60 días','31–60 days','31–60 jours','31–60 dias','31–60일','31–60天'],
  days61to90: ['61–90 días','61–90 days','61–90 jours','61–90 dias','61–90일','61–90天'],
  days91plus: ['Más de 90 días','Over 90 days','Plus de 90 jours','Mais de 90 dias','90일 초과','超过90天'],
  undated: ['Sin fecha válida','No valid date','Sans date valide','Sem data válida','유효 날짜 없음','无有效日期'],
  trend: ['Cobros por mes','Monthly collections','Encaissements mensuels','Recebimentos por mês','월별 수금','月度收款'],
  trendHelp: ['Pagos registrados dentro del periodo seleccionado; el mes actual puede estar incompleto.','Payments within the selected period; the current month may be incomplete.','Paiements sur la période sélectionnée; le mois courant peut être incomplet.','Pagamentos no período selecionado; o mês atual pode estar incompleto.','선택한 기간 내 지급이며 당월은 미완료일 수 있습니다.','所选期间的付款，当前月份可能尚未结束。'],
  concentration: ['Concentración por cliente','Customer concentration','Concentration par client','Concentração por cliente','고객별 집중도','客户集中度'],
  concentrationHelp: ['Participación en el saldo actual. Sin contacto vinculado, cada cuenta se presenta por separado.','Share of current balance. Without a linked contact, each account is shown separately.','Part du solde actuel. Sans contact lié, chaque compte est présenté séparément.','Participação no saldo atual. Sem contato vinculado, cada conta aparece separadamente.','현재 잔액 비중이며 연락처 미연결 시 계정별로 표시합니다.','当前余额占比，未关联联系人的账户分别列出。'],
  unitHelp: ['Saldos actuales y cobros del periodo en la misma divisa. Selecciona una unidad para ver su detalle.','Current balances and period collections in one currency. Select a unit to see details.','Soldes actuels et encaissements dans une même devise. Sélectionnez une unité pour les détails.','Saldos atuais e recebimentos na mesma moeda. Selecione uma unidade para ver detalhes.','동일 통화의 현재 잔액 및 기간 수금입니다. 사업부를 선택하여 상세를 봅니다.','以同一货币比较当前余额和期间收款，选择部门查看明细。'],
  detailHelp: ['Importes en moneda original. Selecciona una cuenta para consultar sus cuotas y todo su historial de pagos.','Original currency amounts. Select an account for its instalments and complete payment history.','Montants en devise d’origine. Sélectionnez un compte pour ses échéances et son historique complet.','Valores na moeda original. Selecione uma conta para parcelas e histórico completo.','원래 통화 금액입니다. 계정을 선택하면 할부와 전체 지급 내역을 봅니다.','保留原币金额，选择账户查看分期和完整付款历史。'],
  payments: ['Cobros del periodo','Period collections','Encaissements de la période','Recebimentos do período','기간 수금','期间收款'],
  customer: ['Cliente / cuenta','Customer / account','Client / compte','Cliente / conta','고객 / 계정','客户 / 账户'],
  unit: ['Unidad','Unit','Unité','Unidade','사업부','部门'],
  business: ['Negocio','Business','Activité','Negócio','사업장','业务'],
  all: ['Todos','All','Tous','Todos','전체','全部'],
  unassigned: ['Sin asignar','Unassigned','Non attribué','Não atribuído','미배정','未分配'],
  share: ['Participación','Share','Part','Participação','비중','占比'],
  reference: ['Folio','Reference','Référence','Referência','번호','编号'],
  date: ['Fecha','Date','Date','Data','날짜','日期'],
  amount: ['Importe','Amount','Montant','Valor','금액','金额'],
  status: ['Estado','Status','Statut','Status','상태','状态'],
  days: ['Mayor atraso (días)','Oldest arrears (days)','Retard maximal (jours)','Maior atraso (dias)','최대 연체 일수','最大逾期天数'],
  receipt: ['Comprobante','Receipt','Justificatif','Comprovante','증빙','凭证'],
  yes: ['Con archivo','With file','Avec fichier','Com arquivo','파일 있음','有文件'],
  no: ['Sin archivo','Without file','Sans fichier','Sem arquivo','파일 없음','无文件'],
  updated: ['Actualizado','Updated','Actualisé','Atualizado','업데이트','更新时间'],
  consolidated: ['Consolidado en','Consolidated in','Consolidé en','Consolidado em','통합 통화','汇总货币'],
  native: ['Saldo en moneda original','Balance in original currency','Solde en devise d’origine','Saldo na moeda original','원래 통화 잔액','原币余额'],
  partial: ['Conversión incompleta','Incomplete conversion','Conversion incomplète','Conversão incompleta','변환 미완료','换算不完整'],
  excluded: ['Registros excluidos','Excluded records','Enregistrements exclus','Registros excluídos','제외 기록','已排除记录'],
  rate: ['Tipo de cambio diario','Daily exchange rate','Taux de change quotidien','Taxa de câmbio diária','일일 환율','每日汇率'],
  reportError: ['No se pudo preparar el reporte. Intenta de nuevo.','Could not prepare the report. Try again.','Impossible de préparer le rapport. Réessayez.','Não foi possível preparar o relatório. Tente novamente.','보고서를 준비하지 못했습니다. 다시 시도하세요.','无法生成报告，请重试。'],
  fullReport: ['Reporte completo del alcance filtrado','Complete report of the filtered scope','Rapport complet du périmètre filtré','Relatório completo do escopo filtrado','필터 범위 전체 보고서','所选范围完整报告'],
  attention: ['Seguimiento','Follow-up','Suivi','Acompanhamento','추적','跟进'],
  overdueAccounts: ['Cuentas con cuotas vencidas','Accounts with overdue instalments','Comptes avec échéances en retard','Contas com parcelas vencidas','연체 할부 계정','有逾期分期款的账户'],
  missingReceipts: ['Cobros sin comprobante','Collections without receipts','Encaissements sans justificatif','Recebimentos sem comprovante','증빙 없는 수금','无凭证收款'],
} satisfies Record<string, [string, string, string, string, string, string]>;
export type ReceivablesKpiCopy = { [K in keyof typeof messages]: string };
export function getReceivablesKpiCopy(locale: string): ReceivablesKpiCopy {
  const index = locale.startsWith('es') ? 0 : locale.startsWith('fr') ? 2 : locale.startsWith('pt') ? 3 : locale.startsWith('ko') ? 4 : locale.startsWith('zh') ? 5 : 1;
  return Object.fromEntries(Object.entries(messages).map(([key, values]) => [key, values[index]])) as ReceivablesKpiCopy;
}
