package com.indice.erp.kpis.currency;

import java.util.Locale;

public enum BasicModuleKpiMetric {
    SALES_TOTAL,
    SALES_COLLECTED,
    SALES_RECEIVABLE_BALANCE,
    SALES_TAX,
    SALES_COMMISSION,
    SALES_OPPORTUNITY_PIPELINE,
    SALES_OPPORTUNITY_WON,
    SALES_OPPORTUNITY_LOST,
    PRODUCT_INVENTORY_VALUE,
    PRODUCT_ESTIMATED_PROFIT,
    INVENTORY_BALANCE_VALUE,
    INVENTORY_MOVEMENT_VALUE,
    EXPENSE_TOTAL,
    EXPENSE_PAID,
    EXPENSE_PAID_TO_DATE,
    EXPENSE_ACTUAL,
    EXPENSE_SUBTOTAL,
    EXPENSE_TAX,
    EXPENSE_BALANCE,
    EXPENSE_OVERDUE_BALANCE,
    EXPENSE_DUE_SOON_BALANCE,
    BUDGET_PLANNED,
    BUDGET_COMMITTED,
    BUDGET_ACTUAL,
    BUDGET_AVAILABLE,
    RECEIVABLE_BALANCE,
    RECEIVABLE_INSTALLMENT_BALANCE,
    RECEIVABLE_PAYMENT_AMOUNT,
    CREDIT_POLICY_LINE,
    CREDIT_POLICY_AVAILABLE,
    CREDIT_SALES_TOTAL_PAYABLE,
    CREDIT_SALES_MONTHLY_PAYMENT,
    CREDIT_SALES_INTEREST,
    PETTY_CASH_CUSTODY_BALANCE,
    PETTY_CASH_CUSTODY_STATEMENT_FUNDED,
    PETTY_CASH_CUSTODY_STATEMENT_SHORTAGE,
    PETTY_CASH_CUSTODY_SETTLEMENT_AMOUNT,
    PETTY_CASH_CUSTODY_SETTLEMENT_AUTHORIZED,
    PETTY_CASH_CUSTODY_SETTLEMENT_PENDING,
    PETTY_CASH_BALANCE,
    PETTY_CASH_LIMIT,
    PETTY_CASH_STATEMENT_OPENING,
    PETTY_CASH_STATEMENT_FUNDED,
    PETTY_CASH_STATEMENT_ESTIMATED,
    PETTY_CASH_STATEMENT_VERIFIED,
    PETTY_CASH_STATEMENT_CLOSING,
    PETTY_CASH_STATEMENT_PENDING,
    PETTY_CASH_STATEMENT_SHORTAGE,
    PETTY_CASH_MOVEMENT_AMOUNT,
    PETTY_CASH_SETTLEMENT_AMOUNT,
    PAYMENT_ACCOUNT_BALANCE,
    HR_ASSET_VALUE,
    HR_EMPLOYEE_MONTHLY_PAYROLL,
    HR_INCENTIVE_AMOUNT,
    PAYROLL_NET_AMOUNT,
    POS_SALES_TOTAL,
    POS_CLOSING_TOTAL,
    POS_CLOSING_CASH_SALES,
    POS_CLOSING_CARD_SALES,
    POS_CLOSING_TRANSFER_SALES,
    POS_CLOSING_CREDIT_SALES,
    POS_CLOSING_EXPECTED_CASH,
    POS_CLOSING_COUNTED_CASH,
    POS_CLOSING_DIFFERENCE,
    POS_CLOSING_ABSOLUTE_DIFFERENCE,
    POS_CLOSING_SHORTAGE,
    POS_CLOSING_OVERAGE,
    POS_CLOSING_REFUNDS,
    PURCHASE_ORDER_TOTAL,
    SUPPLIER_SUBMISSION_TOTAL;

    public static BasicModuleKpiMetric parse(String value) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("metric is required");
        }
        try {
            return valueOf(value.trim().replace('-', '_').toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("Unsupported monetary KPI metric: " + value);
        }
    }
}
