const en = {
  changeStatus: 'Change status', paid: 'Paid', pending: 'Pending', overdue: 'Overdue',
  importStatus: 'Import expenses as', importPaidHint: 'Records the full payment from each selected account, on the expense date.',
  importPendingHint: 'Creates unpaid expenses with the selected due date. Selecting an account does not record a payment.',
  taxHint: 'Checked amounts already include the selected tax. Currency:', includesTax: 'Includes tax',
  tax: 'Tax for this import', taxRate: 'Tax rate (%)', taxRequired: 'Select a positive tax rate.',
  dateRequired: 'Select a valid date.', dueDate: 'Due date', paymentDate: 'Payment date', account: 'Payment account',
  importDateInvalid: 'Paid expenses require a date no later than today. Use Pending for a future expense.',
  status: 'New status', cancel: 'Cancel', apply: 'Apply to selection', choose: 'Select an account',
  paidHint: 'Records the remaining balance of every selected expense as a payment. Existing payments are preserved.',
  pendingHint: 'Sets a due date today or later. Existing partial payments are preserved.',
  overdueHint: 'Sets a due date before today. The original expense date and existing payments are preserved.',
  protected: 'Only open expenses with a remaining balance can use this action. Fund, linked, posted, closed and paid records require their source workflow.',
  currencies: 'Pay expenses in one currency per batch and select an active account in that currency.',
  paymentDateInvalid: 'The payment date must be between the latest expense date and today.',
  pendingDateInvalid: 'Use today or a later due date.', overdueDateInvalid: 'Use a due date before today.',
  limit: 'Select up to 200 expenses.', selected: 'selected expenses',
};
const es: typeof en = {
  changeStatus: 'Cambiar estatus', paid: 'Pagados', pending: 'Pendientes', overdue: 'Vencidos',
  importStatus: 'Importar gastos como', importPaidHint: 'Registra el pago completo desde la cuenta elegida en cada fila, con la fecha del gasto.',
  importPendingHint: 'Crea gastos sin pagar con la fecha de vencimiento seleccionada. Elegir cuenta no registra un pago.',
  taxHint: 'Los montos con palomita ya incluyen el impuesto seleccionado. Moneda:', includesTax: 'Incluye impuesto',
  tax: 'Impuesto de esta carga', taxRate: 'Tasa de impuesto (%)', taxRequired: 'Selecciona una tasa de impuesto mayor a cero.',
  dateRequired: 'Selecciona una fecha válida.', dueDate: 'Fecha de vencimiento', paymentDate: 'Fecha de pago', account: 'Cuenta de pago',
  importDateInvalid: 'Los gastos pagados requieren una fecha hasta hoy. Usa Pendientes para gastos futuros.',
  status: 'Nuevo estatus', cancel: 'Cancelar', apply: 'Aplicar a la selección', choose: 'Selecciona una cuenta',
  paidHint: 'Registra como pago el saldo restante de cada gasto seleccionado. Los abonos anteriores se conservan.',
  pendingHint: 'Establece el vencimiento hoy o después. Los pagos parciales existentes se conservan.',
  overdueHint: 'Establece un vencimiento anterior a hoy. Conserva la fecha original del gasto y los pagos existentes.',
  protected: 'Esta acción requiere gastos abiertos con saldo. Los registros de fondos, vinculados, contabilizados, cerrados o pagados requieren su operación de origen.',
  currencies: 'Paga gastos de una misma moneda por lote y elige una cuenta activa en esa moneda.',
  paymentDateInvalid: 'La fecha de pago debe estar entre la fecha más reciente de los gastos y hoy.',
  pendingDateInvalid: 'El vencimiento debe ser hoy o después.', overdueDateInvalid: 'El vencimiento debe ser anterior a hoy.',
  limit: 'Selecciona hasta 200 gastos.', selected: 'gastos seleccionados',
};
export const getExpenseWorkflowCopy = (locale: string) => locale.toLowerCase().startsWith('es') ? es : en;
