import { AlertTriangle, Banknote, CreditCard, Download, Printer, ReceiptText, TrendingDown, TrendingUp } from 'lucide-react';
import { useRef, type ReactNode } from 'react';
import { escapeDocumentPrintHtml, printDocumentHtml } from '../../../shared/print/documentHtmlPrintEngine';
import { CortesModalFrame } from './CortesModalFrame';
import type { PosCashClosingDetailResponse } from '../types/cashClosingHistory.types';
import { formatCurrency, formatDateTime, getPaymentTotal, toNumber } from '../utils/cortesUtils';

interface CorteDetailModalProps {
  detail: PosCashClosingDetailResponse | null;
  error: string;
  loading: boolean;
  open: boolean;
  onClose: () => void;
  onDownload: () => void;
}

export function CorteDetailModal({
  detail,
  error,
  loading,
  open,
  onClose,
  onDownload,
}: CorteDetailModalProps) {
  const documentRef = useRef<HTMLDivElement>(null);
  const currencyCode = detail?.shift?.currencyCode ?? 'MXN';
  const difference = toNumber(detail?.overShortAmount);
  const handlePrint = () => {
    if (!detail || !documentRef.current) return;
    const folio = `COR-${detail.id}`;
    printDocumentHtml({
      bodyHtml: `
        <main class="print-corte">
          <header class="print-header">
            <div><p>Control de caja</p><h1>Detalle de corte</h1></div>
            <div class="print-meta"><strong>${escapeDocumentPrintHtml(folio)}</strong><span>${escapeDocumentPrintHtml(formatDateTime(detail.closedAt))}</span></div>
          </header>
          ${documentRef.current.outerHTML}
          <footer class="print-footer"><span>Generated by Indice</span><span>${escapeDocumentPrintHtml(folio)}</span></footer>
        </main>`,
      contentStyles: `
        body { padding: 12mm 14mm 10mm; }
        .print-corte { color: #24272c; }
        .print-header { align-items: end; border-bottom: 1px solid #cfd4d8; display: flex; justify-content: space-between; margin-bottom: 8mm; padding-bottom: 4mm; }
        .print-header p, .print-header h1 { margin: 0; }
        .print-header p { color: #68717b; font-size: 9pt; font-weight: 400; }
        .print-header h1 { font-size: 24pt; font-weight: 500; margin-top: 2mm; }
        .print-meta { display: grid; font-size: 9pt; gap: 1mm; text-align: right; }
        .print-meta strong { font-weight: 500; }
        .print-footer { border-top: 1px solid #d8dadd; color: #737b84; display: flex; font-size: 8pt; justify-content: space-between; margin-top: 8mm; padding-top: 3mm; }
        [class*="shadow"] { box-shadow: none !important; }
        section, [class*="rounded"] { break-inside: avoid; }
      `,
      documentTitle: `cash-closing_${folio}`,
      includeApplicationStyles: true,
      locale: 'es-MX',
      pageSize: 'a4',
    });
  };

  return (
    <CortesModalFrame
      modalType="operational-workspace"
      closeLabel="Cerrar detalle de corte"
      eyebrow="Detalle operativo"
      icon={<ReceiptText className="h-5 w-5" />}
      onClose={onClose}
      open={open}
      size="xl"
      title="Detalle de corte"
      subtitle={detail ? `COR-${detail.id} - ${formatDateTime(detail.closedAt)}` : 'Cargando información del cierre'}
      footer={(
        <div className="flex flex-col gap-3 sm:flex-row sm:justify-end">
          <button
            type="button"
            onClick={handlePrint}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-slate-200 px-5 text-sm font-medium text-slate-700 transition hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"
          >
            <Printer className="h-4 w-4" />
            Imprimir
          </button>
          <button
            type="button"
            onClick={onDownload}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#222831] px-5 text-sm font-medium text-white shadow-sm transition hover:bg-[#111827]"
          >
            <Download className="h-4 w-4" />
            Descargar
          </button>
        </div>
      )}
    >
      {loading ? (
        <div className="rounded-lg border border-blue-200 bg-blue-50 px-5 py-4 text-sm font-medium text-blue-800 dark:border-blue-500/30 dark:bg-blue-500/10 dark:text-blue-200">
          Cargando detalle real del corte...
        </div>
      ) : null}

      {error ? (
        <div className="rounded-lg border border-rose-200 bg-rose-50 px-5 py-4 text-sm font-medium text-rose-800 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-200">
          {error}
        </div>
      ) : null}

      {detail ? (
        <div ref={documentRef} className="space-y-5">
          <section className="grid gap-4 lg:grid-cols-[1.4fr_1fr]">
            <div className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="text-xs font-medium tracking-normal text-[#B63B32] dark:text-[#FFB0AA]">Corte operativo</p>
                  <h4 className="mt-2 text-2xl font-medium text-slate-950 dark:text-white">
                    Caja {detail.cashRegister?.name ?? detail.cashRegisterId}
                  </h4>
                  <p className="mt-1 text-sm font-medium text-slate-500 dark:text-slate-400">
                    Almacen {detail.warehouseId} - Turno {detail.shiftId} - Usuario {detail.closedByUserId}
                  </p>
                </div>
                <span className={`rounded-full px-3 py-1 text-xs font-medium ${
                  difference === 0
                    ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-200'
                    : 'bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-200'
                }`}>
                  {difference === 0 ? 'Cuadrado' : 'Con diferencia'}
                </span>
              </div>

              <div className="mt-5 grid gap-3 sm:grid-cols-3">
                <InfoTile label="Apertura" value={formatDateTime(detail.shift?.openedAt)} />
                <InfoTile label="Cierre" value={formatDateTime(detail.closedAt)} />
                <InfoTile label="Moneda" value={currencyCode} />
              </div>
            </div>

            <div className="rounded-lg border border-[#FF6B5E]/20 bg-[#FF6B5E]/10 p-5 shadow-sm dark:border-[#FF6B5E]/25 dark:bg-[#FF6B5E]/15">
              <p className="text-xs font-medium tracking-normal text-[#B63B32] dark:text-[#FFB0AA]">Resumen</p>
              <p className="mt-3 text-4xl font-medium text-slate-950 dark:text-white">
                {formatCurrency(toNumber(detail.totalSalesAmount), currencyCode)}
              </p>
              <p className="mt-1 text-sm font-medium text-slate-600 dark:text-slate-300">
                {detail.ticketsCount} ticket(s) procesado(s)
              </p>
            </div>
          </section>

          <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <MetricCard icon={<Banknote className="h-5 w-5" />} label="Efectivo esperado" value={formatCurrency(toNumber(detail.expectedCashAmount), currencyCode)} />
            <MetricCard icon={<Banknote className="h-5 w-5" />} label="Efectivo contado" value={formatCurrency(toNumber(detail.countedCashAmount), currencyCode)} />
            <MetricCard icon={<AlertTriangle className="h-5 w-5" />} label="Diferencia" value={`${difference > 0 ? '+' : ''}${formatCurrency(difference, currencyCode)}`} tone={difference === 0 ? 'success' : 'warning'} />
            <MetricCard icon={<ReceiptText className="h-5 w-5" />} label="Devoluciones" value={formatCurrency(toNumber(detail.totalRefundsAmount), currencyCode)} />
          </section>

          <section className="grid gap-5 lg:grid-cols-2">
            <DetailSection icon={<CreditCard className="h-5 w-5" />} title="Metodos de pago">
              <LineItem label="Efectivo" value={formatCurrency(getPaymentTotal(detail, 'CASH'), currencyCode)} />
              <LineItem label="Tarjeta" value={formatCurrency(getPaymentTotal(detail, 'CARD'), currencyCode)} />
              <LineItem label="Transferencia" value={formatCurrency(getPaymentTotal(detail, 'TRANSFER'), currencyCode)} />
              <LineItem label="Wallet / vales" value={formatCurrency(getPaymentTotal(detail, 'WALLET'), currencyCode)} />
            </DetailSection>

            <DetailSection icon={<TrendingUp className="h-5 w-5" />} title="Movimientos de efectivo">
              <LineItem label="Apertura" value={formatCurrency(toNumber(detail.openingCashAmount), currencyCode)} />
              <LineItem label="Ventas efectivo" value={formatCurrency(toNumber(detail.cashSalesAmount), currencyCode)} />
              <LineItem label="Entradas" value={formatCurrency(toNumber(detail.cashInAmount), currencyCode)} />
              <LineItem label="Correcciones" value={formatCurrency(toNumber(detail.correctionAmount), currencyCode)} />
            </DetailSection>

            <DetailSection icon={<TrendingDown className="h-5 w-5" />} title="Salidas y retiros">
              <LineItem label="Salidas" value={formatCurrency(toNumber(detail.cashOutAmount), currencyCode)} />
              <LineItem label="Retiros a caja fuerte" value={formatCurrency(toNumber(detail.safeDropAmount), currencyCode)} />
              <LineItem label="Diferencia operativa" value={formatCurrency(difference, currencyCode)} />
            </DetailSection>

            <DetailSection icon={<ReceiptText className="h-5 w-5" />} title="Bitacora">
              <LineItem label="Caja" value={detail.cashRegister?.code ?? `Caja ${detail.cashRegisterId}`} />
              <LineItem label="Unidad" value={detail.unitId ? `Unidad ${detail.unitId}` : 'Sin unidad registrada'} />
              <LineItem label="Negocio" value={detail.businessId ? `Negocio ${detail.businessId}` : 'Sin negocio registrado'} />
              <LineItem label="Notas" value={detail.notes || 'Sin notas'} />
            </DetailSection>
          </section>
        </div>
      ) : null}
    </CortesModalFrame>
  );
}

function InfoTile({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800">
      <p className="text-xs font-medium tracking-normal text-slate-500 dark:text-slate-400">{label}</p>
      <p className="mt-2 text-sm font-medium text-slate-950 dark:text-white">{value}</p>
    </div>
  );
}

function MetricCard({
  icon,
  label,
  tone = 'neutral',
  value,
}: {
  icon: ReactNode;
  label: string;
  tone?: 'neutral' | 'success' | 'warning';
  value: string;
}) {
  const toneClass = tone === 'success'
    ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200'
    : tone === 'warning'
    ? 'border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200'
    : 'border-slate-200 bg-white text-slate-950 dark:border-slate-700 dark:bg-slate-900 dark:text-white';

  return (
    <div className={`rounded-lg border p-5 shadow-sm ${toneClass}`}>
      <div className="flex items-center gap-2 text-slate-500 dark:text-slate-300">
        {icon}
        <p className="text-xs font-medium tracking-normal">{label}</p>
      </div>
      <p className="mt-4 text-2xl font-medium">{value}</p>
    </div>
  );
}

function DetailSection({
  children,
  icon,
  title,
}: {
  children: ReactNode;
  icon: ReactNode;
  title: string;
}) {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900">
      <div className="flex items-center gap-2 text-[#FF6B5E]">
        {icon}
        <h4 className="text-lg font-medium text-slate-950 dark:text-white">{title}</h4>
      </div>
      <div className="mt-4 space-y-3">{children}</div>
    </div>
  );
}

function LineItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-2 last:border-b-0 last:pb-0 dark:border-slate-800">
      <span className="text-sm font-medium text-slate-500 dark:text-slate-400">{label}</span>
      <span className="text-right text-sm font-medium text-slate-950 dark:text-white">{value}</span>
    </div>
  );
}
