package com.indice.erp.finance.pettycash.dto;

import com.fasterxml.jackson.databind.JsonNode;
import com.indice.erp.finance.pettycash.PettyCashFundStatus;
import com.indice.erp.finance.pettycash.PettyCashFundType;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

public record PettyCashFundResponse(
    Long id,
    Long companyId,
    Long unitId,
    Long businessId,
    Long budgetId,
    Long budgetLineId,
    Long paymentAccountId,
    Long fundingSourcePaymentAccountId,
    Long responsibleUserId,
    PettyCashFundType fundType,
    String name,
    String currencyCode,
    BigDecimal limitAmount,
    BigDecimal currentBalanceAmount,
    Integer cutOffDay,
    String fundingSourceName,
    String externalOwnerType,
    String externalOwnerName,
    String externalOwnerRelationship,
    String externalOwnerReference,
    String statementRecipientEmail,
    String managedAssetType,
    String managedAssetName,
    String managedAssetReference,
    Boolean externalIdentityPending,
    Boolean budgetLinkPending,
    List<String> fundingMethods,
    List<String> spendingMethods,
    Boolean kioskEnabled,
    Boolean kioskUsesUniversalPin,
    String kioskAccessUrl,
    String kioskPublicToken,
    PettyCashFundStatus status,
    Long createdByUserId,
    Long updatedByUserId,
    Instant createdAt,
    Instant updatedAt,
    Instant deletedAt,
    Long version,
    JsonNode customFields,
    JsonNode metadata,
    List<PettyCashManagedAsset> managedAssets,
    Long pendingTypeChangeId,
    PettyCashFundType pendingFundType,
    LocalDate pendingTypeEffectiveDate
) {
}
