import type {
  EmployeePerformanceStatus,
  ProcessEmployeePerformanceRow,
  ProcessKpiCard,
  ProcessKpiCategory,
  ProcessKpiStatus,
} from './types';

export const processKpiCards: ProcessKpiCard[] = [
  {
    id: 'opi',
    title: 'Operational Performance Index (OPI)',
    description: 'Combines compliance, quality, and punctuality into the overall business score.',
    category: 'main-product',
    displayType: 'percentage',
    currentValue: 89,
    targetValue: 92,
    displayValue: '89%',
    targetLabel: 'Target 92%',
    trendLabel: '+4 pts vs last month',
    trendDirection: 'up',
    status: 'watch',
    unit: 'Operations',
    business: 'Commercial',
    employee: 'All employees',
    supportText: 'This is the primary product KPI and the first metric the owner should review.',
    featured: true,
  },
  {
    id: 'overall-compliance',
    title: '% Overall Compliance',
    description: 'Measures how consistently the execution plan is completed across the operation.',
    category: 'business',
    displayType: 'percentage',
    currentValue: 92,
    targetValue: 90,
    displayValue: '92%',
    targetLabel: 'Target 90%',
    trendLabel: '+3 pts vs previous cycle',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Operations',
    business: 'Commercial',
    employee: 'All employees',
    supportText: 'A strong compliance rate shows the plan is being executed as expected.',
  },
  {
    id: 'tasks-on-time',
    title: '% Tasks on Time',
    description: 'Shows how disciplined the operation is when delivering tasks by commitment date.',
    category: 'business',
    displayType: 'percentage',
    currentValue: 87,
    targetValue: 90,
    displayValue: '87%',
    targetLabel: 'Target 90%',
    trendLabel: '-1 pt vs previous week',
    trendDirection: 'down',
    status: 'watch',
    unit: 'Operations',
    business: 'Operations',
    employee: 'All employees',
    supportText: 'This KPI surfaces daily discipline and follow-through on committed work.',
  },
  {
    id: 'average-rating',
    title: 'Average Rating',
    description: 'Reflects actual quality validated by supervision or audit review.',
    category: 'business',
    displayType: 'rating',
    currentValue: 4.7,
    targetValue: 4.5,
    displayValue: '4.7 / 5',
    targetLabel: 'Target 4.5 / 5',
    trendLabel: '+0.2 vs previous review',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Operations',
    business: 'Commercial',
    employee: 'All employees',
    supportText: 'Supervision is validating a sustained quality level across the operation.',
  },
  {
    id: 'overdue-tasks',
    title: '% Overdue Tasks',
    description: 'Measures the level of disorganization and operational risk in execution.',
    category: 'business',
    displayType: 'percentage',
    currentValue: 11,
    targetValue: 8,
    displayValue: '11%',
    targetLabel: 'Target 8%',
    trendLabel: '+2 pts overdue exposure',
    trendDirection: 'down',
    status: 'critical',
    unit: 'Operations',
    business: 'Administration',
    employee: 'All employees',
    supportText: 'A rising overdue rate is a direct signal of execution friction and follow-up gaps.',
    inverseGoal: true,
  },
  {
    id: 'projects-at-risk',
    title: '% Projects at Risk',
    description: 'Provides immediate strategic visibility into the portfolio health.',
    category: 'business',
    displayType: 'percentage',
    currentValue: 18,
    targetValue: 12,
    displayValue: '18%',
    targetLabel: 'Target 12%',
    trendLabel: '+3 flagged projects',
    trendDirection: 'down',
    status: 'critical',
    unit: 'Technology',
    business: 'Operations',
    employee: 'Jorge Herrera',
    supportText: 'This KPI helps leadership identify where intervention is needed before deadlines slip further.',
    inverseGoal: true,
  },
  {
    id: 'task-closure-time',
    title: 'Average Task Closure Time',
    description: 'Tracks operational speed from assignment to final completion.',
    category: 'operational',
    displayType: 'days',
    currentValue: 2.8,
    targetValue: 3.2,
    displayValue: '2.8 days',
    targetLabel: 'Target 3.2 days',
    trendLabel: '-0.4 days faster',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Operations',
    business: 'Commercial',
    employee: 'Daniela Solis',
    supportText: 'Faster closure times indicate better coordination and fewer blockers in execution.',
    inverseGoal: true,
  },
  {
    id: 'productivity-per-employee',
    title: 'Productivity per Employee',
    description: 'Measures how many tasks each person completes within the expected operating cadence.',
    category: 'operational',
    displayType: 'tasks',
    currentValue: 28,
    targetValue: 24,
    displayValue: '28 tasks',
    targetLabel: 'Target 24 tasks',
    trendLabel: '+5 completed this cycle',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Operations',
    business: 'Commercial',
    employee: 'Daniela Solis',
    supportText: 'Useful for spotting individual output and team capacity differences.',
  },
  {
    id: 'compliance-per-employee',
    title: 'Compliance per Employee (%)',
    description: 'Highlights who is consistently compliant versus who is falling behind.',
    category: 'operational',
    displayType: 'percentage',
    currentValue: 93,
    targetValue: 90,
    displayValue: '93%',
    targetLabel: 'Target 90%',
    trendLabel: '+2 pts in the latest cut',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Human Resources',
    business: 'People',
    employee: 'Marta Ruiz',
    supportText: 'A direct way to compare execution consistency between collaborators.',
  },
  {
    id: 'employee-rating',
    title: 'Employee Rating',
    description: 'Shows who consistently delivers work with the highest verified quality.',
    category: 'operational',
    displayType: 'rating',
    currentValue: 4.8,
    targetValue: 4.5,
    displayValue: '4.8 / 5',
    targetLabel: 'Target 4.5 / 5',
    trendLabel: '+0.3 audit score',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Human Resources',
    business: 'People',
    employee: 'Marta Ruiz',
    supportText: 'This KPI helps identify employees who execute with strong quality standards.',
  },
  {
    id: 'average-project-progress',
    title: 'Average Project Progress (%)',
    description: 'Summarizes overall portfolio advancement across active projects.',
    category: 'project',
    displayType: 'percentage',
    currentValue: 76,
    targetValue: 80,
    displayValue: '76%',
    targetLabel: 'Target 80%',
    trendLabel: '+5 pts this month',
    trendDirection: 'up',
    status: 'watch',
    unit: 'Technology',
    business: 'Operations',
    employee: 'Jorge Herrera',
    supportText: 'An aggregated view of how much project work is already completed.',
  },
  {
    id: 'projects-on-time',
    title: '% Projects on Time',
    description: 'Tracks how healthy the project portfolio is against expected delivery timing.',
    category: 'project',
    displayType: 'percentage',
    currentValue: 84,
    targetValue: 85,
    displayValue: '84%',
    targetLabel: 'Target 85%',
    trendLabel: '+1 pt recovered',
    trendDirection: 'up',
    status: 'watch',
    unit: 'Technology',
    business: 'Operations',
    employee: 'Jorge Herrera',
    supportText: 'Keeps the focus on deadline reliability and portfolio confidence.',
  },
  {
    id: 'recurring-process-compliance',
    title: '% Compliance of Recurring Processes',
    description: 'Measures whether the recurring operation is truly standardized and executed as designed.',
    category: 'process',
    displayType: 'percentage',
    currentValue: 88,
    targetValue: 90,
    displayValue: '88%',
    targetLabel: 'Target 90%',
    trendLabel: '+4 pts after recent standardization',
    trendDirection: 'up',
    status: 'watch',
    unit: 'Operations',
    business: 'Administration',
    employee: 'Daniela Solis',
    supportText: 'This is the differentiator KPI that shows how mature the standardized operation really is.',
  },
  {
    id: 'active-vs-inactive-processes',
    title: 'Active vs. Inactive Processes',
    description: 'Represents the operational maturity level of the recurring process portfolio.',
    category: 'process',
    displayType: 'ratio',
    currentValue: 42,
    targetValue: 80,
    displayValue: '42 / 7',
    targetLabel: 'Target 80% active',
    trendLabel: '+3 activated processes',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Operations',
    business: 'Administration',
    employee: 'All employees',
    supportText: 'Current mix: 42 active processes versus 7 inactive processes.',
    secondaryValue: 7,
  },
  {
    id: 'performance-score-per-employee',
    title: 'Performance Score per Employee',
    description: 'Individual version of the operational score used for people performance reviews.',
    category: 'performance',
    displayType: 'score',
    currentValue: 91,
    targetValue: 88,
    displayValue: '91 / 100',
    targetLabel: 'Target 88 / 100',
    trendLabel: '+6 pts in the last evaluation',
    trendDirection: 'up',
    status: 'healthy',
    unit: 'Human Resources',
    business: 'People',
    employee: 'Carlos Lopez',
    supportText: 'Useful for HR and culture follow-up when performance needs to be visible at the individual level.',
  },
];

export const processKpiUnits = ['Operations', 'Finance', 'Human Resources', 'Technology'];

export const processKpiBusinesses = ['Administration', 'Commercial', 'Operations', 'People'];

export const processKpiEmployees = [
  'Andrea Molina',
  'Carlos Lopez',
  'Daniela Solis',
  'Jorge Herrera',
  'Marta Ruiz',
];

export const processKpiUnitAdjustments: Record<string, Partial<Record<ProcessKpiCategory, number>>> = {
  Operations: {
    'main-product': 2,
    business: 3,
    operational: 2,
    project: 1,
    process: 3,
    performance: 1,
  },
  Finance: {
    'main-product': -1,
    business: 1,
    operational: 0,
    project: -1,
    process: 1,
    performance: 0,
  },
  'Human Resources': {
    'main-product': 1,
    business: 1,
    operational: 2,
    project: 0,
    process: 1,
    performance: 4,
  },
  Technology: {
    'main-product': 1,
    business: -1,
    operational: 1,
    project: 4,
    process: 2,
    performance: 1,
  },
};

export const processKpiBusinessAdjustments: Record<string, Partial<Record<ProcessKpiCategory, number>>> = {
  Administration: {
    'main-product': -1,
    business: 0,
    operational: 1,
    project: 0,
    process: 3,
    performance: 0,
  },
  Commercial: {
    'main-product': 2,
    business: 3,
    operational: 2,
    project: 1,
    process: 0,
    performance: 1,
  },
  Operations: {
    'main-product': 1,
    business: 1,
    operational: 2,
    project: 3,
    process: 2,
    performance: 0,
  },
  People: {
    'main-product': 1,
    business: 0,
    operational: 1,
    project: 0,
    process: 1,
    performance: 4,
  },
};

export const processKpiEmployeeAdjustments: Record<string, Partial<Record<ProcessKpiCategory, number>>> = {
  'Andrea Molina': {
    'main-product': 1,
    business: 1,
    operational: 1,
    project: 0,
    process: 2,
    performance: 1,
  },
  'Carlos Lopez': {
    'main-product': 0,
    business: 1,
    operational: 1,
    project: 0,
    process: 0,
    performance: 2,
  },
  'Daniela Solis': {
    'main-product': 3,
    business: 2,
    operational: 4,
    project: 1,
    process: 3,
    performance: 4,
  },
  'Jorge Herrera': {
    'main-product': 1,
    business: 0,
    operational: 1,
    project: 4,
    process: 1,
    performance: 1,
  },
  'Marta Ruiz': {
    'main-product': 2,
    business: 1,
    operational: 3,
    project: 0,
    process: 1,
    performance: 4,
  },
};

export const employeePerformanceStatusLabels: Record<EmployeePerformanceStatus, string> = {
  top: 'Top performance',
  solid: 'Solid performance',
  watch: 'Needs attention',
};

export const processEmployeePerformanceRows: ProcessEmployeePerformanceRow[] = [
  {
    employee: 'Daniela Solis',
    unit: 'Operations',
    business: 'Commercial',
    performanceScore: 96,
    compliance: 94,
    rating: 4.9,
    tasksCompleted: 31,
    status: 'top',
  },
  {
    employee: 'Marta Ruiz',
    unit: 'Human Resources',
    business: 'People',
    performanceScore: 93,
    compliance: 92,
    rating: 4.8,
    tasksCompleted: 26,
    status: 'top',
  },
  {
    employee: 'Carlos Lopez',
    unit: 'Finance',
    business: 'Administration',
    performanceScore: 89,
    compliance: 87,
    rating: 4.5,
    tasksCompleted: 22,
    status: 'solid',
  },
  {
    employee: 'Andrea Molina',
    unit: 'Operations',
    business: 'Administration',
    performanceScore: 86,
    compliance: 84,
    rating: 4.3,
    tasksCompleted: 20,
    status: 'solid',
  },
  {
    employee: 'Jorge Herrera',
    unit: 'Technology',
    business: 'Operations',
    performanceScore: 82,
    compliance: 80,
    rating: 4.1,
    tasksCompleted: 18,
    status: 'watch',
  },
];

export const kpiCategoryLabels: Record<ProcessKpiCategory, string> = {
  'main-product': 'Main KPI',
  business: 'Business-level KPI',
  operational: 'Operational KPI',
  project: 'Project KPI',
  process: 'Process KPI',
  performance: 'Performance KPI',
};

export const kpiStatusLabels: Record<ProcessKpiStatus, string> = {
  healthy: 'Healthy',
  watch: 'Watch',
  critical: 'Critical',
};
