import { enCA } from './en-CA';
import type { PurchaseOrderTranslations } from './types';

export const frCA = {
  ...enCA,
  common: { all: 'Tous', approve: 'Approuver', cancel: 'Annuler', close: 'Fermer', currency: 'Devise', date: 'Date', expected: 'Prévu', invoice: 'Facture', manual: 'Manuel', noDate: 'Aucune date', noEmail: 'Aucun courriel', noSku: 'Aucun SKU', notes: 'Notes', pending: 'En attente', provider: 'Fournisseur', received: 'Reçu', save: 'Enregistrer', send: 'Envoyer', subtotal: 'Sous-total', tax: 'Taxe', total: 'Total', units: 'unités', view: 'Voir', warehouse: 'Entrepôt' },
  header: { title: 'Achats du point de vente', subtitle: 'Commandez le réapprovisionnement, recevez la marchandise dans le stock PDV et préparez les factures pour paiement.', supplierPortal: 'Portail fournisseur', newOrder: 'Nouveau bon de commande' },
  views: { orders: 'Achats PDV', submissions: 'Propositions fournisseurs' },
  filters: { title: 'Filtres d’achat', search: 'Rechercher', searchPlaceholder: 'Folio, fournisseur ou entrepôt', status: 'Statut', channel: 'Canal', submissionStatus: 'Statut de la proposition', supplierKiosk: 'Kiosque fournisseur', provider: 'Fournisseur', warehouse: 'Entrepôt', expectedFrom: 'Prévu à partir du', expectedTo: 'Prévu jusqu’au', period: 'Période', periodOptions: { ALL: 'Toute la période', CURRENT_MONTH: 'Ce mois-ci', PREVIOUS_MONTH: 'Mois précédent', LAST_90_DAYS: '90 derniers jours', CURRENT_YEAR: 'Cette année' } },
  orderStatus: { DRAFT: 'Brouillon', REQUESTED: 'Demandé', IN_REVIEW: 'En révision', NEEDS_CLARIFICATION: 'Précisions requises', APPROVED: 'Approuvé', ISSUED: 'Émis', SENT: 'Envoyé', CONFIRMED: 'Confirmé', PARTIALLY_RECEIVED: 'Réception partielle', RECEIVED: 'Reçu', INVOICED: 'Facturé', VALIDATED_FOR_PAYMENT: 'Validé pour paiement', SCHEDULED_FOR_PAYMENT: 'Paiement planifié', PAID: 'Payé', CLOSED: 'Fermé', CANCELLED: 'Annulé', REJECTED: 'Refusé' },
  origin: { INDICE: 'Indice', SUPPLIER_KIOSK: 'Kiosque fournisseur', POS_REPLENISHMENT: 'Réapprovisionnement PDV', SALES: 'Ventes', IMPORT: 'Importation' },
  invoiceStatus: { SUBMITTED: 'En révision', MATCHED: 'Rapprochée', APPROVED_FOR_PAYMENT: 'Prête pour paiement', REJECTED: 'Refusée' },
  submissionStatus: { SUPPLIER_DRAFT: 'Brouillon fournisseur', SUBMITTED: 'Soumise', IN_REVIEW: 'En révision', NEEDS_CLARIFICATION: 'Précisions requises', APPROVED: 'Approuvée', PARTIALLY_APPROVED: 'Approuvée en partie', REJECTED: 'Refusée', CONVERTED_TO_PURCHASE_ORDER: 'Convertie' },
  orderKpis: {
    openOrders: 'achats ouverts', pendingUnits: 'unités à recevoir', committedValue: 'valeur engagée', pendingInvoices: 'factures à rapprocher', delayed: 'en retard',
    delayedAlert: (count: number) => `${count} achats en retard`, pendingUnitsAlert: (count: number) => `${count} unités en attente`, pendingInvoicesAlert: (count: number) => `${count} factures à rapprocher`, nativeValue: (value: string) => `Natif : ${value}`,
    distribution: { draft: 'Brouillon', approval: 'Approbation', supplier: 'Chez le fournisseur', partial: 'Réception partielle', received: 'Reçus', closed: 'Paiement/fermeture', cancelled: 'Annulés' },
    noAlerts: 'Aucune alerte opérationnelle pour les achats PDV avec les filtres actuels.', delayedInsight: (count: number) => `${count} achats nécessitent un suivi fournisseur avant d’affecter la disponibilité en caisse.`, pendingInsight: (count: number, currency: string) => `Recevez ${count} unités en attente pour transformer les achats ouverts en stock vendable. Total consolidé par le serveur en ${currency}.`, invoicesInsight: (count: number) => `Rapprochez ${count} factures pour fermer le cycle d’achat et de paiement.`,
  },
  submissionKpis: {
    visible: 'propositions visibles', toReview: 'à réviser', ready: 'prêtes à acheter', unresolved: 'articles non liés', proposedValue: 'valeur proposée',
    clarificationAlert: (count: number) => `${count} nécessitent des précisions`, unresolvedAlert: (count: number) => `${count} articles sans produit`, convertibleAlert: (count: number) => `${count} prêtes à convertir`, nativeValue: (value: string) => `Natif : ${value}`,
    distribution: { submitted: 'Soumises', review: 'En révision', clarification: 'Précisions', approved: 'Approuvées', converted: 'Converties', rejected: 'Refusées' },
    noAlerts: 'Aucune alerte opérationnelle pour les propositions fournisseurs avec les filtres actuels.', unresolvedInsight: (count: number) => `Liez ${count} articles aux produits PDV avant de convertir les propositions en achats.`, convertibleInsight: (count: number) => `Convertissez ${count} propositions approuvées pour commencer le réapprovisionnement.`, reviewInsight: (count: number, currency: string) => `Révisez ${count} propositions fournisseurs pour décider de leur conversion en achats PDV. Valeur consolidée par le serveur en ${currency}.`,
  },
  orderTable: {
    emptyTitle: 'Aucun achat PDV ne correspond à ces filtres.', emptyDescription: 'Créez un achat lié à un fournisseur, un entrepôt de destination et des produits vendables pour commencer le réapprovisionnement.', title: 'Achats PDV',
    summary: (visible: number, open: number, invoices: number) => `${visible} achats visibles · ${open} ouverts · ${invoices} factures à fermer.`, integrationBadge: 'Stock + paiement sur une ligne',
    columns: ['Achat', 'Opérations', 'Stock', 'Facture et paiement', 'Total', 'Statut', 'Actions'], inventoryReceived: 'Reçu', inventoryPartial: 'Partiel', inventoryPending: 'En attente', expected: (date: string) => `Prévu : ${date}`, lineCount: (count: number) => `${count} articles`, sourceProposal: (id: number) => `Proposition nº ${id}`, receivedUnits: (count: number) => `${count} reçues`, pendingUnits: (count: number) => `${count} en attente`, due: (date: string) => `Échéance : ${date}`, moreInvoices: (count: number) => `+${count} de plus`, noInvoice: 'Aucune facture', request: 'Demander', approve: 'Approuver', send: 'Envoyer', receive: 'Recevoir', reconcile: 'Rapprocher', approvePayment: 'Approuver le paiement', cancel: 'Annuler', itemLabel: 'achats',
  },
  submissionTable: { emptyTitle: 'Aucune proposition fournisseur ne correspond à ces filtres.', emptyDescription: 'Les propositions du kiosque fournisseur apparaîtront ici pour révision et conversion en bons de commande.', title: 'Propositions fournisseurs', summary: (visible: number, review: number, ready: number) => `${visible} propositions visibles · ${review} à réviser · ${ready} prêtes à convertir.`, columns: ['Proposition', 'Fournisseur', 'Soumis par', 'Articles', 'Révision', 'Total', 'Statut', 'Actions'], itemCount: (count: number) => `${count} articles`, unresolved: (count: number) => `${count} non liés`, review: 'Réviser', convert: 'Convertir', view: 'Voir', itemLabel: 'propositions', noContact: 'Aucun contact', linkedProducts: 'Produits liés', noReview: 'Non révisée', noNote: 'Aucune note', tax: 'Taxe', convertedOrder: (id: number) => `BC nº ${id}` },
  detail: { closeLabel: 'Fermer les détails du bon de commande', eyebrow: 'Bon de commande', print: 'Imprimer', close: 'Fermer', footerSummary: (count: number, total: string) => `${count} articles · Total ${total}`, items: 'Articles', itemsSubtitle: 'Réception cumulée par produit.', columns: ['Produit', 'Quantité', 'Reçu', 'En attente', 'Coût', 'Total'], linkedInvoices: 'Factures liées', noLinkedInvoices: 'Aucune facture n’est liée à cet achat.', supplierProposal: 'Proposition fournisseur', origin: 'Origine', provider: 'Fournisseur', warehouse: 'Entrepôt', expected: 'Prévu' },
  receive: { closeLabel: 'Fermer la réception', title: 'Recevoir la marchandise', eyebrow: 'Réception PDV', save: 'Enregistrer la réception', noPending: 'Cet achat ne contient aucun article en attente de réception.', ordered: 'Commandé', received: 'Reçu', pending: 'En attente', receive: 'Recevoir', notes: 'Notes de réception' },
  invoicePanel: { title: 'Factures à rapprocher', description: 'Révisez la facture, le bon de commande et le statut du paiement dans le même espace.', empty: 'Aucune facture fournisseur ne correspond aux filtres actuels.', noOrder: 'Aucun bon de commande', total: 'Total de la facture', due: 'Échéance', reconcile: 'Rapprocher', approve: 'Approuver le paiement', open: 'Ouvrir le document' },
  invoiceModal: { closeLabel: 'Fermer la facture fournisseur', title: 'Facture fournisseur', subtitle: 'Saisie de type kiosque pour que les achats révisent et autorisent le paiement.', eyebrow: 'Comptes fournisseurs PDV', totalSummary: (value: string) => `Total de la facture ${value}`, register: 'Enregistrer la facture', fiscalTitle: 'Données fiscales', fiscalSubtitle: 'Liez la facture à un fournisseur, un bon de commande et aux dates de paiement.', relatedOrder: 'Bon de commande lié', noOrder: 'Aucun bon', provider: 'Fournisseur', invoiceNumber: 'Numéro de facture', currency: 'Devise', invoiceDate: 'Date de facture', dueDate: 'Échéance', amountsTitle: 'Montants et taxe', amountsSubtitle: 'La taxe est calculée selon le taux choisi; utilisez le mode manuel si la facture ne correspond pas.', subtotal: 'Sous-total', tax: 'Taxe', taxAmount: 'Montant de la taxe', total: 'Total de la facture', exempt: 'Exonéré', manual: 'Manuel', documentUrl: 'URL du document', submittedBy: 'Soumis par', notes: 'Notes' },
  create: {
    sessionExpired: 'Votre session a expiré après le redémarrage du système. Reconnectez-vous et recréez l’achat.', forbidden: 'Cette session n’autorise pas cette action. Actualisez la page et reconnectez-vous si le problème persiste.', saveError: 'Impossible d’enregistrer l’achat.', uploadUrlError: 'Aucune URL de téléversement du document n’a été reçue.', savingOrder: 'Enregistrement de l’achat…', uploadingInvoice: 'Téléversement de la facture…', registeringInvoice: 'Enregistrement de la facture…', closeLabel: 'Fermer le nouvel achat PDV', title: 'Nouvel achat PDV', subtitle: 'Rapprochez la facture, le budget et le stock avant de créer l’achat.', eyebrow: 'Réapprovisionnement PDV', create: 'Créer l’achat', createWithInvoice: 'Créer l’achat et la facture', cancel: 'Annuler', footerLines: (count: number) => `${count} articles`, footerDifference: (value: string) => `Écart ${value}`, footerTotal: (value: string) => `Total ${value}`,
    referenceTitle: 'Fournisseur, facture et budget', referenceSubtitle: 'Ces données préparent la référence financière des comptes fournisseurs et des dépenses.', provider: 'Fournisseur', destinationWarehouse: 'Entrepôt de destination', currency: 'Devise', expectedDate: 'Date prévue', linkInvoice: 'Enregistrer une facture liée', linkInvoiceHint: 'Si une facture existe, elle doit correspondre aux articles avant la création.', reconciliation: 'Rapprochement de facture', reconciliationSummary: (invoice: string, items: string) => `Total de facture ${invoice} comparé aux articles ${items}.`, matched: 'Correspond', syncToItems: 'Faire correspondre aux articles', invoiceNumber: 'Numéro de facture', invoiceDate: 'Date de facture', dueDate: 'Échéance', subtotal: 'Sous-total', tax: 'Taxe', taxAmount: 'Montant de la taxe', invoiceTotal: 'Total de la facture', document: 'Fichier de facture', noFile: 'Aucun fichier sélectionné', notes: 'Notes', manual: 'Manuel',
    inventoryTitle: 'Stock des produits', inventorySubtitle: 'Ajoutez des articles jusqu’à ce que le total corresponde à la facture ou au budget.', movement: 'Mouvement', purchaseEntry: 'Entrée d’achat', items: 'Articles', entryTotal: 'Total de l’entrée', searchProduct: 'Rechercher un produit', searchPlaceholder: 'Nom, SKU ou code', quantity: 'Quantité', unitCost: 'Coût unitaire', taxRate: 'Taux de taxe', addItem: 'Ajouter un article', noProducts: 'Aucun produit ne correspond à la recherche.', createProduct: 'Créer le produit', newProductName: 'Nom du nouveau produit', skuOptional: 'SKU (facultatif)', creatingProduct: 'Création…', lineProduct: 'Produit', lineQuantity: 'Quantité', lineUnitCost: 'Coût unitaire', lineTax: 'Taxe', lineTotal: 'Total', removeLine: 'Retirer l’article', emptyLines: 'Ajoutez au moins un produit pour créer l’achat.', upload: 'Téléverser', removeFile: 'Retirer', noProvider: 'Aucun fournisseur', itemSubtotal: 'Sous-total des articles', itemTax: 'Taxe des articles', itemTotal: 'Total des articles', reconciled: 'Rapproché', unreconciled: 'À rapprocher', differenceLabel: (value: string) => `Écart : ${value}`, noInvoiceSummary: 'Sans facture, le bon et l’engagement opérationnel sont créés selon le total des articles.',
  },
  print: { purchaseFile: 'bon-de-commande', receiptFile: 'reception-de-marchandises', supplierEmail: 'Courriel du fournisseur', deliveryWarehouse: 'Entrepôt de livraison', orderDate: 'Date de commande', taxes: 'Taxes', items: 'Articles', orderNotice: 'Document commercial d’achat. Il ne constitue pas une facture fiscale et ne confirme pas à lui seul la réception ni le paiement des marchandises.', notesAndTerms: 'Notes et conditions', preparedBy: 'Préparé par', authorizedBy: 'Autorisé par', supplier: 'Fournisseur', itemColumns: ['SKU', 'Produit', 'Quantité', 'Coût unitaire', 'Taxe', 'Sous-total', 'Total'], orderItems: 'Articles de la commande', orderTitle: 'Bon de commande', confidentiality: 'Interne', purchaseOrder: 'Bon de commande', receiptDate: 'Date de réception', followingStatus: 'Statut après réception', receivedItems: 'Articles reçus', receivedUnits: 'Unités reçues', previousPendingItems: 'Articles auparavant en attente', receiptNotice: 'Registre opérationnel de réception. La commande ne possède pas de folio de réception distinct; le folio affiché est celui du bon de commande.', receiptNotes: 'Notes de réception', deliveredBy: 'Livré par le fournisseur', receivedBy: 'Reçu par l’entrepôt', supervisedBy: 'Supervisé par', receiptRecorded: 'Réception enregistrée', receiptColumns: ['SKU', 'Produit', 'Commandé', 'En attente auparavant', 'Reçu maintenant', 'Solde estimé'], receivedGoods: 'Marchandises reçues', receiptTitle: 'Procès-verbal de réception des marchandises' },
  submissionDetail: { closeLabel: 'Fermer la proposition fournisseur', eyebrow: 'Proposition fournisseur', close: 'Fermer', footerSummary: (count: number, total: string) => `${count} articles · Total ${total}`, itemsTitle: 'Articles proposés', itemsSubtitle: 'Le fournisseur propose; Indice révise, lie les produits et décide lesquels deviennent un achat formel.', unresolvedWarning: (count: number) => `${count} article(s) ne sont pas liés au catalogue de produits. Révisez-les avant la conversion en bon de commande.`, linkedProduct: (id: number) => `Produit nº ${id}`, newProduct: 'Nouveau produit', noSupplierSku: 'Aucun SKU fournisseur', unitCost: (value: string) => `${value} l’unité`, provider: 'Fournisseur', submittedBy: 'Soumis par', supplierFallback: 'Fournisseur', internalReview: 'Révision interne', reviewNote: 'Note de révision', saveReview: 'Enregistrer la révision', convertTitle: 'Convertir en BC', convertNote: 'Note du bon de commande', convert: 'Convertir en bon de commande' },
  cancelDialog: { title: 'Annuler le bon de commande', description: 'L’achat restera dans l’historique et son statut passera à annulé. Cette action ne supprime ni le stock ni les factures.', confirm: 'Annuler l’achat', note: 'Annulé depuis le point de vente.' },
} as const satisfies PurchaseOrderTranslations;
