import { enCA } from './en-CA';
import type { PurchaseOrderTranslations } from './types';

export const koCA = {
  ...enCA,
  common: { all: '전체', approve: '승인', cancel: '취소', close: '닫기', currency: '통화', date: '날짜', expected: '예정', invoice: '청구서', manual: '수동', noDate: '날짜 없음', noEmail: '이메일 없음', noSku: 'SKU 없음', notes: '메모', pending: '대기', provider: '공급업체', received: '입고됨', save: '저장', send: '전송', subtotal: '소계', tax: '세금', total: '합계', units: '개', view: '보기', warehouse: '창고' },
  header: { title: 'POS 구매', subtitle: '공급업체에 재입고를 주문하고 POS 재고로 상품을 입고한 뒤 청구서를 결제 준비 상태로 만듭니다.', supplierPortal: '공급업체 포털', newOrder: '새 구매 주문' },
  views: { orders: 'POS 구매', submissions: '공급업체 제안' },
  filters: { title: '구매 필터', search: '검색', searchPlaceholder: '번호, 공급업체 또는 창고', status: '상태', channel: '채널', submissionStatus: '제안 상태', supplierKiosk: '공급업체 키오스크', provider: '공급업체', warehouse: '창고', expectedFrom: '예정 시작일', expectedTo: '예정 종료일' },
  orderStatus: { DRAFT: '초안', REQUESTED: '요청됨', IN_REVIEW: '검토 중', NEEDS_CLARIFICATION: '설명 필요', APPROVED: '승인됨', ISSUED: '발행됨', SENT: '전송됨', CONFIRMED: '확인됨', PARTIALLY_RECEIVED: '부분 입고', RECEIVED: '입고됨', INVOICED: '청구됨', VALIDATED_FOR_PAYMENT: '결제 검증됨', SCHEDULED_FOR_PAYMENT: '결제 예정', PAID: '결제됨', CLOSED: '마감됨', CANCELLED: '취소됨', REJECTED: '거절됨' },
  origin: { INDICE: 'Indice', SUPPLIER_KIOSK: '공급업체 키오스크', POS_REPLENISHMENT: 'POS 재입고', SALES: '판매', IMPORT: '가져오기' },
  invoiceStatus: { SUBMITTED: '검토 중', MATCHED: '대조 완료', APPROVED_FOR_PAYMENT: '결제 준비', REJECTED: '거절됨' },
  submissionStatus: { SUPPLIER_DRAFT: '공급업체 초안', SUBMITTED: '제출됨', IN_REVIEW: '검토 중', NEEDS_CLARIFICATION: '설명 필요', APPROVED: '승인됨', PARTIALLY_APPROVED: '부분 승인', REJECTED: '거절됨', CONVERTED_TO_PURCHASE_ORDER: '전환됨' },
  orderKpis: { openOrders: '진행 중 구매', pendingUnits: '입고 예정 수량', committedValue: '약정 금액', pendingInvoices: '대조할 청구서', delayed: '지연', delayedAlert: (count: number) => `지연 구매 ${count}건`, pendingUnitsAlert: (count: number) => `대기 수량 ${count}개`, pendingInvoicesAlert: (count: number) => `대조할 청구서 ${count}건`, nativeValue: (value: string) => `원 통화: ${value}`, distribution: { draft: '초안', approval: '승인', supplier: '공급업체 처리 중', partial: '부분 입고', received: '입고 완료', closed: '결제/마감', cancelled: '취소됨' }, noAlerts: '현재 필터에 해당하는 POS 구매 운영 알림이 없습니다.', delayedInsight: (count: number) => `${count}건의 구매는 계산대 가용성에 영향을 주기 전에 공급업체 확인이 필요합니다.`, pendingInsight: (count: number, currency: string) => `대기 수량 ${count}개를 입고해 진행 중 구매를 판매 가능 재고로 전환하세요. 백엔드 통합 합계는 ${currency}입니다.`, invoicesInsight: (count: number) => `${count}건의 청구서를 대조해 구매 및 결제 주기를 마감하세요.` },
  submissionKpis: { visible: '표시 제안', toReview: '검토 필요', ready: '구매 준비', unresolved: '미연결 항목', proposedValue: '제안 금액', clarificationAlert: (count: number) => `${count}건에 설명이 필요합니다`, unresolvedAlert: (count: number) => `제품 미연결 항목 ${count}개`, convertibleAlert: (count: number) => `전환 준비 ${count}건`, nativeValue: (value: string) => `원 통화: ${value}`, distribution: { submitted: '제출됨', review: '검토 중', clarification: '설명 필요', approved: '승인됨', converted: '전환됨', rejected: '거절됨' }, noAlerts: '현재 필터에 해당하는 공급업체 제안 운영 알림이 없습니다.', unresolvedInsight: (count: number) => `제안을 구매로 전환하기 전에 ${count}개 항목을 POS 제품에 연결하세요.`, convertibleInsight: (count: number) => `승인된 제안 ${count}건을 전환해 매장 재입고를 시작하세요.`, reviewInsight: (count: number, currency: string) => `공급업체 제안 ${count}건을 검토해 POS 구매 전환 여부를 결정하세요. 백엔드 통합 금액은 ${currency}입니다.` },
  orderTable: { emptyTitle: '이 필터에 해당하는 POS 구매가 없습니다.', emptyDescription: '공급업체, 도착 창고, 판매 가능 제품에 연결된 구매를 만들어 재입고를 시작하세요.', title: 'POS 구매', summary: (visible: number, open: number, invoices: number) => `표시 ${visible}건 · 진행 ${open}건 · 마감 대기 청구서 ${invoices}건`, integrationBadge: '재고 + 결제를 한 행에서', columns: ['구매', '운영', '재고', '청구서 및 결제', '합계', '상태', '작업'], inventoryReceived: '입고됨', inventoryPartial: '부분', inventoryPending: '대기', expected: (date: string) => `예정: ${date}`, lineCount: (count: number) => `${count}개 항목`, sourceProposal: (id: number) => `제안 #${id}`, receivedUnits: (count: number) => `${count}개 입고`, pendingUnits: (count: number) => `${count}개 대기`, due: (date: string) => `기한: ${date}`, moreInvoices: (count: number) => `+${count}건`, noInvoice: '청구서 없음', request: '요청', approve: '승인', send: '전송', receive: '입고', reconcile: '대조', approvePayment: '결제 승인', cancel: '취소', itemLabel: '구매' },
  submissionTable: { emptyTitle: '이 필터에 해당하는 공급업체 제안이 없습니다.', emptyDescription: '공급업체 키오스크의 제안이 검토 및 구매 주문 전환을 위해 여기에 표시됩니다.', title: '공급업체 제안', summary: (visible: number, review: number, ready: number) => `표시 ${visible}건 · 검토 ${review}건 · 전환 준비 ${ready}건`, columns: ['제안', '공급업체', '제출자', '항목', '검토', '합계', '상태', '작업'], itemCount: (count: number) => `${count}개 항목`, unresolved: (count: number) => `${count}개 미연결`, review: '검토', convert: '전환', view: '보기', itemLabel: '제안', noContact: '연락처 없음', linkedProducts: '제품 연결됨', noReview: '미검토', noNote: '메모 없음', tax: '세금', convertedOrder: (id: number) => `구매 주문 #${id}` },
  detail: { closeLabel: '구매 주문 상세 닫기', eyebrow: '구매 주문', print: '인쇄', close: '닫기', footerSummary: (count: number, total: string) => `${count}개 항목 · 합계 ${total}`, items: '항목', itemsSubtitle: '제품별 누적 입고입니다.', columns: ['제품', '수량', '입고', '대기', '비용', '합계'], linkedInvoices: '연결된 청구서', noLinkedInvoices: '이 구매에 연결된 청구서가 없습니다.', supplierProposal: '공급업체 제안', origin: '출처', provider: '공급업체', warehouse: '창고', expected: '예정' },
  receive: { closeLabel: '상품 입고 닫기', title: '상품 입고', eyebrow: 'POS 입고', save: '입고 저장', noPending: '이 구매에는 입고 대기 항목이 없습니다.', ordered: '주문', received: '입고', pending: '대기', receive: '입고', notes: '입고 메모' },
  invoicePanel: { title: '대조할 청구서', description: '같은 작업 공간에서 청구서, 구매 주문, 결제 상태를 검토합니다.', empty: '현재 필터에 해당하는 공급업체 청구서가 없습니다.', noOrder: '구매 주문 없음', total: '청구서 합계', due: '결제 기한', reconcile: '대조', approve: '결제 승인', open: '문서 열기' },
  invoiceModal: { closeLabel: '공급업체 청구서 닫기', title: '공급업체 청구서', subtitle: '구매 담당자가 검토하고 결제를 승인하는 키오스크형 등록입니다.', eyebrow: 'POS 미지급금', totalSummary: (value: string) => `청구서 합계 ${value}`, register: '청구서 등록', fiscalTitle: '세금 정보', fiscalSubtitle: '청구서를 공급업체, 구매 주문 및 결제일과 연결합니다.', relatedOrder: '관련 주문', noOrder: '주문 없음', provider: '공급업체', invoiceNumber: '청구서 번호', currency: '통화', invoiceDate: '청구일', dueDate: '결제 기한', amountsTitle: '금액 및 세금', amountsSubtitle: '선택한 세율로 세금을 계산하며 금액이 맞지 않을 때 수동을 사용하세요.', subtotal: '소계', tax: '세금', taxAmount: '세액', total: '청구서 합계', exempt: '면세', manual: '수동', documentUrl: '문서 URL', submittedBy: '제출자', notes: '메모' },
  create: { sessionExpired: '시스템 재시작 후 세션이 만료되었습니다. 다시 로그인한 뒤 구매를 다시 만드세요.', forbidden: '현재 세션은 이 작업을 허용하지 않습니다. 페이지를 새로고침하고 문제가 계속되면 다시 로그인하세요.', saveError: '구매를 저장할 수 없습니다.', uploadUrlError: '문서 업로드 URL을 받지 못했습니다.', savingOrder: '구매 저장 중…', uploadingInvoice: '청구서 업로드 중…', registeringInvoice: '청구서 등록 중…', closeLabel: '새 POS 구매 닫기', title: '새 POS 구매', subtitle: '구매를 만들기 전에 청구서, 예산, 재고를 대조합니다.', eyebrow: 'POS 재입고', create: '구매 만들기', createWithInvoice: '구매 및 청구서 만들기', cancel: '취소', footerLines: (count: number) => `${count}개 항목`, footerDifference: (value: string) => `차이 ${value}`, footerTotal: (value: string) => `합계 ${value}`, referenceTitle: '공급업체, 청구서 및 예산', referenceSubtitle: '이 정보는 미지급금과 비용 처리를 위한 재무 기준을 준비합니다.', provider: '공급업체', destinationWarehouse: '도착 창고', currency: '통화', expectedDate: '예정일', linkInvoice: '연결 청구서 등록', linkInvoiceHint: '청구서가 있으면 생성 전에 항목 금액과 일치해야 합니다.', reconciliation: '청구서 대조', reconciliationSummary: (invoice: string, items: string) => `청구서 합계 ${invoice} / 항목 합계 ${items}`, matched: '일치', syncToItems: '항목에 맞추기', invoiceNumber: '청구서 번호', invoiceDate: '청구일', dueDate: '결제 기한', subtotal: '소계', tax: '세금', taxAmount: '세액', invoiceTotal: '청구서 합계', document: '청구서 파일', noFile: '선택한 파일 없음', notes: '메모', manual: '수동', inventoryTitle: '제품 재고', inventorySubtitle: '합계가 청구서 또는 예산과 일치할 때까지 항목을 추가하세요.', movement: '이동', purchaseEntry: '구매 입고', items: '항목', entryTotal: '입고 합계', searchProduct: '제품 검색', searchPlaceholder: '이름, SKU 또는 코드', quantity: '수량', unitCost: '단가', taxRate: '세율', addItem: '항목 추가', noProducts: '검색과 일치하는 제품이 없습니다.', createProduct: '제품 만들기', newProductName: '새 제품 이름', skuOptional: 'SKU(선택)', creatingProduct: '생성 중…', lineProduct: '제품', lineQuantity: '수량', lineUnitCost: '단가', lineTax: '세금', lineTotal: '합계', removeLine: '항목 제거', emptyLines: '구매를 만들려면 제품을 하나 이상 추가하세요.', upload: '업로드', removeFile: '제거', noProvider: '공급업체 없음', itemSubtotal: '항목 소계', itemTax: '항목 세금', itemTotal: '항목 합계', reconciled: '대조 완료', unreconciled: '대조 필요', differenceLabel: (value: string) => `차이: ${value}`, noInvoiceSummary: '청구서가 없으면 항목 합계를 기준으로 주문과 운영 약정이 생성됩니다.' },
  print: { purchaseFile: 'purchase-order', receiptFile: 'goods-receipt', supplierEmail: '공급업체 이메일', deliveryWarehouse: '배송 창고', orderDate: '주문일', taxes: '세금', items: '항목', orderNotice: '상업용 구매 문서입니다. 세금계산서가 아니며 상품 수령 또는 결제를 단독으로 증명하지 않습니다.', notesAndTerms: '메모 및 조건', preparedBy: '작성자', authorizedBy: '승인자', supplier: '공급업체', itemColumns: ['SKU', '제품', '수량', '단가', '세금', '소계', '합계'], orderItems: '주문 항목', orderTitle: '구매 주문', confidentiality: '내부', purchaseOrder: '구매 주문', receiptDate: '수령일', followingStatus: '수령 후 상태', receivedItems: '수령 항목', receivedUnits: '수령 수량', previousPendingItems: '기존 미수령 항목', receiptNotice: '운영용 수령 기록입니다. 별도의 수령 번호가 없으므로 표시된 번호는 구매 주문 번호입니다.', receiptNotes: '수령 메모', deliveredBy: '공급업체 전달', receivedBy: '창고 수령', supervisedBy: '감독자', receiptRecorded: '수령 등록됨', receiptColumns: ['SKU', '제품', '주문', '기존 미수령', '현재 수령', '예상 잔여'], receivedGoods: '수령 상품', receiptTitle: '상품 수령 확인서' },
  submissionDetail: { closeLabel: '공급업체 제안 닫기', eyebrow: '공급업체 제안', close: '닫기', footerSummary: (count: number, total: string) => `${count}개 항목 · 합계 ${total}`, itemsTitle: '제안 항목', itemsSubtitle: '공급업체가 제안하면 Indice가 검토하고 제품을 연결해 정식 구매로 전환할 항목을 결정합니다.', unresolvedWarning: (count: number) => `${count}개 항목이 제품 카탈로그에 연결되지 않았습니다. 구매 주문으로 전환하기 전에 검토하세요.`, linkedProduct: (id: number) => `제품 #${id}`, newProduct: '새 제품', noSupplierSku: '공급업체 SKU 없음', unitCost: (value: string) => `개당 ${value}`, provider: '공급업체', submittedBy: '제출자', supplierFallback: '공급업체', internalReview: '내부 검토', reviewNote: '검토 메모', saveReview: '검토 저장', convertTitle: '구매 주문으로 전환', convertNote: '구매 주문 메모', convert: '구매 주문으로 전환' },
  cancelDialog: { title: '구매 주문 취소', description: '구매는 기록에 남고 상태가 취소됨으로 변경됩니다. 재고 또는 청구서 기록은 삭제되지 않습니다.', confirm: '구매 취소', note: 'POS에서 취소됨.' },
} as const satisfies PurchaseOrderTranslations;
