import { enCA } from './en-CA';
import type { PurchaseOrderTranslations } from './types';

export const zhCA = {
  ...enCA,
  common: { all: '全部', approve: '批准', cancel: '取消', close: '关闭', currency: '币种', date: '日期', expected: '预计', invoice: '发票', manual: '手动', noDate: '无日期', noEmail: '无电子邮件', noSku: '无 SKU', notes: '备注', pending: '待处理', provider: '供应商', received: '已收货', save: '保存', send: '发送', subtotal: '小计', tax: '税额', total: '总计', units: '件', view: '查看', warehouse: '仓库' },
  header: { title: '销售点采购', subtitle: '向供应商订购补货，将商品收进 POS 库存，并准备发票以供付款。', supplierPortal: '供应商门户', newOrder: '新建采购单' },
  views: { orders: 'POS 采购', submissions: '供应商提案' },
  filters: { title: '采购筛选', search: '搜索', searchPlaceholder: '单号、供应商或仓库', status: '状态', channel: '渠道', submissionStatus: '提案状态', supplierKiosk: '供应商自助终端', provider: '供应商', warehouse: '仓库', expectedFrom: '预计开始', expectedTo: '预计结束', period: '期间', periodOptions: { ALL: '全部时间', CURRENT_MONTH: '本月', PREVIOUS_MONTH: '上月', LAST_90_DAYS: '最近90天', CURRENT_YEAR: '今年' } },
  orderStatus: { DRAFT: '草稿', REQUESTED: '已申请', IN_REVIEW: '审核中', NEEDS_CLARIFICATION: '需要说明', APPROVED: '已批准', ISSUED: '已签发', SENT: '已发送', CONFIRMED: '已确认', PARTIALLY_RECEIVED: '部分收货', RECEIVED: '已收货', INVOICED: '已开票', VALIDATED_FOR_PAYMENT: '已验证付款', SCHEDULED_FOR_PAYMENT: '已安排付款', PAID: '已付款', CLOSED: '已关闭', CANCELLED: '已取消', REJECTED: '已拒绝' },
  origin: { INDICE: 'Indice', SUPPLIER_KIOSK: '供应商自助终端', POS_REPLENISHMENT: 'POS 补货', SALES: '销售', IMPORT: '导入' },
  invoiceStatus: { SUBMITTED: '审核中', MATCHED: '已核对', APPROVED_FOR_PAYMENT: '可付款', REJECTED: '已拒绝' },
  submissionStatus: { SUPPLIER_DRAFT: '供应商草稿', SUBMITTED: '已提交', IN_REVIEW: '审核中', NEEDS_CLARIFICATION: '需要说明', APPROVED: '已批准', PARTIALLY_APPROVED: '部分批准', REJECTED: '已拒绝', CONVERTED_TO_PURCHASE_ORDER: '已转换' },
  orderKpis: { openOrders: '进行中的采购', pendingUnits: '待收数量', committedValue: '承诺金额', pendingInvoices: '待核对发票', delayed: '已逾期', delayedAlert: (count: number) => `${count} 笔采购逾期`, pendingUnitsAlert: (count: number) => `${count} 件待收`, pendingInvoicesAlert: (count: number) => `${count} 张发票待核对`, nativeValue: (value: string) => `原币：${value}`, distribution: { draft: '草稿', approval: '审批', supplier: '供应商处理中', partial: '部分收货', received: '已收货', closed: '付款/关闭', cancelled: '已取消' }, noAlerts: '当前筛选条件下没有 POS 采购运营提醒。', delayedInsight: (count: number) => `${count} 笔采购需要跟进供应商，以免影响收银库存。`, pendingInsight: (count: number, currency: string) => `接收 ${count} 件待收商品，将进行中的采购转为可售库存。后端汇总总额以 ${currency} 计。`, invoicesInsight: (count: number) => `核对 ${count} 张发票以完成采购和付款周期。` },
  submissionKpis: { visible: '可见提案', toReview: '待审核', ready: '可采购', unresolved: '未关联项目', proposedValue: '提议金额', clarificationAlert: (count: number) => `${count} 项需要说明`, unresolvedAlert: (count: number) => `${count} 项未关联产品`, convertibleAlert: (count: number) => `${count} 项可转换`, nativeValue: (value: string) => `原币：${value}`, distribution: { submitted: '已提交', review: '审核中', clarification: '需要说明', approved: '已批准', converted: '已转换', rejected: '已拒绝' }, noAlerts: '当前筛选条件下没有供应商提案运营提醒。', unresolvedInsight: (count: number) => `转换提案前，请将 ${count} 个项目关联到 POS 产品。`, convertibleInsight: (count: number) => `转换 ${count} 个已批准提案以开始门店补货。`, reviewInsight: (count: number, currency: string) => `审核 ${count} 个供应商提案并决定是否转为 POS 采购。后端汇总金额以 ${currency} 计。` },
  orderTable: { emptyTitle: '没有符合这些筛选条件的 POS 采购。', emptyDescription: '创建关联供应商、目标仓库和可售产品的采购以开始补货。', title: 'POS 采购', summary: (visible: number, open: number, invoices: number) => `${visible} 笔可见 · ${open} 笔进行中 · ${invoices} 张发票待关闭`, integrationBadge: '库存与付款同一行', columns: ['采购', '运营', '库存', '发票与付款', '总计', '状态', '操作'], inventoryReceived: '已收货', inventoryPartial: '部分', inventoryPending: '待处理', expected: (date: string) => `预计：${date}`, lineCount: (count: number) => `${count} 个项目`, sourceProposal: (id: number) => `提案 #${id}`, receivedUnits: (count: number) => `已收 ${count} 件`, pendingUnits: (count: number) => `待收 ${count} 件`, due: (date: string) => `到期：${date}`, moreInvoices: (count: number) => `另有 ${count} 张`, noInvoice: '无发票', request: '申请', approve: '批准', send: '发送', receive: '收货', reconcile: '核对', approvePayment: '批准付款', cancel: '取消', itemLabel: '采购' },
  submissionTable: { emptyTitle: '没有符合这些筛选条件的供应商提案。', emptyDescription: '供应商自助终端提案将显示在此处，以便审核并转换为采购单。', title: '供应商提案', summary: (visible: number, review: number, ready: number) => `${visible} 项可见 · ${review} 项待审核 · ${ready} 项可转换`, columns: ['提案', '供应商', '提交人', '项目', '审核', '总计', '状态', '操作'], itemCount: (count: number) => `${count} 个项目`, unresolved: (count: number) => `${count} 个未关联`, review: '审核', convert: '转换', view: '查看', itemLabel: '提案', noContact: '无联系方式', linkedProducts: '产品已关联', noReview: '未审核', noNote: '无备注', tax: '税额', convertedOrder: (id: number) => `采购单 #${id}` },
  detail: { closeLabel: '关闭采购单详情', eyebrow: '采购单', print: '打印', close: '关闭', footerSummary: (count: number, total: string) => `${count} 个项目 · 总计 ${total}`, items: '项目', itemsSubtitle: '按产品显示累计收货。', columns: ['产品', '数量', '已收货', '待收货', '成本', '总计'], linkedInvoices: '关联发票', noLinkedInvoices: '此采购没有关联发票。', supplierProposal: '供应商提案', origin: '来源', provider: '供应商', warehouse: '仓库', expected: '预计' },
  receive: { closeLabel: '关闭收货', title: '接收商品', eyebrow: 'POS 收货', save: '保存收货', noPending: '此采购没有待收项目。', ordered: '已订购', received: '已收货', pending: '待处理', receive: '收货', notes: '收货备注' },
  invoicePanel: { title: '待核对发票', description: '在同一工作区审核发票、采购单和付款状态。', empty: '当前筛选条件下没有供应商发票。', noOrder: '无采购单', total: '发票总额', due: '到期日', reconcile: '核对', approve: '批准付款', open: '打开文档' },
  invoiceModal: { closeLabel: '关闭供应商发票', title: '供应商发票', subtitle: '采用自助终端式录入，供采购审核并授权付款。', eyebrow: 'POS 应付账款', totalSummary: (value: string) => `发票总额 ${value}`, register: '登记发票', fiscalTitle: '税务信息', fiscalSubtitle: '将发票与供应商、采购单和付款日期关联。', relatedOrder: '相关采购单', noOrder: '无采购单', provider: '供应商', invoiceNumber: '发票号码', currency: '币种', invoiceDate: '发票日期', dueDate: '到期日', amountsTitle: '金额与税额', amountsSubtitle: '税额按所选税率计算；发票不匹配时请使用手动模式。', subtotal: '小计', tax: '税额', taxAmount: '税额金额', total: '发票总额', exempt: '免税', manual: '手动', documentUrl: '文档 URL', submittedBy: '提交人', notes: '备注' },
  create: { sessionExpired: '系统重启后会话已过期。请重新登录并重新创建采购。', forbidden: '当前会话无权执行此操作。请刷新页面；若问题持续，请重新登录。', saveError: '无法保存采购。', uploadUrlError: '未收到文档上传 URL。', savingOrder: '正在保存采购…', uploadingInvoice: '正在上传发票…', registeringInvoice: '正在登记发票…', closeLabel: '关闭新 POS 采购', title: '新建 POS 采购', subtitle: '创建采购前先核对发票、预算与库存。', eyebrow: 'POS 补货', create: '创建采购', createWithInvoice: '创建采购和发票', cancel: '取消', footerLines: (count: number) => `${count} 个项目`, footerDifference: (value: string) => `差额 ${value}`, footerTotal: (value: string) => `总计 ${value}`, referenceTitle: '供应商、发票与预算', referenceSubtitle: '这些信息用于准备应付账款和费用的财务依据。', provider: '供应商', destinationWarehouse: '目标仓库', currency: '币种', expectedDate: '预计日期', linkInvoice: '登记关联发票', linkInvoiceHint: '若有发票，创建前必须与各项目金额一致。', reconciliation: '发票核对', reconciliationSummary: (invoice: string, items: string) => `发票总额 ${invoice}，项目总额 ${items}。`, matched: '一致', syncToItems: '与项目保持一致', invoiceNumber: '发票号码', invoiceDate: '发票日期', dueDate: '到期日', subtotal: '小计', tax: '税额', taxAmount: '税额金额', invoiceTotal: '发票总额', document: '发票文件', noFile: '未选择文件', notes: '备注', manual: '手动', inventoryTitle: '产品库存', inventorySubtitle: '添加项目，直至总额与发票或预算一致。', movement: '库存变动', purchaseEntry: '采购入库', items: '项目', entryTotal: '入库总额', searchProduct: '搜索产品', searchPlaceholder: '名称、SKU 或代码', quantity: '数量', unitCost: '单位成本', taxRate: '税率', addItem: '添加项目', noProducts: '没有符合搜索条件的产品。', createProduct: '创建产品', newProductName: '新产品名称', skuOptional: 'SKU（可选）', creatingProduct: '正在创建…', lineProduct: '产品', lineQuantity: '数量', lineUnitCost: '单位成本', lineTax: '税额', lineTotal: '总计', removeLine: '移除项目', emptyLines: '请至少添加一个产品以创建采购。', upload: '上传', removeFile: '移除', noProvider: '无供应商', itemSubtotal: '项目小计', itemTax: '项目税额', itemTotal: '项目总计', reconciled: '已核对', unreconciled: '需要核对', differenceLabel: (value: string) => `差额：${value}`, noInvoiceSummary: '若无发票，将按项目总计创建采购单和运营承诺。' },
  print: { purchaseFile: 'purchase-order', receiptFile: 'goods-receipt', supplierEmail: '供应商邮箱', deliveryWarehouse: '收货仓库', orderDate: '订单日期', taxes: '税费', items: '项目', orderNotice: '商业采购文件。它不是税务发票，也不能单独证明货物已收取或付款已完成。', notesAndTerms: '备注与条款', preparedBy: '制单人', authorizedBy: '批准人', supplier: '供应商', itemColumns: ['SKU', '产品', '数量', '单位成本', '税费', '小计', '总计'], orderItems: '订单项目', orderTitle: '采购单', confidentiality: '内部', purchaseOrder: '采购单', receiptDate: '收货日期', followingStatus: '收货后状态', receivedItems: '已收项目', receivedUnits: '已收数量', previousPendingItems: '先前待收项目', receiptNotice: '运营收货记录。订单没有独立的收货编号；所显示的编号属于采购单。', receiptNotes: '收货备注', deliveredBy: '供应商交付', receivedBy: '仓库签收', supervisedBy: '监督人', receiptRecorded: '收货已登记', receiptColumns: ['SKU', '产品', '订购数量', '先前待收', '本次收货', '预计待收'], receivedGoods: '已收货物', receiptTitle: '货物收货记录' },
  submissionDetail: { closeLabel: '关闭供应商提案', eyebrow: '供应商提案', close: '关闭', footerSummary: (count: number, total: string) => `${count} 个项目 · 总计 ${total}`, itemsTitle: '提议项目', itemsSubtitle: '供应商提出方案；Indice 负责审核、关联产品并决定哪些项目转为正式采购。', unresolvedWarning: (count: number) => `${count} 个项目未关联产品目录。转换为采购单前请先审核。`, linkedProduct: (id: number) => `产品 #${id}`, newProduct: '新产品', noSupplierSku: '无供应商 SKU', unitCost: (value: string) => `每件 ${value}`, provider: '供应商', submittedBy: '提交人', supplierFallback: '供应商', internalReview: '内部审核', reviewNote: '审核备注', saveReview: '保存审核', convertTitle: '转换为采购单', convertNote: '采购单备注', convert: '转换为采购单' },
  cancelDialog: { title: '取消采购单', description: '采购将保留在历史记录中，状态改为已取消。此操作不会删除库存或发票记录。', confirm: '取消采购', note: '已从销售点取消。' },
} as const satisfies PurchaseOrderTranslations;
