import type { CreateProductInput, SalesCatalogItem } from '../../types';
import { defaultSalesCurrency, normalizeSalesCurrencyCode } from '../../utils/salesCurrency';
import type { ProductFormState } from '../types/productosTypes';
import { createProductImageGallery, getProductGalleryImages } from './productImages';

export const initialProductForm: ProductFormState = {
  name: '',
  sku: '',
  category: 'Software',
  type: 'Service',
  currency: defaultSalesCurrency,
  price: '',
  cost: '',
  logisticsCost: '',
  additionalCost: '',
  desiredMarginPercentage: '30',
  taxCategory: 'Standard VAT',
  status: 'Active',
  visibility: 'Commercial',
  barcode: '',
  generatedLabels: [],
  imageUrl: '',
  imageAlt: '',
  galleryUrls: '',
  uploadedImages: [],
  description: '',
  baseUnit: 'Piece',
  saleUnit: 'Unit',
  unitsPerSaleUnit: '1',
  pricingMode: 'Per sale unit',
  saleUnitPrice: '',
  minimumSaleQuantity: '1',
  saleIncrement: '1',
  wholesalePrice: '',
  wholesaleMinimumQuantity: '',
  packagingBarcode: '',
  packagingNotes: '',
  bundleItems: [],
  usesInventory: false,
  reservable: false,
  availabilityIcalUrl: '',
  serviceUnit: 'Project',
  serviceEstimatedDuration: '',
  serviceScopeNotes: '',
  serviceDeliveryNotes: '',
  subscriptionFrequency: 'Monthly',
  subscriptionCycleLabel: '',
  subscriptionRenewalBehavior: '',
  subscriptionMinimumTerm: '',
  subscriptionCancellationNotes: '',
  operationalUseNotes: '',
  internalReference: '',
};

export function buildProductForm(product: SalesCatalogItem): ProductFormState {
  const galleryImages = getProductGalleryImages(product);

  return {
    name: product.name,
    sku: product.sku,
    category: product.category,
    type: product.type,
    currency: normalizeSalesCurrencyCode(product.currency),
    price: String(product.price),
    cost: String(product.cost),
    logisticsCost: '',
    additionalCost: '',
    desiredMarginPercentage: '30',
    taxCategory: product.taxCategory,
    status: product.status,
    visibility: product.visibility,
    barcode: product.barcode ?? '',
    generatedLabels: product.generatedLabels ?? [],
    imageUrl: '',
    imageAlt: '',
    galleryUrls: '',
    uploadedImages: galleryImages.map((image, index) => ({
      id: `${product.id}-image-${index}-${image.id}`,
      url: image.url,
      alt: image.alt,
      source: 'url',
      objectKey: image.objectKey,
      fileName: image.fileName,
      contentType: image.contentType,
      sizeBytes: image.sizeBytes,
    })),
    baseUnit: product.packaging?.baseUnit ?? 'Piece',
    saleUnit: product.packaging?.saleUnit ?? 'Unit',
    unitsPerSaleUnit: String(product.packaging?.unitsPerSaleUnit ?? 1),
    pricingMode: product.packaging?.pricingMode ?? 'Per sale unit',
    saleUnitPrice: product.packaging?.saleUnitPrice === undefined ? '' : String(product.packaging.saleUnitPrice),
    minimumSaleQuantity: String(product.packaging?.minimumSaleQuantity ?? 1),
    saleIncrement: String(product.packaging?.saleIncrement ?? 1),
    wholesalePrice: product.packaging?.wholesalePrice === undefined ? '' : String(product.packaging.wholesalePrice),
    wholesaleMinimumQuantity: product.packaging?.wholesaleMinimumQuantity === undefined ? '' : String(product.packaging.wholesaleMinimumQuantity),
    packagingBarcode: product.packaging?.barcode ?? '',
    packagingNotes: product.packaging?.notes ?? '',
    bundleItems: (product.packaging?.bundleItems ?? []).map((item) => ({
      id: item.id,
      name: item.name,
      quantity: String(item.quantity),
      unit: item.unit,
      notes: item.notes ?? '',
    })),
    usesInventory: Boolean(product.stockPrepared || product.warehousePrepared),
    reservable: Boolean(product.reservable),
    availabilityIcalUrl: product.availabilityIcalUrl ?? '',
    serviceUnit: 'Project',
    serviceEstimatedDuration: '',
    serviceScopeNotes: '',
    serviceDeliveryNotes: '',
    subscriptionFrequency: 'Monthly',
    subscriptionCycleLabel: '',
    subscriptionRenewalBehavior: '',
    subscriptionMinimumTerm: '',
    subscriptionCancellationNotes: '',
    operationalUseNotes: '',
    internalReference: '',
    description: product.description,
  };
}

export function buildProductInput(
  form: ProductFormState,
  thumbnailTone: SalesCatalogItem['thumbnailTone'] = 'coral',
): CreateProductInput {
  const images = createProductImageGallery({
    productId: form.sku.trim() || 'new-product',
    primaryImageUrl: form.imageUrl.trim() || undefined,
    primaryImageAlt: form.imageAlt.trim() || undefined,
    galleryUrls: form.galleryUrls,
    uploadedImages: form.uploadedImages,
    productName: form.name.trim(),
  });

  return {
    name: form.name.trim(),
    sku: form.sku.trim(),
    category: form.category as SalesCatalogItem['category'],
    type: form.type,
    description: form.description.trim(),
    price: Number(form.price) || 0,
    cost: Number(form.cost) || 0,
    currency: normalizeSalesCurrencyCode(form.currency),
    taxCategory: form.taxCategory,
    status: form.status,
    visibility: form.visibility,
    barcode: form.barcode.trim() || undefined,
    generatedLabels: form.generatedLabels.length > 0 ? form.generatedLabels : undefined,
    imageUrl: images.imageUrl,
    imageAlt: images.imageAlt,
    gallery: images.gallery,
    packaging: {
      baseUnit: form.baseUnit,
      saleUnit: form.saleUnit,
      unitsPerSaleUnit: Number(form.unitsPerSaleUnit) || 1,
      pricingMode: form.pricingMode,
      saleUnitPrice: form.saleUnitPrice.trim() ? Number(form.saleUnitPrice) || 0 : undefined,
      minimumSaleQuantity: Number(form.minimumSaleQuantity) || 1,
      saleIncrement: Number(form.saleIncrement) || 1,
      wholesalePrice: form.wholesalePrice.trim() ? Number(form.wholesalePrice) || 0 : undefined,
      wholesaleMinimumQuantity: form.wholesaleMinimumQuantity.trim() ? Number(form.wholesaleMinimumQuantity) || 1 : undefined,
      barcode: form.packagingBarcode.trim() || undefined,
      notes: form.packagingNotes.trim() || undefined,
      bundleItems: form.bundleItems
        .filter((item) => item.name.trim())
        .map((item) => ({
          id: item.id,
          name: item.name.trim(),
          quantity: Number(item.quantity) || 1,
          unit: item.unit,
          notes: item.notes.trim() || undefined,
        })),
    },
    thumbnailTone,
    stockPrepared: form.usesInventory,
    warehousePrepared: form.usesInventory,
    posPrepared: form.visibility === 'POS ready',
    variantsPrepared: form.type === 'Subscription' || form.type === 'Package',
    reservable: form.reservable,
    availabilityIcalUrl: form.reservable ? form.availabilityIcalUrl.trim() : undefined,
  };
}
