import type { DiagnosticTagId, DiagnosisPillar } from './types';

type TagCatalogEntry = {
  label: string;
  pillar: DiagnosisPillar;
  businessImpact: string;
  recommendedAction: string;
  quickWin: string;
  suggestedModule: string;
};

const people = 'Recursos Humanos';
const processes = 'Procesos y tareas';
const products = 'CRM / Punto de venta';
const finance = 'Gastos y KPIs';

export const DIAGNOSTIC_TAG_CATALOG: Record<DiagnosticTagId, TagCatalogEntry> = {
  dependencia_fundador: {
    label: 'Dependencia del fundador',
    pillar: 'people',
    businessImpact: 'El crecimiento queda limitado por la agenda de una persona clave.',
    recommendedAction: 'Separar decisiones estrategicas de tareas operativas y asignar duenos por flujo.',
    quickWin: 'Elegir una decision repetitiva y delegarla con criterio, limite y revision semanal.',
    suggestedModule: people,
  },
  baja_delegacion: {
    label: 'Delegacion incompleta',
    pillar: 'people',
    businessImpact: 'El equipo ejecuta, pero la direccion sigue cargando control y validacion.',
    recommendedAction: 'Definir responsables con autonomia, criterio de exito y puntos de control.',
    quickWin: 'Publicar una tabla simple de responsable, decision y fecha de revision.',
    suggestedModule: people,
  },
  roles_poco_claros: {
    label: 'Roles poco claros',
    pillar: 'people',
    businessImpact: 'Las tareas regresan a direccion o se duplican entre personas.',
    recommendedAction: 'Documentar quien decide, quien ejecuta y quien valida cada frente critico.',
    quickWin: 'Crear una matriz RACI para los tres procesos mas repetidos.',
    suggestedModule: people,
  },
  responsabilidades_poco_claras: {
    label: 'Responsabilidades poco claras',
    pillar: 'people',
    businessImpact: 'La ambiguedad retrasa entregas y vuelve manual el seguimiento.',
    recommendedAction: 'Asignar un dueno visible por tarea recurrente, con fecha y estado.',
    quickWin: 'Convertir pendientes recurrentes en tareas con responsable unico.',
    suggestedModule: processes,
  },
  seguimiento_manual: {
    label: 'Seguimiento manual',
    pillar: 'people',
    businessImpact: 'La operacion depende de recordatorios, chats y memoria.',
    recommendedAction: 'Centralizar tareas activas en una vista unica de responsables, fechas y estados.',
    quickWin: 'Mover los pendientes de chat a un tablero operativo.',
    suggestedModule: processes,
  },
  comunicacion_por_chat: {
    label: 'Comunicacion por chat',
    pillar: 'people',
    businessImpact: 'Las decisiones se pierden en conversaciones y el seguimiento queda disperso.',
    recommendedAction: 'Separar anuncios, tareas y decisiones en espacios consultables.',
    quickWin: 'Crear un canal o tablero solo para decisiones y acuerdos.',
    suggestedModule: processes,
  },
  reuniones_sin_cierre: {
    label: 'Reuniones sin cierre operativo',
    pillar: 'people',
    businessImpact: 'La conversacion genera sensacion de avance, pero no control real.',
    recommendedAction: 'Cerrar cada reunion con responsable, fecha y siguiente accion.',
    quickWin: 'Usar una plantilla de acuerdos para cada reunion semanal.',
    suggestedModule: processes,
  },
  onboarding_manual: {
    label: 'Onboarding manual',
    pillar: 'people',
    businessImpact: 'Cada nueva persona aprende distinto y consume tiempo del equipo.',
    recommendedAction: 'Crear una guia de incorporacion con accesos, rutinas y primeras tareas.',
    quickWin: 'Documentar el primer dia de trabajo en una checklist reutilizable.',
    suggestedModule: people,
  },
  baja_documentacion: {
    label: 'Baja documentacion',
    pillar: 'processes',
    businessImpact: 'El conocimiento vive en personas y la operacion se vuelve fragil.',
    recommendedAction: 'Documentar los flujos mas repetidos con pasos, dueno y criterio de cierre.',
    quickWin: 'Documentar el proceso que mas se repite esta semana.',
    suggestedModule: processes,
  },
  procesos_informales: {
    label: 'Procesos informales',
    pillar: 'processes',
    businessImpact: 'Cada persona ejecuta distinto y el resultado se vuelve inconsistente.',
    recommendedAction: 'Definir entrada, pasos, salida esperada y responsable por proceso clave.',
    quickWin: 'Convertir un flujo informal en checklist operativa.',
    suggestedModule: processes,
  },
  baja_visibilidad_operativa: {
    label: 'Baja visibilidad operativa',
    pillar: 'processes',
    businessImpact: 'Los retrasos se detectan tarde y afectan servicio, ventas o costos.',
    recommendedAction: 'Revisar pendientes, vencidos y bloqueos con una cadencia fija.',
    quickWin: 'Crear una vista semanal de tareas vencidas y bloqueadas.',
    suggestedModule: processes,
  },
  baja_automatizacion: {
    label: 'Baja automatizacion',
    pillar: 'processes',
    businessImpact: 'El equipo consume energia en tareas repetitivas que no agregan criterio.',
    recommendedAction: 'Convertir tareas repetidas en plantillas, reglas o recordatorios.',
    quickWin: 'Automatizar o templatar una tarea semanal recurrente.',
    suggestedModule: processes,
  },
  operacion_no_replicable: {
    label: 'Operacion no replicable',
    pillar: 'processes',
    businessImpact: 'Abrir otra unidad o contratar otra persona exige improvisar.',
    recommendedAction: 'Estandarizar los procesos que mas afectan cliente, equipo y caja.',
    quickWin: 'Crear una version 1 de la checklist del proceso principal.',
    suggestedModule: processes,
  },
  perdida_tiempo_manual: {
    label: 'Perdida de tiempo manual',
    pillar: 'processes',
    businessImpact: 'El costo operativo se esconde en tareas repetitivas y poco visibles.',
    recommendedAction: 'Identificar tareas manuales frecuentes y decidir cuales templatar o automatizar.',
    quickWin: 'Registrar durante una semana las tareas manuales repetidas.',
    suggestedModule: processes,
  },
  perdida_tiempo_coordinacion: {
    label: 'Perdida de tiempo por coordinacion',
    pillar: 'processes',
    businessImpact: 'El avance depende de persecucion manual entre personas.',
    recommendedAction: 'Hacer visible el estado de cada tarea sin pedir actualizaciones por chat.',
    quickWin: 'Usar estados simples: pendiente, en curso, bloqueado y terminado.',
    suggestedModule: processes,
  },
  perdida_tiempo_informacion: {
    label: 'Perdida de tiempo por informacion',
    pillar: 'processes',
    businessImpact: 'El equipo tarda en encontrar datos, acuerdos o documentos para ejecutar.',
    recommendedAction: 'Centralizar informacion critica por proceso y responsable.',
    quickWin: 'Crear un indice de documentos y accesos del flujo principal.',
    suggestedModule: processes,
  },
  perdida_tiempo_seguimiento: {
    label: 'Perdida de tiempo por seguimiento',
    pillar: 'processes',
    businessImpact: 'La gerencia invierte tiempo en pedir avances que deberian estar visibles.',
    recommendedAction: 'Crear un tablero de seguimiento con vencidos, bloqueos y responsables.',
    quickWin: 'Revisar tareas vencidas cada lunes con responsables visibles.',
    suggestedModule: processes,
  },
  dependencia_personas_clave: {
    label: 'Dependencia de personas clave',
    pillar: 'processes',
    businessImpact: 'La ausencia de una persona puede detener decisiones o entregas.',
    recommendedAction: 'Definir responsable principal, respaldo y documentacion minima por proceso critico.',
    quickWin: 'Nombrar un respaldo para el proceso mas sensible.',
    suggestedModule: processes,
  },
  errores_reactivos: {
    label: 'Errores gestionados reactivamente',
    pillar: 'processes',
    businessImpact: 'Los mismos problemas se repiten y erosionan margen, tiempo y confianza.',
    recommendedAction: 'Registrar causa, correccion y prevencion por error relevante.',
    quickWin: 'Crear una minuta de aprendizaje para el ultimo error operativo.',
    suggestedModule: processes,
  },
  baja_escalabilidad: {
    label: 'Baja escalabilidad',
    pillar: 'processes',
    businessImpact: 'Crecer aumentara complejidad mas rapido que la capacidad de controlarla.',
    recommendedAction: 'Estandarizar antes de expandir equipo, unidades o canales.',
    quickWin: 'Elegir un proceso que debe funcionar igual aunque el volumen suba.',
    suggestedModule: processes,
  },
  oferta_poco_clara: {
    label: 'Oferta poco clara',
    pillar: 'products',
    businessImpact: 'Si el equipo no explica igual que vende, el mercado tampoco entiende por que comprar.',
    recommendedAction: 'Definir oferta principal con problema, solucion, cliente ideal y resultado esperado.',
    quickWin: 'Escribir la oferta principal en una frase y validarla con el equipo comercial.',
    suggestedModule: products,
  },
  cliente_objetivo_difuso: {
    label: 'Cliente objetivo difuso',
    pillar: 'products',
    businessImpact: 'Vender a todos dispersa marketing, servicio y desarrollo de producto.',
    recommendedAction: 'Elegir el segmento con mayor margen, repeticion o velocidad de compra.',
    quickWin: 'Nombrar el cliente ideal y el cliente que conviene dejar de perseguir.',
    suggestedModule: products,
  },
  ingresos_no_priorizados: {
    label: 'Ingresos no priorizados',
    pillar: 'products',
    businessImpact: 'El negocio puede invertir esfuerzo en lineas que no sostienen rentabilidad.',
    recommendedAction: 'Ordenar ofertas por ingreso, margen, recurrencia y complejidad operativa.',
    quickWin: 'Crear una tabla de top productos por ventas y margen estimado.',
    suggestedModule: products,
  },
  baja_diversificacion: {
    label: 'Baja diversificacion',
    pillar: 'products',
    businessImpact: 'Depender de una sola linea expone al negocio ante cambios de demanda.',
    recommendedAction: 'Definir una segunda fuente de ingreso viable sin diluir la oferta principal.',
    quickWin: 'Identificar el complemento mas natural a la oferta actual.',
    suggestedModule: products,
  },
  precios_por_intuicion: {
    label: 'Precios por intuicion',
    pillar: 'products',
    businessImpact: 'El negocio puede crecer en ventas mientras pierde margen.',
    recommendedAction: 'Conectar precio, costo directo, descuento permitido y margen minimo.',
    quickWin: 'Calcular margen real de los tres productos o servicios mas vendidos.',
    suggestedModule: finance,
  },
  baja_medicion_comercial: {
    label: 'Baja medicion comercial',
    pillar: 'products',
    businessImpact: 'Las decisiones comerciales se basan en percepcion y no en comportamiento real.',
    recommendedAction: 'Medir ventas, margen, recurrencia y quejas por oferta.',
    quickWin: 'Crear un tablero semanal de ventas por producto y margen estimado.',
    suggestedModule: products,
  },
  propuesta_valor_debil: {
    label: 'Propuesta de valor debil',
    pillar: 'products',
    businessImpact: 'Si la promesa es generica, el precio se vuelve el unico argumento.',
    recommendedAction: 'Definir tres razones concretas por las que el cliente deberia elegir la empresa.',
    quickWin: 'Comparar la promesa actual contra tres competidores directos.',
    suggestedModule: products,
  },
  feedback_cliente_informal: {
    label: 'Feedback de cliente informal',
    pillar: 'products',
    businessImpact: 'El producto evoluciona desde intuicion interna y no desde evidencia del cliente.',
    recommendedAction: 'Cerrar el ciclo de feedback con preguntas, registro y decision de mejora.',
    quickWin: 'Preguntar a cinco clientes que valoraron, que falto y que casi impide la compra.',
    suggestedModule: products,
  },
  producto_reactivo: {
    label: 'Producto reactivo',
    pillar: 'products',
    businessImpact: 'Las mejoras compiten con urgencias y no construyen ventaja acumulada.',
    recommendedAction: 'Priorizar mejoras por impacto, esfuerzo, responsable y fecha.',
    quickWin: 'Crear un backlog de mejoras con impacto esperado.',
    suggestedModule: products,
  },
  foco_comercial_disperso: {
    label: 'Foco comercial disperso',
    pillar: 'products',
    businessImpact: 'Demasiadas prioridades comerciales diluyen ejecucion y aprendizaje.',
    recommendedAction: 'Elegir una prioridad comercial por mes y medir su efecto.',
    quickWin: 'Definir la prioridad comercial de los proximos 30 dias.',
    suggestedModule: products,
  },
  baja_visibilidad_financiera: {
    label: 'Baja visibilidad financiera',
    pillar: 'finance',
    businessImpact: 'El negocio decide tarde y puede confundir ventas con salud financiera.',
    recommendedAction: 'Consolidar ingresos, egresos, caja disponible y cuentas por cobrar semanalmente.',
    quickWin: 'Crear una vista semanal de caja, ingresos, gastos y cobranza.',
    suggestedModule: finance,
  },
  revision_financiera_esporadica: {
    label: 'Revision financiera esporadica',
    pillar: 'finance',
    businessImpact: 'Los problemas financieros aparecen cuando ya son urgentes.',
    recommendedAction: 'Instalar una revision fija de caja, margen y gastos.',
    quickWin: 'Agendar 30 minutos semanales para revisar caja y margen.',
    suggestedModule: finance,
  },
  flujo_no_proyectado: {
    label: 'Flujo no proyectado',
    pillar: 'finance',
    businessImpact: 'La empresa puede ser rentable en papel y aun asi quedarse sin liquidez.',
    recommendedAction: 'Proyectar entradas y salidas de las proximas cuatro semanas.',
    quickWin: 'Construir una proyeccion de caja de 4 semanas.',
    suggestedModule: finance,
  },
  costos_aproximados: {
    label: 'Costos aproximados',
    pillar: 'finance',
    businessImpact: 'Precios y descuentos pueden destruir margen sin que sea evidente.',
    recommendedAction: 'Separar costos directos, gastos fijos y variables por linea o unidad.',
    quickWin: 'Calcular costo directo de las tres ofertas mas importantes.',
    suggestedModule: finance,
  },
  margen_estimado: {
    label: 'Margen estimado',
    pillar: 'finance',
    businessImpact: 'El crecimiento puede financiarse con utilidad insuficiente.',
    recommendedAction: 'Definir margen minimo aceptable y revisarlo antes de descuentos.',
    quickWin: 'Definir un margen minimo por producto o servicio principal.',
    suggestedModule: finance,
  },
  decisiones_por_intuicion: {
    label: 'Decisiones por intuicion',
    pillar: 'finance',
    businessImpact: 'La intuicion sin datos aumenta errores repetidos en precio, gasto y crecimiento.',
    recommendedAction: 'Revisar caja, margen e impacto esperado antes de decisiones relevantes.',
    quickWin: 'Crear una checklist financiera para aprobar compras, descuentos o contrataciones.',
    suggestedModule: finance,
  },
  ventas_no_predecibles: {
    label: 'Ventas no predecibles',
    pillar: 'finance',
    businessImpact: 'La planeacion depende de ventas de ultimo minuto.',
    recommendedAction: 'Separar ingresos recurrentes, probables y extraordinarios.',
    quickWin: 'Clasificar el ingreso del mes en recurrente, probable y extraordinario.',
    suggestedModule: finance,
  },
  deuda_poco_visible: {
    label: 'Deuda poco visible',
    pillar: 'finance',
    businessImpact: 'Pagos mal calendarizados presionan caja y bloquean decisiones.',
    recommendedAction: 'Listar deuda, pagos, tasas y fechas criticas en una vista mensual.',
    quickWin: 'Crear calendario de pagos de deuda de los proximos 90 dias.',
    suggestedModule: finance,
  },
  sin_colchon_crisis: {
    label: 'Baja preparacion ante crisis',
    pillar: 'finance',
    businessImpact: 'Un mes dificil puede obligar a recortes improvisados o deuda cara.',
    recommendedAction: 'Definir caja minima, gastos pausables y escenario de emergencia.',
    quickWin: 'Identificar gastos que pueden pausarse si caja baja del minimo.',
    suggestedModule: finance,
  },
  cumplimiento_fiscal_reactivo: {
    label: 'Cumplimiento fiscal reactivo',
    pillar: 'finance',
    businessImpact: 'Pendientes fiscales pueden convertirse en multas o decisiones apresuradas.',
    recommendedAction: 'Crear calendario fiscal con responsables, fechas y documentos requeridos.',
    quickWin: 'Listar las proximas tres obligaciones fiscales y su responsable.',
    suggestedModule: finance,
  },
};
