import type { LearningCharacterId, LearningModeControl } from '../../../learningMode';
import type { SalesGuidanceTabId } from './types';

type CharacterExamples = Record<LearningCharacterId, string>;

interface SalesControlSeed {
  id: string;
  emoji: string;
  kind: string;
  title: string;
  purpose: string;
  behavior: string;
  whenToUse: string;
  result: string;
  focus: string;
  examples: CharacterExamples;
}

const createControl = ({ focus, examples, ...control }: SalesControlSeed): LearningModeControl => ({
  ...control,
  tipByCharacter: {
    emily: `Convierte ${focus} en un estándar comercial que pueda repetirse con la misma calidad en cada cafetería.`,
    juanito: `Relaciona ${focus} con un responsable, una fecha y un dato verificable para que el seguimiento no dependa de tu memoria.`,
    camila: `Haz visible ${focus} aunque la relación con clientes y colaboradores sea cercana; la confianza funciona mejor con acuerdos claros.`,
  },
  storyByCharacter: examples,
});

export const salesLearningControls: Partial<Record<
  SalesGuidanceTabId,
  readonly LearningModeControl[]
>> = {
  leads: [
    createControl({
      id: 'lead-columns',
      emoji: '🧩',
      kind: 'Botón de configuración',
      title: 'Columnas',
      purpose: 'Define qué datos del pipeline aparecen en la tabla y cómo se ordenan.',
      behavior: 'Abre el configurador para mostrar, ocultar, ordenar y ajustar las columnas disponibles.',
      whenToUse: 'Úsalo antes de una revisión enfocada en responsables, valor, etapa, temperatura o próxima actividad.',
      result: 'Evita perder señales importantes entre información que no necesitas para la decisión actual.',
      focus: 'la lectura del pipeline',
      examples: {
        emily: 'Emily muestra sucursal, responsable, etapa y próxima actividad. Así sus gerentes revisan oportunidades con el mismo criterio en todas las cafeterías.',
        juanito: 'Juanito deja visibles valor estimado, probabilidad y fecha de seguimiento. Sus números explican qué oportunidad necesita acción y quién debe realizarla.',
        camila: 'Camila organiza primero cliente, vehículo, pieza solicitada y responsable. El equipo de mostrador entiende el caso sin preguntarle todo nuevamente.',
      },
    }),
    createControl({
      id: 'create-opportunity',
      emoji: '➕',
      kind: 'Botón de acción',
      title: 'Crear oportunidad',
      purpose: 'Registra una posibilidad real de venta con cliente, responsable, valor y siguiente paso.',
      behavior: 'Abre el formulario de oportunidad y la incorpora al pipeline después de validar los datos requeridos.',
      whenToUse: 'Úsalo cuando exista una necesidad comercial concreta que merezca seguimiento.',
      result: 'Evita que solicitudes y conversaciones con potencial de ingreso queden fuera del proceso comercial.',
      focus: 'la captura disciplinada de oportunidades',
      examples: {
        emily: 'Emily registra la solicitud de servicio de café para una oficina y asigna a una responsable. La oportunidad avanza aunque ella esté atendiendo otra sucursal.',
        juanito: 'Juanito captura una negociación de abasto con valor y fecha. Deja de contar posibles ventas en una hoja separada del seguimiento real.',
        camila: 'Camila registra a un taller que solicita surtido recurrente. La conversación deja de vivir solo en el teléfono del vendedor que lo atendió.',
      },
    }),
    createControl({
      id: 'create-quote-from-lead',
      emoji: '💬',
      kind: 'Botón de acción',
      title: 'Crear cotización',
      purpose: 'Transforma una oportunidad calificada en una propuesta con productos, precios y condiciones.',
      behavior: 'Abre el constructor de cotización conservando el cliente y el contexto de la oportunidad.',
      whenToUse: 'Úsalo cuando la necesidad, alcance y persona decisora estén suficientemente claros.',
      result: 'Reduce recaptura y mantiene conectada la propuesta con el origen de la venta.',
      focus: 'el paso de oportunidad a propuesta',
      examples: {
        emily: 'Emily cotiza un servicio corporativo desde la oportunidad ya calificada. Conserva el contexto y protege el estándar de precio de sus cafeterías.',
        juanito: 'Juanito genera la cotización cuando presupuesto y volumen están confirmados. Puede comparar valor potencial contra la oferta realmente enviada.',
        camila: 'Camila convierte la solicitud del taller en una cotización con piezas y vigencia. El mostrador no necesita reconstruir el pedido desde mensajes.',
      },
    }),
    createControl({
      id: 'create-sale-from-lead',
      emoji: '💼',
      kind: 'Botón de acción',
      title: 'Crear venta',
      purpose: 'Registra un cierre comercial cuando la oportunidad ya cuenta con la información necesaria.',
      behavior: 'Abre el flujo de venta y conecta cliente, productos, responsable y contexto disponible.',
      whenToUse: 'Úsalo únicamente después de confirmar aceptación y condiciones del cierre.',
      result: 'Evita registrar como ingreso una conversación que todavía no está ganada.',
      focus: 'la conversión correcta a venta',
      examples: {
        emily: 'Emily convierte un servicio aceptado en venta y deja preparada la entrega para la cafetería responsable.',
        juanito: 'Juanito crea la venta solo cuando puede explicar monto, responsable y validación. Sus totales dejan de mezclar cierres reales con intenciones.',
        camila: 'Camila registra la venta del pedido confirmado y el almacén conoce qué piezas debe preparar sin depender de una llamada.',
      },
    }),
    createControl({
      id: 'lead-views',
      emoji: '🗃️',
      kind: 'Selector de vista',
      title: 'Tabla, embudo y agenda',
      purpose: 'Permite leer las mismas oportunidades como registros, etapas visuales o actividades programadas.',
      behavior: 'Cambia la presentación sin modificar los datos ni perder los filtros actuales.',
      whenToUse: 'Usa tabla para detalle, embudo para balance por etapa y agenda para compromisos con fecha.',
      result: 'Evita administrar listas separadas para analizar, priorizar y programar el seguimiento.',
      focus: 'la vista adecuada para cada revisión',
      examples: {
        emily: 'Emily usa el embudo en su reunión semanal y la agenda para confirmar que cada gerente tenga un siguiente contacto programado.',
        juanito: 'Juanito revisa valores en tabla, distribución en embudo y vencimientos en agenda. Los tres enfoques leen la misma fuente de datos.',
        camila: 'Camila utiliza la agenda para que vendedores y mostrador sepan a quién llamar hoy, sin recorrer conversaciones antiguas.',
      },
    }),
    createControl({
      id: 'lead-filters',
      emoji: '🔎',
      kind: 'Filtros comerciales',
      title: 'Buscar y filtrar oportunidades',
      purpose: 'Acota el pipeline por periodo, etapa, responsable, temperatura, fuente, estado o prioridad.',
      behavior: 'Actualiza vistas e indicadores para mostrar únicamente el segmento seleccionado.',
      whenToUse: 'Úsalo para responder una pregunta específica antes de tomar una decisión comercial.',
      result: 'Permite detectar atrasos, concentración de riesgo y cargas de seguimiento por responsable.',
      focus: 'la segmentación del seguimiento',
      examples: {
        emily: 'Emily filtra oportunidades sin próxima actividad y descubre qué gerente necesita apoyo para sostener el estándar de seguimiento.',
        juanito: 'Juanito filtra cierres del periodo y compara ganadas contra perdidas. Analiza resultados sin contaminar el cálculo con oportunidades abiertas.',
        camila: 'Camila filtra solicitudes calientes y vencidas. El equipo atiende primero los casos que pueden convertirse o perderse hoy.',
      },
    }),
    createControl({
      id: 'lead-record-actions',
      emoji: '🛠️',
      kind: 'Acciones del registro',
      title: 'Consultar, editar, programar y cerrar',
      purpose: 'Administra el expediente completo de una oportunidad durante su ciclo comercial.',
      behavior: 'Las acciones permiten ver detalle, archivos e historial; editar datos, programar actividades o eliminar con confirmación.',
      whenToUse: 'Úsalas cada vez que cambie el contexto, exista nueva evidencia o termine la oportunidad.',
      result: 'Conserva una historia comercial explicable y evita seguimientos basados en versiones distintas.',
      focus: 'el expediente vivo de cada oportunidad',
      examples: {
        emily: 'Emily revisa historial y actividades antes de intervenir en una cuenta. Apoya a la gerente sin repetir preguntas al cliente.',
        juanito: 'Juanito actualiza etapa, valor y fecha cuando recibe nueva información. El pipeline mantiene cifras que corresponden con la realidad.',
        camila: 'Camila consulta archivos y notas antes de prometer una pieza. El vendedor y el almacén trabajan con el mismo contexto.',
      },
    }),
  ],
  contacts: [
    createControl({
      id: 'contact-columns',
      emoji: '🧩',
      kind: 'Botón de configuración',
      title: 'Columnas',
      purpose: 'Define qué información del directorio se muestra y en qué orden.',
      behavior: 'Abre el configurador para mostrar, ocultar y ordenar datos de contacto, empresa, responsable y relación.',
      whenToUse: 'Úsalo para adaptar la tabla a una revisión comercial, fiscal o de seguimiento.',
      result: 'Reduce ruido y hace visibles los datos necesarios para atender correctamente a cada persona.',
      focus: 'la organización del directorio',
      examples: {
        emily: 'Emily muestra empresa, sucursal de referencia y responsable. Sus gerentes reconocen rápidamente el contexto de cada contacto.',
        juanito: 'Juanito ordena correo, teléfono, datos fiscales y propietario. Puede validar completitud sin revisar cada ficha por separado.',
        camila: 'Camila coloca primero empresa, tipo de cliente y teléfono. El mostrador encuentra la relación correcta durante una llamada.',
      },
    }),
    createControl({
      id: 'import-contacts',
      emoji: '📥',
      kind: 'Botón de acción',
      title: 'Importar contactos',
      purpose: 'Incorpora varios contactos desde un archivo sin capturarlos uno por uno.',
      behavior: 'Abre el asistente, valida columnas y datos, muestra errores y confirma los registros aceptados.',
      whenToUse: 'Úsalo al migrar una base existente o incorporar una lista autorizada de clientes.',
      result: 'Acelera la migración sin convertir errores del archivo en registros difíciles de corregir.',
      focus: 'la importación controlada de información',
      examples: {
        emily: 'Emily importa la lista corporativa y revisa duplicados antes de asignar responsables por región.',
        juanito: 'Juanito valida cuántas filas fueron aceptadas y cuáles fallaron. Sus conteos coinciden antes y después de la migración.',
        camila: 'Camila convierte la libreta digital de clientes en un directorio compartido que ya no vive únicamente en un teléfono.',
      },
    }),
    createControl({
      id: 'add-contact',
      emoji: '➕',
      kind: 'Botón de acción',
      title: 'Agregar contacto',
      purpose: 'Crea la ficha comercial de una persona o empresa antes de relacionarla con oportunidades y cotizaciones.',
      behavior: 'Abre el formulario, valida datos personales, fiscales y de responsable, y agrega el registro al directorio.',
      whenToUse: 'Úsalo en el primer contacto significativo con un prospecto, cliente o decisor.',
      result: 'Evita oportunidades sin identidad clara y reduce contactos duplicados.',
      focus: 'la creación de un directorio confiable',
      examples: {
        emily: 'Emily registra al responsable de compras de una oficina antes de preparar la propuesta de servicio.',
        juanito: 'Juanito crea un solo contacto con correo, teléfono y datos fiscales completos. Después relaciona todas sus oportunidades con esa ficha.',
        camila: 'Camila registra al dueño del taller y su empresa. Los vendedores dejan de guardar versiones diferentes del mismo cliente.',
      },
    }),
    createControl({
      id: 'contact-search-sort',
      emoji: '🔎',
      kind: 'Herramientas de consulta',
      title: 'Buscar y ordenar contactos',
      purpose: 'Localiza personas y organiza el directorio por el dato que necesitas revisar.',
      behavior: 'La búsqueda reduce coincidencias y los encabezados cambian el orden sin alterar los registros.',
      whenToUse: 'Úsalos antes de comunicarte, editar o crear una oportunidad para un contacto existente.',
      result: 'Evita duplicar fichas y acelera el acceso al contexto correcto.',
      focus: 'la consulta del contacto correcto',
      examples: {
        emily: 'Emily busca la empresa antes de agregar una nueva persona y encuentra que ya existe una relación administrada por otra sucursal.',
        juanito: 'Juanito ordena por responsable y revisa cuántos contactos no tienen dueño comercial asignado.',
        camila: 'Camila busca por empresa o teléfono y evita crear otra ficha para un cliente que ya atendió alguien del mostrador.',
      },
    }),
    createControl({
      id: 'contact-communication',
      emoji: '📞',
      kind: 'Acciones de comunicación',
      title: 'Llamar, enviar correo o WhatsApp',
      purpose: 'Inicia la comunicación desde los datos guardados en la ficha.',
      behavior: 'Abre la aplicación correspondiente utilizando el teléfono o correo registrado.',
      whenToUse: 'Úsalas después de confirmar que el dato pertenece al contacto correcto y está vigente.',
      result: 'Reduce recaptura y mantiene el seguimiento ligado al directorio oficial.',
      focus: 'la comunicación desde datos confiables',
      examples: {
        emily: 'Emily contacta al responsable corporativo desde su ficha y confirma el siguiente paso con la gerente asignada.',
        juanito: 'Juanito utiliza el número registrado y evita llamar a versiones antiguas guardadas en hojas distintas.',
        camila: 'Camila abre WhatsApp desde el contacto correcto y el equipo sabe qué cliente y empresa están atendiendo.',
      },
    }),
    createControl({
      id: 'contact-edit-delete',
      emoji: '✏️',
      kind: 'Acciones del registro',
      title: 'Editar y eliminar contacto',
      purpose: 'Actualiza información vigente o retira fichas que no deben conservarse.',
      behavior: 'Editar abre el formulario existente; eliminar muestra relaciones y solicita confirmación antes de continuar.',
      whenToUse: 'Úsalos cuando cambien datos o después de revisar oportunidades y cotizaciones relacionadas.',
      result: 'Mantiene un directorio limpio sin romper accidentalmente la historia comercial.',
      focus: 'el mantenimiento de cada contacto',
      examples: {
        emily: 'Emily actualiza al nuevo decisor sin crear otra empresa y conserva el historial de la relación.',
        juanito: 'Juanito revisa cuántas oportunidades dependen del contacto antes de eliminarlo. Protege la integridad de sus datos.',
        camila: 'Camila corrige el teléfono en la ficha compartida y evita que cada vendedor conserve una versión diferente.',
      },
    }),
  ],
  quotes: [
    createControl({
      id: 'review-expirations',
      emoji: '⏰',
      kind: 'Botón de acción',
      title: 'Revisar vencimientos',
      purpose: 'Identifica cotizaciones vencidas o próximas a vencer que requieren seguimiento.',
      behavior: 'Aplica el enfoque correspondiente para mostrar propuestas con vigencia crítica.',
      whenToUse: 'Úsalo al iniciar la jornada comercial o antes de la reunión de pipeline.',
      result: 'Evita perder propuestas viables por falta de contacto oportuno.',
      focus: 'el seguimiento de vigencias',
      examples: {
        emily: 'Emily revisa propuestas por vencer y asigna el seguimiento antes de que el cliente corporativo cierre su decisión.',
        juanito: 'Juanito calcula el valor de cotizaciones en riesgo y prioriza las que combinan mayor monto y fecha más cercana.',
        camila: 'Camila detecta una cotización de piezas por vencer y confirma disponibilidad antes de volver a llamar al taller.',
      },
    }),
    createControl({
      id: 'new-quote',
      emoji: '➕',
      kind: 'Botón de acción',
      title: 'Nueva cotización',
      purpose: 'Construye una propuesta con cliente, partidas, precios, impuestos, margen, condiciones y vigencia.',
      behavior: 'Abre el constructor por secciones y valida la preparación antes de guardar o enviar.',
      whenToUse: 'Úsalo después de comprender la necesidad y confirmar qué productos o servicios se ofrecerán.',
      result: 'Reduce propuestas incompletas y protege el margen antes de comprometerse con el cliente.',
      focus: 'la preparación completa de cada propuesta',
      examples: {
        emily: 'Emily cotiza un servicio de café con alcance, vigencia y margen definidos. Otra gerente puede entender y ejecutar la propuesta.',
        juanito: 'Juanito captura costo, precio e impuestos antes de enviar. La cotización no aparenta una utilidad que realmente no existe.',
        camila: 'Camila agrega cada pieza, disponibilidad y condición para que el cliente sepa exactamente qué recibirá.',
      },
    }),
    createControl({
      id: 'quote-filters',
      emoji: '🔎',
      kind: 'Filtros y orden',
      title: 'Buscar, filtrar y ordenar cotizaciones',
      purpose: 'Segmenta propuestas por cliente, estado, vendedor, oportunidad, monto o vigencia.',
      behavior: 'Actualiza tabla e indicadores con el conjunto seleccionado y permite ordenar desde encabezados.',
      whenToUse: 'Úsalos para responder una pregunta comercial concreta antes de actuar.',
      result: 'Hace visibles cuellos de botella, propuestas sin seguimiento y concentración de valor.',
      focus: 'la lectura enfocada de cotizaciones',
      examples: {
        emily: 'Emily filtra propuestas enviadas por gerente y revisa cuáles no tienen respuesta registrada.',
        juanito: 'Juanito ordena por monto y margen para distinguir propuestas grandes de propuestas realmente rentables.',
        camila: 'Camila filtra cotizaciones en borrador y termina las que quedaron pendientes por confirmar piezas.',
      },
    }),
    createControl({
      id: 'quote-readiness',
      emoji: '🛡️',
      kind: 'Señales de preparación',
      title: 'Revisar margen, vigencia y datos faltantes',
      purpose: 'Advierte si una propuesta tiene riesgos antes de enviarse o convertirse en venta.',
      behavior: 'Calcula señales con cliente, partidas, costos, impuestos, margen y fechas capturadas.',
      whenToUse: 'Úsalo antes de enviar, aprobar descuentos o registrar la aceptación.',
      result: 'Evita compromisos sin costo conocido, margen suficiente o información ejecutable.',
      focus: 'la calidad financiera y operativa de la oferta',
      examples: {
        emily: 'Emily detiene una propuesta con margen bajo y revisa el alcance antes de dañar el estándar de rentabilidad de sus cafeterías.',
        juanito: 'Juanito no envía hasta que costos, impuestos y vigencia estén completos. Los números de la propuesta pueden explicarse.',
        camila: 'Camila detecta que una pieza no tiene costo actualizado y lo corrige antes de prometer un precio al taller.',
      },
    }),
    createControl({
      id: 'quote-record-actions',
      emoji: '🛠️',
      kind: 'Acciones de cotización',
      title: 'Ver, editar, imprimir y actualizar estado',
      purpose: 'Administra la propuesta durante su negociación y conserva una versión comprensible.',
      behavior: 'Las acciones abren vista previa o edición, generan el documento y actualizan el estado según el avance.',
      whenToUse: 'Úsalas cuando exista una corrección, una respuesta del cliente o necesidad de compartir el documento.',
      result: 'Mantiene alineados documento, estado comercial y condiciones acordadas.',
      focus: 'el expediente de la cotización',
      examples: {
        emily: 'Emily revisa la vista previa antes de enviarla y confirma que otra sucursal pueda cumplir lo ofrecido.',
        juanito: 'Juanito actualiza el estado después de cada respuesta. Sus reportes distinguen borradores, ofertas vivas y propuestas cerradas.',
        camila: 'Camila imprime una propuesta clara para el cliente y conserva en el sistema la misma versión que entregó.',
      },
    }),
    createControl({
      id: 'quote-conversion',
      emoji: '🏁',
      kind: 'Acción de conversión',
      title: 'Convertir cotización aceptada',
      purpose: 'Transforma una propuesta ganada en venta sin volver a capturar cliente, productos y totales.',
      behavior: 'Valida el estado y transfiere la información al flujo de ejecución comercial.',
      whenToUse: 'Úsalo únicamente después de contar con aceptación clara del cliente.',
      result: 'Conecta negociación y ejecución sin duplicar o perder información.',
      focus: 'la conversión de propuesta a venta',
      examples: {
        emily: 'Emily convierte la propuesta corporativa aceptada y la sucursal responsable recibe el mismo alcance que fue negociado.',
        juanito: 'Juanito conserva monto, moneda y partidas al convertir. La venta coincide con la cotización que utilizó para calcular el margen.',
        camila: 'Camila convierte el pedido aceptado y almacén recibe la lista exacta de piezas, sin transcribir mensajes.',
      },
    }),
  ],
  sales: [
    createControl({
      id: 'sales-columns',
      emoji: '🧩',
      kind: 'Botón de configuración',
      title: 'Columnas',
      purpose: 'Define qué información de cierre y ejecución aparece en la tabla de ventas.',
      behavior: 'Abre el configurador para mostrar, ocultar y ordenar columnas sin alterar los registros.',
      whenToUse: 'Úsalo para revisar validación financiera, inventario, entrega, comisión o responsable.',
      result: 'Hace visible el tramo operativo que necesita atención después del cierre.',
      focus: 'la lectura del ciclo de venta',
      examples: {
        emily: 'Emily muestra entrega, sucursal y responsable para saber si la experiencia prometida ya fue ejecutada.',
        juanito: 'Juanito deja visibles monto, estado financiero e inventario. Cada venta puede reconciliarse con sus controles.',
        camila: 'Camila organiza cliente, piezas, almacén y entrega. Mostrador entiende qué sigue sin preguntarle personalmente.',
      },
    }),
    createControl({
      id: 'commission-rules',
      emoji: '📐',
      kind: 'Botón de configuración',
      title: 'Reglas de comisión',
      purpose: 'Define cómo se calculan incentivos comerciales según condiciones conocidas.',
      behavior: 'Abre la configuración de reglas, productos, vendedores, porcentajes y vigencia.',
      whenToUse: 'Úsalo antes de calcular comisiones o cuando cambie la política comercial.',
      result: 'Evita acuerdos distintos por persona y pagos difíciles de explicar.',
      focus: 'las reglas transparentes de comisión',
      examples: {
        emily: 'Emily define una regla común para servicios corporativos. Sus gerentes conocen qué conducta y margen generan comisión.',
        juanito: 'Juanito documenta porcentajes y condiciones antes del cierre. El cálculo puede repetirse y conciliarse sin discusiones.',
        camila: 'Camila reemplaza promesas verbales por reglas visibles para familiares y vendedores. El reconocimiento se vuelve más justo.',
      },
    }),
    createControl({
      id: 'create-sale',
      emoji: '➕',
      kind: 'Botón de acción',
      title: 'Crear venta',
      purpose: 'Registra un cierre ganado con cliente, productos, vendedor, pago y contexto de ejecución.',
      behavior: 'Abre el formulario de venta y permite partir de información comercial existente.',
      whenToUse: 'Úsalo cuando exista aceptación y sea necesario iniciar validaciones posteriores.',
      result: 'Separa el cierre real de las oportunidades todavía abiertas.',
      focus: 'el registro completo del cierre',
      examples: {
        emily: 'Emily registra el contrato de servicio aceptado y asigna la cafetería que ejecutará la entrega.',
        juanito: 'Juanito captura monto, evidencia y vendedor. La venta entra a sus números únicamente cuando puede rastrearse.',
        camila: 'Camila registra el pedido confirmado y conecta al cliente con las piezas que almacén debe preparar.',
      },
    }),
    createControl({
      id: 'sales-commission-view',
      emoji: '🔄',
      kind: 'Selector de vista',
      title: 'Ventas y comisiones',
      purpose: 'Alterna entre la ejecución de cierres y el cálculo de incentivos derivados.',
      behavior: 'Cambia la vista conservando una sola fuente de ventas y sus reglas relacionadas.',
      whenToUse: 'Usa Ventas para operación y Comisiones para revisión de pagos e incentivos.',
      result: 'Evita administrar cierres y comisiones en listas desconectadas.',
      focus: 'la relación entre resultado e incentivo',
      examples: {
        emily: 'Emily revisa primero que el servicio esté ejecutado y después analiza la comisión correspondiente.',
        juanito: 'Juanito compara el total vendido con el total comisionable. Detecta diferencias sin unir manualmente dos archivos.',
        camila: 'Camila muestra a cada vendedor cómo su comisión proviene de ventas registradas y condiciones visibles.',
      },
    }),
    createControl({
      id: 'sales-filters',
      emoji: '🔎',
      kind: 'Filtros comerciales',
      title: 'Buscar y filtrar ventas',
      purpose: 'Segmenta cierres por cliente, vendedor, unidad, negocio, estado o periodo.',
      behavior: 'Actualiza tabla e indicadores para mostrar únicamente el contexto seleccionado.',
      whenToUse: 'Úsalo antes de revisar pendientes, desempeño o validaciones específicas.',
      result: 'Permite separar problemas comerciales, financieros y de ejecución.',
      focus: 'la segmentación de ventas',
      examples: {
        emily: 'Emily filtra una cafetería y revisa entregas pendientes antes de comparar resultados entre sucursales.',
        juanito: 'Juanito filtra ventas pendientes de finanzas y reconcilia únicamente ese grupo con la evidencia recibida.',
        camila: 'Camila filtra pedidos pendientes de inventario para que almacén atienda primero compromisos ya vendidos.',
      },
    }),
    createControl({
      id: 'sales-lifecycle-actions',
      emoji: '🚦',
      kind: 'Acciones de ejecución',
      title: 'Enviar a finanzas, crédito o inventario',
      purpose: 'Traslada la venta al responsable de validar pago, cartera o movimiento de mercancía.',
      behavior: 'Actualiza el estado y prepara la información necesaria para el siguiente módulo sin ejecutar tareas ajenas.',
      whenToUse: 'Úsalas cuando la venta tenga la evidencia y datos requeridos por la siguiente área.',
      result: 'Evita que el cierre comercial se confunda con pago validado, crédito aprobado o stock entregado.',
      focus: 'el traspaso entre responsables',
      examples: {
        emily: 'Emily envía la venta a finanzas y luego a la sucursal responsable. Cada equipo recibe el contexto cuando le corresponde actuar.',
        juanito: 'Juanito separa venta, cobro y salida de inventario. Sus números pueden explicar en qué etapa se encuentra cada monto.',
        camila: 'Camila manda el pedido a inventario y deja de pedir por teléfono que alguien aparte las piezas.',
      },
    }),
    createControl({
      id: 'sales-record-actions',
      emoji: '🛠️',
      kind: 'Acciones del registro',
      title: 'Ver detalle, resumen, comisión y cancelar',
      purpose: 'Consulta la historia del cierre, administra su incentivo o detiene una venta incorrecta.',
      behavior: 'Abre las vistas y formularios correspondientes; cancelar solicita confirmación antes de cambiar el estado.',
      whenToUse: 'Úsalas ante una revisión, corrección, conciliación o cancelación confirmada.',
      result: 'Conserva trazabilidad sobre decisiones posteriores al cierre.',
      focus: 'la administración responsable de cada venta',
      examples: {
        emily: 'Emily consulta el resumen antes de hablar con un cliente y cancela únicamente después de coordinar a las áreas involucradas.',
        juanito: 'Juanito revisa detalle y comisión antes de corregir. No borra una diferencia sin conservar la explicación del cambio.',
        camila: 'Camila consulta la venta antes de resolver una devolución. El equipo trabaja con el pedido registrado y no con recuerdos distintos.',
      },
    }),
  ],
  contracts: [
    createControl({
      id: 'create-contract',
      emoji: '➕',
      kind: 'Botón de acción',
      title: 'Crear contrato',
      purpose: 'Formaliza alcance, fechas, responsables, valor y compromisos de una relación comercial.',
      behavior: 'Abre el formulario de contrato y permite conectarlo con cliente, cotización o venta.',
      whenToUse: 'Úsalo cuando el acuerdo requiera firma, renovación o condiciones que deben conservarse.',
      result: 'Convierte promesas comerciales en obligaciones operativas consultables.',
      focus: 'la formalización de compromisos',
      examples: {
        emily: 'Emily formaliza un servicio corporativo para que cada cafetería conozca frecuencia, nivel de servicio y vigencia.',
        juanito: 'Juanito conecta monto, fechas y condiciones con la venta. El ingreso esperado tiene un acuerdo que puede revisarse.',
        camila: 'Camila documenta el suministro recurrente a un taller y evita que precios y entregas dependan de acuerdos recordados de forma diferente.',
      },
    }),
    createControl({
      id: 'template-library',
      emoji: '📚',
      kind: 'Botón de configuración',
      title: 'Biblioteca de plantillas',
      purpose: 'Reutiliza estructuras contractuales aprobadas para acuerdos frecuentes.',
      behavior: 'Abre las plantillas disponibles para consultar, seleccionar o administrar formatos.',
      whenToUse: 'Úsalo antes de crear un contrato repetitivo o estandarizar una nueva relación.',
      result: 'Reduce omisiones y evita redactar condiciones distintas para casos equivalentes.',
      focus: 'las plantillas contractuales',
      examples: {
        emily: 'Emily usa la misma base para servicios corporativos y ajusta solo los datos que realmente cambian.',
        juanito: 'Juanito compara cada nuevo contrato contra una plantilla aprobada. Las variables comerciales quedan separadas de las cláusulas estándar.',
        camila: 'Camila utiliza una plantilla para acuerdos recurrentes con talleres. La relación cercana deja de impedir que existan condiciones claras.',
      },
    }),
    createControl({
      id: 'contract-filters-metrics',
      emoji: '🔎',
      kind: 'Herramientas de seguimiento',
      title: 'Revisar estados, vencimientos y firmas',
      purpose: 'Muestra qué contratos están activos, pendientes, próximos a vencer o en renovación.',
      behavior: 'Los filtros y métricas segmentan el conjunto sin modificar documentos.',
      whenToUse: 'Úsalos en la revisión comercial periódica y antes de preparar renovaciones.',
      result: 'Evita ingresos y relaciones en riesgo por fechas que nadie estaba vigilando.',
      focus: 'el calendario contractual',
      examples: {
        emily: 'Emily revisa contratos por vencer antes de planear capacidad en sus cafeterías y contacta a los clientes con anticipación.',
        juanito: 'Juanito suma el valor de contratos pendientes de firma y lo separa de ingresos ya asegurados.',
        camila: 'Camila identifica acuerdos que deben renovarse con talleres antes de continuar entregando bajo condiciones antiguas.',
      },
    }),
    createControl({
      id: 'contract-actions',
      emoji: '✍️',
      kind: 'Acciones del contrato',
      title: 'Editar, enviar, firmar y renovar',
      purpose: 'Administra el documento durante su aprobación, firma, vigencia y continuidad.',
      behavior: 'Cada acción actualiza el estado y conserva la trazabilidad del paso correspondiente.',
      whenToUse: 'Úsalas conforme avance el acuerdo y verifica responsable y versión antes de enviar.',
      result: 'Mantiene alineados documento, estado y siguiente acción contractual.',
      focus: 'el ciclo de vida del contrato',
      examples: {
        emily: 'Emily confirma la versión antes de enviarla y prepara la renovación con tiempo suficiente para sostener el servicio.',
        juanito: 'Juanito registra cada cambio de estado y distingue contratos enviados de contratos realmente firmados.',
        camila: 'Camila deja evidencia de quién aceptó y cuándo. La relación comercial no depende de una conversación perdida.',
      },
    }),
  ],
  kpis: [
    createControl({
      id: 'print-sales-kpis',
      emoji: '🖨️',
      kind: 'Botón de acción',
      title: 'Imprimir reporte',
      purpose: 'Genera una lectura compartible de los indicadores comerciales visibles.',
      behavior: 'Abre el flujo de impresión con los datos y contexto actualmente disponibles.',
      whenToUse: 'Úsalo para reuniones de revisión o para conservar una lectura autorizada del periodo.',
      result: 'Ayuda a discutir decisiones con una misma versión de la información.',
      focus: 'la lectura compartida de indicadores',
      examples: {
        emily: 'Emily lleva el reporte a su reunión regional y compara conversión, margen y seguimiento con los gerentes.',
        juanito: 'Juanito imprime el mismo corte que utilizó para tomar decisiones y evita comparar capturas obtenidas con filtros diferentes.',
        camila: 'Camila revisa el reporte con su familia y convierte resultados comerciales en responsables y acciones concretas.',
      },
    }),
    createControl({
      id: 'sales-kpi-filters',
      emoji: '🔎',
      kind: 'Filtros analíticos',
      title: 'Filtrar por unidad, negocio, vendedor y búsqueda',
      purpose: 'Define el contexto exacto que alimenta los indicadores y tablas comerciales.',
      behavior: 'Recalcula la lectura usando únicamente los registros que cumplen los filtros seleccionados.',
      whenToUse: 'Úsalo antes de comparar equipos, ubicaciones, responsables o segmentos.',
      result: 'Evita conclusiones construidas con operaciones que no son comparables.',
      focus: 'el contexto de cada indicador',
      examples: {
        emily: 'Emily compara cafeterías equivalentes y detecta dónde el seguimiento comercial necesita un estándar más fuerte.',
        juanito: 'Juanito confirma unidad, tienda y vendedor antes de interpretar una variación. El denominador correcto importa tanto como el resultado.',
        camila: 'Camila filtra el negocio principal y revisa al vendedor responsable sin mezclar pedidos de mostrador con cuentas mayoristas.',
      },
    }),
    createControl({
      id: 'sales-kpi-context',
      emoji: '🌐',
      kind: 'Contexto de datos',
      title: 'Moneda, tipo de cambio y registros incluidos',
      purpose: 'Explica con qué moneda, fecha de conversión y volumen de registros se calculó la lectura.',
      behavior: 'Muestra el contexto financiero y el desglose nativo utilizado para los totales preferidos.',
      whenToUse: 'Revísalo antes de comparar periodos o ventas registradas en monedas distintas.',
      result: 'Evita interpretar diferencias de conversión como cambios reales de desempeño.',
      focus: 'la base de cálculo de los indicadores',
      examples: {
        emily: 'Emily confirma la fecha del tipo de cambio antes de comparar una cuenta corporativa con resultados locales.',
        juanito: 'Juanito revisa moneda nativa, conversión y número de registros. Puede reconstruir por qué un total cambió.',
        camila: 'Camila identifica qué pedidos entraron al corte antes de explicar una variación al equipo.',
      },
    }),
    createControl({
      id: 'sales-kpi-cards',
      emoji: '📊',
      kind: 'Indicadores comerciales',
      title: 'Leer conversión, pipeline, margen y ejecución',
      purpose: 'Resume el desempeño desde adquisición hasta cierre y preparación operativa.',
      behavior: 'Calcula tarjetas y señales con contactos, oportunidades, cotizaciones, ventas y productos.',
      whenToUse: 'Úsalos para detectar dónde se está perdiendo valor, velocidad o rentabilidad.',
      result: 'Conecta actividad comercial con decisiones y no solo con volumen de ventas.',
      focus: 'la relación entre los indicadores',
      examples: {
        emily: 'Emily observa conversión junto con margen y descubre que una sucursal vende más, pero con descuentos que limitan su crecimiento.',
        juanito: 'Juanito relaciona pipeline, cierres y preparación de inventario. Un buen número comercial no oculta problemas de ejecución.',
        camila: 'Camila identifica que muchas cotizaciones no avanzan por disponibilidad de piezas y coordina una mejora con almacén.',
      },
    }),
    createControl({
      id: 'sales-kpi-rankings',
      emoji: '🏆',
      kind: 'Tablas de análisis',
      title: 'Ranking y desempeño de oportunidades',
      purpose: 'Explica qué responsables y oportunidades están detrás de los resultados generales.',
      behavior: 'Ordena vendedores y registros con las medidas calculadas para facilitar una revisión detallada.',
      whenToUse: 'Úsalo después de detectar una señal general y antes de asignar acciones o apoyo.',
      result: 'Evita premiar o corregir personas sin comprender el contexto que produjo el indicador.',
      focus: 'la explicación detrás de los resultados',
      examples: {
        emily: 'Emily usa el ranking para identificar prácticas de una gerente que pueden enseñarse al resto de las cafeterías.',
        juanito: 'Juanito baja del porcentaje general a las oportunidades concretas y encuentra dónde se acumuló el retraso.',
        camila: 'Camila revisa casos individuales antes de hablar con un vendedor. La conversación se centra en hechos y apoyo, no en suposiciones.',
      },
    }),
  ],
};
