import type {
  PayrollBreakdownConfig,
  PayrollColumnDefinition,
  PayrollDetailedColumnKey,
  PayrollEditTableColumnKey,
  PayrollEmployerSummaryConfig,
  PayrollJurisdiction,
} from '../types/payrollJurisdiction';

const mexicoSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const canadaSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'province', label: 'Province' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const usaSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'province', label: 'State' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const brazilSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const colombiaSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'transportAllowance', label: 'Transport Allowance' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const mexicoDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'rfc', label: 'RFC' },
  { key: 'curp', label: 'CURP' },
  { key: 'nss', label: 'NSS' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'contributionType', label: 'Contribution Type' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'integratedDailyWage', label: 'Integrated Daily Salary (SDI)' },
  { key: 'baseContributionSalary', label: 'Contribution Base Salary (SBC)' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'bonusesCommissions', label: 'Bonuses / Commissions' },
  { key: 'vacationPremium', label: 'Vacation Premium' },
  { key: 'proportionalChristmasBonus', label: 'Proportional Christmas Bonus' },
  { key: 'totalEarnings', label: 'Total Earnings' },
  { key: 'isrBeforeSubsidy', label: 'ISR Before Subsidy' },
  { key: 'employmentSubsidy', label: 'Employment Subsidy' },
  { key: 'finalIsr', label: 'Final ISR' },
  { key: 'employeeImss', label: 'HR User IMSS' },
  { key: 'infonavitType', label: 'INFONAVIT Type' },
  { key: 'infonavitDiscount', label: 'INFONAVIT Discount' },
  { key: 'employerImss', label: 'Employer IMSS' },
  { key: 'employerInfonavit', label: 'Employer INFONAVIT' },
  { key: 'sar', label: 'SAR 2%' },
  { key: 'payrollStateTax', label: 'Payroll Tax / State Tax' },
  { key: 'occupationalRisk', label: 'Occupational Risk' },
  { key: 'childcareImss', label: 'Childcare IMSS' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'loans', label: 'Loans' },
  { key: 'otherDiscounts', label: 'Other Discounts' },
  { key: 'netAdjustment', label: 'Net Adjustment' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'breakdown', label: 'Breakdown' },
];

const canadaStandardDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'sin', label: 'SIN' },
  { key: 'province', label: 'Province' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'hourlyRate', label: 'Hourly Rate' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'vacationPay', label: 'Vacation Pay' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'federalTax', label: 'Federal Tax' },
  { key: 'provincialTax', label: 'Provincial Tax' },
  { key: 'employeeCpp', label: 'HR User CPP' },
  { key: 'employeeCpp2', label: 'HR User CPP2' },
  { key: 'employeeEi', label: 'HR User EI' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerCpp', label: 'Employer CPP' },
  { key: 'employerCpp2', label: 'Employer CPP2' },
  { key: 'employerEi', label: 'Employer EI' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

const canadaQuebecDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'sin', label: 'SIN' },
  { key: 'province', label: 'Province' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'hourlyRate', label: 'Hourly Rate' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'vacationPay', label: 'Vacation Pay' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'federalTax', label: 'Federal Tax' },
  { key: 'quebecProvincialTax', label: 'Quebec Provincial Tax' },
  { key: 'employeeQpp', label: 'HR User QPP' },
  { key: 'employeeQpp2', label: 'HR User QPP2' },
  { key: 'employeeQpip', label: 'HR User QPIP' },
  { key: 'employeeEi', label: 'HR User EI' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerQpp', label: 'Employer QPP' },
  { key: 'employerQpp2', label: 'Employer QPP2' },
  { key: 'employerQpip', label: 'Employer QPIP' },
  { key: 'employerEi', label: 'Employer EI' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

const brazilDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'cpf', label: 'CPF' },
  { key: 'pisPasep', label: 'PIS/PASEP' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'monthlySalary', label: 'Monthly Salary' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'nightShiftPremium', label: 'Night Shift Premium' },
  { key: 'hazardUnhealthyPremium', label: 'Hazard / Unhealthy Premium' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'vacationPay', label: 'Vacation Pay' },
  { key: 'vacationBonusOneThird', label: 'Vacation Bonus 1/3' },
  { key: 'thirteenthSalaryProvision', label: '13th Salary Provision' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'employeeInss', label: 'HR User INSS' },
  { key: 'irrf', label: 'IRRF' },
  { key: 'transportationVoucher', label: 'Transportation Voucher' },
  { key: 'mealBenefitsDeduction', label: 'Meal / Benefits Deduction' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerInss', label: 'Employer INSS' },
  { key: 'fgts', label: 'FGTS' },
  { key: 'ratWorkAccident', label: 'RAT / Work Accident' },
  { key: 'thirdPartyContributions', label: 'Third-party Contributions' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

const colombiaDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'idNumber', label: 'ID Number' },
  { key: 'contractType', label: 'Contract Type' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'monthlySalary', label: 'Monthly Salary' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'nightSurcharge', label: 'Night Surcharge' },
  { key: 'sundayHolidaySurcharge', label: 'Sunday / Holiday Surcharge' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'transportAllowance', label: 'Transport Allowance' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'employeeHealth', label: 'HR User Health' },
  { key: 'employeePension', label: 'HR User Pension' },
  { key: 'withholdingTax', label: 'Withholding Tax' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerHealth', label: 'Employer Health' },
  { key: 'employerPension', label: 'Employer Pension' },
  { key: 'arl', label: 'ARL' },
  { key: 'severance', label: 'Severance' },
  { key: 'severanceInterest', label: 'Severance Interest' },
  { key: 'serviceBonus', label: 'Service Bonus' },
  { key: 'vacationProvision', label: 'Vacation Provision' },
  { key: 'familyCompensationFund', label: 'Family Compensation Fund' },
  { key: 'icbf', label: 'ICBF' },
  { key: 'sena', label: 'SENA' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

const usaDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'sin', label: 'SSN / Tax ID' },
  { key: 'province', label: 'State' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'hourlyRate', label: 'Hourly Rate' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'federalTax', label: 'Federal Withholding' },
  { key: 'provincialTax', label: 'State Withholding' },
  { key: 'employeeCpp', label: 'HR User Social Security' },
  { key: 'employeeEi', label: 'HR User Medicare' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerCpp', label: 'Employer Social Security' },
  { key: 'employerEi', label: 'Employer Medicare' },
  { key: 'payrollStateTax', label: 'FUTA / SUTA' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

export const payrollSimplifiedColumnsByJurisdiction: Record<
  PayrollJurisdiction,
  Array<PayrollColumnDefinition<PayrollEditTableColumnKey>>
> = {
  MX: mexicoSimplifiedColumns,
  CO: colombiaSimplifiedColumns,
  US: usaSimplifiedColumns,
  CA_STANDARD: canadaSimplifiedColumns,
  CA_QUEBEC: canadaSimplifiedColumns,
  BR: brazilSimplifiedColumns,
};

export const payrollDetailedColumnsByJurisdiction: Record<
  PayrollJurisdiction,
  Array<PayrollColumnDefinition<PayrollDetailedColumnKey>>
> = {
  MX: mexicoDetailedColumns,
  CO: colombiaDetailedColumns,
  US: usaDetailedColumns,
  CA_STANDARD: canadaStandardDetailedColumns,
  CA_QUEBEC: canadaQuebecDetailedColumns,
  BR: brazilDetailedColumns,
};

export const payrollEmployerSummaryConfigByJurisdiction: Record<PayrollJurisdiction, PayrollEmployerSummaryConfig> = {
  MX: {
    helperText: 'Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerImss', label: 'Employer IMSS' },
      { key: 'employerInfonavit', label: 'Employer INFONAVIT' },
      { key: 'sar', label: 'SAR 2%' },
      { key: 'payrollStateTax', label: 'Payroll Tax / State Tax' },
      { key: 'occupationalRisk', label: 'Occupational Risk' },
      { key: 'childcareImss', label: 'Childcare IMSS' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  CO: {
    helperText: 'Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerHealth', label: 'Employer Health' },
      { key: 'employerPension', label: 'Employer Pension' },
      { key: 'arl', label: 'ARL' },
      { key: 'severance', label: 'Severance' },
      { key: 'severanceInterest', label: 'Severance Interest' },
      { key: 'serviceBonus', label: 'Service Bonus' },
      { key: 'vacationProvision', label: 'Vacation Provision' },
      { key: 'familyCompensationFund', label: 'Family Compensation Fund' },
      { key: 'icbf', label: 'ICBF' },
      { key: 'sena', label: 'SENA' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  US: {
    helperText: 'Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerCpp', label: 'Employer Social Security' },
      { key: 'employerEi', label: 'Employer Medicare' },
      { key: 'payrollStateTax', label: 'FUTA / SUTA' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  CA_STANDARD: {
    helperText: 'Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerCpp', label: 'Employer CPP' },
      { key: 'employerCpp2', label: 'Employer CPP2' },
      { key: 'employerEi', label: 'Employer EI' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  CA_QUEBEC: {
    helperText: 'Quebec payroll uses QPP, QPP2, QPIP and Quebec provincial tax. Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerQpp', label: 'Employer QPP' },
      { key: 'employerQpp2', label: 'Employer QPP2' },
      { key: 'employerQpip', label: 'Employer QPIP' },
      { key: 'employerEi', label: 'Employer EI' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  BR: {
    helperText: 'Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerInss', label: 'Employer INSS' },
      { key: 'fgts', label: 'FGTS' },
      { key: 'ratWorkAccident', label: 'RAT / Work Accident' },
      { key: 'thirdPartyContributions', label: 'Third-party Contributions' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
};

export const payrollBreakdownConfigByJurisdiction: Record<PayrollJurisdiction, PayrollBreakdownConfig> = {
  MX: {
    taxSectionTitle: 'ISR Calculation',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations are company costs. They do not reduce the HR user net pay.',
    contributionBreakdownTitle: 'IMSS Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  CO: {
    taxSectionTitle: '',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'Social Security / Parafiscal Breakdown',
    benefitsSectionTitle: 'Benefits / Provisions',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  US: {
    taxSectionTitle: 'Federal / State Withholding',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'Social Security / Medicare Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  CA_STANDARD: {
    taxSectionTitle: 'Federal / Provincial Tax',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'CPP / EI Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  CA_QUEBEC: {
    taxSectionTitle: 'Federal / Quebec Tax',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Quebec payroll uses QPP, QPP2, QPIP and Quebec provincial tax. Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'QPP / QPIP / EI Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  BR: {
    taxSectionTitle: '',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'INSS / IRRF Breakdown',
    benefitsSectionTitle: 'Benefits / Vouchers',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
};

export const payrollStatutoryColumnKeysByJurisdiction: Record<PayrollJurisdiction, PayrollDetailedColumnKey[]> = {
  MX: [
    'isrBeforeSubsidy',
    'employmentSubsidy',
    'finalIsr',
    'employeeImss',
    'infonavitDiscount',
    'employerImss',
    'employerInfonavit',
    'sar',
    'payrollStateTax',
    'occupationalRisk',
    'childcareImss',
    'totalEmployerObligations',
  ],
  CO: [
    'employeeHealth',
    'employeePension',
    'withholdingTax',
    'employerHealth',
    'employerPension',
    'arl',
    'severance',
    'severanceInterest',
    'serviceBonus',
    'vacationProvision',
    'familyCompensationFund',
    'icbf',
    'sena',
    'totalEmployerObligations',
  ],
  US: [
    'federalTax',
    'provincialTax',
    'employeeCpp',
    'employeeEi',
    'employerCpp',
    'employerEi',
    'payrollStateTax',
    'employerBenefits',
    'totalEmployerObligations',
  ],
  CA_STANDARD: [
    'federalTax',
    'provincialTax',
    'employeeCpp',
    'employeeCpp2',
    'employeeEi',
    'employerCpp',
    'employerCpp2',
    'employerEi',
    'employerBenefits',
    'totalEmployerObligations',
  ],
  CA_QUEBEC: [
    'federalTax',
    'quebecProvincialTax',
    'employeeQpp',
    'employeeQpp2',
    'employeeQpip',
    'employeeEi',
    'employerQpp',
    'employerQpp2',
    'employerQpip',
    'employerEi',
    'employerBenefits',
    'totalEmployerObligations',
  ],
  BR: [
    'employeeInss',
    'irrf',
    'transportationVoucher',
    'mealBenefitsDeduction',
    'employerInss',
    'fgts',
    'ratWorkAccident',
    'thirdPartyContributions',
    'employerBenefits',
    'totalEmployerObligations',
  ],
};
