import type {
  PayrollBreakdownConfig,
  PayrollColumnDefinition,
  PayrollDetailedColumnKey,
  PayrollEditTableColumnKey,
  PayrollEmployerSummaryConfig,
  PayrollJurisdiction,
} from '../types/payrollJurisdiction';

const mexicoSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Nómina fiscal' },
  { key: 'employee', label: 'Colaborador' },
  { key: 'unit', label: 'Unidad' },
  { key: 'business', label: 'Negocio' },
  { key: 'daysWorked', label: 'Días trabajados' },
  { key: 'daysAbsent', label: 'Faltas' },
  { key: 'periodSalary', label: 'Sueldo del periodo' },
  { key: 'variablePay', label: 'Percepciones variables' },
  { key: 'grossPay', label: 'Total de percepciones' },
  { key: 'totalDeductions', label: 'Total de deducciones' },
  { key: 'netPay', label: 'Neto a pagar' },
  { key: 'status', label: 'Estado' },
  { key: 'breakdown', label: 'Desglose' },
];

const canadaSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'province', label: 'Province' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const usaSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Statutory Payroll' },
  { key: 'employee', label: 'HR User' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'province', label: 'State' },
  { key: 'daysWorked', label: 'Days Worked' },
  { key: 'daysAbsent', label: 'Absence Days' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'variablePay', label: 'Variable Pay' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Breakdown' },
];

const brazilSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Folha fiscal' },
  { key: 'employee', label: 'Colaborador' },
  { key: 'unit', label: 'Unidade' },
  { key: 'business', label: 'Negócio' },
  { key: 'employmentType', label: 'Tipo de vínculo' },
  { key: 'daysWorked', label: 'Dias trabalhados' },
  { key: 'daysAbsent', label: 'Faltas' },
  { key: 'periodSalary', label: 'Salário do período' },
  { key: 'variablePay', label: 'Remuneração variável' },
  { key: 'grossPay', label: 'Remuneração bruta' },
  { key: 'totalDeductions', label: 'Total de descontos' },
  { key: 'netPay', label: 'Salário líquido' },
  { key: 'status', label: 'Status' },
  { key: 'breakdown', label: 'Memória de cálculo' },
];

const colombiaSimplifiedColumns: Array<PayrollColumnDefinition<PayrollEditTableColumnKey>> = [
  { key: 'statutoryPayroll', label: 'Nómina electrónica' },
  { key: 'employee', label: 'Colaborador' },
  { key: 'unit', label: 'Unidad' },
  { key: 'business', label: 'Negocio' },
  { key: 'employmentType', label: 'Tipo de vinculación' },
  { key: 'daysWorked', label: 'Días trabajados' },
  { key: 'daysAbsent', label: 'Ausencias' },
  { key: 'periodSalary', label: 'Sueldo del periodo' },
  { key: 'transportAllowance', label: 'Auxilio de transporte' },
  { key: 'variablePay', label: 'Pagos variables' },
  { key: 'grossPay', label: 'Total devengado' },
  { key: 'totalDeductions', label: 'Total deducciones' },
  { key: 'netPay', label: 'Neto a pagar' },
  { key: 'status', label: 'Estado' },
  { key: 'breakdown', label: 'Desglose' },
];

const mexicoDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'Colaborador' },
  { key: 'rfc', label: 'RFC' },
  { key: 'curp', label: 'CURP' },
  { key: 'nss', label: 'NSS' },
  { key: 'unit', label: 'Unidad' },
  { key: 'business', label: 'Negocio' },
  { key: 'contributionType', label: 'Tipo de cotización' },
  { key: 'dailyWage', label: 'Salario diario' },
  { key: 'integratedDailyWage', label: 'Salario Diario Integrado (SDI)' },
  { key: 'baseContributionSalary', label: 'Salario Base de Cotización (SBC)' },
  { key: 'daysPaid', label: 'Días pagados' },
  { key: 'totalWorkedHours', label: 'Horas trabajadas' },
  { key: 'hoursPerDay', label: 'Horas por día' },
  { key: 'overtimeHours', label: 'Horas extra' },
  { key: 'periodSalary', label: 'Sueldo del periodo' },
  { key: 'overtimeAmount', label: 'Importe de horas extra' },
  { key: 'bonusesCommissions', label: 'Bonos / comisiones' },
  { key: 'vacationPremium', label: 'Prima vacacional' },
  { key: 'proportionalChristmasBonus', label: 'Aguinaldo proporcional' },
  { key: 'totalEarnings', label: 'Total de percepciones' },
  { key: 'isrBeforeSubsidy', label: 'ISR antes de subsidio' },
  { key: 'employmentSubsidy', label: 'Subsidio para el empleo' },
  { key: 'finalIsr', label: 'ISR retenido' },
  { key: 'employeeImss', label: 'Cuota obrera IMSS' },
  { key: 'infonavitType', label: 'Tipo de crédito INFONAVIT' },
  { key: 'infonavitDiscount', label: 'Descuento INFONAVIT' },
  { key: 'employerImss', label: 'Cuota patronal IMSS' },
  { key: 'employerInfonavit', label: 'Aportación patronal INFONAVIT' },
  { key: 'sar', label: 'SAR - Retiro 2%' },
  { key: 'payrollStateTax', label: 'Impuesto sobre nóminas (ISN)' },
  { key: 'occupationalRisk', label: 'Riesgo de trabajo' },
  { key: 'childcareImss', label: 'Guarderías y prestaciones sociales' },
  { key: 'totalEmployerObligations', label: 'Total de obligaciones patronales' },
  { key: 'loans', label: 'Préstamos' },
  { key: 'otherDiscounts', label: 'Otras deducciones' },
  { key: 'netAdjustment', label: 'Ajuste neto' },
  { key: 'totalDeductions', label: 'Total de deducciones' },
  { key: 'netPay', label: 'Neto a pagar' },
  { key: 'breakdown', label: 'Desglose' },
];

const canadaStandardDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'sin', label: 'SIN' },
  { key: 'province', label: 'Province' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'hourlyRate', label: 'Hourly Rate' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'vacationPay', label: 'Vacation Pay' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'federalTax', label: 'Federal Tax' },
  { key: 'provincialTax', label: 'Provincial Tax' },
  { key: 'employeeCpp', label: 'HR User CPP' },
  { key: 'employeeCpp2', label: 'HR User CPP2' },
  { key: 'employeeEi', label: 'HR User EI' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerCpp', label: 'Employer CPP' },
  { key: 'employerCpp2', label: 'Employer CPP2' },
  { key: 'employerEi', label: 'Employer EI' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

const canadaQuebecDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'sin', label: 'SIN' },
  { key: 'province', label: 'Province' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'hourlyRate', label: 'Hourly Rate' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'vacationPay', label: 'Vacation Pay' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'federalTax', label: 'Federal Tax' },
  { key: 'quebecProvincialTax', label: 'Quebec Provincial Tax' },
  { key: 'employeeQpp', label: 'HR User QPP' },
  { key: 'employeeQpp2', label: 'HR User QPP2' },
  { key: 'employeeQpip', label: 'HR User QPIP' },
  { key: 'employeeEi', label: 'HR User EI' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerQpp', label: 'Employer QPP' },
  { key: 'employerQpp2', label: 'Employer QPP2' },
  { key: 'employerQpip', label: 'Employer QPIP' },
  { key: 'employerEi', label: 'Employer EI' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

const brazilDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'Colaborador' },
  { key: 'cpf', label: 'CPF' },
  { key: 'pisPasep', label: 'PIS/PASEP' },
  { key: 'unit', label: 'Unidade' },
  { key: 'business', label: 'Negócio' },
  { key: 'employmentType', label: 'Tipo de vínculo' },
  { key: 'payType', label: 'Tipo de remuneração' },
  { key: 'monthlySalary', label: 'Salário mensal' },
  { key: 'dailyWage', label: 'Salário diário' },
  { key: 'daysPaid', label: 'Dias pagos' },
  { key: 'totalWorkedHours', label: 'Horas trabalhadas' },
  { key: 'overtimeHours', label: 'Horas extras' },
  { key: 'nightShiftPremium', label: 'Adicional noturno' },
  { key: 'hazardUnhealthyPremium', label: 'Insalubridade / periculosidade' },
  { key: 'periodSalary', label: 'Salário do período' },
  { key: 'overtimeAmount', label: 'Valor de horas extras' },
  { key: 'variablePayTotal', label: 'Remuneração variável' },
  { key: 'vacationPay', label: 'Férias' },
  { key: 'vacationBonusOneThird', label: '1/3 constitucional de férias' },
  { key: 'thirteenthSalaryProvision', label: 'Provisão 13º salário' },
  { key: 'taxableBenefits', label: 'Benefícios tributáveis' },
  { key: 'grossPay', label: 'Remuneração bruta' },
  { key: 'employeeInss', label: 'INSS segurado' },
  { key: 'irrf', label: 'IRRF' },
  { key: 'transportationVoucher', label: 'Vale-transporte' },
  { key: 'mealBenefitsDeduction', label: 'Desconto benefícios' },
  { key: 'otherDeductions', label: 'Outros descontos' },
  { key: 'totalDeductions', label: 'Total de descontos' },
  { key: 'netPay', label: 'Salário líquido' },
  { key: 'employerInss', label: 'INSS patronal' },
  { key: 'fgts', label: 'FGTS' },
  { key: 'ratWorkAccident', label: 'RAT/SAT ajustado por FAP' },
  { key: 'thirdPartyContributions', label: 'Terceiros / Sistema S' },
  { key: 'employerBenefits', label: 'Provisões trabalhistas' },
  { key: 'totalEmployerObligations', label: 'Total de encargos patronais' },
  { key: 'totalPayrollCost', label: 'Custo total da folha' },
  { key: 'breakdown', label: 'Memória de cálculo' },
];

const colombiaDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'Colaborador' },
  { key: 'idNumber', label: 'Documento' },
  { key: 'contractType', label: 'Tipo de contrato' },
  { key: 'unit', label: 'Unidad' },
  { key: 'business', label: 'Negocio' },
  { key: 'employmentType', label: 'Tipo de vinculación' },
  { key: 'payType', label: 'Tipo de pago' },
  { key: 'monthlySalary', label: 'Salario mensual' },
  { key: 'dailyWage', label: 'Salario diario' },
  { key: 'daysPaid', label: 'Días pagados' },
  { key: 'totalWorkedHours', label: 'Horas trabajadas' },
  { key: 'overtimeHours', label: 'Horas extra' },
  { key: 'nightSurcharge', label: 'Recargo nocturno' },
  { key: 'sundayHolidaySurcharge', label: 'Recargo dominical / festivo' },
  { key: 'periodSalary', label: 'Sueldo del periodo' },
  { key: 'overtimeAmount', label: 'Valor horas extra' },
  { key: 'transportAllowance', label: 'Auxilio de transporte' },
  { key: 'variablePayTotal', label: 'Pagos variables' },
  { key: 'retroactiveAdjustments', label: 'Retroactivos' },
  { key: 'payrollCorrections', label: 'Correcciones' },
  { key: 'terminationSettlement', label: 'Liquidación' },
  { key: 'terminationIndemnity', label: 'Indemnización' },
  { key: 'grossPay', label: 'Total devengado' },
  { key: 'employeeHealth', label: 'EPS trabajador' },
  { key: 'employeePension', label: 'AFP trabajador' },
  { key: 'withholdingTax', label: 'Retención en la fuente' },
  { key: 'otherDeductions', label: 'Otras deducciones' },
  { key: 'totalDeductions', label: 'Total deducciones' },
  { key: 'netPay', label: 'Neto a pagar' },
  { key: 'employerHealth', label: 'EPS empleador' },
  { key: 'employerPension', label: 'AFP empleador' },
  { key: 'arl', label: 'ARL' },
  { key: 'severance', label: 'Cesantías' },
  { key: 'severanceInterest', label: 'Intereses sobre cesantías' },
  { key: 'serviceBonus', label: 'Prima de servicios' },
  { key: 'vacationProvision', label: 'Provisión vacaciones' },
  { key: 'familyCompensationFund', label: 'Caja de compensación familiar' },
  { key: 'icbf', label: 'ICBF' },
  { key: 'sena', label: 'SENA' },
  { key: 'totalEmployerObligations', label: 'Total obligaciones patronales' },
  { key: 'totalPayrollCost', label: 'Costo total de nómina' },
  { key: 'breakdown', label: 'Desglose' },
];

const usaDetailedColumns: Array<PayrollColumnDefinition<PayrollDetailedColumnKey>> = [
  { key: 'employee', label: 'HR User' },
  { key: 'sin', label: 'SSN / Tax ID' },
  { key: 'province', label: 'State' },
  { key: 'unit', label: 'Unit' },
  { key: 'business', label: 'Business' },
  { key: 'employmentType', label: 'Employment Type' },
  { key: 'payType', label: 'Pay Type' },
  { key: 'hourlyRate', label: 'Hourly Rate' },
  { key: 'dailyWage', label: 'Daily Salary' },
  { key: 'daysPaid', label: 'Days Paid' },
  { key: 'totalWorkedHours', label: 'Total Worked Hours' },
  { key: 'hoursPerDay', label: 'Hours Per Day' },
  { key: 'overtimeHours', label: 'Overtime Hours' },
  { key: 'periodSalary', label: 'Period Salary' },
  { key: 'overtimeAmount', label: 'Overtime Amount' },
  { key: 'variablePayTotal', label: 'Variable Pay' },
  { key: 'taxableBenefits', label: 'Taxable Benefits' },
  { key: 'grossPay', label: 'Gross Pay' },
  { key: 'federalTax', label: 'Federal Withholding' },
  { key: 'provincialTax', label: 'State Withholding / Employee Programs' },
  { key: 'employeeCpp', label: 'HR User Social Security' },
  { key: 'employeeEi', label: 'HR User Medicare' },
  { key: 'otherDeductions', label: 'Other Deductions' },
  { key: 'totalDeductions', label: 'Total Deductions' },
  { key: 'netPay', label: 'Net Pay' },
  { key: 'employerCpp', label: 'Employer Social Security' },
  { key: 'employerEi', label: 'Employer Medicare' },
  { key: 'payrollStateTax', label: 'FUTA / SUTA / State Employer Programs' },
  { key: 'employerBenefits', label: 'Employer Benefits' },
  { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
  { key: 'totalPayrollCost', label: 'Total Payroll Cost' },
  { key: 'breakdown', label: 'Breakdown' },
];

export const payrollSimplifiedColumnsByJurisdiction: Record<
  PayrollJurisdiction,
  Array<PayrollColumnDefinition<PayrollEditTableColumnKey>>
> = {
  MX: mexicoSimplifiedColumns,
  CO: colombiaSimplifiedColumns,
  US: usaSimplifiedColumns,
  CA_STANDARD: canadaSimplifiedColumns,
  CA_QUEBEC: canadaSimplifiedColumns,
  BR: brazilSimplifiedColumns,
};

export const payrollDetailedColumnsByJurisdiction: Record<
  PayrollJurisdiction,
  Array<PayrollColumnDefinition<PayrollDetailedColumnKey>>
> = {
  MX: mexicoDetailedColumns,
  CO: colombiaDetailedColumns,
  US: usaDetailedColumns,
  CA_STANDARD: canadaStandardDetailedColumns,
  CA_QUEBEC: canadaQuebecDetailedColumns,
  BR: brazilDetailedColumns,
};

export const payrollEmployerSummaryConfigByJurisdiction: Record<PayrollJurisdiction, PayrollEmployerSummaryConfig> = {
  MX: {
    helperText: 'Las obligaciones patronales son costos del patrón y no disminuyen el neto del colaborador.',
    metrics: [
      { key: 'employerImss', label: 'Cuota patronal IMSS' },
      { key: 'employerInfonavit', label: 'Aportación patronal INFONAVIT' },
      { key: 'sar', label: 'SAR - Retiro 2%' },
      { key: 'payrollStateTax', label: 'Impuesto sobre nóminas (ISN)' },
      { key: 'occupationalRisk', label: 'Riesgo de trabajo' },
      { key: 'childcareImss', label: 'Guarderías y prestaciones sociales' },
      { key: 'totalEmployerObligations', label: 'Total de obligaciones patronales' },
      { key: 'totalPayrollCost', label: 'Costo total de nómina', accent: 'primary' },
    ],
  },
  CO: {
    helperText: 'Las obligaciones patronales incluyen seguridad social, parafiscales y provisiones laborales. No disminuyen el neto del colaborador.',
    metrics: [
      { key: 'employerHealth', label: 'EPS empleador' },
      { key: 'employerPension', label: 'AFP empleador' },
      { key: 'arl', label: 'ARL' },
      { key: 'severance', label: 'Cesantías' },
      { key: 'severanceInterest', label: 'Intereses sobre cesantías' },
      { key: 'serviceBonus', label: 'Prima de servicios' },
      { key: 'vacationProvision', label: 'Provisión vacaciones' },
      { key: 'familyCompensationFund', label: 'Caja de compensación familiar' },
      { key: 'icbf', label: 'ICBF' },
      { key: 'sena', label: 'SENA' },
      { key: 'totalEmployerObligations', label: 'Total obligaciones patronales' },
      { key: 'totalPayrollCost', label: 'Costo total de nómina', accent: 'primary' },
    ],
  },
  US: {
    helperText: 'Employer obligations include FICA match, FUTA, SUTA and configured state employer programs.',
    metrics: [
      { key: 'employerCpp', label: 'Employer Social Security' },
      { key: 'employerEi', label: 'Employer Medicare' },
      { key: 'payrollStateTax', label: 'FUTA / SUTA / State Employer Programs' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  CA_STANDARD: {
    helperText: 'Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerCpp', label: 'Employer CPP' },
      { key: 'employerCpp2', label: 'Employer CPP2' },
      { key: 'employerEi', label: 'Employer EI' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  CA_QUEBEC: {
    helperText: 'Quebec payroll uses QPP, QPP2, QPIP and Quebec provincial tax. Employer obligations include statutory payroll rows only.',
    metrics: [
      { key: 'employerQpp', label: 'Employer QPP' },
      { key: 'employerQpp2', label: 'Employer QPP2' },
      { key: 'employerQpip', label: 'Employer QPIP' },
      { key: 'employerEi', label: 'Employer EI' },
      { key: 'employerBenefits', label: 'Employer Benefits' },
      { key: 'totalEmployerObligations', label: 'Total Employer Obligations' },
      { key: 'totalPayrollCost', label: 'Total Payroll Cost', accent: 'primary' },
    ],
  },
  BR: {
    helperText: 'Encargos patronais incluem INSS patronal, FGTS, RAT/SAT ajustado por FAP e terceiros configurados.',
    metrics: [
      { key: 'employerInss', label: 'INSS patronal' },
      { key: 'fgts', label: 'FGTS' },
      { key: 'ratWorkAccident', label: 'RAT/SAT ajustado por FAP' },
      { key: 'thirdPartyContributions', label: 'Terceiros / Sistema S' },
      { key: 'employerBenefits', label: 'Provisões trabalhistas' },
      { key: 'totalEmployerObligations', label: 'Total de encargos patronais' },
      { key: 'totalPayrollCost', label: 'Custo total da folha', accent: 'primary' },
    ],
  },
};

export const payrollBreakdownConfigByJurisdiction: Record<PayrollJurisdiction, PayrollBreakdownConfig> = {
  MX: {
    taxSectionTitle: 'Cálculo de ISR',
    employeeDeductionsTitle: 'Deducciones del colaborador',
    employerObligationsTitle: 'Obligaciones patronales',
    employerObligationsDescription: 'Las obligaciones patronales son costos del patrón. No disminuyen el neto del colaborador.',
    contributionBreakdownTitle: 'Cuotas obrero-patronales',
    internalOnlyNotice: 'Este colaborador se administra solo para control interno de nómina. No se calculan impuestos ni contribuciones de seguridad social.',
    finalCalculationTitle: 'Cálculo final',
  },
  CO: {
    taxSectionTitle: '',
    employeeDeductionsTitle: 'Deducciones del colaborador',
    employerObligationsTitle: 'Obligaciones patronales',
    employerObligationsDescription: 'Las obligaciones patronales no reducen el neto del colaborador.',
    contributionBreakdownTitle: 'Seguridad social / parafiscales',
    benefitsSectionTitle: 'Prestaciones / provisiones',
    internalOnlyNotice: 'Este colaborador se administra solo para control interno de nómina. No se calculan aportes legales.',
    finalCalculationTitle: 'Cálculo final',
  },
  US: {
    taxSectionTitle: 'Federal / State Withholding and Employee Programs',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations include FICA match, FUTA, SUTA and configured state employer programs.',
    contributionBreakdownTitle: 'FICA / Unemployment / State Programs Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  CA_STANDARD: {
    taxSectionTitle: 'Federal / Provincial Tax',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'CPP / EI Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  CA_QUEBEC: {
    taxSectionTitle: 'Federal / Quebec Tax',
    employeeDeductionsTitle: 'HR User Deductions',
    employerObligationsTitle: 'Employer Obligations',
    employerObligationsDescription: 'Quebec payroll uses QPP, QPP2, QPIP and Quebec provincial tax. Employer obligations include statutory payroll rows only.',
    contributionBreakdownTitle: 'QPP / QPIP / EI Breakdown',
    internalOnlyNotice: 'This HR user is managed for internal payroll control only. Taxes and statutory contributions are not calculated.',
    finalCalculationTitle: 'Final Calculation',
  },
  BR: {
    taxSectionTitle: 'INSS / IRRF',
    employeeDeductionsTitle: 'Descontos do colaborador',
    employerObligationsTitle: 'Encargos patronais',
    employerObligationsDescription: 'Encargos patronais não reduzem o salário líquido do colaborador.',
    contributionBreakdownTitle: 'INSS / FGTS / RAT / Terceiros',
    benefitsSectionTitle: 'Provisões / vales',
    internalOnlyNotice: 'Este colaborador se administra apenas para controle interno de folha. Impostos e encargos legais não são calculados.',
    finalCalculationTitle: 'Cálculo final',
  },
};

export const payrollStatutoryColumnKeysByJurisdiction: Record<PayrollJurisdiction, PayrollDetailedColumnKey[]> = {
  MX: [
    'isrBeforeSubsidy',
    'employmentSubsidy',
    'finalIsr',
    'employeeImss',
    'infonavitDiscount',
    'employerImss',
    'employerInfonavit',
    'sar',
    'payrollStateTax',
    'occupationalRisk',
    'childcareImss',
    'totalEmployerObligations',
  ],
  CO: [
    'employeeHealth',
    'employeePension',
    'withholdingTax',
    'retroactiveAdjustments',
    'payrollCorrections',
    'terminationSettlement',
    'terminationIndemnity',
    'employerHealth',
    'employerPension',
    'arl',
    'severance',
    'severanceInterest',
    'serviceBonus',
    'vacationProvision',
    'familyCompensationFund',
    'icbf',
    'sena',
    'totalEmployerObligations',
  ],
  US: [
    'federalTax',
    'provincialTax',
    'employeeCpp',
    'employeeEi',
    'employerCpp',
    'employerEi',
    'payrollStateTax',
    'employerBenefits',
    'totalEmployerObligations',
  ],
  CA_STANDARD: [
    'federalTax',
    'provincialTax',
    'employeeCpp',
    'employeeCpp2',
    'employeeEi',
    'employerCpp',
    'employerCpp2',
    'employerEi',
    'employerBenefits',
    'totalEmployerObligations',
  ],
  CA_QUEBEC: [
    'federalTax',
    'quebecProvincialTax',
    'employeeQpp',
    'employeeQpp2',
    'employeeQpip',
    'employeeEi',
    'employerQpp',
    'employerQpp2',
    'employerQpip',
    'employerEi',
    'employerBenefits',
    'totalEmployerObligations',
  ],
  BR: [
    'employeeInss',
    'irrf',
    'transportationVoucher',
    'mealBenefitsDeduction',
    'employerInss',
    'fgts',
    'ratWorkAccident',
    'thirdPartyContributions',
    'employerBenefits',
    'totalEmployerObligations',
  ],
};
