import { payrollActions,payrollReads,payrollChangeSchema,payrollResultSchema,payrollRunSchema } from "./hrPayrollContracts.js";
import { attendanceActions, attendanceReads, attendanceChangeSchema, attendanceResultSchema, attendanceCalendarSchema, attendanceEventSchema, attendanceScheduleViewSchema, attendanceLocationViewSchema, attendanceCandidateSchema } from "./hrAttendanceContracts.js";
import { z } from "zod";

const id = z.number().int().positive();
const text = z.string().max(120);
const date = z.iso.date().optional();
export const employeeChangeSchema = z.object({
  firstName: text.optional(), lastName: text.optional(), email: z.email().max(254).optional(), phone: z.string().max(40).optional(),
  position: text.optional(), department: text.optional(), unitId: id.optional(), businessId: id.optional(), hireDate: date,
  salary: z.number().positive().optional(), payPeriod: z.string().max(30).optional(), salaryType: z.enum(["daily", "hourly"]).optional(),
  hourlyRate: z.number().positive().optional(), contractType: z.string().max(30).optional(), contractStartDate: date, contractEndDate: date,
  registrationCountry: z.enum(["AR","BR","CA","CL","CO","ES","MX","PE","US"]).optional()
}).strict();
export const assetChangeSchema = z.object({ assetCode: z.string().max(80).optional(), assetType: z.string().min(1).max(50), name: z.string().min(1).max(160), model: z.string().max(160).optional(), serialNumber: z.string().max(160).optional(),
  responsibleUserCompanyId: id.optional(), unitId: id.optional(), status: z.enum(["available", "assigned", "maintenance", "custody", "inactive"]).optional(),
  assignedAt: z.iso.datetime({ local: true }).optional(), valueAmount: z.number().nonnegative().optional(), valueCurrency: z.string().regex(/^[A-Z]{3}$/).optional(), notes: z.string().max(4000).optional() }).strict();
export const announcementChangeSchema = z.object({ title: z.string().min(1).max(200), type: z.enum(["general", "urgent", "reminder", "celebration"]).optional(), content: z.string().min(1).max(20000),
  audienceType: z.enum(["all", "units", "departments", "employees"]).optional(), status: z.enum(["draft", "published", "scheduled"]).optional(), scheduledFor: z.iso.datetime({ local: true }).optional(),
  unitIds: z.array(id).max(100).optional(), userCompanyIds: z.array(id).max(500).optional(), departmentNames: z.array(text).max(100).optional() }).strict();
export const terminationChangeSchema=z.object({ exitDate:z.iso.date(),lastWorkingDay:z.iso.date().optional(),reasonType:z.enum(["resignation","termination_for_cause","contract_end","mutual_agreement","other"]),specificReason:z.string().max(120).optional(),summary:z.string().min(1).max(4000) }).strict();
export const assetUpdateSchema=assetChangeSchema.partial().omit({responsibleUserCompanyId:true,status:true,assignedAt:true}).strict();
export const assetAssignmentSchema=z.object({ responsibleUserCompanyId:id.optional(),unitId:id.optional(),status:z.enum(["available","assigned","maintenance","custody","inactive"]),effectiveAt:z.iso.datetime({local:true}).optional(),notes:z.string().max(4000).optional(),changeReason:z.string().max(120).optional() }).strict();
export const recordChangeSchema=z.object({userCompanyId:id,type:z.enum(["incident","warning","observation","recognition","training"]),severity:z.enum(["low","medium","high"]).optional(),status:z.enum(["pending","reviewed","resolved"]).optional(),title:z.string().min(1).max(160),description:z.string().min(1).max(1000),actionsTaken:z.string().max(2000).optional(),eventDate:z.iso.datetime({local:true}),witnesses:z.array(z.object({userCompanyId:id.optional(),name:z.string().max(160).optional()}).strict()).max(100).optional()}).strict();
export const hrActionNameSchema = z.enum([...payrollActions,...attendanceActions, "create_hr_incentive","cancel_hr_incentive","create_employee", "update_employee", "import_employees", "inactivate_employee", "create_hr_asset", "create_announcement",
  "create_my_hr_permission","withdraw_my_hr_permission","approve_hr_permission","reject_hr_permission","terminate_employee","update_hr_asset","reassign_hr_asset","change_hr_asset_status","update_announcement","mark_announcement_read","mark_announcement_unread","create_hr_record","update_hr_record"]);
export type HrActionName = z.infer<typeof hrActionNameSchema>;
export const permissionChangeSchema=z.object({type:z.enum(["vacation","sick_leave","personal","maternity","bereavement","unpaid","other"]).optional(),payrollTreatment:z.enum(["paid","unpaid"]).optional(),startDate:z.iso.date().optional(),endDate:z.iso.date().optional(),halfDay:z.boolean().optional(),reason:z.string().max(2000).optional(),reviewNotes:z.string().max(2000).optional()}).strict();
export const incentiveChangeSchema=z.object({name:z.string().min(1).max(160),description:z.string().max(4000).optional(),type:z.enum(["manual","kpi"]).optional(),amount:z.number().positive().max(999999999.99),currency:z.string().regex(/^[A-Z]{3}$/),status:z.enum(["active","scheduled","paused"]).optional(),startDate:z.iso.date(),endDate:z.iso.date().optional(),applicationMode:z.enum(["next_payroll","specific_date"]).optional(),scopeType:z.enum(["all","employees","units","businesses"]),employeeIds:z.array(id).min(1).max(100).optional(),unitIds:z.array(id).min(1).max(100).optional(),businessIds:z.array(id).min(1).max(100).optional(),sourceReferenceType:z.string().max(80).optional(),sourceReferenceId:z.string().max(120).optional()}).strict();
export const hrChangeSchema = z.object({ id: id.optional(), employee: employeeChangeSchema.optional(), employees: z.array(employeeChangeSchema).min(1).max(100).optional(), asset: assetChangeSchema.partial().optional(), announcement: announcementChangeSchema.optional(),termination:terminationChangeSchema.optional(),assignment:assetAssignmentSchema.optional(),record:recordChangeSchema.optional(),permission:permissionChangeSchema.optional(),incentive:incentiveChangeSchema.optional(), attendance:attendanceChangeSchema.optional(),payroll:payrollChangeSchema.optional() }).strict();
export type HrChange = z.infer<typeof hrChangeSchema>;
export const hrPageRequestSchema = z.object({ query: z.string().max(120).optional(), status: z.string().max(30).optional(), unitId: id.optional(), businessId: id.optional(), page: z.number().int().positive().optional(), limit: z.number().int().min(1).max(100).optional(), cursor: z.string().max(256).optional() }).strict();
export type HrPageRequest = z.infer<typeof hrPageRequestSchema>;
export const hrReadRequestSchema = z.object({ id: id.optional(), page: hrPageRequestSchema.optional(), month: z.string().regex(/^\d{4}-\d{2}$/).optional(), startDate:z.iso.date().optional(),endDate:z.iso.date().optional(),availableOnly:z.boolean().optional() }).strict();
export type HrReadRequest = z.infer<typeof hrReadRequestSchema>;
export const hrReadNameSchema = z.enum([...payrollReads,...attendanceReads, "get_hr_asset_history","get_announcement_receipts","list_hr_incentives","get_hr_incentive","list_my_hr_permissions","get_my_hr_permission","list_hr_permissions","get_hr_permission","list_announcement_audience", "list_hr_records", "get_hr_record_detail", "list_hr_organization", "get_employee_file", "list_hr_assets", "get_hr_asset_detail", "list_announcements", "get_announcement_detail"]);
export type HrReadName = z.infer<typeof hrReadNameSchema>;
const employeeViewSchema = z.object({ userCompanyId: z.number().int().nonnegative(), employeeCode: z.string(), name: z.string(), email: z.string(), phone: z.string(), position: z.string(), department: z.string(),
  unitId: id.nullable(), unitName: z.string(), businessId: id.nullable(), businessName: z.string(), status: z.string(), registrationCountry: z.string(), salaryCurrency: z.string().nullable(), salary: z.number().nullable(), payPeriod: z.string(), salaryType: z.string(), hourlyRate: z.number().nullable(),
  hireDate: z.iso.date().nullable(), contractType: z.string(), contractStartDate: z.iso.date().nullable(), contractEndDate: z.iso.date().nullable(),
  documents: z.array(z.object({ id, type: z.string(), fileName: z.string(), mimeType: z.string(), sizeBytes: z.number().int().nullable() })) });
const assetViewSchema = z.object({ id: z.number().int().nonnegative(), assetCode: z.string().nullable(), name: z.string(), assetType: z.string(), model: z.string().nullable(), serialNumber: z.string().nullable(), unitId: id.nullable(), unitName: z.string().nullable(),
  responsibleUserCompanyId: id.nullable(), responsibleName: z.string().nullable(), status: z.string(), valueAmount: z.number().nullable(), valueCurrency: z.string(), notes: z.string().nullable(), photoCount: z.number().int().nonnegative() });
const announcementViewSchema = z.object({ id: z.number().int().nonnegative(), title: z.string(), type: z.string(), content: z.string(), audienceType: z.string(), audienceSummary: z.string(), status: z.string(), scheduledFor: z.string().nullable(), deliveryCount: z.number().int().nonnegative(), readCount: z.number().int().nonnegative(), read: z.boolean(), attachmentCount: z.number().int().nonnegative() });
function page<S extends z.ZodType>(schema: S) { return z.object({ items: z.array(schema), returnedCount: z.number().int().nonnegative(), totalCount: z.number().int().nonnegative(), hasMore: z.boolean(), nextPage: z.number().int().positive().nullable(), nextCursor: z.string().nullable() }); }
const recordViewSchema = z.object({ witnesses:z.array(z.object({userCompanyId:id.nullable(),name:z.string()})).optional(), id, folio: z.string(), userCompanyId: id, employeeName: z.string(), unitId: id.nullable(), unitName: z.string(), businessId: id.nullable(), businessName: z.string(), type: z.string(), severity: z.string(), status: z.string(), title: z.string(), description: z.string(), actionsTaken: z.string(), eventDate: z.string(), attachments: z.array(z.object({ id, type: z.string(), fileName: z.string(), mimeType: z.string(), sizeBytes: z.number().int().nullable() })), history: z.array(z.object({ type: z.string(), fromStatus: z.string(), toStatus: z.string(), note: z.string(), actorName: z.string(), date: z.string() })) });
const permissionViewSchema=z.object({id:z.number().int().nonnegative(),folio:z.string(),userCompanyId:id,employeeName:z.string(),type:z.string(),payrollTreatment:z.string(),startDate:z.string(),endDate:z.string(),days:z.number().nonnegative(),halfDay:z.boolean(),status:z.string(),reason:z.string(),reviewNotes:z.string(),reviewedAt:z.string(),reviewedBy:z.string(),attachments:z.array(z.object({id,type:z.string(),fileName:z.string(),mimeType:z.string(),sizeBytes:z.number().int().nullable()}))});
const incentiveViewSchema=z.object({id:z.number().int().nonnegative(),code:z.string(),name:z.string(),description:z.string(),type:z.string(),amount:z.number(),currency:z.string(),status:z.string(),startDate:z.string(),endDate:z.string(),applicationMode:z.string(),scopeSummary:z.string(),eligibleCount:z.number().int().nonnegative(),appliedCount:z.number().int().nonnegative(),applications:z.array(z.object({userCompanyId:id,employeeName:z.string(),amount:z.number(),currency:z.string(),exchangeRate:z.number(),status:z.string()}))});
export const hrReadSchemas = {list_hr_payroll_runs:page(payrollRunSchema),get_hr_payroll_run:payrollRunSchema,list_hr_schedule_candidates:page(attendanceCandidateSchema), list_hr_schedules:page(attendanceScheduleViewSchema),get_hr_schedule:attendanceScheduleViewSchema,list_hr_locations:page(attendanceLocationViewSchema),get_hr_location:attendanceLocationViewSchema,get_my_attendance_calendar:attendanceCalendarSchema,get_my_attendance_events:page(attendanceEventSchema),get_hr_attendance_events:page(attendanceEventSchema),get_hr_attendance_calendar:attendanceCalendarSchema,get_hr_asset_history:page(z.object({id,type:z.string(),fromStatus:z.string(),toStatus:z.string(),responsibleUserCompanyId:id.nullable(),responsibleName:z.string(),unitId:id.nullable(),unitName:z.string(),startedAt:z.string(),endedAt:z.string(),reason:z.string(),notes:z.string(),actorName:z.string(),endedByName:z.string()})),get_announcement_receipts:page(z.object({userCompanyId:id,employeeName:z.string(),status:z.string(),deliveredAt:z.string(),readAt:z.string()})), list_hr_incentives:page(incentiveViewSchema),get_hr_incentive:incentiveViewSchema,list_my_hr_permissions:page(permissionViewSchema),get_my_hr_permission:permissionViewSchema,list_hr_permissions:page(permissionViewSchema),get_hr_permission:permissionViewSchema, list_announcement_audience: page(z.object({ referenceType: z.enum(["UNIT", "EMPLOYEE", "DEPARTMENT"]), id: id.nullable(), name: z.string(), unitId: id.nullable(), unitName: z.string(), activeUserCount: z.number().int().nonnegative() })), list_hr_records: page(recordViewSchema), get_hr_record_detail: recordViewSchema, list_hr_organization: page(z.object({ referenceType: z.enum(["UNIT", "BUSINESS"]), id, name: z.string(), unitId: id.nullable(), unitName: z.string() })), get_employee_file: employeeViewSchema, list_hr_assets: page(assetViewSchema), get_hr_asset_detail: assetViewSchema, list_announcements: page(announcementViewSchema), get_announcement_detail: announcementViewSchema };
export type HrReadResult = z.infer<(typeof hrReadSchemas)[HrReadName]>;
export const hrResultSchema = z.object({ employees: z.array(employeeViewSchema), asset: assetViewSchema.nullable(), announcement: announcementViewSchema.nullable(), record:recordViewSchema.extend({id:z.number().int().nonnegative()}).nullable().optional(),permission:permissionViewSchema.nullable().optional(),withdrawn:z.boolean().optional(),incentive:incentiveViewSchema.nullable().optional(),attendance:attendanceResultSchema.nullable().optional(),payroll:payrollResultSchema.nullable().optional() });
const storedEmployeeSchema = employeeChangeSchema.extend({ phone: z.string().nullable().optional(), hireDate: z.iso.date().nullable().optional(),
  salary: z.number().nonnegative().nullable().optional(), hourlyRate: z.number().positive().nullable().optional(),
  contractStartDate: z.iso.date().nullable().optional(), contractEndDate: z.iso.date().nullable().optional(), registrationCountry: z.enum(["AR","BR","CA","CL","CO","ES","MX","PE","US"]).nullable().optional() });
const storedAssetSchema = assetChangeSchema.extend({ status:z.enum(["available","assigned","maintenance","custody","inactive"]).nullable().optional(), assetCode: z.string().nullable().optional(), model: z.string().nullable().optional(), serialNumber: z.string().nullable().optional(),
  responsibleUserCompanyId: id.nullable().optional(), unitId: id.nullable().optional(), assignedAt: z.string().nullable().optional(), valueAmount: z.number().nullable().optional(), notes: z.string().nullable().optional() });
const storedAnnouncementSchema = announcementChangeSchema.extend({ scheduledFor: z.string().nullable().optional(), unitIds: z.array(id).nullable().optional(), userCompanyIds: z.array(id).nullable().optional(), departmentNames: z.array(text).nullable().optional() });
export const hrPreviewSchema = z.object({ action: hrActionNameSchema, confirmationToken: z.string().startsWith("idx_confirm_"), expiresAt: z.iso.datetime(), requiresConfirmation: z.literal(true), before: hrResultSchema, after: hrResultSchema, changes: z.object({ payroll:payrollChangeSchema.nullable().optional(),attendance:attendanceChangeSchema.nullable().optional(),
  id: id.nullable(), employee: storedEmployeeSchema.nullable(), employees: z.array(storedEmployeeSchema).nullable(), asset: storedAssetSchema.partial().nullable(), announcement: storedAnnouncementSchema.nullable(),
  termination:terminationChangeSchema.extend({lastWorkingDay:z.iso.date().nullable().optional(),specificReason:z.string().nullable().optional()}).nullable().optional(),
  assignment:assetAssignmentSchema.extend({responsibleUserCompanyId:id.nullable().optional(),unitId:id.nullable().optional(),effectiveAt:z.string().nullable().optional(),notes:z.string().nullable().optional(),changeReason:z.string().nullable().optional()}).nullable().optional(),
  record:recordChangeSchema.extend({severity:z.string().nullable().optional(),actionsTaken:z.string().nullable().optional(),witnesses:z.array(z.object({userCompanyId:id.nullable(),name:z.string()})).nullable().optional()}).nullable().optional(),
  incentive:incentiveChangeSchema.extend({description:z.string().nullable().optional(),endDate:z.iso.date().nullable().optional(),employeeIds:z.array(id).nullable().optional(),unitIds:z.array(id).nullable().optional(),businessIds:z.array(id).nullable().optional(),sourceReferenceType:z.string().nullable().optional(),sourceReferenceId:z.string().nullable().optional()}).nullable().optional(),
  permission:permissionChangeSchema.extend({type:z.string().nullable().optional(),payrollTreatment:z.string().nullable().optional(),startDate:z.iso.date().nullable().optional(),endDate:z.iso.date().nullable().optional(),halfDay:z.boolean().nullable().optional(),reason:z.string().nullable().optional(),reviewNotes:z.string().nullable().optional()}).nullable().optional()
}), effects: z.array(z.string()) });
export const hrCommitSchema = z.object({ action: hrActionNameSchema, replayed: z.boolean(), correlationId: z.uuid(), result: hrResultSchema });
export type HrPreview = z.infer<typeof hrPreviewSchema>;
export type HrCommitted = z.infer<typeof hrCommitSchema>;
