import { z } from "zod";
const id=z.number().int().positive(),n=z.number().int().nonnegative(),money=z.number(),text=z.string().nullable(),date=z.iso.date();
export const payrollReads=["list_hr_payroll_runs","get_hr_payroll_run"] as const;
export const payrollActions=["prepare_hr_payroll","adjust_hr_payroll_line","recalculate_hr_payroll","approve_hr_payroll","register_hr_payroll_paid","cancel_hr_payroll"] as const;
export const payrollChangeSchema=z.object({payPeriod:z.enum(["weekly","biweekly","semimonthly","monthly"]).nullable().optional(),periodStartDate:date.nullable().optional(),periodEndDate:date.nullable().optional(),groupingMode:z.enum(["single","unit","business"]).nullable().optional(),lineId:id.nullable().optional(),payrollTreatment:z.enum(["fiscal_payroll","operational_payroll","accounts_payable","no_payroll"]).nullable().optional(),notes:z.string().max(2000).nullable().optional(),manualItems:z.array(z.object({category:z.enum(["earning","deduction","employer_contribution","provision"]),label:z.string().min(1).max(180),amount:money}).strict()).max(100).nullable().optional()}).strict();
const item=z.object({code:z.string(),category:z.string(),label:z.string(),amount:money,sourceType:z.string(),currency:z.string(),taxTreatment:z.string(),taxable:z.boolean(),affectsSocialSecurity:z.boolean(),affectsEmployerCost:z.boolean()});
export const payrollLineSchema=z.object({id:n,userCompanyId:id,employeeName:z.string(),unitId:id.nullable(),unitName:text,businessId:id.nullable(),businessName:text,country:z.string(),jurisdiction:text,currency:z.string(),fxRate:money,payPeriod:z.string(),payrollTreatment:z.string(),paymentRoute:z.string(),notes:text,grossAmount:money,deductionsAmount:money,employerContributionsAmount:money,netAmount:money,daysPayable:money,paidLeaveDays:money,absenceDays:money,missingAttendanceDays:money,regularHours:money,overtimeHours:money,statutoryCompliance:z.boolean(),calculationWarnings:z.array(z.string()),attendanceWarnings:z.array(z.string()),items:z.array(item)});
export const payrollRunSchema=z.object({id:n,groupingMode:z.string(),groupingKey:text,groupingLabel:text,payPeriod:z.string(),periodStartDate:date,periodEndDate:date,status:z.enum(["draft","approved","paid","cancelled"]),employeeCount:n,totals:z.array(z.object({currency:z.string(),grossAmount:money,deductionsAmount:money,employerContributionsAmount:money,netAmount:money})),lines:z.array(payrollLineSchema),reused:z.boolean()});
export const payrollResultSchema=z.object({runs:z.array(payrollRunSchema)});
export const payrollInputs={
  prepare_hr_payroll:z.object({payroll:payrollChangeSchema.pick({payPeriod:true,periodStartDate:true,periodEndDate:true,groupingMode:true}).extend({payPeriod:z.enum(["weekly","biweekly","semimonthly","monthly"]),periodStartDate:date})}).strict(),
  adjust_hr_payroll_line:z.object({id,payroll:payrollChangeSchema.pick({lineId:true,payrollTreatment:true,notes:true,manualItems:true}).extend({lineId:id,manualItems:payrollChangeSchema.shape.manualItems.unwrap().unwrap()})}).strict(),
  recalculate_hr_payroll:z.object({id}).strict(),approve_hr_payroll:z.object({id}).strict(),register_hr_payroll_paid:z.object({id}).strict(),cancel_hr_payroll:z.object({id}).strict()
};
export const payrollDescriptions={prepare_hr_payroll:"Prepara nómina con frecuencia, fecha y agrupación explícitas. El propietario calcula todos los colaboradores, deducciones, aportaciones e incentivos en moneda nativa y respeta el calendario y el país. Reutiliza periodos existentes; muestra las filas completas (máximo 500).",adjust_hr_payroll_line:"Reemplaza la lista completa de conceptos manuales de una línea en borrador (0–100). Conserva incentivos y usa el motor fiscal oficial. Revisa importes, moneda y tratamiento antes de confirmar.",recalculate_hr_payroll:"Recalcula una nómina autorizada con el motor oficial y conserva el estado borrador. No aprueba ni paga.",approve_hr_payroll:"Aprueba y congela la nómina validada por el propietario del país, con separación de funciones. Crea las cuentas por pagar correspondientes. No transfiere dinero.",register_hr_payroll_paid:"Registra el pago con el ciclo vigente y separación de funciones. Exige las cuentas por pagar ya pagadas cuando corresponde; no inicia transferencia.",cancel_hr_payroll:"Cancela únicamente nómina editable en borrador. Conserva sus líneas, importes e historial; no revierte nómina aprobada o pagada."};
