import { z } from "zod";
const id=z.number().int().positive(), nullableId=id.nullable(), text=z.string().nullable();
const decimal=z.union([z.number().finite(),z.string().regex(/^-?\d+(?:\.\d+)?$/)]), nonnegative=z.number().finite().nonnegative();
export const salesWorkflowReadNames=["list_commercial_sales","get_commercial_sale","list_sales_contracts","get_sales_contract","list_sales_follow_ups","get_sales_follow_up","list_commission_rules","get_commission_rule"] as const;
export const salesWorkflowActionNames=["create_commercial_sale","update_commercial_sale","convert_quote_to_sale","approve_sale_commercial","confirm_sale_inventory","confirm_sale_collection","update_sale_delivery","cancel_commercial_sale","create_sales_contract","update_sales_contract","review_sales_contract","cancel_sales_contract","create_sales_follow_up","update_sales_follow_up","set_sales_follow_up_status","create_commission_rule","update_commission_rule","set_commission_rule_status"] as const;
export const salesWorkflowReadNameSchema=z.enum(salesWorkflowReadNames), salesWorkflowActionNameSchema=z.enum(salesWorkflowActionNames);
const line=z.object({productId:id,quantity:z.number().positive(),unitPrice:nonnegative.optional(),discountPercent:nonnegative.max(100).optional(),taxPercent:nonnegative.max(100).optional()}).strict();
const sale=z.object({customerId:id.optional(),quoteId:id.optional(),warehouseId:id.optional(),date:z.iso.date().optional(),currency:z.string().regex(/^[A-Z]{3}$/).optional(),items:z.array(line).min(1).max(100).optional(),notes:z.string().max(4000).optional()}).strict();
const collection=z.object({paymentMethod:z.enum(["cash","transfer","credit"]),paymentAccountId:id.optional(),reference:z.string().max(300).optional()}).strict();
const contract=z.object({customerId:id,quoteId:id.optional(),title:z.string().trim().min(1).max(220),contractType:z.enum(["service_agreement","sales_agreement","renewal_agreement","subscription_agreement","nda","operational_agreement","custom_contract"]),country:z.enum(["MX","CA"]).optional(),expirationDate:z.iso.date().optional(),notes:z.string().max(4000).optional()}).strict();
const followUp=z.object({customerId:id,relationType:z.enum(["one_time_customer","recurrent_customer","renewal_customer","dormant_customer","lost_prospect"]),postSaleType:z.string().min(1).max(80),nextFollowUpDate:z.iso.date().optional(),renewalDate:z.iso.date().optional(),nextAction:z.string().max(250).optional(),notes:z.string().max(4000).optional()}).strict();
const rule=z.object({name:z.string().trim().min(1).max(180),userCompanyIds:z.array(id).max(100).optional(),productIds:z.array(id).max(100).optional(),type:z.enum(["percentage_of_sale","fixed_per_sale","percentage_of_product","fixed_per_product"]),value:nonnegative,validFrom:z.iso.date().optional(),validUntil:z.iso.date().optional(),priority:z.number().int().optional(),notes:z.string().max(4000).optional()}).strict();
export const salesWorkflowChangeSchema=z.object({id:id.optional(),sale:sale.optional(),collection:collection.optional(),contract:contract.optional(),followUp:followUp.optional(),rule:rule.optional(),status:z.string().optional(),reason:z.string().min(5).max(500).optional()}).strict();
export const salesWorkflowInputs={
 create_commercial_sale:z.object({sale:sale.required({customerId:true,currency:true,items:true}).omit({quoteId:true})}).strict(),
 update_commercial_sale:z.object({id,sale:sale.required({customerId:true,currency:true,items:true}).omit({quoteId:true})}).strict(),
 convert_quote_to_sale:z.object({sale:sale.required({quoteId:true}).omit({items:true,customerId:true})}).strict(),
 approve_sale_commercial:z.object({id}).strict(),confirm_sale_inventory:z.object({id}).strict(),confirm_sale_collection:z.object({id,collection}).strict(),
 update_sale_delivery:z.object({id,status:z.enum(["pending","in_progress","delivered"])}).strict(),cancel_commercial_sale:z.object({id,reason:z.string().trim().min(5).max(500)}).strict(),
 create_sales_contract:z.object({contract}).strict(),update_sales_contract:z.object({id,contract}).strict(),review_sales_contract:z.object({id}).strict(),cancel_sales_contract:z.object({id,reason:z.string().trim().min(5).max(500)}).strict(),
 create_sales_follow_up:z.object({followUp}).strict(),update_sales_follow_up:z.object({id,followUp}).strict(),set_sales_follow_up_status:z.object({id,status:z.enum(["active","pending_follow_up","in_service","renewal_soon","recurrent","at_risk","completed","closed"])}).strict(),
 create_commission_rule:z.object({rule}).strict(),update_commission_rule:z.object({id,rule}).strict(),set_commission_rule_status:z.object({id,status:z.enum(["active","inactive"])}).strict()
} as const;
export const salesWorkflowQuerySchema=z.object({id:id.optional(),query:z.string().max(120).optional(),status:z.string().max(50).optional(),from:z.iso.date().optional(),to:z.iso.date().optional(),limit:id.max(50).optional(),cursor:z.string().max(180).optional()}).strict();
const saleView=z.object({id:nullableId,code:text,customerId:nullableId,quoteId:nullableId,unitId:nullableId,businessId:nullableId,warehouseId:nullableId,customerName:text,sellerName:text,date:z.iso.date().nullable(),currency:z.string().regex(/^[A-Z]{3}$/),subtotal:decimal,discountTotal:decimal,taxTotal:decimal,total:decimal,marginReady:z.boolean(),marginTotal:decimal,commercialStatus:text,financeStatus:text,inventoryStatus:text,inventoryMovementStatus:text,deliveryStatus:text,commissionStatus:text,commissionAmount:decimal,paymentMethod:text,paymentReference:text,items:z.array(z.object({productId:nullableId,name:text,quantity:decimal,unitPrice:decimal,discountPercent:decimal,taxPercent:decimal,subtotal:decimal,taxAmount:decimal,unitCost:decimal.nullable(),costCurrency:text,costSource:text}).strict()),notes:text,posOwned:z.boolean()}).strict();
const contractView=z.object({id:nullableId,code:text,customerId:nullableId,quoteId:nullableId,title:text,customerName:text,contractType:text,country:text,status:text,signatureStatus:text,expirationDate:z.iso.date().nullable(),notes:text}).strict();
const followUpView=z.object({id:nullableId,code:text,customerId:nullableId,customerName:text,relationType:text,postSaleType:text,status:text,nextFollowUpDate:z.iso.date().nullable(),renewalDate:z.iso.date().nullable(),nextAction:text,notes:text}).strict();
const ruleView=z.object({id:nullableId,code:text,name:text,userCompanyIds:z.array(id),productIds:z.array(id),type:text,value:decimal,status:text,validFrom:z.iso.date().nullable(),validUntil:z.iso.date().nullable(),priority:z.number().int(),notes:text}).strict();
export const salesWorkflowRecordsSchema=z.object({sales:z.array(saleView),contracts:z.array(contractView),followUps:z.array(followUpView),rules:z.array(ruleView)}).strict();
export const salesWorkflowReadSchema=z.object({records:salesWorkflowRecordsSchema,totalCount:z.number().int().nonnegative(),hasMore:z.boolean(),nextCursor:text,scope:z.string()}).strict();
export const salesWorkflowPreviewSchema=z.object({action:salesWorkflowActionNameSchema,confirmationToken:z.string().regex(/^idx_confirm_[A-Za-z0-9_-]{43}$/),expiresAt:z.string(),requiresConfirmation:z.literal(true),before:salesWorkflowRecordsSchema,after:salesWorkflowRecordsSchema,changes:salesWorkflowChangeSchema,
 stock:z.array(z.object({productId:nullableId,warehouseId:nullableId,required:decimal,available:decimal,reserved:decimal,unitCost:decimal,consumesStock:z.boolean(),ready:z.boolean()}).strict()),
 collection:z.object({paymentAccountId:nullableId,method:text,currency:text,amount:decimal,createsUniversalCash:z.boolean(),reversesCollection:z.boolean()}).strict().nullable(),effects:z.array(z.string()).min(1)}).strict();
export const salesWorkflowCommittedSchema=z.object({action:salesWorkflowActionNameSchema,replayed:z.boolean(),correlationId:z.string(),result:z.object({action:salesWorkflowActionNameSchema,records:salesWorkflowRecordsSchema}).strict()}).strict();
export const salesWorkflowCommitRequestSchema=z.object({confirmationToken:z.string().regex(/^idx_confirm_[A-Za-z0-9_-]{43}$/),idempotencyKey:z.string().min(8).max(128)}).strict();
export type SalesWorkflowReadName=z.infer<typeof salesWorkflowReadNameSchema>;export type SalesWorkflowActionName=z.infer<typeof salesWorkflowActionNameSchema>;
export type SalesWorkflowQuery=z.infer<typeof salesWorkflowQuerySchema>;export type SalesWorkflowChange=z.infer<typeof salesWorkflowChangeSchema>;
export type SalesWorkflowReadResult=z.infer<typeof salesWorkflowReadSchema>;export type SalesWorkflowPreview=z.infer<typeof salesWorkflowPreviewSchema>;export type SalesWorkflowCommitted=z.infer<typeof salesWorkflowCommittedSchema>;
