import {financeReadNames} from "./financeContracts.js";
import {terminalReadNames} from "./terminalContracts.js";
import {posOperationsReadNames} from "./posOperationsContracts.js";
import {commissionReadNames} from "./commissionContracts.js";
import {inventoryCatalogReadNames} from "./inventoryCatalogContracts.js";
import {procurementReadNames,procurementActionNames} from "./procurementContracts.js";
import type { RegisteredTool } from "@modelcontextprotocol/sdk/server/mcp.js";
import { indiceToolNameSchema, type IndiceToolName } from "./contracts.js";

/** Discovery metadata only. Spring remains the authority for every invocation. */
export const toolScopes: Record<IndiceToolName, string> = {
"list_finance_accounting_accounts":"expenses.read",
"get_finance_accounting_account":"expenses.read",
"create_finance_accounting_account":"expenses.accounting.manage",
"preview_create_finance_accounting_account":"expenses.accounting.manage",
"update_finance_accounting_account":"expenses.accounting.manage",
"preview_update_finance_accounting_account":"expenses.accounting.manage",
"inactivate_finance_accounting_account":"expenses.accounting.manage",
"preview_inactivate_finance_accounting_account":"expenses.accounting.manage",
"list_finance_payment_accounts":"expenses.read",
"get_finance_payment_account":"expenses.read",
"create_finance_payment_account":"expenses.accounts.manage",
"preview_create_finance_payment_account":"expenses.accounts.manage",
"update_finance_payment_account":"expenses.accounts.manage",
"preview_update_finance_payment_account":"expenses.accounts.manage",
"inactivate_finance_payment_account":"expenses.accounts.manage",
"preview_inactivate_finance_payment_account":"expenses.accounts.manage",
"list_finance_providers":"expenses.read",
"get_finance_provider":"expenses.read",
"create_finance_provider":"expenses.providers.manage",
"preview_create_finance_provider":"expenses.providers.manage",
"update_finance_provider":"expenses.providers.manage",
"preview_update_finance_provider":"expenses.providers.manage",
"inactivate_finance_provider":"expenses.providers.manage",
"preview_inactivate_finance_provider":"expenses.providers.manage",
"list_finance_budgets":"expenses.read",
"get_finance_budget":"expenses.read",
"create_finance_budget":"expenses.budgets.manage",
"preview_create_finance_budget":"expenses.budgets.manage",
"update_finance_budget":"expenses.budgets.manage",
"preview_update_finance_budget":"expenses.budgets.manage",
"inactivate_finance_budget":"expenses.budgets.manage",
"preview_inactivate_finance_budget":"expenses.budgets.manage",
"list_finance_budget_lines":"expenses.read",
"get_finance_budget_line":"expenses.read",
"create_finance_budget_line":"expenses.budgets.manage",
"preview_create_finance_budget_line":"expenses.budgets.manage",
"update_finance_budget_line":"expenses.budgets.manage",
"preview_update_finance_budget_line":"expenses.budgets.manage",
"inactivate_finance_budget_line":"expenses.budgets.manage",
"preview_inactivate_finance_budget_line":"expenses.budgets.manage",
"create_budget_obligation_schedule":"expenses.budgets.manage",
"preview_create_budget_obligation_schedule":"expenses.budgets.manage",
"list_budget_obligation_reviews":"expenses.read",
"list_finance_expenses":"expenses.read",
"get_finance_expense":"expenses.read",
"list_expense_payments":"expenses.read",
"create_expense_payable":"expenses.manage",
"preview_create_expense_payable":"expenses.manage",
"correct_finance_expense":"expenses.manage",
"preview_correct_finance_expense":"expenses.manage",
"submit_finance_expense":"expenses.manage",
"preview_submit_finance_expense":"expenses.manage",
"approve_finance_expense":"expenses.approve",
"preview_approve_finance_expense":"expenses.approve",
"reject_finance_expense":"expenses.approve",
"preview_reject_finance_expense":"expenses.approve",
"cancel_finance_expense":"expenses.reverse",
"preview_cancel_finance_expense":"expenses.reverse",
"close_finance_expense":"expenses.manage",
"preview_close_finance_expense":"expenses.manage",
"remove_finance_expense":"expenses.reverse",
"preview_remove_finance_expense":"expenses.reverse",
"classify_finance_expense":"expenses.manage",
"preview_classify_finance_expense":"expenses.manage",
"import_finance_expenses":"expenses.manage",
"preview_import_finance_expenses":"expenses.manage",
"classify_finance_expenses":"expenses.manage",
"preview_classify_finance_expenses":"expenses.manage",
"update_finance_expense_due_status":"expenses.manage",
"preview_update_finance_expense_due_status":"expenses.manage",
"register_expense_payment":"expenses.pay",
"preview_register_expense_payment":"expenses.pay",
"settle_expense_payment":"expenses.pay",
"preview_settle_expense_payment":"expenses.pay",
"reverse_expense_payment":"expenses.reverse",
"preview_reverse_expense_payment":"expenses.reverse",
"pay_finance_expenses":"expenses.pay",
"preview_pay_finance_expenses":"expenses.pay",
"correct_finance_expenses":"expenses.manage",
"preview_correct_finance_expenses":"expenses.manage",
"list_petty_cash_funds":"petty_cash.read",
"get_petty_cash_fund":"petty_cash.read",
"list_petty_cash_receipts":"petty_cash.read",
"get_petty_cash_receipt":"petty_cash.read",
"list_petty_cash_statements":"petty_cash.read",
"get_petty_cash_statement":"petty_cash.read",
"list_petty_cash_movements":"petty_cash.read",
"get_petty_cash_movement":"petty_cash.read",
"list_petty_cash_type_changes":"petty_cash.read",
"list_petty_cash_responsibles":"petty_cash.read",
"create_petty_cash_fund":"petty_cash.funds.manage",
"preview_create_petty_cash_fund":"petty_cash.funds.manage",
"update_petty_cash_fund":"petty_cash.funds.manage",
"preview_update_petty_cash_fund":"petty_cash.funds.manage",
"close_petty_cash_fund":"petty_cash.funds.manage",
"preview_close_petty_cash_fund":"petty_cash.funds.manage",
"schedule_type_change_petty_cash_fund":"petty_cash.funds.manage",
"preview_schedule_type_change_petty_cash_fund":"petty_cash.funds.manage",
"cancel_type_change_petty_cash_fund":"petty_cash.funds.manage",
"preview_cancel_type_change_petty_cash_fund":"petty_cash.funds.manage",
"disable_kiosk_petty_cash_fund":"petty_cash.funds.manage",
"preview_disable_kiosk_petty_cash_fund":"petty_cash.funds.manage",
"enable_kiosk_petty_cash_fund":"petty_cash.funds.manage",
"preview_enable_kiosk_petty_cash_fund":"petty_cash.funds.manage",
"revoke_kiosk_petty_cash_fund":"petty_cash.funds.manage",
"preview_revoke_kiosk_petty_cash_fund":"petty_cash.funds.manage",
"deposit_petty_cash_fund":"petty_cash.deposit:create",
"preview_deposit_petty_cash_fund":"petty_cash.deposit:create",
"capture_petty_cash_receipt":"petty_cash.expense:create",
"preview_capture_petty_cash_receipt":"petty_cash.expense:create",
"authorize_petty_cash_receipt":"petty_cash.receipts.approve",
"preview_authorize_petty_cash_receipt":"petty_cash.receipts.approve",
"reject_petty_cash_receipt":"petty_cash.receipts.manage",
"preview_reject_petty_cash_receipt":"petty_cash.receipts.manage",
"reverse_petty_cash_receipt":"petty_cash.receipts.manage",
"preview_reverse_petty_cash_receipt":"petty_cash.receipts.manage",
"classify_petty_cash_receipt":"petty_cash.receipts.manage",
"preview_classify_petty_cash_receipt":"petty_cash.receipts.manage",
"bulk_classify_petty_cash_receipt":"petty_cash.receipts.manage",
"preview_bulk_classify_petty_cash_receipt":"petty_cash.receipts.manage",
"close_petty_cash_statement":"petty_cash.statements.close",
"preview_close_petty_cash_statement":"petty_cash.statements.close",
"remove_expense_attachment":"expenses.manage",
"preview_remove_expense_attachment":"expenses.manage",
"remove_budget_line_attachment":"expenses.budgets.manage",
"preview_remove_budget_line_attachment":"expenses.budgets.manage",
"remove_petty_cash_receipt_attachment":"petty_cash.receipts.manage",
"preview_remove_petty_cash_receipt_attachment":"petty_cash.receipts.manage",
export_finance_report:"files.read",attach_expense_file:"files.attach",preview_attach_expense_file:"files.attach",attach_budget_line_file:"files.attach",preview_attach_budget_line_file:"files.attach",attach_petty_cash_receipt_file:"files.attach",preview_attach_petty_cash_receipt_file:"files.attach",

"get_pos_terminal_binding":"pos.read",
"get_pos_terminal_payment":"pos.read",
"get_pos_terminal_payment_by_request":"pos.read",
"list_pos_pending_terminal_payments":"pos.read",
"get_pos_card_refund":"pos.read",
"get_pos_card_refund_by_request":"pos.read",
"get_pos_card_return_refund":"pos.read",
"create_pos_terminal_payment":"pos.terminal.manage",
"preview_create_pos_terminal_payment":"pos.terminal.manage",
"recover_pos_terminal_payment":"pos.terminal.manage",
"preview_recover_pos_terminal_payment":"pos.terminal.manage",
"cancel_pos_terminal_payment":"pos.terminal.manage",
"preview_cancel_pos_terminal_payment":"pos.terminal.manage",
"refund_pos_card_payment":"pos.returns.manage",
"preview_refund_pos_card_payment":"pos.returns.manage",
"recheck_pos_card_refund":"pos.returns.manage",
"preview_recheck_pos_card_refund":"pos.returns.manage",
"confirm_pos_card_return":"pos.returns.manage",
"preview_confirm_pos_card_return":"pos.returns.manage",
"list_pos_closings":"pos.read",
"get_pos_closing":"pos.read",
"list_pos_closing_settlements":"pos.read",
"list_pos_source_orders":"pos.read",
"get_pos_source_order":"pos.read",
"list_pos_pretickets":"pos.read",
"get_pos_preticket":"pos.read",
"confirm_pos_closing_settlement":"pos.settlements.manage",
"preview_confirm_pos_closing_settlement":"pos.settlements.manage",
"claim_pos_source_order":"pos.orders.manage",
"preview_claim_pos_source_order":"pos.orders.manage",
"release_pos_source_order":"pos.orders.manage",
"preview_release_pos_source_order":"pos.orders.manage",
"claim_pos_preticket":"pos.orders.manage",
"preview_claim_pos_preticket":"pos.orders.manage",
"release_pos_preticket":"pos.orders.manage",
"preview_release_pos_preticket":"pos.orders.manage",
"list_inventory_providers":"inventory.read",
"list_sales_commission_cuts":"sales.read",
"get_sales_commission_cut":"sales.read",
"list_sales_commission_schedules":"sales.read",
"get_sales_commission_schedule":"sales.read",
"create_sales_commission_cut":"sales.commissions.cut",
"preview_create_sales_commission_cut":"sales.commissions.cut",
"create_sales_commission_schedule":"sales.commissions.schedule",
"preview_create_sales_commission_schedule":"sales.commissions.schedule",
"update_sales_commission_schedule":"sales.commissions.schedule",
"preview_update_sales_commission_schedule":"sales.commissions.schedule",
"set_sales_commission_schedule_status":"sales.commissions.schedule",
"preview_set_sales_commission_schedule_status":"sales.commissions.schedule",
"get_inventory_provider":"inventory.read",
"list_inventory_discounts":"inventory.read",
"get_inventory_discount":"inventory.read",
"evaluate_inventory_discounts":"inventory.read",
"create_inventory_provider":"inventory.providers.manage",
"preview_create_inventory_provider":"inventory.providers.manage",
"update_inventory_provider":"inventory.providers.manage",
"preview_update_inventory_provider":"inventory.providers.manage",
"set_inventory_provider_status":"inventory.providers.manage",
"preview_set_inventory_provider_status":"inventory.providers.manage",
"create_inventory_discount":"inventory.discounts.manage",
"preview_create_inventory_discount":"inventory.discounts.manage",
"update_inventory_discount":"inventory.discounts.manage",
"preview_update_inventory_discount":"inventory.discounts.manage",
"set_inventory_discount_status":"inventory.discounts.manage",
"preview_set_inventory_discount_status":"inventory.discounts.manage",

"list_purchase_orders":"inventory.read",
"get_purchase_order":"inventory.read",
"list_supplier_submissions":"inventory.read",
"get_supplier_submission":"inventory.read",
"list_supplier_invoices":"inventory.read",
"get_supplier_invoice":"inventory.read",
"list_product_suppliers":"inventory.read",
"get_product_supplier":"inventory.read",
"create_purchase_order":"inventory.procurement.manage",
"preview_create_purchase_order":"inventory.procurement.manage",
"update_purchase_order_draft":"inventory.procurement.manage",
"preview_update_purchase_order_draft":"inventory.procurement.manage",
"request_purchase_order":"inventory.procurement.manage",
"preview_request_purchase_order":"inventory.procurement.manage",
"approve_purchase_order":"inventory.procurement.approve",
"preview_approve_purchase_order":"inventory.procurement.approve",
"send_purchase_order":"inventory.procurement.manage",
"preview_send_purchase_order":"inventory.procurement.manage",
"cancel_purchase_order":"inventory.procurement.manage",
"preview_cancel_purchase_order":"inventory.procurement.manage",
"receive_purchase_order":"inventory.procurement.receive",
"preview_receive_purchase_order":"inventory.procurement.receive",
"create_supplier_submission":"inventory.procurement.manage",
"preview_create_supplier_submission":"inventory.procurement.manage",
"review_supplier_submission":"inventory.procurement.approve",
"preview_review_supplier_submission":"inventory.procurement.approve",
"convert_supplier_submission":"inventory.procurement.approve",
"preview_convert_supplier_submission":"inventory.procurement.approve",
"submit_supplier_invoice":"inventory.invoices.manage",
"preview_submit_supplier_invoice":"inventory.invoices.manage",
"review_supplier_invoice":"inventory.invoices.manage",
"preview_review_supplier_invoice":"inventory.invoices.manage",
"save_product_supplier":"inventory.procurement.manage",
"preview_save_product_supplier":"inventory.procurement.manage",
"update_product_supplier":"inventory.procurement.manage",
"preview_update_product_supplier":"inventory.procurement.manage",

"list_pos_registers":"pos.read",
"get_pos_register":"pos.read",
"list_pos_shifts":"pos.read",
"get_pos_shift":"pos.read",
"get_my_pos_shift":"pos.read",
"get_pos_closing_summary":"pos.read",
"list_pos_tickets":"pos.read",
"get_pos_ticket":"pos.read",
"list_pos_cash_movements":"pos.read",
"list_pos_inventory_receipts":"pos.read",
"get_pos_return":"pos.read",
"recover_pos_checkout":"pos.read",
"preview_create_pos_register":"pos.registers.manage",
"create_pos_register":"pos.registers.manage",
"preview_update_pos_register":"pos.registers.manage",
"update_pos_register":"pos.registers.manage",
"preview_inactivate_pos_register":"pos.registers.manage",
"inactivate_pos_register":"pos.registers.manage",
"preview_open_pos_shift":"pos.shifts.manage",
"open_pos_shift":"pos.shifts.manage",
"preview_close_pos_shift":"pos.shifts.manage",
"close_pos_shift":"pos.shifts.manage",
"preview_cancel_pos_shift":"pos.shifts.manage",
"cancel_pos_shift":"pos.shifts.manage",
"preview_record_pos_cash_movement":"pos.cash.manage",
"record_pos_cash_movement":"pos.cash.manage",
"preview_complete_pos_checkout":"pos.checkout",
"complete_pos_checkout":"pos.checkout",
"preview_receive_pos_inventory":"pos.inventory.receive",
"receive_pos_inventory":"pos.inventory.receive",
"preview_reverse_pos_inventory_receipt":"pos.inventory.receive",
"reverse_pos_inventory_receipt":"pos.inventory.receive",
"preview_prepare_pos_return":"pos.returns.manage",
"prepare_pos_return":"pos.returns.manage",
"preview_confirm_pos_cash_return":"pos.returns.manage",
"confirm_pos_cash_return":"pos.returns.manage",
"preview_cancel_pos_return":"pos.returns.manage",
"cancel_pos_return":"pos.returns.manage",
"list_commercial_sales":"sales.read",
"get_commercial_sale":"sales.read",
"list_sales_contracts":"sales.read",
"get_sales_contract":"sales.read",
"list_sales_follow_ups":"sales.read",
"get_sales_follow_up":"sales.read",
"list_commission_rules":"sales.read",
"get_commission_rule":"sales.read",
"preview_create_commercial_sale":"sales.manage",
"create_commercial_sale":"sales.manage",
"preview_update_commercial_sale":"sales.manage",
"update_commercial_sale":"sales.manage",
"preview_convert_quote_to_sale":"sales.manage",
"convert_quote_to_sale":"sales.manage",
"preview_approve_sale_commercial":"sales.manage",
"approve_sale_commercial":"sales.manage",
"preview_confirm_sale_inventory":"sales.manage",
"confirm_sale_inventory":"sales.manage",
"preview_confirm_sale_collection":"sales.collections.confirm",
"confirm_sale_collection":"sales.collections.confirm",
"preview_update_sale_delivery":"sales.manage",
"update_sale_delivery":"sales.manage",
"preview_cancel_commercial_sale":"sales.cancel",
"cancel_commercial_sale":"sales.cancel",
"preview_create_sales_contract":"sales.contracts.manage",
"create_sales_contract":"sales.contracts.manage",
"preview_update_sales_contract":"sales.contracts.manage",
"update_sales_contract":"sales.contracts.manage",
"preview_review_sales_contract":"sales.contracts.manage",
"review_sales_contract":"sales.contracts.manage",
"preview_cancel_sales_contract":"sales.contracts.manage",
"cancel_sales_contract":"sales.contracts.manage",
"preview_create_sales_follow_up":"sales.followups.manage",
"create_sales_follow_up":"sales.followups.manage",
"preview_update_sales_follow_up":"sales.followups.manage",
"update_sales_follow_up":"sales.followups.manage",
"preview_set_sales_follow_up_status":"sales.followups.manage",
"set_sales_follow_up_status":"sales.followups.manage",
"preview_create_commission_rule":"sales.commissions.manage",
"create_commission_rule":"sales.commissions.manage",
"preview_update_commission_rule":"sales.commissions.manage",
"update_commission_rule":"sales.commissions.manage",
"preview_set_commission_rule_status":"sales.commissions.manage",
"set_commission_rule_status":"sales.commissions.manage",
"list_inventory_products":"inventory.read",
"get_inventory_product":"inventory.read",
"list_inventory_warehouses":"inventory.read",
"get_inventory_warehouse":"inventory.read",
"list_inventory_balances":"inventory.read",
"get_inventory_balance":"inventory.read",
"list_inventory_movements":"inventory.read",
"get_inventory_movement":"inventory.read",
"get_inventory_metrics":"inventory.read",
"preview_create_inventory_product":"inventory.products.manage",
"create_inventory_product":"inventory.products.manage",
"preview_update_inventory_product":"inventory.products.manage",
"update_inventory_product":"inventory.products.manage",
"preview_inactivate_inventory_product":"inventory.products.manage",
"inactivate_inventory_product":"inventory.products.manage",
"preview_create_inventory_warehouse":"inventory.warehouses.manage",
"create_inventory_warehouse":"inventory.warehouses.manage",
"preview_update_inventory_warehouse":"inventory.warehouses.manage",
"update_inventory_warehouse":"inventory.warehouses.manage",
"preview_inactivate_inventory_warehouse":"inventory.warehouses.manage",
"inactivate_inventory_warehouse":"inventory.warehouses.manage",
"preview_configure_inventory_stock":"inventory.stock.manage",
"configure_inventory_stock":"inventory.stock.manage",
"preview_receive_inventory_stock":"inventory.movements.create",
"receive_inventory_stock":"inventory.movements.create",
"preview_issue_inventory_stock":"inventory.movements.create",
"issue_inventory_stock":"inventory.movements.create",
"preview_transfer_inventory_stock":"inventory.movements.create",
"transfer_inventory_stock":"inventory.movements.create",
"preview_count_inventory_stock":"inventory.movements.create",
"count_inventory_stock":"inventory.movements.create",
"preview_cancel_inventory_movement":"inventory.movements.cancel",
"cancel_inventory_movement":"inventory.movements.cancel",
stage_chatgpt_file:"files.attach",get_my_attendance_calendar:"hr.attendance:read",get_my_attendance_events:"hr.attendance:read",get_hr_attendance_events:"hr.control.read",assign_hr_rest_days:"hr.attendance.correct",preview_assign_hr_rest_days:"hr.attendance.correct",stage_operational_file:"files.attach",list_operational_files:"files.read",get_operational_file:"files.read",export_hr_payroll:"files.read",export_commerce_report:"files.read",attach_inventory_product_image:"files.attach",preview_attach_inventory_product_image:"files.attach",attach_sale_payment_evidence:"files.attach",preview_attach_sale_payment_evidence:"files.attach",attach_sales_contract_file:"files.attach",preview_attach_sales_contract_file:"files.attach",attach_supplier_invoice_file:"files.attach",preview_attach_supplier_invoice_file:"files.attach",attach_pos_receipt_file:"files.attach",preview_attach_pos_receipt_file:"files.attach",preview_attach_employee_document:"files.attach",attach_employee_document:"files.attach",preview_attach_announcement_file:"files.attach",attach_announcement_file:"files.attach",preview_add_hr_asset_photo:"files.attach",add_hr_asset_photo:"files.attach",preview_attach_hr_record_file:"files.attach",attach_hr_record_file:"files.attach",preview_attach_my_hr_permission_file:"files.attach",attach_my_hr_permission_file:"files.attach",preview_attach_hr_permission_file:"files.attach",attach_hr_permission_file:"files.attach",preview_attach_task_evidence:"files.attach",attach_task_evidence:"files.attach",get_hr_kpis:"hr.kpis:read",
 list_hr_payroll_runs:"hr.payroll.read",
 get_hr_payroll_run:"hr.payroll.read",
 prepare_hr_payroll:"hr.payroll.prepare",preview_prepare_hr_payroll:"hr.payroll.prepare",
 adjust_hr_payroll_line:"hr.payroll.prepare",preview_adjust_hr_payroll_line:"hr.payroll.prepare",
 recalculate_hr_payroll:"hr.payroll.prepare",preview_recalculate_hr_payroll:"hr.payroll.prepare",
 approve_hr_payroll:"hr.payroll.approve",preview_approve_hr_payroll:"hr.payroll.approve",
 register_hr_payroll_paid:"hr.payroll.pay",preview_register_hr_payroll_paid:"hr.payroll.pay",
 cancel_hr_payroll:"hr.payroll.prepare",preview_cancel_hr_payroll:"hr.payroll.prepare",
  list_projects:"projects.read",
  get_project:"projects.read",
  list_processes:"processes.read",
  get_process:"processes.read",
  list_process_collaborators:"processes.read",
  list_process_runs:"processes.read",
  get_process_run:"processes.read",
  get_process_version:"processes.read",
  create_project:"projects.manage",preview_create_project:"projects.manage",
  update_project:"projects.manage",preview_update_project:"projects.manage",
  complete_project:"projects.manage",preview_complete_project:"projects.manage",
  cancel_project:"projects.manage",preview_cancel_project:"projects.manage",
  archive_project:"projects.manage",preview_archive_project:"projects.manage",
  create_process:"processes.manage",preview_create_process:"processes.manage",
  update_process:"processes.manage",preview_update_process:"processes.manage",
  pause_process:"processes.manage",preview_pause_process:"processes.manage",
  archive_process:"processes.manage",preview_archive_process:"processes.manage",
  generate_process_tasks:"processes.run",preview_generate_process_tasks:"processes.run",
  create_process_run:"processes.run",preview_create_process_run:"processes.run",
list_hr_schedule_candidates:"hr.control.read",
list_hr_schedules:"hr.control.read",
get_hr_schedule:"hr.control.read",
list_hr_locations:"hr.control.read",
get_hr_location:"hr.control.read",
get_hr_attendance_calendar:"hr.control.read",
create_hr_schedule:"hr.control.manage",
preview_create_hr_schedule:"hr.control.manage",
update_hr_schedule:"hr.control.manage",
preview_update_hr_schedule:"hr.control.manage",
assign_hr_schedule:"hr.control.manage",
preview_assign_hr_schedule:"hr.control.manage",
create_hr_location:"hr.control.manage",
preview_create_hr_location:"hr.control.manage",
update_hr_location:"hr.control.manage",
preview_update_hr_location:"hr.control.manage",
set_hr_allowed_locations:"hr.control.manage",
preview_set_hr_allowed_locations:"hr.control.manage",
assign_hr_work_site:"hr.control.manage",
preview_assign_hr_work_site:"hr.control.manage",
clear_hr_work_assignments:"hr.control.manage",
preview_clear_hr_work_assignments:"hr.control.manage",
correct_hr_attendance:"hr.attendance.correct",
preview_correct_hr_attendance:"hr.attendance.correct",
record_hr_attendance_event:"hr.attendance.correct",
preview_record_hr_attendance_event:"hr.attendance.correct",
get_process_task_kpis: "tasks.kpis:read", get_hr_asset_history:"hr.assets.read",get_announcement_receipts:"hr.announcements.receipts:read",
  list_hr_incentives:"hr.incentives.read",
  get_hr_incentive:"hr.incentives.read",
  create_hr_incentive:"hr.incentives.manage",preview_create_hr_incentive:"hr.incentives.manage",
  cancel_hr_incentive:"hr.incentives.manage",preview_cancel_hr_incentive:"hr.incentives.manage",
  list_my_hr_permissions:"hr.permissions.self:read",
  get_my_hr_permission:"hr.permissions.self:read",
  list_hr_permissions:"hr.permissions.read",
  get_hr_permission:"hr.permissions.read",
  create_my_hr_permission:"hr.permissions.request",preview_create_my_hr_permission:"hr.permissions.request",
  withdraw_my_hr_permission:"hr.permissions.request",preview_withdraw_my_hr_permission:"hr.permissions.request",
  approve_hr_permission:"hr.permissions.review",preview_approve_hr_permission:"hr.permissions.review",
  reject_hr_permission:"hr.permissions.review",preview_reject_hr_permission:"hr.permissions.review",
  update_task_dependency:"tasks.operate",preview_update_task_dependency:"tasks.operate",
  terminate_employee: "hr.people.terminate", preview_terminate_employee: "hr.people.terminate",
  update_hr_asset: "hr.assets.manage", preview_update_hr_asset: "hr.assets.manage",
  reassign_hr_asset: "hr.assets.manage", preview_reassign_hr_asset: "hr.assets.manage",
  change_hr_asset_status: "hr.assets.manage", preview_change_hr_asset_status: "hr.assets.manage",
  update_announcement: "hr.announcements.manage", preview_update_announcement: "hr.announcements.manage",
  mark_announcement_read: "hr.announcements.respond", preview_mark_announcement_read: "hr.announcements.respond",
  mark_announcement_unread: "hr.announcements.respond", preview_mark_announcement_unread: "hr.announcements.respond",
  create_hr_record: "hr.records.manage", preview_create_hr_record: "hr.records.manage",
  update_hr_record: "hr.records.manage", preview_update_hr_record: "hr.records.manage",
  list_hr_records: "hr.records.read", get_hr_record_detail: "hr.records.read",
  list_hr_organization: "hr.people.manage",
  list_announcement_audience: "hr.announcements.manage",
  get_employee_file: "hr.people.details:read", list_hr_assets: "hr.assets.read", get_hr_asset_detail: "hr.assets.read",
  list_announcements: "hr.announcements.read", get_announcement_detail: "hr.announcements.read",
  create_employee: "hr.people.manage", preview_create_employee: "hr.people.manage",
  update_employee: "hr.people.manage", preview_update_employee: "hr.people.manage",
  import_employees: "hr.people.import", preview_import_employees: "hr.people.import",
  inactivate_employee: "hr.people.manage", preview_inactivate_employee: "hr.people.manage",
  create_hr_asset: "hr.assets.manage", preview_create_hr_asset: "hr.assets.manage",
  create_announcement: "hr.announcements.manage", preview_create_announcement: "hr.announcements.manage",
  get_system_guide: "learning.read",
  get_learning_progress: "learning.read",
  get_next_learning_mission: "learning.read",
  preview_update_learning_progress: "learning.manage",
  update_learning_progress: "learning.manage",
  schedule_task: "tasks.operate", preview_schedule_task: "tasks.operate",
  add_task_follow_up: "tasks.operate", preview_add_task_follow_up: "tasks.operate",
  update_task_contribution: "tasks.operate", preview_update_task_contribution: "tasks.operate",
  share_task: "tasks.operate", preview_share_task: "tasks.operate",
  complete_task: "tasks.operate", preview_complete_task: "tasks.operate",
  audit_task: "tasks.audit", preview_audit_task: "tasks.audit",
  cancel_task: "tasks.operate", preview_cancel_task: "tasks.operate",
  list_task_organization: "tasks.read",
  get_customer_detail: "customers.read",
  list_opportunities: "opportunities.read",
  get_opportunity_detail: "opportunities.read",
  get_opportunity_pipeline: "opportunities.read",
  list_quotes: "quotes.read",
  get_quote_detail: "quotes.read",
  search_commercial_assignees: "commercial.references:read",
  create_customer: "customers.create",
  preview_create_customer: "customers.create",
  update_customer: "customers.update",
  preview_update_customer: "customers.update",
  create_opportunity: "opportunities.create",
  preview_create_opportunity: "opportunities.create",
  update_opportunity: "opportunities.update",
  preview_update_opportunity: "opportunities.update",
  create_quote: "quotes.create",
  preview_create_quote: "quotes.create",
  update_quote: "quotes.update",
  preview_update_quote: "quotes.update",

  get_sales_today: "sales.today:read", get_business_snapshot: "business.snapshot:read",
  get_attention_items: "business.snapshot:read", search_employees: "hr.people:read",
  get_employee_overview: "hr.people:read", get_attendance_exceptions: "hr.attendance:read",
  list_tasks: "tasks.read", get_task_detail: "tasks.read", get_sales_summary: "sales.read",
  list_sales: "sales.read", get_sale_detail: "sales.read", get_cash_status: "pos.read",
  search_products: "inventory.read", get_product_detail: "inventory.read", get_inventory_summary: "inventory.read",
  get_expense_summary: "expenses.read", list_expenses: "expenses.read", get_expense_detail: "expenses.read",
  get_funds_status: "petty_cash.read", get_receivables_status: "receivables.read",
  get_my_business_context: "business.context:read", list_units_and_businesses: "business.context:read",
  list_payment_accounts: "finance.references:read", list_funds: "petty_cash.read",
  search_customers: "customers.read", search_providers: "providers.read", list_warehouses: "warehouses.read",
  search_budget_lines: "budget_lines.read", search_accounting_accounts: "accounting_accounts.read",
  search_task_assignees: "tasks.delegate", preview_update_task: "tasks.update", update_task: "tasks.update",
  preview_create_task: "tasks.create", create_task: "tasks.create",
  preview_create_expense_draft: "expenses.create", create_expense_draft: "expenses.create",
  preview_register_fund_expense: "petty_cash.expense:create", register_fund_expense: "petty_cash.expense:create",
  preview_add_money_to_fund: "petty_cash.deposit:create", add_money_to_fund: "petty_cash.deposit:create"
};

export const supportedScopes = [...new Set([...Object.values(toolScopes), "tasks.organize", "openid", "email"])].sort();

export function bearerChallenge(metadataUrl: URL, error?: "invalid_token"): string {
  return `Bearer resource_metadata="${metadataUrl}", scope="${supportedScopes.join(" ")}"`
    + (error ? `, error="${error}", error_description="Reconnect your Indice account to continue"` : "");
}

export function configureTool(tool: RegisteredTool, name: string, allowedTools?: ReadonlySet<string>): void {
  const scope = toolScopes[indiceToolNameSchema.parse(name)];
  tool.update({ _meta: { ...tool._meta, securitySchemes: [{ type: "oauth2", scopes: [scope] }] } });
  if (allowedTools && !allowedTools.has(name)) tool.disable();
}

export function isRetryableRead(path: string, method: string): boolean {
  const pathname = path.split("?", 1)[0];
  if (method === "GET") return ["/api/v1/ai/access/verify", "/api/v1/ai/access/capabilities",
    "/api/v1/ai/tools/sales/today", "/api/v1/ai/tools/business/snapshot", "/api/v1/ai/tools/references/business-context"].includes(pathname!);
  if (method !== "POST") return false;
  if (["/api/v1/ai/tools/learning/guide", "/api/v1/ai/tools/learning/progress"].includes(pathname!)) return true;
  if (pathname === "/api/v1/ai/tools/kpis/get_hr_kpis") return true;
  if (pathname === "/api/v1/ai/tools/kpis/get_process_task_kpis") return true;
  if (pathname?.startsWith("/api/v1/ai/tools/process_workflows/")) {
    const name=indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/process_workflows/".length));
    return name.success && ["projects.read","processes.read"].includes(toolScopes[name.data]);
  }
  if(pathname?.startsWith("/api/v1/ai/tools/finance_workflows/"))return financeReadNames.some(name=>pathname===`/api/v1/ai/tools/finance_workflows/${name}`);
  if(pathname?.startsWith("/api/v1/ai/tools/files/")) return ["list_operational_files","get_operational_file","export_hr_payroll","export_commerce_report","export_finance_report"].some(name=>pathname===`/api/v1/ai/tools/files/${name}`);
  if (pathname?.startsWith("/api/v1/ai/tools/hr/")) {
    if (["/api/v1/ai/tools/hr/list_hr_organization", "/api/v1/ai/tools/hr/list_announcement_audience"].includes(pathname)) return true;
    const name = indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/hr/".length));
    return name.success && /(?:\.read|:read)$/.test(toolScopes[name.data]);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/query/")) {
    const name = indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/query/".length));
    return name.success && /(?:\.read|:read)$/.test(toolScopes[name.data]);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/sales_workflows/")) {
    const name=indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/sales_workflows/".length));
    return method === "POST" && name.success && ["list_commercial_sales","get_commercial_sale","list_sales_contracts","get_sales_contract","list_sales_follow_ups","get_sales_follow_up","list_commission_rules","get_commission_rule"].includes(name.data);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/terminal_workflows/")) {
    return terminalReadNames.some(name=>pathname===`/api/v1/ai/tools/terminal_workflows/${name}`);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/pos_operations/")) {
    return posOperationsReadNames.some(name=>pathname===`/api/v1/ai/tools/pos_operations/${name}`);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/commission_workflows/")) {
    return commissionReadNames.some(name=>pathname===`/api/v1/ai/tools/commission_workflows/${name}`);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/inventory_catalog_workflows/")) {
    return method === "POST" && inventoryCatalogReadNames.some(name=>pathname===`/api/v1/ai/tools/inventory_catalog_workflows/${name}`);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/procurement_workflows/")) {
    return method === "POST" && procurementReadNames.some(name=>pathname===`/api/v1/ai/tools/procurement_workflows/${name}`);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/pos_workflows/")) {
    const name=indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/pos_workflows/".length));
    return method === "POST" && name.success && ["list_pos_registers","get_pos_register","list_pos_shifts","get_pos_shift","get_my_pos_shift","get_pos_closing_summary","list_pos_tickets","get_pos_ticket","list_pos_cash_movements","list_pos_inventory_receipts","get_pos_return","recover_pos_checkout"].includes(name.data);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/inventory_workflows/")) {
    const name = indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/inventory_workflows/".length));
    return name.success && /(?:\.read|:read)$/.test(toolScopes[name.data]);
  }
  if (pathname?.startsWith("/api/v1/ai/tools/commercial/")) {
    const name = indiceToolNameSchema.safeParse(pathname.slice("/api/v1/ai/tools/commercial/".length));
    return name.success && /(?:\.read|:read)$/.test(toolScopes[name.data]);
  }
  return ["task-assignees", "task-organization", "organization", "payment-accounts", "funds", "customers", "providers", "warehouses", "budget-lines", "accounting-accounts"]
    .some(reference => pathname === `/api/v1/ai/tools/references/${reference}`);
}
