// Regional variants share their language copy, as in the other basic-module KPI workspaces.
const messages = {
  consolidated: ['Consolidado en','Consolidated in','Consolidé en','Consolidado em','통합 통화','汇总货币'],
  native: ['Compras en moneda original','Purchases in original currency','Achats en devise d’origine','Compras na moeda original','원래 통화 구매','采购原币金额'],
  partial: ['Conversión incompleta','Incomplete conversion','Conversion incomplète','Conversão incompleta','변환 미완료','换算不完整'],
  excluded: ['Registros excluidos','Excluded records','Enregistrements exclus','Registros excluídos','제외된 기록','已排除记录'],
  rate: ['Tipo de cambio diario','Daily exchange rate','Taux de change quotidien','Taxa de câmbio diária','일일 환율','每日汇率'],
  title: ['Indicadores de Caja chica','Petty cash indicators','Indicateurs de petite caisse','Indicadores de caixa pequeno','소액 현금 지표','备用金指标'],
  subtitle: ['Fondos, compras, comprobación y seguimiento de cortes.','Funds, purchases, authorization and statement follow-up.','Fonds, achats, validation et suivi des relevés.','Fundos, compras, comprovação e acompanhamento de fechamentos.','자금, 구매, 승인 및 명세 추적.','资金、采购、审核及结账跟进。'],
  overview: ['Resumen','Overview','Résumé','Resumo','요약','概览'],
  analysis: ['Análisis','Analysis','Analyse','Análise','분석','分析'],
  units: ['Por unidad','By unit','Par unité','Por unidade','사업부별','按部门'],
  details: ['Cortes y comprobantes','Statements and receipts','Relevés et justificatifs','Fechamentos e comprovantes','명세 및 증빙','结账与凭证'],
  views: ['Vistas de indicadores','Indicator views','Vues des indicateurs','Vistas dos indicadores','지표 보기','指标视图'],
  refresh: ['Actualizar datos','Refresh data','Actualiser','Atualizar dados','새로 고침','刷新数据'],
  print: ['Imprimir reporte','Print report','Imprimer le rapport','Imprimir relatório','보고서 인쇄','打印报告'],
  classification: ['Origen de los fondos','Fund ownership','Propriété des fonds','Origem dos fundos','자금 소유권','资金归属'],
  internal: ['Dinero de la empresa','Company funds','Fonds de l’entreprise','Dinheiro da empresa','회사 자금','公司资金'],
  external: ['Dinero de terceros','Third-party funds','Fonds de tiers','Dinheiro de terceiros','제3자 자금','第三方资金'],
  context: ['El periodo corresponde al corte. Los saldos son actuales; no representan un arqueo físico. La unidad y el negocio son los actuales del fondo.','Period refers to the statement. Balances are current, not physical cash counts. Unit and business use the fund’s current assignment.','La période est celle du relevé. Les soldes sont actuels, sans comptage physique. Unité et activité sont celles du fonds actuel.','O período corresponde ao fechamento. Saldos atuais, sem contagem física. Unidade e negócio são os atuais do fundo.','기간은 명세 기준입니다. 잔액은 현재 장부 잔액이며 실사 금액이 아닙니다. 사업부와 사업장은 현재 배정 기준입니다.','期间以结账为准。余额为当前账面余额，并非现金盘点金额。部门和业务按资金当前归属。'],
  externalHelp: ['Dinero en custodia: sus compras validadas no son gastos ni liquidez de la empresa.','Custody funds: validated purchases are neither company expenses nor company liquidity.','Fonds en garde : les achats validés ne sont ni des dépenses ni des liquidités de l’entreprise.','Fundos em custódia: compras validadas não são despesas nem liquidez da empresa.','수탁 자금의 승인된 구매는 회사 비용이나 유동성이 아닙니다.','代管资金的已审核采购不属于公司费用或流动资金。'],
  unavailable: ['No disponible','Unavailable','Indisponible','Indisponível','사용 불가','不可用'],
  loading: ['Cargando datos…','Loading data…','Chargement…','Carregando dados…','불러오는 중…','正在加载…'],
  sourceError: ['No se pudieron cargar los datos de Caja chica. Usa Actualizar datos para reintentar.','Petty cash data could not be loaded. Use Refresh data to retry.','Impossible de charger les données. Utilisez Actualiser pour réessayer.','Não foi possível carregar os dados. Use Atualizar dados para tentar novamente.','소액 현금 데이터를 불러오지 못했습니다. 새로 고침으로 다시 시도하세요.','无法加载备用金数据，请刷新重试。'],
  moneyError: ['Algunos importes no están disponibles. No se muestran como cero. Actualiza para reintentar.','Some amounts are unavailable and are not shown as zero. Refresh to retry.','Certains montants sont indisponibles, sans être remplacés par zéro. Actualisez pour réessayer.','Alguns valores estão indisponíveis e não são exibidos como zero. Atualize para tentar novamente.','일부 금액을 표시할 수 없어 0으로 대체하지 않았습니다. 새로 고침하세요.','部分金额不可用，未以零代替。请刷新重试。'],
  empty: ['No hay registros con estos filtros.','No records match these filters.','Aucun enregistrement pour ces filtres.','Nenhum registro com estes filtros.','필터에 해당하는 기록이 없습니다.','筛选条件下没有记录。'],
  updated: ['Actualizado','Updated','Actualisé','Atualizado','업데이트','更新时间'],
  funded: ['Fondos entregados','Funds delivered','Fonds versés','Fundos entregues','지급 자금','已交付资金'],
  fundedHelp: ['Asignaciones y depósitos adicionales de los cortes seleccionados; excluye saldos arrastrados.','Allocations and additional deposits in selected statements; excludes carried balances.','Dotations et dépôts supplémentaires des relevés sélectionnés; hors soldes reportés.','Aportes e depósitos adicionais dos fechamentos selecionados; exclui saldos transferidos.','선택한 명세의 배정 및 추가 입금액이며 이월 잔액은 제외합니다.','所选结账的拨款和追加存款，不含结转余额。'],
  captured: ['Compras capturadas','Captured purchases','Achats saisis','Compras registradas','등록 구매','已登记采购'],
  capturedHelp: ['Importe de compras vigentes, incluidas las pendientes; excluye rechazadas y anuladas.','Valid purchases including pending receipts; excludes rejected and reversed purchases.','Achats valides, y compris en attente; hors achats rejetés ou annulés.','Compras vigentes, incluindo pendentes; exclui rejeitadas e estornadas.','대기 중인 구매를 포함하며 거절 및 취소 구매는 제외합니다.','包含待审核的有效采购，不含已拒绝或冲销采购。'],
  authorized: ['Salidas autorizadas','Authorized outflows','Sorties validées','Saídas autorizadas','승인된 지출','已授权支出'],
  authorizedHelp: ['Compras contabilizadas para la empresa o validadas para terceros, según el origen del corte.','Company purchases posted as expenses or third-party purchases validated, by statement ownership.','Achats comptabilisés pour l’entreprise ou validés pour des tiers, selon le relevé.','Compras contabilizadas para a empresa ou validadas para terceiros, conforme o fechamento.','명세 소유권에 따라 회사 비용으로 처리되거나 제3자용으로 승인된 구매입니다.','根据结账资金归属，统计已记为公司费用或已审核的第三方采购。'],
  pending: ['Por autorizar','Awaiting authorization','À valider','A autorizar','승인 대기','待授权'],
  pendingHelp: ['Compras vigentes que todavía no completan su autorización. Tener un archivo no equivale a estar autorizado.','Valid purchases awaiting authorization. Having an attachment does not mean authorized.','Achats valides en attente de validation. Un fichier joint ne vaut pas validation.','Compras vigentes aguardando autorização. Ter anexo não equivale a autorização.','승인이 완료되지 않은 구매입니다. 첨부 파일만으로 승인되지는 않습니다.','尚未完成授权的有效采购。有附件不等于已授权。'],
  balance: ['Saldo registrado actual','Current recorded balance','Solde actuel enregistré','Saldo atual registrado','현재 장부 잔액','当前账面余额'],
  balanceHelp: ['Fondos activos del alcance que mantienen este origen hoy. Conserva negativos; no es presupuesto disponible.','Scoped active funds with this ownership today. Keeps negative balances; not available budget.','Fonds actifs du périmètre ayant cette propriété aujourd’hui. Soldes négatifs conservés; pas un budget disponible.','Fundos ativos do escopo com esta origem hoje. Preserva negativos; não é orçamento disponível.','현재 이 소유권에 속한 범위 내 활성 자금입니다. 음수 잔액을 유지하며 가용 예산이 아닙니다.','当前归属此类型的范围内活跃资金，保留负值，并非可用预算。'],
  shortage: ['Faltantes registrados','Recorded shortages','Manquants enregistrés','Faltas registradas','기록된 부족액','已记录短缺'],
  shortageHelp: ['Histórico de faltantes del corte, incluidos los resueltos. No equivale a deuda pendiente.','Historical statement shortages, including resolved amounts. Not outstanding debt.','Manquants historiques du relevé, y compris résolus. Ce n’est pas une dette à régler.','Histórico de faltas do fechamento, incluindo resolvidas. Não equivale a dívida pendente.','해결된 금액을 포함한 과거 부족액이며 미결 채무가 아닙니다.','包含已处理金额的结账历史短缺，不等于未偿债务。'],
  evidence: ['Compras con evidencia','Purchases with evidence','Achats avec justificatif','Compras com comprovante','증빙 있는 구매','附凭证采购'],
  evidenceHelp: ['Compras vigentes con al menos un adjunto / compras vigentes. La autorización sin archivo se conserva.','Valid purchases with an attachment / valid purchases. Authorization without a file remains valid.','Achats valides avec pièce jointe / achats valides. Une validation sans fichier est conservée.','Compras vigentes com anexo / compras vigentes. Autorização sem arquivo é preservada.','증빙 있는 유효 구매 / 전체 유효 구매. 파일 없이 승인된 상태는 유지됩니다.','至少有一个附件的有效采购 / 全部有效采购。无附件授权保持有效。'],
  open: ['Cortes sin cerrar','Statements still open','Relevés non clôturés','Fechamentos em aberto','미마감 명세','未关闭结账'],
  openHelp: ['Incluye cortes comprobados aún no cerrados. No significa que todos estén vencidos.','Includes reconciled statements not yet closed. Not all are overdue.','Inclut les relevés rapprochés non clôturés. Ils ne sont pas tous en retard.','Inclui fechamentos comprovados ainda não encerrados. Nem todos estão vencidos.','대사가 끝났지만 마감되지 않은 명세를 포함합니다. 모두 기한 초과인 것은 아닙니다.','含已核对但尚未关闭的结账，不表示全部已逾期。'],
  purchases: ['compras','purchases','achats','compras','구매','笔采购'],
  statements: ['Cortes','Statements','Relevés','Fechamentos','명세','结账'],
  funds: ['Fondos','Funds','Fonds','Fundos','자금','资金'],
  noSample: ['Sin compras para medir','No purchases to measure','Aucun achat à mesurer','Sem compras para medir','측정할 구매 없음','没有可统计采购'],
  viewDetail: ['Ver detalle','View detail','Voir le détail','Ver detalhe','상세 보기','查看明细'],
  composition: ['Avance de autorización','Authorization progress','Avancement des validations','Progresso de autorização','승인 진행률','授权进度'],
  compositionHelp: ['Autorizado y pendiente componen las compras vigentes. La proporción se mide por importe.','Authorized and pending make up valid purchases. Share is measured by amount.','Validés et en attente composent les achats valides. Part calculée en montant.','Autorizado e pendente compõem as compras vigentes. Proporção medida por valor.','승인 및 대기 금액이 유효 구매를 구성합니다. 비율은 금액 기준입니다.','已授权和待授权组成有效采购，比例按金额计算。'],
  trend: ['Evolución por corte','Statement trend','Évolution par relevé','Evolução por fechamento','명세별 추이','结账趋势'],
  trendHelp: ['Todos los periodos seleccionados; mismo alcance para compras y autorizaciones.','Every selected period; same scope for purchases and authorizations.','Toutes les périodes sélectionnées; même périmètre pour achats et validations.','Todos os períodos selecionados; mesmo escopo para compras e autorizações.','선택한 모든 기간의 구매와 승인을 같은 범위로 표시합니다.','所有所选期间，采购与授权使用相同范围。'],
  unitHelp: ['Comparación en la misma divisa. Un mayor importe no significa peor desempeño. Selecciona una unidad para filtrar.','Comparison in the same currency. Higher amounts do not mean worse performance. Select a unit to filter.','Comparaison dans la même devise. Un montant élevé ne signifie pas une moins bonne performance. Sélectionnez une unité.','Comparação na mesma moeda. Um valor maior não significa pior desempenho. Selecione uma unidade para filtrar.','같은 통화로 비교합니다. 금액이 크다고 성과가 나쁜 것은 아닙니다. 사업부를 선택하여 필터링하세요.','按相同货币比较。金额高不表示表现差，选择部门以筛选。'],
  responsible: ['Responsable','Responsible person','Responsable','Responsável','담당자','负责人'],
  byFund: ['Distribución por fondo','Distribution by fund','Répartition par fonds','Distribuição por fundo','자금별 분포','按资金分布'],
  byResponsible: ['Seguimiento por responsable','Follow-up by responsible person','Suivi par responsable','Acompanhamento por responsável','담당자별 추적','按负责人跟进'],
  historicalResponsible: ['Responsable registrado en el corte; importes comparables, sin calificaciones personales.','Responsible person recorded on the statement; comparable amounts, no personal ratings.','Responsable enregistré sur le relevé; montants comparables, sans notation personnelle.','Responsável registrado no fechamento; valores comparáveis, sem notas pessoais.','명세에 기록된 담당자별 비교 금액이며 개인 평가가 아닙니다.','按结账记录的负责人显示可比金额，不进行个人评分。'],
  attention: ['Seguimiento operativo','Operational follow-up','Suivi opérationnel','Acompanhamento operacional','운영 추적','运营跟进'],
  negative: ['Fondos con saldo negativo','Funds with negative balances','Fonds à solde négatif','Fundos com saldo negativo','음수 잔액 자금','负余额资金'],
  missing: ['Compras sin adjunto','Purchases without attachment','Achats sans pièce jointe','Compras sem anexo','첨부 없는 구매','无附件采购'],
  evidenceNote: ['La falta de adjunto requiere revisión; no revoca una autorización ni prueba un faltante de dinero.','Missing attachments call for review; they neither revoke authorization nor prove missing cash.','Une pièce manquante appelle une vérification; elle n’annule pas la validation et ne prouve pas un manque de fonds.','A falta de anexo exige revisão; não revoga autorização nem prova falta de dinheiro.','첨부 누락은 검토 대상이며 승인 취소나 현금 부족을 의미하지 않습니다.','缺少附件需要复核，但不会撤销授权，也不证明现金短缺。'],
  unlinked: ['Movimientos sin corte excluidos de este análisis','Unlinked movements excluded from this analysis','Mouvements sans relevé exclus de cette analyse','Movimentos sem fechamento excluídos desta análise','분석에서 제외된 미연결 거래','本分析排除的未关联结账交易'],
  current: ['Actual','Current','Actuel','Atual','현재','当前'],
  period: ['Periodo del corte','Statement period','Période du relevé','Período do fechamento','명세 기간','结账期间'],
  status: ['Estado del corte','Statement status','Statut du relevé','Status do fechamento','명세 상태','结账状态'],
  unit: ['Unidad','Unit','Unité','Unidade','사업부','部门'],
  business: ['Negocio','Business','Activité','Negócio','사업장','业务'],
  search: ['Buscar','Search','Rechercher','Buscar','검색','搜索'],
  searchHelp: ['Fondo, folio, responsable o propietario','Fund, reference, responsible person or owner','Fonds, référence, responsable ou propriétaire','Fundo, referência, responsável ou proprietário','자금, 번호, 담당자 또는 소유자','资金、编号、负责人或所有者'],
  all: ['Todos','All','Tous','Todos','전체','全部'],
  amount: ['Importe','Amount','Montant','Valor','금액','金额'],
  date: ['Fecha','Date','Date','Data','날짜','日期'],
  receipt: ['Compra / comprobante','Purchase / receipt','Achat / justificatif','Compra / comprovante','구매 / 증빙','采购 / 凭证'],
  receiptStatus: ['Estado','Status','Statut','Status','상태','状态'],
  receiptHelp: ['Importes en su moneda original. Rechazadas y anuladas aparecen para trazabilidad, sin sumar a los indicadores.','Amounts in original currency. Rejected and reversed receipts remain visible for traceability, excluded from indicators.','Montants en devise d’origine. Rejets et annulations restent visibles pour la traçabilité, hors indicateurs.','Valores na moeda original. Rejeitadas e estornadas permanecem para rastreabilidade, fora dos indicadores.','원래 통화 금액입니다. 거절 및 취소 증빙은 추적을 위해 표시되며 지표에서 제외됩니다.','金额保留原币。已拒绝和冲销凭证用于追溯，不计入指标。'],
  attachments: ['Adjuntos','Attachments','Pièces jointes','Anexos','첨부','附件'],
  movements: ['Movimientos de los cortes','Statement movements','Mouvements des relevés','Movimentos dos fechamentos','명세 거래','结账交易'],
  movementType: ['Tipo de movimiento','Movement type','Type de mouvement','Tipo de movimento','거래 유형','交易类型'],
  recordedClosing: ['Saldo registrado del corte','Recorded statement balance','Solde enregistré du relevé','Saldo registrado do fechamento','명세 장부 잔액','结账账面余额'],
  statementHelp: ['Saldos e importes históricos en moneda original; no sumes monedas diferentes.','Historical balances and amounts in original currency; do not add different currencies.','Soldes et montants historiques en devise d’origine; ne pas additionner des devises différentes.','Saldos e valores históricos na moeda original; não some moedas diferentes.','원래 통화의 과거 잔액 및 금액이며 서로 다른 통화를 합산하지 마세요.','历史余额及金额保留原币，请勿将不同币种直接相加。'],
  fullReport: ['Reporte completo del alcance filtrado','Complete filtered-scope report','Rapport complet du périmètre filtré','Relatório completo do escopo filtrado','필터 범위 전체 보고서','完整筛选范围报告'],
  reportError: ['No se pudo preparar el reporte. Inténtalo de nuevo.','The report could not be prepared. Please retry.','Impossible de préparer le rapport. Réessayez.','Não foi possível preparar o relatório. Tente novamente.','보고서를 준비하지 못했습니다. 다시 시도하세요.','无法生成报告，请重试。'],
} as const;
export function getPettyCashKpiCopy(locale: string) {
  const index = Math.max(0, ['es', 'en', 'fr', 'pt', 'ko', 'zh'].indexOf(locale.toLowerCase().split('-')[0]));
  return Object.fromEntries(Object.entries(messages).map(([key, values]) => [key, values[index]])) as { [K in keyof typeof messages]: string };
}
export type PettyCashKpiCopy = ReturnType<typeof getPettyCashKpiCopy>;
