// Order: Spanish, English, French, Portuguese, Korean, Chinese. Regional variants share vocabulary.
const messages = {
  title: ['Operación comercial','Commercial operations','Opérations commerciales','Operação comercial','영업 운영','商业运营'],
  subtitle: ['Revisa clientes y coordina el siguiente paso por país.','Review customers and coordinate the next step by country.','Suivez les clients et la prochaine étape par pays.','Revise clientes e coordene a próxima etapa por país.','국가별 고객과 다음 단계를 확인하세요.','按国家查看客户并协调下一步。'],
  pending: ['Pendientes','Needs attention','À traiter','Pendências','처리 대기','待处理'],
  MX: ['México','Mexico','Mexique','México','멕시코','墨西哥'],
  CA: ['Canadá','Canada','Canada','Canadá','캐나다','加拿大'],
  refresh: ['Actualizar','Refresh','Actualiser','Atualizar','새로고침','刷新'],
  search: ['Buscar cliente','Find customer','Chercher un client','Buscar cliente','고객 검색','搜索客户'],
  filters: ['Buscar y filtrar','Search and filter','Recherche et filtres','Busca e filtros','검색 및 필터','搜索和筛选'],
  all: ['Todos','All','Tous','Todos','전체','全部'],
  attention: ['Situación','Situation','Situation','Situação','상황','情况'],
  billing: ['Revisar acceso y cobro','Review access and billing','Vérifier accès et facturation','Revisar acesso e cobrança','접근 및 청구 확인','检查访问和账单'],
  trial: ['Revisar vencimiento de prueba','Review trial expiry','Vérifier la fin de l’essai','Revisar vencimento do teste','체험 종료 확인','检查试用到期'],
  country: ['País sin confirmar','Country unconfirmed','Pays non confirmé','País não confirmado','국가 미확인','国家未确认'],
  review: ['Consultar cuenta','Review account','Consulter le compte','Consultar conta','계정 확인','查看账户'],
  distributor: ['Distribuidor asignado','Assigned distributor','Distributeur attribué','Distribuidor atribuído','배정된 유통업체','指定经销商'],
  assigned: ['Con distribuidor','With distributor','Avec distributeur','Com distribuidor','유통업체 있음','有经销商'],
  unassigned: ['Sin distribuidor','No distributor','Sans distributeur','Sem distribuidor','유통업체 없음','无经销商'],
  deadline: ['Vencimiento de prueba','Trial expiry','Fin de l’essai','Vencimento do teste','체험 종료일','试用到期'],
  overdue: ['Fecha vencida','Past due date','Date dépassée','Data vencida','기한 경과','已过期'],
  week: ['Próximos 7 días','Next 7 days','Prochains 7 jours','Próximos 7 dias','향후 7일','未来7天'],
  undated: ['Sin fecha de prueba vigente','No current trial date','Aucune date d’essai en cours','Sem data de teste vigente','현재 체험 날짜 없음','无当前试用日期'],
  company: ['Cliente','Customer','Client','Cliente','고객','客户'],
  actions: ['Acciones','Actions','Actions','Ações','작업','操作'],
  open: ['Abrir seguimiento','Open follow-up','Ouvrir le suivi','Abrir acompanhamento','후속 조치 열기','打开跟进'],
  loaded: ['Clientes cargados','Loaded customers','Clients chargés','Clientes carregados','불러온 고객','已加载客户'],
  matching: ['Coincidencias en lo cargado','Matches in loaded records','Résultats parmi les données chargées','Resultados nos registros carregados','불러온 항목 중 일치','已加载记录中的匹配项'],
  coverage: ['Los filtros de país y situación se aplican a los clientes cargados. Carga más para ampliar la búsqueda.','Country and situation filters apply to loaded customers. Load more to expand the search.','Les filtres portent sur les clients chargés. Chargez-en davantage pour élargir la recherche.','Os filtros usam os clientes carregados. Carregue mais para ampliar a busca.','필터는 불러온 고객에 적용됩니다. 더 불러와 검색 범위를 넓히세요.','筛选仅适用于已加载客户。加载更多以扩大搜索范围。'],
  more: ['Cargar más clientes','Load more customers','Charger plus de clients','Carregar mais clientes','고객 더 불러오기','加载更多客户'],
  loading: ['Cargando clientes…','Loading customers…','Chargement des clients…','Carregando clientes…','고객 불러오는 중…','正在加载客户…'],
  error: ['No fue posible cargar la información. Reintenta.','Could not load the information. Retry.','Impossible de charger les données. Réessayez.','Não foi possível carregar os dados. Tente novamente.','정보를 불러오지 못했습니다. 다시 시도하세요.','无法加载信息，请重试。'],
  denied: ['Tu acceso a esta información ya no está disponible.','Your access to this information is no longer available.','Votre accès à ces données n’est plus disponible.','Seu acesso a estes dados não está mais disponível.','이 정보에 대한 접근 권한이 없습니다.','你已无权访问此信息。'],
  empty: ['No hay coincidencias en los clientes cargados.','No matches in loaded customers.','Aucun résultat parmi les clients chargés.','Nenhum resultado nos clientes carregados.','불러온 고객 중 일치하는 항목이 없습니다.','已加载客户中没有匹配项。'],
  clear: ['Limpiar filtros','Clear filters','Effacer les filtres','Limpar filtros','필터 초기화','清除筛选'],
  availability: ['Alcance de esta bandeja','Inbox coverage','Périmètre de cette liste','Alcance desta lista','목록 범위','列表范围'],
  pendingConnection: ['Aquí se muestran cuentas existentes. Las solicitudes de la web y el registro de etapas, responsables y próximas acciones comerciales aún no están disponibles en esta sección.','This view shows existing accounts. Website requests and saved commercial stages, owners and next actions are not available here yet.','Cette vue présente les comptes existants. Les demandes web et le suivi commercial enregistré ne sont pas encore disponibles ici.','Esta tela mostra contas existentes. Solicitações web e etapas, responsáveis e próximas ações comerciais ainda não estão disponíveis aqui.','기존 계정만 표시됩니다. 웹 요청 및 영업 단계, 담당자, 다음 작업 기록은 아직 제공되지 않습니다.','此处显示现有账户，尚不支持网站申请及销售阶段、负责人和下一步行动的保存。'],
  guide: ['Recorrido de referencia','Reference journey','Parcours de référence','Percurso de referência','참고 절차','参考流程'],
  guideHelp: ['Estas etapas describen el recorrido; no indican el avance guardado de una cuenta ni cambian su contrato.','These steps describe the journey; they do not indicate saved account progress or change its contract.','Ces étapes décrivent le parcours, sans indiquer un avancement enregistré ni modifier le contrat.','Estas etapas descrevem o percurso; não indicam progresso salvo nem alteram o contrato.','참고 절차이며 저장된 진행 상태나 계약 변경을 나타내지 않습니다.','这些步骤仅说明流程，不代表已保存进度，也不改变合同。'],
  received: ['Solicitud recibida','Request received','Demande reçue','Solicitação recebida','요청 접수','收到申请'],
  diagnosis: ['Contacto y diagnóstico','Contact and diagnosis','Contact et diagnostic','Contato e diagnóstico','연락 및 진단','联系与诊断'],
  guidedTrial: ['Prueba guiada','Guided trial','Essai accompagné','Teste guiado','안내형 체험','引导试用'],
  proposal: ['Propuesta comercial','Commercial proposal','Proposition commerciale','Proposta comercial','상업 제안','商业提案'],
  implementation: ['Implementación','Implementation','Mise en œuvre','Implementação','구축','实施'],
  followUp: ['Seguimiento mensual','Monthly follow-up','Suivi mensuel','Acompanhamento mensal','월간 후속 조치','每月跟进'],
  accessPending: ['Acceso pendiente','Access pending','Accès en attente','Acesso pendente','접근 대기','等待开通'],
  selfTrial: ['Prueba autogestionada','Self-service trial','Essai autonome','Teste autogerenciado','셀프서비스 체험','自助试用'],
  subscription: ['Contratación pendiente','Subscription pending','Souscription en attente','Contratação pendente','구독 대기','等待订阅'],
  operating: ['Cuenta operando','Account operating','Compte en activité','Conta operando','계정 운영 중','账户运营'],
  support: ['Seguimiento y soporte','Follow-up and support','Suivi et assistance','Acompanhamento e suporte','후속 조치 및 지원','跟进与支持'],
  mxHelp: ['Venta con diagnóstico, implementación y acompañamiento según lo contratado.','Sales with diagnosis, implementation and follow-up as contracted.','Vente avec diagnostic, mise en œuvre et suivi selon le contrat.','Venda com diagnóstico, implementação e acompanhamento contratado.','계약에 따른 진단, 구축 및 후속 지원.','按合同提供诊断、实施和跟进。'],
  caHelp: ['Autoservicio con soporte. La consultoría y la implementación no se presuponen incluidas.','Self-service with support. Consulting and implementation are not presumed included.','Libre-service avec assistance, sans présumer une consultation ou une mise en œuvre incluse.','Autosserviço com suporte. Consultoria e implementação não são presumidas como incluídas.','지원이 제공되는 셀프서비스입니다. 컨설팅 및 구축 포함을 가정하지 않습니다.','提供支持的自助服务，不默认包含咨询和实施。'],
  countryHelp: ['Agrupado por país registrado. La moneda y el idioma no determinan el servicio contratado.','Grouped by recorded country. Currency and language do not determine contracted services.','Regroupé par pays enregistré. Devise et langue ne déterminent pas les services souscrits.','Agrupado pelo país registrado. Moeda e idioma não determinam o serviço contratado.','등록 국가별로 분류합니다. 통화와 언어는 계약 서비스를 결정하지 않습니다.','按登记国家分组，货币和语言不决定合同服务。'],
  details: ['Ficha de seguimiento','Follow-up record','Fiche de suivi','Ficha de acompanhamento','후속 조치 기록','跟进记录'],
  summary: ['Resumen','Summary','Résumé','Resumo','요약','概览'],
  history: ['Historial','History','Historique','Histórico','기록','历史'],
  account: ['Abrir cliente','Open customer','Ouvrir le client','Abrir cliente','고객 열기','打开客户'],
  users: ['Usuarios','Users','Utilisateurs','Usuários','사용자','用户'],
  invoices: ['Facturación','Billing','Facturation','Faturamento','청구','账单'],
  care: ['Centro de atención','Customer care','Centre de service','Central de atendimento','고객 지원','客户服务'],
  consulting: ['Consultorías','Consulting','Consultations','Consultorias','컨설팅','咨询'],
  close: ['Cerrar','Close','Fermer','Fechar','닫기','关闭'],
  contact: ['Contacto propietario','Owner contact','Contact propriétaire','Contato do proprietário','소유자 연락처','所有者联系信息'],
  plan: ['Productos contratados','Contracted products','Produits souscrits','Produtos contratados','계약 상품','已订购产品'],
  version: ['Versión de contrato','Contract version','Version du contrat','Versão do contrato','계약 버전','合同版本'],
  currency: ['Moneda contractual','Contract currency','Devise du contrat','Moeda contratual','계약 통화','合同货币'],
  registeredCountry: ['País registrado','Recorded country','Pays enregistré','País registrado','등록 국가','登记国家'],
  missing: ['No disponible','Not available','Indisponible','Não disponível','사용 불가','不可用'],
  suggested: ['Acción sugerida','Suggested action','Action suggérée','Ação sugerida','권장 작업','建议行动'],
  nextActionHelp: ['Sugerencia basada en el estado de la cuenta; no es una tarea asignada.','Suggestion based on account status; not an assigned task.','Suggestion basée sur le compte, pas une tâche attribuée.','Sugestão baseada na conta, não uma tarefa atribuída.','계정 상태에 따른 제안이며 배정된 작업이 아닙니다.','基于账户状态的建议，并非已分配任务。'],
  source: ['Información de la cuenta','Account information','Informations du compte','Informações da conta','계정 정보','账户信息'],
  noChanges: ['Consulta de datos y accesos a las funciones existentes.','Data review and access to existing functions.','Consultation des données et accès aux fonctions existantes.','Consulta de dados e acesso às funções existentes.','데이터 확인 및 기존 기능 접근.','查看数据并访问现有功能。'],
} as const;
export type CommercialCopyKey = keyof typeof messages;
export function commercialCopy(locale: string): Record<CommercialCopyKey, string> {
  const index = locale.startsWith('es') ? 0 : locale.startsWith('fr') ? 2 : locale.startsWith('pt') ? 3 : locale.startsWith('ko') ? 4 : locale.startsWith('zh') ? 5 : 1;
  return Object.fromEntries(Object.entries(messages).map(([key, values]) => [key, values[index]])) as Record<CommercialCopyKey, string>;
}
