const en = {
  title: 'Bulk actions', selected: 'selected', total: 'Total', filtered: 'Filtered totals', selectedTotal: 'Selected totals',
  DELETE: 'Delete', UNIT: 'Change unit', BUSINESS: 'Change business', PROVIDER: 'Change provider',
  PAYMENT_ACCOUNT: 'Change payment account', ACCOUNTING_ACCOUNT: 'Change accounting account',
  cancel: 'Cancel', apply: 'Apply to selection', search: 'Search options', choose: 'Select an option', clear: 'Unassigned',
  reason: 'Reason (at least 8 characters)', all: 'Select visible rows', row: 'Select row',
  confirm: 'The change applies to every selected record. Review the selection before confirming.',
  protected: 'The selection contains protected or linked records. Open their source workflow to make an adjustment.',
  deleteDraft: 'Only unpaid drafts can be deleted here. Paid expenses require a payment reversal.',
  payment: 'This changes the account for future payments. Existing payments retain their original account.',
  noBalance: 'Some selected expenses are fully paid and have no future payment account to change.',
  custody: 'The payment account belongs to the selected fund. It cannot be changed on individual receipts.',
  cut: 'This cut is closed. Its receipts cannot be changed.',
  reverse: 'Deleting receipts reverses their outflows and preserves the records and the reason in the history.',
  unit: 'Changing unit clears the business on every selected expense.',
  business: 'All selected expenses must belong to the same unit. The new business must belong to that unit.',
  limit: 'Select up to 200 records per operation.', error: 'The operation could not be completed. Your selection has been preserved.',
};
const es: typeof en = {
  title: 'Acciones en masa', selected: 'seleccionados', total: 'Total', filtered: 'Totales filtrados', selectedTotal: 'Total seleccionado',
  DELETE: 'Eliminar', UNIT: 'Cambiar unidad', BUSINESS: 'Cambiar negocio', PROVIDER: 'Cambiar proveedor',
  PAYMENT_ACCOUNT: 'Cambiar cuenta de pago', ACCOUNTING_ACCOUNT: 'Cambiar cuenta contable',
  cancel: 'Cancelar', apply: 'Aplicar a la selección', search: 'Buscar opciones', choose: 'Seleccionar una opción', clear: 'Sin asignar',
  reason: 'Motivo (mínimo 8 caracteres)', all: 'Seleccionar filas visibles', row: 'Seleccionar fila',
  confirm: 'El cambio se aplicará a todos los registros seleccionados. Revisa la selección antes de confirmar.',
  protected: 'La selección contiene registros protegidos o vinculados. Abre su operación de origen para hacer un ajuste.',
  deleteDraft: 'Aquí solo se eliminan borradores sin pagos. Los gastos pagados requieren una reversión del pago.',
  payment: 'Cambia la cuenta prevista para pagos futuros. Los pagos registrados conservan su cuenta original.',
  noBalance: 'Hay gastos completamente pagados en la selección; no tienen una cuenta para pagos futuros que cambiar.',
  custody: 'La cuenta de pago pertenece al fondo seleccionado. No se puede cambiar en sus comprobantes.',
  cut: 'Este corte está cerrado. Sus comprobantes no se pueden modificar.',
  reverse: 'Eliminar comprobantes revierte sus salidas y conserva los registros y el motivo en el historial.',
  unit: 'Al cambiar la unidad se quitará el negocio de todos los gastos seleccionados.',
  business: 'Todos los gastos seleccionados deben pertenecer a la misma unidad. El nuevo negocio debe ser de esa unidad.',
  limit: 'Selecciona hasta 200 registros por operación.', error: 'No se pudo completar la operación. Se conservó tu selección.',
};
const pt: typeof en = {
  title: 'Ações em massa', selected: 'selecionados', total: 'Total', filtered: 'Totais filtrados', selectedTotal: 'Total selecionado',
  DELETE: 'Excluir', UNIT: 'Alterar unidade', BUSINESS: 'Alterar negócio', PROVIDER: 'Alterar fornecedor',
  PAYMENT_ACCOUNT: 'Alterar conta de pagamento', ACCOUNTING_ACCOUNT: 'Alterar conta contábil',
  cancel: 'Cancelar', apply: 'Aplicar à seleção', search: 'Buscar opções', choose: 'Selecionar uma opção', clear: 'Sem atribuição',
  reason: 'Motivo (mínimo de 8 caracteres)', all: 'Selecionar linhas visíveis', row: 'Selecionar linha',
  confirm: 'A alteração será aplicada a todos os registros selecionados. Revise a seleção antes de confirmar.',
  protected: 'A seleção contém registros protegidos ou vinculados. Abra a operação de origem para fazer um ajuste.',
  deleteDraft: 'Somente rascunhos sem pagamentos podem ser excluídos aqui. Despesas pagas exigem estorno.',
  payment: 'Altera a conta prevista para pagamentos futuros. Pagamentos registrados mantêm a conta original.',
  noBalance: 'Há despesas totalmente pagas na seleção, sem conta para pagamentos futuros a alterar.',
  custody: 'A conta de pagamento pertence ao fundo. Não pode ser alterada nos comprovantes.',
  cut: 'Este fechamento está encerrado. Seus comprovantes não podem ser alterados.',
  reverse: 'Excluir comprovantes estorna suas saídas e preserva os registros e o motivo no histórico.',
  unit: 'Alterar a unidade remove o negócio de todas as despesas selecionadas.',
  business: 'As despesas selecionadas e o novo negócio devem pertencer à mesma unidade.',
  limit: 'Selecione até 200 registros por operação.', error: 'Não foi possível concluir a operação. Sua seleção foi preservada.',
};
const fr: typeof en = {
  title: 'Actions groupées', selected: 'sélectionnés', total: 'Total', filtered: 'Totaux filtrés', selectedTotal: 'Total sélectionné',
  DELETE: 'Supprimer', UNIT: 'Changer l’unité', BUSINESS: 'Changer l’activité', PROVIDER: 'Changer le fournisseur',
  PAYMENT_ACCOUNT: 'Changer le compte de paiement', ACCOUNTING_ACCOUNT: 'Changer le compte comptable',
  cancel: 'Annuler', apply: 'Appliquer à la sélection', search: 'Rechercher des options', choose: 'Sélectionner une option', clear: 'Non attribué',
  reason: 'Motif (au moins 8 caractères)', all: 'Sélectionner les lignes visibles', row: 'Sélectionner la ligne',
  confirm: 'La modification concerne tous les enregistrements sélectionnés. Vérifiez la sélection avant de confirmer.',
  protected: 'La sélection contient des enregistrements protégés ou liés. Ouvrez leur opération d’origine pour effectuer un ajustement.',
  deleteDraft: 'Seuls les brouillons non payés peuvent être supprimés ici. Les dépenses payées nécessitent une contrepassation.',
  payment: 'Modifie le compte prévu pour les paiements futurs. Les paiements enregistrés conservent leur compte d’origine.',
  noBalance: 'Certaines dépenses sélectionnées sont entièrement payées et n’ont pas de compte de paiement futur à modifier.',
  custody: 'Le compte de paiement appartient au fonds. Il ne peut pas être modifié sur ses justificatifs.',
  cut: 'Cette période est clôturée. Ses justificatifs ne peuvent pas être modifiés.',
  reverse: 'La suppression contre-passe les sorties et conserve les enregistrements et le motif dans l’historique.',
  unit: 'Changer l’unité retire l’activité de toutes les dépenses sélectionnées.',
  business: 'Toutes les dépenses sélectionnées et la nouvelle activité doivent appartenir à la même unité.',
  limit: 'Sélectionnez au maximum 200 enregistrements par opération.', error: 'L’opération a échoué. Votre sélection a été conservée.',
};
export const getFinanceBulkCopy = (locale: string) => locale.toLowerCase().startsWith('es') ? es
  : locale.toLowerCase().startsWith('pt') ? pt : locale.toLowerCase().startsWith('fr') ? fr : en;
export type FinanceBulkAction = 'DELETE' | 'UNIT' | 'BUSINESS' | 'PROVIDER' | 'PAYMENT_ACCOUNT' | 'ACCOUNTING_ACCOUNT';
