import type { PointOfSaleLocale } from '../../translations';

const en = {
  title: 'Process refund', subtitle: 'Find the original receipt and verify the provider payment.', sensitive: 'Sensitive operation',
  disclaimer: 'This action refunds the terminal payment. Inventory and credit-document changes use their own approved workflows.',
  saleNumber: 'Receipt number', placeholder: 'POS-20260922143000-ABCDE', lookup: 'Find sale', loading: 'Working...', anotherSale: 'Find another sale',
  provider: 'Provider', providerStatus: 'Payment status', saleTotal: 'Sale total', terminalPayment: 'Terminal payment', refunded: 'Refunded', refundable: 'Available to refund',
  latest: 'Latest refund request', full: 'Full refund', fullHelp: 'Refund the full remaining amount', partial: 'Partial refund', partialHelp: 'Enter a specific amount',
  amount: 'Refund amount', reason: 'Reason', reasonPlaceholder: 'Explain why this refund is required', submit: 'Submit refund', retry: 'Retry same request',
  refresh: 'Verify with provider', confirmed: 'Provider confirmed the refund.', pending: 'The request is still being verified. Do not create another refund.',
  attention: 'The provider result requires manual reconciliation. Do not create another refund.', notSubmitted: 'The provider did not accept this request. Review the details before submitting a new request.',
  unavailable: 'This sale has no refundable supported terminal payment.', complete: 'The terminal payment has been fully refunded.', newRefund: 'Prepare another refund',
  cancel: 'Cancel', close: 'Close', errorReference: 'Enter the receipt number.', errorReason: 'Enter a reason with at least 3 characters.',
  errorAmount: 'Enter a positive amount with no more than 2 decimals.', errorAmountExceeds: 'The amount exceeds the available refund balance.',
  errorLookup: 'The sale could not be loaded.', errorSubmit: 'The refund result is not confirmed. Retry with the same request.', errorRefresh: 'The provider status could not be refreshed.',
  recheck: 'Recheck provider evidence', reviewReason: 'Review reason', reviewHelp: 'Explain why an authenticated provider recheck is required (8–500 characters). Square may retry the exact stored request and idempotency key only when the payment still matches its original refund balance.',
  reviewPlaceholder: 'Explain the reason for this provider recheck', errorReviewReason: 'Enter a review reason between 8 and 500 characters.', errorRecheck: 'The provider evidence could not be rechecked.',
  errorConflict: 'The refund changed. Current details were reloaded; review them before trying again.',
};

type Copy = typeof en;
const es: Copy = {
  title: 'Procesar reembolso', subtitle: 'Busca el ticket original y verifica el pago del proveedor.', sensitive: 'Operación sensible',
  disclaimer: 'Esta acción reembolsa el pago de la terminal. El inventario y los documentos de crédito usan sus propios flujos autorizados.',
  saleNumber: 'Número de ticket', placeholder: 'POS-20260922143000-ABCDE', lookup: 'Buscar venta', loading: 'Procesando...', anotherSale: 'Buscar otra venta',
  provider: 'Proveedor', providerStatus: 'Estado del pago', saleTotal: 'Total de venta', terminalPayment: 'Pago de terminal', refunded: 'Reembolsado', refundable: 'Disponible para reembolso',
  latest: 'Última solicitud de reembolso', full: 'Reembolso total', fullHelp: 'Reembolsa todo el saldo disponible', partial: 'Reembolso parcial', partialHelp: 'Captura un importe específico',
  amount: 'Importe del reembolso', reason: 'Motivo', reasonPlaceholder: 'Explica por qué se requiere este reembolso', submit: 'Solicitar reembolso', retry: 'Reintentar la misma solicitud',
  refresh: 'Verificar con el proveedor', confirmed: 'El proveedor confirmó el reembolso.', pending: 'La solicitud sigue en verificación. No generes otro reembolso.',
  attention: 'El resultado del proveedor requiere conciliación manual. No generes otro reembolso.', notSubmitted: 'El proveedor no aceptó esta solicitud. Revisa los datos antes de enviar una nueva.',
  unavailable: 'Esta venta no tiene un pago de terminal compatible disponible para reembolso.', complete: 'El pago de terminal fue reembolsado por completo.', newRefund: 'Preparar otro reembolso',
  cancel: 'Cancelar', close: 'Cerrar', errorReference: 'Ingresa el número de ticket.', errorReason: 'Ingresa un motivo de al menos 3 caracteres.',
  errorAmount: 'Ingresa un importe positivo con máximo 2 decimales.', errorAmountExceeds: 'El importe supera el saldo disponible para reembolso.',
  errorLookup: 'No se pudo cargar la venta.', errorSubmit: 'El resultado no está confirmado. Reintenta con la misma solicitud.', errorRefresh: 'No se pudo actualizar el estado del proveedor.',
  recheck: 'Volver a verificar con el proveedor', reviewReason: 'Motivo de la revisión', reviewHelp: 'Explica por qué se requiere una verificación autenticada del proveedor (8–500 caracteres). Square puede reintentar exactamente la solicitud y clave guardadas solo si el pago conserva el saldo original.',
  reviewPlaceholder: 'Explica el motivo de esta verificación', errorReviewReason: 'Ingresa un motivo de revisión de 8 a 500 caracteres.', errorRecheck: 'No se pudo volver a verificar la evidencia del proveedor.',
  errorConflict: 'El reembolso cambió. Se cargaron los datos actuales; revísalos antes de intentarlo de nuevo.',
};

const catalogs: Record<PointOfSaleLocale, Copy> = {
  'en-CA': en, 'en-US': en, 'es-MX': es, 'es-CO': es,
  'fr-CA': { ...en, title: 'Traiter un remboursement', subtitle: 'Trouvez le reçu original et vérifiez le paiement du fournisseur.', sensitive: 'Opération sensible', disclaimer: 'Cette action rembourse le paiement du terminal. Les stocks et les documents de crédit suivent leurs propres processus approuvés.', saleNumber: 'Numéro de reçu', lookup: 'Rechercher la vente', loading: 'Traitement...', anotherSale: 'Rechercher une autre vente', provider: 'Fournisseur', providerStatus: 'État du paiement', saleTotal: 'Total de la vente', terminalPayment: 'Paiement du terminal', refunded: 'Remboursé', refundable: 'Montant remboursable', latest: 'Dernière demande de remboursement', full: 'Remboursement total', fullHelp: 'Rembourser tout le solde disponible', partial: 'Remboursement partiel', partialHelp: 'Saisissez un montant précis', amount: 'Montant du remboursement', reason: 'Motif', reasonPlaceholder: 'Expliquez pourquoi ce remboursement est requis', submit: 'Soumettre le remboursement', retry: 'Réessayer la même demande', refresh: 'Vérifier auprès du fournisseur', confirmed: 'Le fournisseur a confirmé le remboursement.', pending: 'La demande est encore en cours de vérification. Ne créez pas un autre remboursement.', attention: 'Le résultat du fournisseur exige un rapprochement manuel. Ne créez pas un autre remboursement.', notSubmitted: 'Le fournisseur n’a pas accepté cette demande. Vérifiez les détails avant d’en soumettre une nouvelle.', unavailable: 'Cette vente ne contient aucun paiement de terminal compatible remboursable.', complete: 'Le paiement du terminal a été entièrement remboursé.', newRefund: 'Préparer un autre remboursement', cancel: 'Annuler', close: 'Fermer', errorReference: 'Saisissez le numéro de reçu.', errorReason: 'Saisissez un motif d’au moins 3 caractères.', errorAmount: 'Saisissez un montant positif avec au plus 2 décimales.', errorAmountExceeds: 'Le montant dépasse le solde remboursable.', errorLookup: 'La vente n’a pas pu être chargée.', errorSubmit: 'Le résultat du remboursement n’est pas confirmé. Réessayez la même demande.', errorRefresh: 'L’état du fournisseur n’a pas pu être actualisé.' },
  'pt-BR': { ...en, title: 'Processar reembolso', subtitle: 'Localize o recibo original e verifique o pagamento do provedor.', sensitive: 'Operação sensível', disclaimer: 'Esta ação reembolsa o pagamento do terminal. Estoque e documentos de crédito seguem fluxos próprios aprovados.', saleNumber: 'Número do recibo', lookup: 'Buscar venda', loading: 'Processando...', anotherSale: 'Buscar outra venda', provider: 'Provedor', providerStatus: 'Status do pagamento', saleTotal: 'Total da venda', terminalPayment: 'Pagamento do terminal', refunded: 'Reembolsado', refundable: 'Disponível para reembolso', latest: 'Última solicitação de reembolso', full: 'Reembolso total', fullHelp: 'Reembolsa todo o saldo disponível', partial: 'Reembolso parcial', partialHelp: 'Informe um valor específico', amount: 'Valor do reembolso', reason: 'Motivo', reasonPlaceholder: 'Explique por que este reembolso é necessário', submit: 'Solicitar reembolso', retry: 'Tentar a mesma solicitação novamente', refresh: 'Verificar com o provedor', confirmed: 'O provedor confirmou o reembolso.', pending: 'A solicitação ainda está em verificação. Não crie outro reembolso.', attention: 'O resultado do provedor exige conciliação manual. Não crie outro reembolso.', notSubmitted: 'O provedor não aceitou esta solicitação. Revise os dados antes de enviar uma nova.', unavailable: 'Esta venda não tem um pagamento de terminal compatível disponível para reembolso.', complete: 'O pagamento do terminal foi totalmente reembolsado.', newRefund: 'Preparar outro reembolso', cancel: 'Cancelar', close: 'Fechar', errorReference: 'Informe o número do recibo.', errorReason: 'Informe um motivo com pelo menos 3 caracteres.', errorAmount: 'Informe um valor positivo com no máximo 2 casas decimais.', errorAmountExceeds: 'O valor excede o saldo disponível para reembolso.', errorLookup: 'Não foi possível carregar a venda.', errorSubmit: 'O resultado não foi confirmado. Tente novamente com a mesma solicitação.', errorRefresh: 'Não foi possível atualizar o status do provedor.' },
  'ko-CA': { ...en, title: '환불 처리', subtitle: '원본 영수증을 찾아 공급자 결제를 확인하세요.', sensitive: '민감한 작업', disclaimer: '이 작업은 단말기 결제만 환불합니다. 재고 및 대변 문서는 각각 승인된 절차를 따릅니다.', saleNumber: '영수증 번호', lookup: '판매 찾기', loading: '처리 중...', anotherSale: '다른 판매 찾기', provider: '공급자', providerStatus: '결제 상태', saleTotal: '판매 합계', terminalPayment: '단말기 결제', refunded: '환불됨', refundable: '환불 가능 금액', latest: '최근 환불 요청', full: '전액 환불', fullHelp: '남은 금액 전부 환불', partial: '부분 환불', partialHelp: '특정 금액 입력', amount: '환불 금액', reason: '사유', reasonPlaceholder: '환불이 필요한 이유를 입력하세요', submit: '환불 요청', retry: '같은 요청 다시 시도', refresh: '공급자에서 확인', confirmed: '공급자가 환불을 확인했습니다.', pending: '요청을 확인 중입니다. 다른 환불을 만들지 마세요.', attention: '공급자 결과를 수동으로 조정해야 합니다. 다른 환불을 만들지 마세요.', notSubmitted: '공급자가 이 요청을 수락하지 않았습니다. 새 요청 전에 세부 정보를 확인하세요.', unavailable: '이 판매에는 환불 가능한 지원 단말기 결제가 없습니다.', complete: '단말기 결제가 전액 환불되었습니다.', newRefund: '다른 환불 준비', cancel: '취소', close: '닫기', errorReference: '영수증 번호를 입력하세요.', errorReason: '3자 이상의 사유를 입력하세요.', errorAmount: '소수점 이하 2자리 이내의 양수를 입력하세요.', errorAmountExceeds: '금액이 환불 가능 잔액을 초과합니다.', errorLookup: '판매를 불러오지 못했습니다.', errorSubmit: '환불 결과가 확인되지 않았습니다. 같은 요청으로 다시 시도하세요.', errorRefresh: '공급자 상태를 새로 고치지 못했습니다.' },
  'zh-CA': { ...en, title: '处理退款', subtitle: '查找原始收据并验证服务商付款。', sensitive: '敏感操作', disclaimer: '此操作仅退还终端付款。库存和贷项文件使用各自已批准的流程。', saleNumber: '收据编号', lookup: '查找销售', loading: '处理中...', anotherSale: '查找其他销售', provider: '服务商', providerStatus: '付款状态', saleTotal: '销售总额', terminalPayment: '终端付款', refunded: '已退款', refundable: '可退款金额', latest: '最近退款请求', full: '全额退款', fullHelp: '退还全部剩余金额', partial: '部分退款', partialHelp: '输入指定金额', amount: '退款金额', reason: '原因', reasonPlaceholder: '说明需要退款的原因', submit: '提交退款', retry: '重试同一请求', refresh: '向服务商核验', confirmed: '服务商已确认退款。', pending: '请求仍在核验中。请勿创建其他退款。', attention: '服务商结果需要人工对账。请勿创建其他退款。', notSubmitted: '服务商未接受此请求。提交新请求前请检查详细信息。', unavailable: '此销售没有可退款的受支持终端付款。', complete: '终端付款已全额退款。', newRefund: '准备另一笔退款', cancel: '取消', close: '关闭', errorReference: '请输入收据编号。', errorReason: '请输入至少 3 个字符的原因。', errorAmount: '请输入最多 2 位小数的正数金额。', errorAmountExceeds: '金额超过可退款余额。', errorLookup: '无法加载销售。', errorSubmit: '退款结果尚未确认。请使用同一请求重试。', errorRefresh: '无法刷新服务商状态。' },
};

type ReviewCopy = Pick<Copy, 'recheck' | 'reviewReason' | 'reviewHelp' | 'reviewPlaceholder'
  | 'errorReviewReason' | 'errorRecheck' | 'errorConflict'>;
const reviews: Record<PointOfSaleLocale, ReviewCopy> = {
  'en-CA': en, 'en-US': en, 'es-MX': es, 'es-CO': es,
  'fr-CA': { recheck: 'Revérifier auprès du fournisseur', reviewReason: 'Motif de la vérification', reviewHelp: 'Expliquez pourquoi une vérification authentifiée est requise (8 à 500 caractères). Square peut réessayer la demande et la clé enregistrées seulement si le solde remboursé reste celui d’origine.', reviewPlaceholder: 'Expliquez le motif de cette vérification', errorReviewReason: 'Saisissez un motif de 8 à 500 caractères.', errorRecheck: 'Les preuves du fournisseur n’ont pas pu être revérifiées.', errorConflict: 'Le remboursement a changé. Les données actuelles ont été rechargées; vérifiez-les avant de réessayer.' },
  'pt-BR': { recheck: 'Verificar novamente com o provedor', reviewReason: 'Motivo da verificação', reviewHelp: 'Explique por que uma verificação autenticada é necessária (8–500 caracteres). A Square pode repetir a solicitação e a chave salvas somente se o saldo reembolsado continuar no valor original.', reviewPlaceholder: 'Explique o motivo desta verificação', errorReviewReason: 'Informe um motivo de 8 a 500 caracteres.', errorRecheck: 'Não foi possível verificar novamente as evidências do provedor.', errorConflict: 'O reembolso mudou. Os dados atuais foram recarregados; revise-os antes de tentar novamente.' },
  'ko-CA': { recheck: '공급자 증거 다시 확인', reviewReason: '검토 사유', reviewHelp: '인증된 공급자 재확인이 필요한 이유를 8~500자로 입력하세요. 환불 잔액이 원래 값과 같을 때만 Square가 저장된 요청과 멱등성 키를 그대로 재시도할 수 있습니다.', reviewPlaceholder: '재확인 사유를 입력하세요', errorReviewReason: '8~500자의 검토 사유를 입력하세요.', errorRecheck: '공급자 증거를 다시 확인하지 못했습니다.', errorConflict: '환불 정보가 변경되었습니다. 최신 정보를 다시 불러왔으니 확인 후 다시 시도하세요.' },
  'zh-CA': { recheck: '重新核验服务商证据', reviewReason: '审核原因', reviewHelp: '请用 8–500 个字符说明为何需要经过身份验证的服务商核验。只有退款余额仍等于原始值时，Square 才可重试完全相同的已存请求和幂等键。', reviewPlaceholder: '说明此次核验的原因', errorReviewReason: '请输入 8–500 个字符的审核原因。', errorRecheck: '无法重新核验服务商证据。', errorConflict: '退款已发生变化。已重新加载当前详情；请检查后重试。' },
};

export const getPosReturnCopy = (locale: PointOfSaleLocale) => ({ ...catalogs[locale], ...reviews[locale] });
