const locales: Record<string, number> = { 'en-CA': 0, 'en-US': 0, 'es-MX': 1, 'es-CO': 1, 'fr-CA': 2, 'pt-BR': 3, 'ko-CA': 4, 'zh-CA': 5 };
// English, Spanish, French, Portuguese, Korean, Chinese. Entered company/campaign names are unchanged.
const messages = {
  title: ['Acquisition and commercial flow', 'Captación y flujo comercial', 'Acquisition et parcours commercial', 'Captação e fluxo comercial', '고객 유치 및 영업 흐름', '获客与销售流程'],
  subtitle: ['Follow Indice leads from first contact to diagnosis, proposal and commercial close.', 'Sigue los prospectos de Índice desde el contacto hasta el diagnóstico, la propuesta y el cierre comercial.', 'Suivez les prospects d’Indice du contact au diagnostic, à la proposition et à la conclusion.', 'Acompanhe os leads da Índice do contato ao diagnóstico, proposta e fechamento.', 'Índice 잠재 고객의 연락, 진단, 제안 및 계약 성사 과정을 확인하세요.', '跟踪 Índice 潜在客户从联系到诊断、提案和成交的过程。'],
  overview: ['Commercial overview', 'Resumen comercial', 'Résumé commercial', 'Resumo comercial', '영업 요약', '销售概览'],
  sources: ['Campaigns and plans', 'Campañas y planes', 'Campagnes et forfaits', 'Campanhas e planos', '캠페인 및 요금제', '营销活动与套餐'],
  traffic: ['Website traffic', 'Tráfico web', 'Trafic Web', 'Tráfego web', '웹사이트 트래픽', '网站流量'],
  market: ['Lead market', 'Mercado del prospecto', 'Marché du prospect', 'Mercado do lead', '잠재 고객 시장', '潜在客户市场'],
  allMarkets: ['All markets', 'Todos los mercados', 'Tous les marchés', 'Todos os mercados', '모든 시장', '所有市场'],
  mexico: ['Mexico', 'México', 'Mexique', 'México', '멕시코', '墨西哥'],
  canada: ['Canada', 'Canadá', 'Canada', 'Canadá', '캐나다', '加拿大'],
  other: ['Other or unspecified', 'Otro o sin especificar', 'Autre ou non précisé', 'Outro ou não especificado', '기타 또는 미지정', '其他或未指定'],
  received: ['Confirmed leads', 'Prospectos confirmados', 'Prospects confirmés', 'Leads confirmados', '확인된 잠재 고객', '已确认潜在客户'],
  contacted: ['Contact recorded', 'Contacto registrado', 'Contact enregistré', 'Contato registrado', '연락 기록', '已记录联系'],
  scheduled: ['Diagnosis scheduled', 'Diagnóstico agendado', 'Diagnostic planifié', 'Diagnóstico agendado', '진단 예약', '已预约诊断'],
  diagnosed: ['Diagnosis completed', 'Diagnóstico realizado', 'Diagnostic réalisé', 'Diagnóstico realizado', '진단 완료', '已完成诊断'],
  proposal: ['Proposal reached', 'Propuesta presentada', 'Proposition présentée', 'Proposta apresentada', '제안 단계 도달', '已提出提案'],
  won: ['Commercial wins', 'Cierres comerciales', 'Affaires conclues', 'Fechamentos comerciais', '영업 성사', '销售成交'],
  trial: ['Guided trials recorded', 'Pruebas guiadas registradas', 'Essais guidés enregistrés', 'Testes guiados registrados', '기록된 체험', '已记录指导试用'],
  contactSla: ['Contact within 24 hours', 'Contacto en 24 horas', 'Contact dans les 24 heures', 'Contato em 24 horas', '24시간 내 연락', '24 小时内联系'],
  diagnosisRate: ['Lead to diagnosis', 'Prospecto a diagnóstico', 'Prospect vers diagnostic', 'Lead para diagnóstico', '잠재 고객의 진단 전환', '潜在客户转为诊断'],
  winRate: ['Proposal to close', 'Propuesta a cierre', 'Proposition vers conclusion', 'Proposta para fechamento', '제안의 성사 전환', '提案转为成交'],
  cohort: ['Leads received {from}–{to}; stages reached as of this refresh. Dates use UTC.', 'Prospectos recibidos del {from} al {to}; etapas alcanzadas a esta actualización. Fechas en UTC.', 'Prospects reçus du {from} au {to}; étapes atteintes à cette actualisation. Dates UTC.', 'Leads recebidos de {from} a {to}; etapas alcançadas nesta atualização. Datas UTC.', '{from}~{to} 접수된 잠재 고객의 현재 도달 단계입니다. 날짜는 UTC 기준입니다.', '{from} 至 {to} 收到的潜在客户，以及截至本次刷新的阶段。日期使用 UTC。'],
  recordedLeads: ['Saved diagnosis requests, including website and social channels.', 'Solicitudes de diagnóstico guardadas, de web y redes sociales.', 'Demandes de diagnostic enregistrées, Web et réseaux sociaux.', 'Solicitações de diagnóstico salvas, da web e redes sociais.', '웹 및 소셜 채널에서 저장된 진단 요청입니다.', '来自网站和社交渠道的已保存诊断请求。'],
  slaHelper: ['{met} of {eligible} leads at least 24 hours old. Open the missed cases.', '{met} de {eligible} prospectos con al menos 24 horas de antigüedad. Abre los casos fuera de plazo.', '{met} sur {eligible} prospects âgés d’au moins 24 heures. Voir les retards.', '{met} de {eligible} leads com pelo menos 24 horas. Abra os casos fora do prazo.', '접수 후 24시간 이상 지난 {eligible}명 중 {met}명입니다. 기한 초과 사례를 확인하세요.', '接收至少 24 小时的 {eligible} 个潜在客户中有 {met} 个及时联系。查看超时记录。'],
  diagnosisHelper: ['{count} of {total} received leads reached diagnosis.', '{count} de {total} prospectos recibidos llegaron al diagnóstico.', '{count} sur {total} prospects ont atteint le diagnostic.', '{count} de {total} leads chegaram ao diagnóstico.', '접수 {total}명 중 {count}명이 진단에 도달했습니다.', '收到的 {total} 个潜在客户中有 {count} 个完成诊断。'],
  winHelper: ['{count} wins from {total} leads that reached proposal; newer leads are still maturing.', '{count} cierres de {total} prospectos que llegaron a propuesta; los más recientes siguen madurando.', '{count} conclusions sur {total} prospects ayant atteint la proposition; les plus récents évoluent encore.', '{count} fechamentos de {total} leads com proposta; os mais recentes ainda estão evoluindo.', '제안에 도달한 {total}명 중 {count}명이 성사되었습니다. 최근 고객은 아직 진행 중입니다.', '到达提案阶段的 {total} 个潜在客户中有 {count} 个成交；近期客户仍在跟进。'],
  funnel: ['Stages reached', 'Etapas alcanzadas', 'Étapes atteintes', 'Etapas alcançadas', '도달 단계', '已达到的阶段'],
  funnelHelp: ['Each lead counts once in every recorded stage, even after moving forward. A stage may be skipped.', 'Cada prospecto cuenta una vez por etapa registrada, aunque ya haya avanzado. Puede haber etapas omitidas.', 'Chaque prospect compte une fois par étape enregistrée, même après progression. Certaines étapes peuvent être sautées.', 'Cada lead conta uma vez por etapa registrada, mesmo após avançar. Etapas podem ser puladas.', '진행 후에도 기록된 각 단계에서 한 번씩 계산합니다. 일부 단계는 건너뛸 수 있습니다.', '每个潜在客户在已记录的各阶段仅计一次，即使已进入下一阶段。部分阶段可能被跳过。'],
  cohortRate: ['{rate} of received leads', '{rate} de los prospectos recibidos', '{rate} des prospects reçus', '{rate} dos leads recebidos', '접수된 잠재 고객의 {rate}', '占已接收潜在客户的 {rate}'],
  averageContact: ['Average first recorded contact: {hours} hours · {count} records', 'Primer contacto registrado: {hours} horas en promedio · {count} registros', 'Premier contact enregistré : {hours} heures en moyenne · {count} dossiers', 'Primeiro contato registrado: média de {hours} horas · {count} registros', '첫 연락 기록 평균: {hours}시간 · {count}건', '首次联系记录平均：{hours} 小时 · {count} 条记录'],
  contactDefinition: ['First Contacted or Diagnosis scheduled event. Unrecorded contact is not counted.', 'Primer cambio a Contactado o Diagnóstico agendado. Los contactos sin registrar no cuentan.', 'Premier passage à Contacté ou Diagnostic planifié. Les contacts non enregistrés ne comptent pas.', 'Primeira mudança para Contatado ou Diagnóstico agendado. Contatos não registrados não contam.', '연락됨 또는 진단 예약의 첫 기록을 사용합니다. 미기록 연락은 포함되지 않습니다.', '使用首次“已联系”或“诊断已预约”记录。未记录的联系不计入。'],
  outcomeNote: ['A guided trial records a commercial decision. A win records a close; neither confirms account activation or payment.', 'La prueba guiada registra una decisión comercial. El cierre registra un acuerdo; ninguno confirma activación de cuenta ni cobro.', 'Un essai guidé enregistre une décision commerciale. Une conclusion enregistre un accord; ni l’un ni l’autre ne confirme activation ou paiement.', 'O teste guiado registra uma decisão comercial. O fechamento registra um acordo; nenhum confirma ativação de conta ou pagamento.', '체험은 영업 결정을, 성사는 합의를 기록합니다. 계정 활성화나 결제 완료를 뜻하지 않습니다.', '指导试用记录商业决定，成交记录协议；两者均不确认账户激活或付款。'],
  attention: ['Follow-up needing attention', 'Seguimientos que requieren atención', 'Suivis à traiter', 'Acompanhamentos que precisam de atenção', '주의가 필요한 후속 조치', '需要关注的跟进'],
  currentScope: ['Open follow-up, all intake dates. Uses the selected market.', 'Seguimientos abiertos de todas las fechas. Aplica el mercado seleccionado.', 'Suivis ouverts, toutes dates de réception. Marché sélectionné.', 'Acompanhamentos abertos de todas as datas. Mercado selecionado.', '선택한 시장의 모든 접수일에 걸친 진행 중 후속 조치입니다.', '所有接收日期的未结束跟进，按所选市场筛选。'],
  overdue: ['Overdue next actions', 'Próximas acciones vencidas', 'Actions en retard', 'Próximas ações vencidas', '기한이 지난 다음 조치', '已逾期的下一步行动'],
  unassigned: ['Without an owner', 'Sin responsable', 'Sans responsable', 'Sem responsável', '담당자 없음', '无负责人'],
  missing_action: ['Without a next action', 'Sin próxima acción', 'Sans prochaine action', 'Sem próxima ação', '다음 조치 없음', '无下一步行动'],
  uncontacted: ['No contact recorded after 24 hours', 'Sin contacto registrado después de 24 h', 'Sans contact enregistré après 24 h', 'Sem contato registrado após 24 h', '24시간 후에도 연락 기록 없음', '24 小时后仍无联系记录'],
  trial_attention: ['Trials expiring or expired', 'Pruebas por vencer o vencidas', 'Essais proches de la fin ou expirés', 'Testes a vencer ou vencidos', '곧 만료되거나 만료된 체험', '即将到期或已到期的试用'],
  trialHelp: ['{ending} end within 3 days · {expired} expired', '{ending} vencen en 3 días · {expired} vencidas', '{ending} expirent dans 3 jours · {expired} expirés', '{ending} vencem em 3 dias · {expired} vencidos', '3일 내 만료 {ending}건 · 만료 {expired}건', '3 天内到期 {ending} 个 · 已到期 {expired} 个'],
  sla_missed: ['Contact outside 24 hours', 'Contacto fuera de 24 horas', 'Contact hors délai de 24 heures', 'Contato fora de 24 horas', '24시간 연락 기한 초과', '联系超过 24 小时'],
  campaigns: ['Commercial results by campaign', 'Resultados comerciales por campaña', 'Résultats par campagne', 'Resultados comerciais por campanha', '캠페인별 영업 결과', '营销活动的销售结果'],
  campaignsHelp: ['Origin declared on the lead form. This does not identify an anonymous website visitor.', 'Origen declarado en el formulario del prospecto. No identifica a un visitante anónimo de la web.', 'Origine déclarée dans le formulaire. N’identifie pas un visiteur Web anonyme.', 'Origem declarada no formulário. Não identifica um visitante anônimo da web.', '잠재 고객 양식에 기록된 출처입니다. 익명 웹 방문자를 식별하지 않습니다.', '潜在客户表单中声明的来源，不用于识别匿名网站访客。'],
  coverage: ['Showing {shown} of {total} source groups, ranked by confirmed leads.', 'Mostrando {shown} de {total} grupos de origen, ordenados por prospectos confirmados.', '{shown} groupes sur {total}, classés par prospects confirmés.', 'Mostrando {shown} de {total} grupos, por leads confirmados.', '확인된 잠재 고객 순으로 {total}개 출처 그룹 중 {shown}개를 표시합니다.', '按已确认潜在客户排序，显示 {total} 个来源组中的 {shown} 个。'],
  planInterest: ['Demand by plan of interest', 'Demanda por plan de interés', 'Demande par forfait souhaité', 'Demanda por plano de interesse', '관심 요금제별 수요', '按意向套餐划分的需求'],
  planHelp: ['Declared interest, not an active subscription.', 'Interés declarado; no es una contratación activa.', 'Intérêt déclaré, pas un abonnement actif.', 'Interesse declarado, não uma assinatura ativa.', '기록된 관심이며 활성 구독이 아닙니다.', '已声明的兴趣，不代表有效订阅。'],
  noPlan: ['Not specified', 'Sin especificar', 'Non précisé', 'Não especificado', '미지정', '未指定'],
  unattributed: ['Unattributed', 'Sin atribución', 'Sans attribution', 'Sem atribuição', '출처 미상', '未归因'],
  source: ['Lead origin', 'Origen del prospecto', 'Origine du prospect', 'Origem do lead', '잠재 고객 출처', '潜在客户来源'],
  actions: ['Actions', 'Acciones', 'Actions', 'Ações', '작업', '操作'],
  details: ['Lead details', 'Detalle de prospectos', 'Détail des prospects', 'Detalhes dos leads', '잠재 고객 상세', '潜在客户详情'],
  company: ['Company', 'Empresa', 'Entreprise', 'Empresa', '회사', '企业'],
  status: ['Current stage', 'Etapa actual', 'Étape actuelle', 'Etapa atual', '현재 단계', '当前阶段'],
  owner: ['Owner', 'Responsable', 'Responsable', 'Responsável', '담당자', '负责人'],
  nextAction: ['Next action', 'Próxima acción', 'Prochaine action', 'Próxima ação', '다음 조치', '下一步行动'],
  receivedAt: ['Received', 'Recibido', 'Reçu', 'Recebido', '접수일', '接收时间'],
  openLead: ['Open follow-up', 'Abrir seguimiento', 'Ouvrir le suivi', 'Abrir acompanhamento', '후속 조치 열기', '打开跟进'],
  loading: ['Loading commercial data…', 'Cargando datos comerciales…', 'Chargement des données commerciales…', 'Carregando dados comerciais…', '영업 데이터 불러오는 중…', '正在加载销售数据…'],
  error: ['Commercial data could not be loaded. Try again.', 'No se pudieron cargar los datos comerciales. Vuelve a intentarlo.', 'Impossible de charger les données commerciales. Réessayez.', 'Não foi possível carregar os dados comerciais. Tente novamente.', '영업 데이터를 불러오지 못했습니다. 다시 시도하세요.', '无法加载销售数据。请重试。'],
  empty: ['No confirmed leads in this scope yet.', 'Todavía no hay prospectos confirmados en este alcance.', 'Aucun prospect confirmé dans ce périmètre.', 'Ainda não há leads confirmados neste escopo.', '이 범위에 확인된 잠재 고객이 아직 없습니다.', '此范围内暂无已确认的潜在客户。'],
  noDetails: ['No leads match this indicator.', 'No hay prospectos que coincidan con este indicador.', 'Aucun prospect ne correspond à cet indicateur.', 'Nenhum lead corresponde a este indicador.', '이 지표에 해당하는 잠재 고객이 없습니다.', '没有符合此指标的潜在客户。'],
  reload: ['Retry', 'Reintentar', 'Réessayer', 'Tentar novamente', '다시 시도', '重试'],
  close: ['Close', 'Cerrar', 'Fermer', 'Fechar', '닫기', '关闭'],
  measuredSubmitRate: ['Measured website submission rate', 'Tasa de envío web medido', 'Taux d’envoi Web mesuré', 'Taxa de envio web medido', '측정된 웹 제출 비율', '已测量的网站提交率'],
  measuredSubmitHelp: ['Sessions with at least one submission event / measured sessions.', 'Sesiones con al menos un evento de envío / sesiones medidas.', 'Sessions avec un événement d’envoi / sessions mesurées.', 'Sessões com evento de envio / sessões medidas.', '제출 이벤트가 있는 세션 / 측정된 세션입니다.', '至少有一次提交事件的会话 / 已测量会话。'],
  measurementPending: ['Website measurement pending; commercial lead records remain available.', 'Medición web pendiente; los registros comerciales de prospectos siguen disponibles.', 'Mesure Web en attente; les dossiers commerciaux restent disponibles.', 'Medição web pendente; registros comerciais continuam disponíveis.', '웹 측정이 대기 중입니다. 영업 잠재 고객 기록은 이용 가능합니다.', '网站测量待启用，销售潜在客户记录仍可用。'],
  NEW: ['New', 'Nuevo', 'Nouveau', 'Novo', '신규', '新建'],
  CONTACTED: ['Contacted', 'Contactado', 'Contacté', 'Contatado', '연락됨', '已联系'],
  DIAGNOSIS_SCHEDULED: ['Diagnosis scheduled', 'Diagnóstico agendado', 'Diagnostic planifié', 'Diagnóstico agendado', '진단 예약', '已预约诊断'],
  DIAGNOSIS_COMPLETED: ['Diagnosis completed', 'Diagnóstico realizado', 'Diagnostic réalisé', 'Diagnóstico realizado', '진단 완료', '已完成诊断'],
  TRIAL_ACTIVE: ['Trial recorded', 'Prueba registrada', 'Essai enregistré', 'Teste registrado', '체험 기록', '已记录试用'],
  PROPOSAL: ['Proposal', 'Propuesta', 'Proposition', 'Proposta', '제안', '提案'],
  WON: ['Won', 'Ganado', 'Conclu', 'Ganho', '성사', '成交'],
  LOST: ['Lost', 'Perdido', 'Perdu', 'Perdido', '실패', '流失'],
  NURTURE: ['Nurture', 'Nutrición', 'Suivi à long terme', 'Nutrição', '장기 육성', '培育'],
} as const;
export type LeadAnalyticsCopyKey = keyof typeof messages;
export function getLeadAnalyticsCopy(locale: string) {
  const index = locales[locale] ?? 0;
  return { t: (key: LeadAnalyticsCopyKey, values: Record<string, string | number> = {}) =>
    messages[key][index].replace(/\{(\w+)\}/g, (token, name: string) => String(values[name] ?? token)) };
}
