import { useLanguage } from '../../shared/context';

const employeesEs = {
  title: 'Colaboradores',
  subtitle: 'Gestiona tu equipo de trabajo',
  configureColumns: 'Columnas',
  addEmployee: 'Agregar colaborador',
  loading: 'Cargando colaboradores...',
  backendConnected:
    'Los colaboradores de esta pantalla ahora se cargan desde el backend de Spring. Las acciones de crear, actualizar, terminar y eliminar también están conectadas.',
  errors: {
    load: 'No fue posible cargar los colaboradores.',
    save: 'No fue posible guardar el colaborador.',
    delete: 'No fue posible eliminar el colaborador.',
    terminate: 'No fue posible terminar el contrato del colaborador.',
  },
  cards: {
    teamTotal: 'Total del equipo',
    teamTotalHint: 'Personal registrado en RH',
    active: 'Activos',
    activeHint: 'Colaboradores operando hoy',
    training: 'Capacitación',
    trainingHint: 'Integración y onboarding',
    activeAreas: 'Áreas activas',
    activeAreasHint: (count: number) =>
      count === 1 ? '1 persona en vacaciones actualmente' : `${count} en vacaciones actualmente`,
  },
  filters: {
    title: 'Filtros',
    searchLabel: 'Buscar colaborador',
    searchPlaceholder: 'Nombre o código...',
    unit: 'Unidad',
    business: 'Negocio',
    department: 'Departamento',
    status: 'Estado',
    all: 'Todos',
    allUnits: 'Todas las unidades',
    allBusinesses: 'Todos los negocios',
  },
  table: {
    selectAllVisible: 'Seleccionar todos los colaboradores visibles',
    selectEmployee: (name: string) => `Seleccionar a ${name}`,
    emptyState: 'No se encontraron colaboradores con los filtros actuales.',
    defaultNewEmployee: 'Nuevo colaborador',
    defaultUnassignedRole: 'Sin asignar',
    defaultBusiness: 'Negocio A',
  },
  columns: {
    selection: 'Selección',
    collaborator: 'Nombre',
    lastName: 'Apellidos',
    email: 'Correo electrónico',
    position: 'Puesto',
    department: 'Departamento',
    unit: 'Unidad',
    business: 'Negocio',
    status: 'Estado',
    salary: 'Salario',
    payPeriod: 'Periodo de pago',
    contact: 'Contacto',
    joinDate: 'Ingreso',
    birthDate: 'Fecha de nacimiento',
    address: 'Dirección',
    curp: 'CURP',
    rfc: 'RFC',
    nss: 'NSS',
    actions: 'Acciones',
  },
  statusLabels: {
    Activo: 'Activo',
    Vacaciones: 'Vacaciones',
    Capacitacion: 'Capacitación',
    Inactivo: 'Inactivo',
  },
  paymentPeriods: {
    weekly: 'Semanal',
    biweekly: 'Quincenal',
    monthly: 'Mensual',
  },
};

const employeesEn = {
  title: 'Employees',
  subtitle: 'Manage your team and workforce details',
  configureColumns: 'Columns',
  addEmployee: 'Add employee',
  loading: 'Loading employees...',
  backendConnected:
    'Employees on this screen are now loaded from the Spring backend. Create, update, terminate, and delete actions are also connected.',
  errors: {
    load: 'Unable to load employees.',
    save: 'Unable to save employee.',
    delete: 'Unable to delete employee.',
    terminate: 'Unable to terminate employee.',
  },
  cards: {
    teamTotal: 'Team total',
    teamTotalHint: 'Registered HR employees',
    active: 'Active',
    activeHint: 'Employees operating today',
    training: 'Training',
    trainingHint: 'Onboarding and enablement',
    activeAreas: 'Active areas',
    activeAreasHint: (count: number) =>
      count === 1 ? '1 employee currently on vacation' : `${count} employees currently on vacation`,
  },
  filters: {
    title: 'Filters',
    searchLabel: 'Search employee',
    searchPlaceholder: 'Name or code...',
    unit: 'Unit',
    business: 'Business',
    department: 'Department',
    status: 'Status',
    all: 'All',
    allUnits: 'All units',
    allBusinesses: 'All businesses',
  },
  table: {
    selectAllVisible: 'Select all visible employees',
    selectEmployee: (name: string) => `Select ${name}`,
    emptyState: 'No employees matched the current filters.',
    defaultNewEmployee: 'New employee',
    defaultUnassignedRole: 'Unassigned',
    defaultBusiness: 'Business A',
  },
  columns: {
    selection: 'Selection',
    collaborator: 'Name',
    lastName: 'Last name',
    email: 'Email',
    position: 'Position',
    department: 'Department',
    unit: 'Unit',
    business: 'Business',
    status: 'Status',
    salary: 'Salary',
    payPeriod: 'Pay period',
    contact: 'Contact',
    joinDate: 'Join date',
    birthDate: 'Date of birth',
    address: 'Address',
    curp: 'National ID',
    rfc: 'Tax ID',
    nss: 'Social security',
    actions: 'Actions',
  },
  statusLabels: {
    Activo: 'Active',
    Vacaciones: 'Vacation',
    Capacitacion: 'Training',
    Inactivo: 'Inactive',
  },
  paymentPeriods: {
    weekly: 'Weekly',
    biweekly: 'Biweekly',
    monthly: 'Monthly',
  },
};

const baseEnglish = {
  shell: {
    title: 'Human Resources',
    subtitle: 'Manage employees, attendance, payroll and more.',
    back: 'Back',
    tabs: {
      collaborators: 'Employees',
      attendance: 'Attendance',
      control: 'Control',
      payroll: 'Payroll',
      announcements: 'Announcements',
      assets: 'Assets',
      records: 'Records',
      permissions: 'Permissions',
      incentives: 'Incentives',
      kpis: 'KPIs',
    },
  },
  attendance: {
    title: 'Attendance',
    subtitle: 'Register your check-in/check-out with photo and location.',
    viewRecords: 'View my records',
    markBlock: 'Mark block',
    collaborator: 'Employee',
    photo: 'Photo',
    photoRequired: 'Required to register',
    takePhoto: 'Take photo',
    photoTaken: 'Photo taken',
    photoTip: 'Tip: keep your face centered and use good lighting.',
    location: 'Location',
    locationRequired: 'Required to register',
    getLocation: 'Get location',
    locationObtained: 'Location obtained',
    noLocation: 'No location',
    register: 'Record',
    registerHint: 'It will be enabled when there is photo + location',
    entry: 'Check-in',
    exit: 'Check-out',
    successEntry: (employee: string, time: string) => `Check-in recorded for ${employee} at ${time}.`,
    successExit: (employee: string, time: string) => `Check-out recorded for ${employee} at ${time}.`,
  },
  control: {
    title: 'Control',
    subtitle: 'Monitor attendance in real time and manage configurations.',
    registerLocations: 'Register locations',
    schedules: 'Schedules',
    kiosk: 'Kiosk',
    kioskLink: 'Kiosk link',
    kioskLinkCopied: 'Kiosk link copied successfully.',
    dailyAttendance: 'Attendance of the day',
    entry: 'Check-in',
    exit: 'Check-out',
    noRecord: 'No record',
    location: 'Location',
    attendanceCalendar: 'Attendance Calendar',
  },
  attendanceLocationModal: {
    title: 'Register locations',
    banner:
      'Set up your locations so the attendance table shows the place name instead of latitude/longitude by proximity. You can use Here (GPS) or paste a Google Maps link to extract coordinates.',
    activeLocations: (count: number) => `Active locations: ${count}`,
    unsavedChanges: 'Changes are not saved until you press Save.',
    noPendingChanges: 'No pending changes',
    fields: {
      name: 'Name',
      latitude: 'Latitude',
      longitude: 'Longitude',
      googleMapsLink: 'Google Maps link (optional)',
      altitude: 'Altitude (optional)',
      radius: 'Radius (m)',
    },
    placeholders: {
      name: 'Ex. Office',
      googleMapsLink: 'Paste the Google Maps link here',
      altitude: 'm.a.s.l.',
    },
    buttons: {
      extract: 'Extract',
      here: 'Here',
      add: 'Add',
      remove: 'Remove',
      load: 'Load',
      close: 'Close',
      save: 'Save',
    },
    table: {
      name: 'NAME',
      lat: 'LAT',
      lng: 'LNG',
      radius: 'RADIUS',
      action: 'ACTION',
    },
    tip:
      'Tip: in Google Maps, share the place and paste the link here. If the link is very short (maps.app.goo.gl), open it and copy the full URL.',
    alerts: {
      requiredFields: 'Please complete Name, Latitude, Longitude, and Radius.',
      noLocation: 'Unable to get the location.',
      permissionDenied:
        'Location permission denied. Please enable location permissions in your browser.',
      positionUnavailable: 'Location information is not available.',
      timeout: 'The request to get location timed out.',
      unsupported: 'Your browser does not support geolocation.',
    },
  },
  attendanceKiosk: {
    title: 'Kiosk · Attendance',
    intro:
      'Search your name and register your check-in. At the end of your shift, register your check-out.',
    greetings: {
      morning: 'Good morning ☀️',
      afternoon: 'Good afternoon ⛅',
      evening: 'Good evening 🌙',
    },
    messages: [
      'Take it easy and with pride. You are doing great.',
      'Your effort makes a difference. Keep going.',
      'Every day is a new opportunity. Make the most of it.',
      'Your work matters. Thank you for your dedication.',
      'You are a key part of the team. Great job.',
    ],
    checklist: {
      selectName: 'Select your name',
      getLocation: 'Get location',
      takePhoto: 'Take photo',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
    },
    labels: {
      date: 'Date',
      search: 'Search',
      employees: 'Employees',
      code: 'Code',
      photo: 'Photo',
      location: 'Location',
    },
    today: '(today)',
    searchPlaceholder: 'Name or code',
    noResults: 'No results.',
    selectEmployee: 'Select an employee',
    selectEmployeeHint: 'Use the search box or the list on the left',
    noPhoto: 'No photo',
    photoRequired: 'Required to register.',
    photoTaken: 'Photo taken',
    takePhoto: 'Take photo',
    photoTip: 'Tip: centered face and good lighting.',
    noLocation: 'No location',
    locationRequired: 'Required to register.',
    locationObtained: 'Location obtained',
    getLocation: 'Get location',
    enableWhenReady: 'Enabled when there is photo + location.',
    register: 'Register',
    toggleTip: 'Tip: single button — toggles check-in/check-out according to the selected type.',
    success: (employee: string, type: string, time: string) =>
      `Attendance recorded successfully\n\n${employee}\nType: ${type}\nTime: ${time}`,
  },
  attendanceSchedules: {
    title: 'Configure schedules',
    filters: {
      search: 'Search',
      searchPlaceholder: 'Name or code',
      unit: 'Unit',
      business: 'Business',
      allUnits: 'All',
      allBusinesses: 'All',
      searchButton: 'Search',
    },
    employees: {
      title: 'Employees',
      selected: 'Selected',
      code: 'Code',
      employee: 'Employee',
      department: 'Dept.',
      loadError: 'Unable to load employees',
    },
    schedule: {
      title: 'Schedule to apply',
      subtitle: 'It will be applied equally to everyone selected',
      clear: 'Clear',
      mode: 'Mode',
      strict: 'Strict schedule',
      open: 'Open schedule',
      modeHelp: 'Open: check in at any time. Strict: only within the configured schedule.',
      openEnabledTitle: 'Open schedule enabled',
      openEnabledBody:
        'Employees can register at any time. It is not necessary to configure specific times.',
      tolerance: 'Check-in tolerance',
      minutes: 'minutes',
      toleranceHelp: (minutes: number) =>
        `Employees may check in up to ${minutes} minutes late without penalty.`,
      blockAfterToleranceTitle: 'Do not allow check-in after tolerance time',
      blockAfterToleranceBody:
        'The registration will be blocked if the configured tolerance window has passed.',
      blockOutsideLocationTitle: 'Do not allow check-in outside the selected location',
      blockOutsideLocationBody: 'Registration will only be allowed from the configured location.',
      allowedLocation: 'Allowed location',
      days: {
        mon: 'Mon',
        tue: 'Tue',
        wed: 'Wed',
        thu: 'Thu',
        fri: 'Fri',
        sat: 'Sat',
        sun: 'Sun',
      },
      columns: {
        day: 'Day',
        entry: 'Check-in',
        exit: 'Check-out',
        meal: 'Meal (min)',
        break: 'Break',
      },
      availableLocations: {
        none: 'None',
        hq: 'Central Office - Monterrey',
        north: 'North Branch',
        south: 'South Branch',
        warehouse: 'Main Warehouse',
        distribution: 'Distribution Center',
      },
    },
    multiSelection: {
      title: 'Multiple selection',
      body: (count: number) =>
        `You have ${count} employees selected. The schedule will be applied equally to all of them.`,
    },
    buttons: {
      cancel: 'Cancel',
      apply: 'Apply to selected',
    },
    alerts: {
      selectAtLeastOne: 'You must select at least one employee.',
      success: (count: number, mode: string, toleranceText: string) =>
        `Schedules applied successfully\n\nEmployees: ${count}\nMode: ${mode}${toleranceText}\n\nThe schedules were configured correctly.`,
    },
  },
  attendanceCalendar: {
    title: 'Attendance Calendar',
    months: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    legend: {
      entryRegistered: 'Check-in registered',
      exitRegistered: 'Check-out registered',
      currentDay: 'Current day',
    },
    statusModalTitle: (day: number) => `Change status for day ${day}`,
    systemRecord: 'System Record',
    notEditable: 'Not editable',
    entry: 'Check-in',
    exit: 'Check-out',
    totalTime: 'Total time',
    viewGoogleMaps: 'View on Google Maps',
    manualUpdate: 'Change status manually:',
    buttons: {
      attendance: 'Mark as Attendance',
      absence: 'Mark as Absence',
      tardy: 'Mark as Tardy',
      rest: 'Mark as Rest',
    },
    statuses: {
      attendance: 'Attendance',
      absence: 'Absence',
      tardy: 'Tardy',
      rest: 'Rest',
      none: 'No status',
    },
    currentStatus: (label: string) => `Current status: ${label}`,
    noStatusAssigned: 'No status assigned',
  },
  announcements: {
    title: 'Announcements',
    subtitle: 'Send announcements and important messages to your employees',
    export: 'Export',
    newAnnouncement: 'New announcement',
    searchLabel: 'Filters',
    searchPlaceholder: 'Title or content...',
    type: 'Type',
    status: 'Status',
    audience: 'Recipients',
    all: 'All',
    audiences: {
      all: 'All',
      operations: 'Operations',
      leaders: 'Leaders',
      everyone: 'Everyone',
    },
    types: {
      General: 'General',
      Urgente: 'Urgent',
      Recordatorio: 'Reminder',
      Celebracion: 'Celebration',
    },
    statuses: {
      Publicado: 'Published',
      Programado: 'Scheduled',
      Borrador: 'Draft',
    },
    table: {
      title: 'Title',
      type: 'Type',
      recipients: 'Recipients',
      publicationDate: 'Publication date',
      reads: 'Reads',
      status: 'Status',
      actions: 'Actions',
    },
  },
  assets: {
    title: 'Company Assets',
    subtitle: 'Track assigned equipment, devices, and vehicles',
    newAsset: 'New asset',
    loading: 'Loading assets...',
    emptyState: 'No assets matched the current filters.',
    errors: {
      load: 'Unable to load assets.',
      save: 'Unable to save asset.',
      details: 'Unable to load asset details.',
      status: 'Unable to update asset status.',
    },
    cards: {
      total: 'Total assets',
      assigned: 'Assigned',
      available: 'Available',
      maintenance: 'Under maintenance',
    },
    searchPlaceholder: 'Search asset...',
    filters: {
      allTypes: 'All types',
      allStatuses: 'All statuses',
      allUnits: 'All units',
      computerEquipment: 'Computer equipment',
      attendanceControl: 'Attendance control',
      operation: 'Operations',
      maintenance: 'Maintenance',
      available: 'Available',
      assigned: 'Assigned',
      inMaintenance: 'Maintenance',
      custody: 'Custody',
      inactive: 'Inactive',
    },
    statuses: {
      Asignado: 'Assigned',
      Mantenimiento: 'Maintenance',
      Resguardo: 'Custody',
      Disponible: 'Available',
      Inactivo: 'Inactive',
    },
    table: {
      id: 'ID',
      type: 'Type',
      asset: 'Asset',
      model: 'Model',
      serialNumber: 'Serial number',
      responsible: 'Responsible',
      unit: 'Unit',
      status: 'Status',
      assignedAt: 'Assignment date',
      value: 'Value',
      notes: 'Notes',
      actions: 'Actions',
    },
    columnPicker: {
      button: 'Columns',
      title: 'Visible columns',
      subtitle: 'Select the asset table columns you want to display.',
      visibleCount: (visible: number, total: number) => `${visible} of ${total} columns visible`,
      selectAll: 'Select all',
      reset: 'Reset',
      required: 'Required column',
      cancel: 'Cancel',
      apply: 'Apply',
    },
    actionsMenu: {
      viewDetails: 'View details',
      edit: 'Edit',
      delete: 'Delete',
      reassign: 'Reassign',
      maintenance: 'Maintenance',
      deactivate: 'Deactivate',
      moreActions: (assetName: string) => `More actions for ${assetName}`,
    },
    actionAlerts: {
      details: 'Asset details',
      reassignPending: 'Reassignment flow will be connected here.',
      movedToMaintenance: (assetName: string) => `${assetName} was moved to maintenance.`,
      deactivated: (assetName: string) => `${assetName} was marked as inactive.`,
    },
    confirmDeactivate: {
      title: 'Deactivate asset',
      description: 'This action will mark the asset as inactive in the table.',
      confirm: 'Deactivate',
      cancel: 'Cancel',
    },
    detailsModal: {
      title: 'Asset details',
      subtitle: 'Review the full asset record, assignment, and audit information.',
      sections: {
        overview: 'Overview',
        assignment: 'Assignment',
        audit: 'Audit trail',
      },
      fields: {
        code: 'Asset code',
        type: 'Type',
        asset: 'Asset',
        model: 'Model',
        serialNumber: 'Serial number',
        responsible: 'Responsible',
        responsibleEmail: 'Responsible email',
        unit: 'Unit',
        status: 'Status',
        assignedAt: 'Assignment date',
        value: 'Value',
        notes: 'Notes',
        createdBy: 'Created by',
        createdAt: 'Created at',
        updatedBy: 'Updated by',
        updatedAt: 'Updated at',
      },
      empty: {
        unassigned: 'Unassigned',
        noEmail: 'No email',
        noUnit: 'No unit',
        noNotes: 'No notes recorded',
        system: 'System',
      },
      close: 'Close',
    },
    addNewAsset: {
      title: 'New asset',
      subtitle: 'Register a new company asset',
      editTitle: 'Edit asset',
      editSubtitle: 'Update the selected company asset',
      sections: {
        general: 'General information',
        assignment: 'Assignment',
        valueDetails: 'Value and details',
      },
      fields: {
        assetId: 'Asset ID',
        assetType: 'Asset type',
        assetName: 'Asset name',
        model: 'Model',
        serialNumber: 'Serial number',
        responsible: 'Responsible',
        unit: 'Unit',
        status: 'Status',
        assignedDate: 'Assignment date',
        value: 'Value (USD)',
        notes: 'Additional notes',
      },
      placeholders: {
        assetId: 'Ex: ACT-001',
        assetName: 'Ex: MacBook Pro 16',
        model: 'Ex: M2 Pro',
        serialNumber: 'Ex: MRE-2023-9445',
        responsible: 'Responsible name',
        unit: 'Select unit',
        status: 'Select status',
        value: 'Ex: $45,000',
        notes: 'Additional information about the asset...',
      },
      options: {
        laptop: 'Laptop',
        attendanceTerminal: 'Attendance terminal',
        mobileDevice: 'Mobile device',
        maintenanceKit: 'Maintenance kit',
        available: 'Available',
        assigned: 'Assigned',
        maintenance: 'Maintenance',
        custody: 'Custody',
        inactive: 'Inactive',
      },
      buttons: {
        cancel: 'Cancel',
        save: 'Save asset',
        saveChanges: 'Save changes',
      },
      success: (assetName: string) => `${assetName} was created successfully.`,
      successUpdated: (assetName: string) => `${assetName} was updated successfully.`,
    },
  },
  records: {
    title: 'Administrative Records',
    subtitle: 'History of events, incidents, and employee reports',
    newRecord: 'New record',
    showFilters: 'Show filters',
    hideFilters: 'Hide filters',
    searchPlaceholder: 'Search by folio, employee, title, or description...',
    filters: {
      collaborator: 'Employee',
      allCollaborators: 'All employees',
      type: 'Event type',
      allTypes: 'All types',
      severity: 'Severity level',
      allLevels: 'All levels',
      status: 'Status',
      allStatuses: 'All statuses',
      fromDate: 'Date from',
      toDate: 'Date to',
    },
    types: {
      Reconocimiento: 'Recognition',
      Amonestación: 'Warning',
      Incidente: 'Incident',
      Sanción: 'Sanction',
    },
    statuses: {
      Revisado: 'Reviewed',
      Resuelto: 'Resolved',
      Pendiente: 'Pending',
    },
    table: {
      folio: 'Folio',
      collaborator: 'Employee',
      eventType: 'Event type',
      title: 'Title',
      eventDate: 'Event date',
      severity: 'Severity',
      status: 'Status',
      actions: 'Actions',
    },
  },
  permissions: {
    title: 'Permissions and absences',
    subtitle: 'Manage employee leave, vacation, and absence requests',
    requestPermission: 'Request permission',
    cards: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      thisMonth: 'This month',
    },
    table: {
      folio: 'Folio',
      collaborator: 'Employee',
      permissionType: 'Permission type',
      startDate: 'Start date',
      endDate: 'End date',
      days: 'Days',
      status: 'Status',
      actions: 'Actions',
    },
  },
  payroll: {
    title: 'Payroll',
    subtitle: 'Manage pay periods and process payrolls',
    preferences: 'Payroll preferences',
    filtersTitle: 'Filters',
    activeFilters: 'Active',
    clearFilters: 'Clear filters',
    filters: {
      period: 'Period',
      unit: 'Unit',
      business: 'Business',
      allRecords: 'All records',
      thisMonth: 'This month',
      thisYear: 'This year',
      allUnits: 'All',
      allBusinesses: 'All',
    },
    table: {
      period: 'Period',
      dates: 'Dates',
      frequency: 'Frequency',
      employees: 'Employees',
      totalAmount: 'Total amount',
      status: 'Status',
      unit: 'Unit',
      business: 'Business',
      actions: 'Actions',
      noResults: 'No payrolls found',
      adjustFilters: 'Try adjusting the search filters',
      payrollCount: 'payroll(s)',
      employeeCount: 'employees',
      total: 'Total',
    },
  },
  kpis: {
    title: 'Human Resources KPIs',
    subtitle: 'Key performance indicators for team and personnel management',
    filterPeriod: 'Filter period',
    exportReport: 'Export report',
    filters: {
      year: 'Year',
      month: 'Month',
      january: 'January',
      february: 'February',
      march: 'March',
      allUnits: 'All units',
      allDepartments: 'All departments',
    },
    sections: {
      team: 'Team',
      workforceManagement: 'Workforce management',
      operation: 'Operations',
      teamAttendance: 'Team attendance',
      permissionDistribution: 'Permission distribution',
      unitSummary: 'Business unit summary',
    },
    cards: {
      activeEmployees: 'Active employees',
      punctuality: 'Punctuality',
      absenteeism: 'Absenteeism',
      tardiness: 'Tardiness',
      permissionsRequested: 'Permission requests',
      absenceDays: 'Absence days',
      payrollCost: 'Payroll cost',
      avgCostPerEmployee: 'Average cost per employee',
      assignedAssets: 'Assigned assets',
      assetsInMaintenance: 'Assets in maintenance',
      workIncidents: 'Work incidents',
      teamHealth: 'Team health',
    },
    table: {
      unit: 'Unit',
      employees: 'Employees',
      attendance: 'Attendance',
      absenteeism: 'Absenteeism',
      payroll: 'Payroll',
      incidents: 'Incidents',
      total: 'TOTAL',
    },
  },
  employees: employeesEn,
};

const baseSpanish = {
  shell: {
    title: 'Recursos Humanos',
    subtitle: 'Administra colaboradores, asistencia, nómina y más.',
    back: 'Regresar',
    tabs: {
      collaborators: 'Colaboradores',
      attendance: 'Asistencia',
      control: 'Control',
      payroll: 'Nómina',
      announcements: 'Comunicados',
      assets: 'Activos',
      records: 'Actas',
      permissions: 'Permisos',
      incentives: 'Incentives',
      kpis: 'KPIs',
    },
  },
  attendance: {
    title: 'Asistencia',
    subtitle: 'Registra tu entrada/salida con foto y ubicación.',
    viewRecords: 'Ver mis registros',
    markBlock: 'Marcar bloque',
    collaborator: 'Colaborador',
    photo: 'Foto',
    photoRequired: 'Requerida para registrar',
    takePhoto: 'Tomar foto',
    photoTaken: 'Foto tomada',
    photoTip: 'Tip: coloca el rostro centrado y con buena luz.',
    location: 'Ubicación',
    locationRequired: 'Requerida para registrar',
    getLocation: 'Obtener ubicación',
    locationObtained: 'Ubicación obtenida',
    noLocation: 'Sin ubicación',
    register: 'Registro',
    registerHint: 'Se abrirá cuando hay foto + ubicación',
    entry: 'Entrada',
    exit: 'Salida',
    successEntry: (employee: string, time: string) => `Entrada registrada para ${employee} a las ${time}.`,
    successExit: (employee: string, time: string) => `Salida registrada para ${employee} a las ${time}.`,
  },
  control: {
    title: 'Control',
    subtitle: 'Monitorea la asistencia en tiempo real y gestiona configuraciones.',
    registerLocations: 'Registrar ubicaciones',
    schedules: 'Horarios',
    kiosk: 'Kiosko',
    kioskLink: 'Kiosko Link',
    kioskLinkCopied: 'Kiosko Link copiado correctamente.',
    dailyAttendance: 'Asistencia del día',
    entry: 'Entrada',
    exit: 'Salida',
    noRecord: 'Sin registro',
    location: 'Ubicación',
    attendanceCalendar: 'Calendario de Asistencia',
  },
  attendanceLocationModal: {
    title: 'Registrar ubicaciones',
    banner:
      'Configura tus ubicaciones para que en la tabla de asistencia se muestre el nombre del lugar en vez de la latitud/longitud por cercanía. Puedes usar Aquí (GPS) o pegar un enlace de Google Maps para extraer coordenadas.',
    activeLocations: (count: number) => `Ubicaciones activas: ${count}`,
    unsavedChanges: 'Los cambios no se guardan hasta presionar Guardar.',
    noPendingChanges: 'Sin cambios pendientes',
    fields: {
      name: 'Nombre',
      latitude: 'Latitud',
      longitude: 'Longitud',
      googleMapsLink: 'Enlace de Google Maps (opcional)',
      altitude: 'Altitud (opcional)',
      radius: 'Radio (m)',
    },
    placeholders: {
      name: 'Ej. Oficina',
      googleMapsLink: 'Pega aquí el enlace de Google Maps',
      altitude: 'm.s.n.m.',
    },
    buttons: {
      extract: 'Extraer',
      here: 'Aquí',
      add: 'Agregar',
      remove: 'Quitar',
      load: 'Cargar',
      close: 'Cerrar',
      save: 'Guardar',
    },
    table: {
      name: 'NOMBRE',
      lat: 'LAT',
      lng: 'LNG',
      radius: 'RADIO',
      action: 'ACCIÓN',
    },
    tip:
      'Tip: en Google Maps, comparte el lugar y pega el enlace aquí. Si el enlace es muy corto (maps.app.goo.gl), ábrelo y copia la URL completa.',
    alerts: {
      requiredFields: 'Por favor completa Nombre, Latitud, Longitud y Radio.',
      noLocation: 'No se pudo obtener la ubicación.',
      permissionDenied:
        'Permiso de ubicación denegado. Por favor, habilita los permisos de ubicación en tu navegador.',
      positionUnavailable: 'La información de ubicación no está disponible.',
      timeout: 'El tiempo de espera para obtener la ubicación ha expirado.',
      unsupported: 'Tu navegador no soporta geolocalización.',
    },
  },
  attendanceKiosk: {
    title: 'Kiosco · Pase de lista',
    intro:
      'Busca tu nombre y registra tu ingreso. Al terminar tu jornada, registra tu salida.',
    greetings: {
      morning: 'Buenos días ☀️',
      afternoon: 'Buenas tardes ⛅',
      evening: 'Buenas noches 🌙',
    },
    messages: [
      'Hazlo con calma y con orgullo. Vas bien.',
      'Tu esfuerzo hace la diferencia. Sigue adelante.',
      'Cada día es una nueva oportunidad. Aprovéchala.',
      'Tu trabajo importa. Gracias por tu dedicación.',
      'Eres parte fundamental del equipo. Excelente trabajo.',
    ],
    checklist: {
      selectName: 'Selecciona tu nombre',
      getLocation: 'Obtén ubicación',
      takePhoto: 'Toma foto',
      checkIn: 'Ingreso',
      checkOut: 'Salida',
    },
    labels: {
      date: 'Fecha',
      search: 'Buscar',
      employees: 'Colaboradores',
      code: 'Código',
      photo: 'Foto',
      location: 'Ubicación',
    },
    today: '(hoy)',
    searchPlaceholder: 'Nombre o código',
    noResults: 'Sin resultados.',
    selectEmployee: 'Selecciona un colaborador',
    selectEmployeeHint: 'Usa el buscador o la lista de la izquierda',
    noPhoto: 'Sin foto',
    photoRequired: 'Requerida para marcar.',
    photoTaken: 'Foto tomada',
    takePhoto: 'Tomar foto',
    photoTip: 'Tip: rostro centrado y buena luz.',
    noLocation: 'Sin ubicación',
    locationRequired: 'Requerida para marcar.',
    locationObtained: 'Ubicación obtenida',
    getLocation: 'Obtener ubicación',
    enableWhenReady: 'Se habilita cuando hay foto + ubicación.',
    register: 'Registrar',
    toggleTip: 'Tip: botón único — alterna ingreso/salida según el tipo seleccionado.',
    success: (employee: string, type: string, time: string) =>
      `Asistencia registrada exitosamente\n\n${employee}\nTipo: ${type}\nHora: ${time}`,
  },
  attendanceSchedules: {
    title: 'Configurar horarios',
    filters: {
      search: 'Buscar',
      searchPlaceholder: 'Nombre o código',
      unit: 'Unidad',
      business: 'Negocio',
      allUnits: 'Todas',
      allBusinesses: 'Todos',
      searchButton: 'Buscar',
    },
    employees: {
      title: 'Colaboradores',
      selected: 'Seleccionados',
      code: 'Código',
      employee: 'Colaborador',
      department: 'Depto.',
      loadError: 'No se pudo cargar colaboradores',
    },
    schedule: {
      title: 'Horario a aplicar',
      subtitle: 'Se aplicará igual a todos los seleccionados',
      clear: 'Limpiar',
      mode: 'Modo',
      strict: 'Horario estricto',
      open: 'Horario abierto',
      modeHelp: 'Abierto: marca a cualquier hora. Estricto: sólo dentro del horario configurado.',
      openEnabledTitle: 'Horario abierto activado',
      openEnabledBody:
        'Los colaboradores podrán marcar a cualquier hora. No es necesario configurar horarios específicos.',
      tolerance: 'Tolerancia en ingreso',
      minutes: 'minutos',
      toleranceHelp: (minutes: number) =>
        `Los colaboradores podrán marcar ingreso hasta ${minutes} minutos tarde sin penalización.`,
      blockAfterToleranceTitle: 'No permitir registro después de tiempo de tolerancia',
      blockAfterToleranceBody:
        'Se bloqueará el registro si pasa el tiempo de tolerancia configurado.',
      blockOutsideLocationTitle: 'No permitir registro fuera de la ubicación seleccionada',
      blockOutsideLocationBody: 'Solo se podrá registrar desde la ubicación configurada.',
      allowedLocation: 'Ubicación permitida',
      days: {
        mon: 'Lun',
        tue: 'Mar',
        wed: 'Mié',
        thu: 'Jue',
        fri: 'Vie',
        sat: 'Sáb',
        sun: 'Dom',
      },
      columns: {
        day: 'Día',
        entry: 'Entrada',
        exit: 'Salida',
        meal: 'Comida (min)',
        break: 'Descanso',
      },
      availableLocations: {
        none: 'Ninguna',
        hq: 'Oficina Central - Monterrey',
        north: 'Sucursal Norte',
        south: 'Sucursal Sur',
        warehouse: 'Almacén Principal',
        distribution: 'Centro de Distribución',
      },
    },
    multiSelection: {
      title: 'Selección múltiple',
      body: (count: number) =>
        `Tienes ${count} colaboradores seleccionados. El horario se aplicará a todos por igual.`,
    },
    buttons: {
      cancel: 'Cancelar',
      apply: 'Aplicar a seleccionados',
    },
    alerts: {
      selectAtLeastOne: 'Debes seleccionar al menos un colaborador.',
      success: (count: number, mode: string, toleranceText: string) =>
        `Horarios aplicados exitosamente\n\nColaboradores: ${count}\nModo: ${mode}${toleranceText}\n\nLos horarios han sido configurados correctamente.`,
    },
  },
  attendanceCalendar: {
    title: 'Calendario de Asistencia',
    months: [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio',
      'Julio',
      'Agosto',
      'Septiembre',
      'Octubre',
      'Noviembre',
      'Diciembre',
    ],
    weekdays: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    legend: {
      entryRegistered: 'Entrada registrada',
      exitRegistered: 'Salida registrada',
      currentDay: 'Día actual',
    },
    statusModalTitle: (day: number) => `Modificar estatus del día ${day}`,
    systemRecord: 'Registro del Sistema',
    notEditable: 'No modificable',
    entry: 'Entrada',
    exit: 'Salida',
    totalTime: 'Tiempo total',
    viewGoogleMaps: 'Ver en Google Maps',
    manualUpdate: 'Modificar estatus manualmente:',
    buttons: {
      attendance: 'Marcar como Asistencia',
      absence: 'Marcar como Falta',
      tardy: 'Marcar como Retardo',
      rest: 'Marcar como Descanso',
    },
    statuses: {
      attendance: 'Asistencia',
      absence: 'Falta',
      tardy: 'Retardo',
      rest: 'Descanso',
      none: 'Sin estatus',
    },
    currentStatus: (label: string) => `Estatus actual: ${label}`,
    noStatusAssigned: 'Sin estatus asignado',
  },
  announcements: {
    title: 'Comunicados',
    subtitle: 'Envía anuncios y mensajes importantes a tus colaboradores',
    export: 'Exportar',
    newAnnouncement: 'Nuevo comunicado',
    searchLabel: 'Filtros',
    searchPlaceholder: 'Título o contenido...',
    type: 'Tipo',
    status: 'Estado',
    audience: 'Destinatarios',
    all: 'Todos',
    audiences: {
      all: 'Todos',
      operations: 'Operaciones',
      leaders: 'Líderes',
      everyone: 'Todo el personal',
    },
    types: {
      General: 'General',
      Urgente: 'Urgente',
      Recordatorio: 'Recordatorio',
      Celebracion: 'Celebración',
    },
    statuses: {
      Publicado: 'Publicado',
      Programado: 'Programado',
      Borrador: 'Borrador',
    },
    table: {
      title: 'Título',
      type: 'Tipo',
      recipients: 'Destinatarios',
      publicationDate: 'Fecha publicación',
      reads: 'Leídos',
      status: 'Estado',
      actions: 'Acciones',
    },
  },
  assets: {
    title: 'Activos de la Empresa',
    subtitle: 'Control de equipos, dispositivos y vehículos asignados',
    newAsset: 'Nuevo activo',
    loading: 'Cargando activos...',
    emptyState: 'No se encontraron activos con los filtros actuales.',
    errors: {
      load: 'No fue posible cargar los activos.',
      save: 'No fue posible guardar el activo.',
      details: 'No fue posible cargar los detalles del activo.',
      status: 'No fue posible actualizar el estado del activo.',
    },
    cards: {
      total: 'Total de activos',
      assigned: 'Asignados',
      available: 'Disponibles',
      maintenance: 'En mantenimiento',
    },
    searchPlaceholder: 'Buscar activo...',
    filters: {
      allTypes: 'Todos los tipos',
      allStatuses: 'Todos los estados',
      allUnits: 'Todas las unidades',
      computerEquipment: 'Equipo de computo',
      attendanceControl: 'Control de asistencia',
      operation: 'Operacion',
      maintenance: 'Mantenimiento',
      available: 'Disponible',
      assigned: 'Asignado',
      inMaintenance: 'Mantenimiento',
      custody: 'Resguardo',
      inactive: 'Inactivo',
    },
    statuses: {
      Asignado: 'Asignado',
      Mantenimiento: 'Mantenimiento',
      Resguardo: 'Resguardo',
      Disponible: 'Disponible',
      Inactivo: 'Inactivo',
    },
    table: {
      id: 'ID',
      type: 'Tipo',
      asset: 'Activo',
      model: 'Modelo',
      serialNumber: 'Número de serie',
      responsible: 'Responsable',
      unit: 'Unidad',
      status: 'Estado',
      assignedAt: 'Fecha asignación',
      value: 'Valor',
      notes: 'Notas',
      actions: 'Acciones',
    },
    columnPicker: {
      button: 'Columnas',
      title: 'Columnas visibles',
      subtitle: 'Selecciona las columnas de activos que deseas ver en la tabla.',
      visibleCount: (visible: number, total: number) => `${visible} de ${total} columnas visibles`,
      selectAll: 'Seleccionar todas',
      reset: 'Restablecer',
      required: 'Columna obligatoria',
      cancel: 'Cancelar',
      apply: 'Aplicar',
    },
    actionsMenu: {
      viewDetails: 'Ver detalles',
      edit: 'Editar',
      delete: 'Eliminar',
      reassign: 'Reasignar',
      maintenance: 'Mantenimiento',
      deactivate: 'Dar de baja',
      moreActions: (assetName: string) => `Más acciones para ${assetName}`,
    },
    actionAlerts: {
      details: 'Detalles del activo',
      reassignPending: 'Aquí se conectará el flujo de reasignación.',
      movedToMaintenance: (assetName: string) => `${assetName} se movió a mantenimiento.`,
      deactivated: (assetName: string) => `${assetName} se marcó como inactivo.`,
    },
    confirmDeactivate: {
      title: 'Dar de baja activo',
      description: 'Esta acción marcará el activo como inactivo dentro de la tabla.',
      confirm: 'Dar de baja',
      cancel: 'Cancelar',
    },
    detailsModal: {
      title: 'Detalles del activo',
      subtitle: 'Revisa el registro completo del activo, su asignación y su rastro de auditoría.',
      sections: {
        overview: 'Resumen',
        assignment: 'Asignación',
        audit: 'Auditoría',
      },
      fields: {
        code: 'Código del activo',
        type: 'Tipo',
        asset: 'Activo',
        model: 'Modelo',
        serialNumber: 'Número de serie',
        responsible: 'Responsable',
        responsibleEmail: 'Correo del responsable',
        unit: 'Unidad',
        status: 'Estado',
        assignedAt: 'Fecha de asignación',
        value: 'Valor',
        notes: 'Notas',
        createdBy: 'Creado por',
        createdAt: 'Creado el',
        updatedBy: 'Actualizado por',
        updatedAt: 'Actualizado el',
      },
      empty: {
        unassigned: 'Sin asignar',
        noEmail: 'Sin correo',
        noUnit: 'Sin unidad',
        noNotes: 'Sin notas registradas',
        system: 'Sistema',
      },
      close: 'Cerrar',
    },
    addNewAsset: {
      title: 'Nuevo activo',
      subtitle: 'Registra un nuevo activo de la empresa',
      editTitle: 'Editar activo',
      editSubtitle: 'Actualiza el activo seleccionado de la empresa',
      sections: {
        general: 'Información general',
        assignment: 'Asignación',
        valueDetails: 'Valor y detalles',
      },
      fields: {
        assetId: 'ID del activo',
        assetType: 'Tipo de activo',
        assetName: 'Nombre del activo',
        model: 'Modelo',
        serialNumber: 'Número de serie',
        responsible: 'Responsable',
        unit: 'Unidad',
        status: 'Estado',
        assignedDate: 'Fecha de asignación',
        value: 'Valor (USD)',
        notes: 'Notas adicionales',
      },
      placeholders: {
        assetId: 'Ej: ACT-001',
        assetName: 'Ej: MacBook Pro 16',
        model: 'Ej: M2 Pro',
        serialNumber: 'Ej: MRE-2023-9445',
        responsible: 'Nombre del responsable',
        unit: 'Seleccionar unidad',
        status: 'Seleccionar estado',
        value: 'Ej: $45,000',
        notes: 'Información adicional sobre el activo...',
      },
      options: {
        laptop: 'Laptop',
        attendanceTerminal: 'Terminal de asistencia',
        mobileDevice: 'Dispositivo móvil',
        maintenanceKit: 'Kit de mantenimiento',
        available: 'Disponible',
        assigned: 'Asignado',
        maintenance: 'Mantenimiento',
        custody: 'Resguardo',
        inactive: 'Inactivo',
      },
      buttons: {
        cancel: 'Cancelar',
        save: 'Guardar activo',
        saveChanges: 'Guardar cambios',
      },
      success: (assetName: string) => `${assetName} se creó correctamente.`,
      successUpdated: (assetName: string) => `${assetName} se actualizó correctamente.`,
    },
  },
  records: {
    title: 'Actas administrativas',
    subtitle: 'Historial de eventos, incidentes y reportes de colaboradores',
    newRecord: 'Nueva acta',
    showFilters: 'Mostrar filtros',
    hideFilters: 'Ocultar filtros',
    searchPlaceholder: 'Buscar por folio, colaborador, título o descripción...',
    filters: {
      collaborator: 'Colaborador',
      allCollaborators: 'Todos los colaboradores',
      type: 'Tipo de evento',
      allTypes: 'Todos los tipos',
      severity: 'Nivel de gravedad',
      allLevels: 'Todos los niveles',
      status: 'Estado',
      allStatuses: 'Todos los estados',
      fromDate: 'Fecha desde',
      toDate: 'Fecha hasta',
    },
    types: {
      Reconocimiento: 'Reconocimiento',
      Amonestación: 'Amonestación',
      Incidente: 'Incidente',
      Sanción: 'Sanción',
    },
    statuses: {
      Revisado: 'Revisado',
      Resuelto: 'Resuelto',
      Pendiente: 'Pendiente',
    },
    table: {
      folio: 'Folio',
      collaborator: 'Colaborador',
      eventType: 'Tipo de evento',
      title: 'Título',
      eventDate: 'Fecha evento',
      severity: 'Gravedad',
      status: 'Estado',
      actions: 'Acciones',
    },
  },
  permissions: {
    title: 'Permisos y ausencias',
    subtitle: 'Gestiona solicitudes de permisos, vacaciones y ausencias de los colaboradores',
    requestPermission: 'Solicitar permiso',
    cards: {
      pending: 'Pendientes',
      approved: 'Aprobados',
      rejected: 'Rechazados',
      thisMonth: 'Este mes',
    },
    table: {
      folio: 'Folio',
      collaborator: 'Colaborador',
      permissionType: 'Tipo de permiso',
      startDate: 'Fecha inicio',
      endDate: 'Fecha fin',
      days: 'Días',
      status: 'Estado',
      actions: 'Acciones',
    },
  },
  payroll: {
    title: 'Nómina',
    subtitle: 'Gestiona períodos de pago y procesa nóminas',
    preferences: 'Preferencias de nómina',
    filtersTitle: 'Filtros',
    activeFilters: 'Activos',
    clearFilters: 'Limpiar filtros',
    filters: {
      period: 'Período',
      unit: 'Unidad',
      business: 'Negocio',
      allRecords: 'Todos los registros',
      thisMonth: 'Este mes',
      thisYear: 'Este año',
      allUnits: 'Todas',
      allBusinesses: 'Todos',
    },
    table: {
      period: 'Período',
      dates: 'Fechas',
      frequency: 'Frecuencia',
      employees: 'Colaboradores',
      totalAmount: 'Monto total',
      status: 'Estado',
      unit: 'Unidad',
      business: 'Negocio',
      actions: 'Acciones',
      noResults: 'No se encontraron nóminas',
      adjustFilters: 'Intenta ajustar los filtros de búsqueda',
      payrollCount: 'nómina(s)',
      employeeCount: 'colaboradores',
      total: 'Total',
    },
  },
  kpis: {
    title: 'KPIs de Recursos Humanos',
    subtitle: 'Indicadores clave de desempeño del equipo y gestión del personal',
    filterPeriod: 'Filtrar período',
    exportReport: 'Exportar reporte',
    filters: {
      year: 'Año',
      month: 'Mes',
      january: 'Enero',
      february: 'Febrero',
      march: 'Marzo',
      allUnits: 'Todas las unidades',
      allDepartments: 'Todos los departamentos',
    },
    sections: {
      team: 'Equipo',
      workforceManagement: 'Gestión del personal',
      operation: 'Operación',
      teamAttendance: 'Asistencia del equipo',
      permissionDistribution: 'Distribución de permisos',
      unitSummary: 'Resumen por unidad de negocio',
    },
    cards: {
      activeEmployees: 'Colaboradores activos',
      punctuality: 'Puntualidad',
      absenteeism: 'Ausentismo',
      tardiness: 'Retardos',
      permissionsRequested: 'Permisos solicitados',
      absenceDays: 'Días de ausencia',
      payrollCost: 'Costo de nómina',
      avgCostPerEmployee: 'Costo promedio por colaborador',
      assignedAssets: 'Activos asignados',
      assetsInMaintenance: 'Activos en mantenimiento',
      workIncidents: 'Incidentes laborales',
      teamHealth: 'Salud del equipo',
    },
    table: {
      unit: 'Unidad',
      employees: 'Colaboradores',
      attendance: 'Asistencia',
      absenteeism: 'Ausentismo',
      payroll: 'Nómina',
      incidents: 'Incidentes',
      total: 'TOTAL',
    },
  },
  employees: employeesEs,
};

const hrAttendanceFr = {
  attendance: {
    title: 'Présence',
    subtitle: 'Enregistrez votre entrée/sortie avec photo et localisation.',
    viewRecords: 'Voir mes registres',
    markBlock: 'Marquer bloc',
    collaborator: 'Employé',
    photo: 'Photo',
    photoRequired: 'Requise pour enregistrer',
    takePhoto: 'Prendre une photo',
    photoTaken: 'Photo prise',
    photoTip: 'Astuce : gardez votre visage centré et bien éclairé.',
    location: 'Localisation',
    locationRequired: 'Requise pour enregistrer',
    getLocation: 'Obtenir la localisation',
    locationObtained: 'Localisation obtenue',
    noLocation: 'Aucune localisation',
    register: 'Enregistrement',
    registerHint: 'S’active lorsque la photo et la localisation sont disponibles',
    entry: 'Entrée',
    exit: 'Sortie',
    successEntry: (employee: string, time: string) => `Entrée enregistrée pour ${employee} à ${time}.`,
    successExit: (employee: string, time: string) => `Sortie enregistrée pour ${employee} à ${time}.`,
  },
  control: {
    title: 'Contrôle',
    subtitle: 'Surveillez la présence en temps réel et gérez la configuration.',
    registerLocations: 'Enregistrer les emplacements',
    schedules: 'Horaires',
    kiosk: 'Kiosque',
    kioskLink: 'Lien du kiosque',
    kioskLinkCopied: 'Lien du kiosque copié avec succès.',
    dailyAttendance: 'Présence du jour',
    entry: 'Entrée',
    exit: 'Sortie',
    noRecord: 'Aucun enregistrement',
    location: 'Localisation',
    attendanceCalendar: 'Calendrier de présence',
  },
  attendanceLocationModal: {
    title: 'Enregistrer les emplacements',
    banner:
      'Configurez vos emplacements afin que le tableau de présence affiche le nom du lieu au lieu de la latitude/longitude. Vous pouvez utiliser Ici (GPS) ou coller un lien Google Maps pour extraire les coordonnées.',
    activeLocations: (count: number) => `Emplacements actifs : ${count}`,
    unsavedChanges: 'Les modifications ne sont pas enregistrées tant que vous n’appuyez pas sur Enregistrer.',
    noPendingChanges: 'Aucun changement en attente',
    fields: {
      name: 'Nom',
      latitude: 'Latitude',
      longitude: 'Longitude',
      googleMapsLink: 'Lien Google Maps (optionnel)',
      altitude: 'Altitude (optionnelle)',
      radius: 'Rayon (m)',
    },
    placeholders: {
      name: 'Ex. Bureau',
      googleMapsLink: 'Collez ici le lien Google Maps',
      altitude: 'm',
    },
    buttons: {
      extract: 'Extraire',
      here: 'Ici',
      add: 'Ajouter',
      remove: 'Retirer',
      load: 'Charger',
      close: 'Fermer',
      save: 'Enregistrer',
    },
    table: {
      name: 'NOM',
      lat: 'LAT',
      lng: 'LNG',
      radius: 'RAYON',
      action: 'ACTION',
    },
    tip:
      'Astuce : dans Google Maps, partagez le lieu et collez le lien ici. Si le lien est très court (maps.app.goo.gl), ouvrez-le et copiez l’URL complète.',
    alerts: {
      requiredFields: 'Veuillez remplir le nom, la latitude, la longitude et le rayon.',
      noLocation: 'Impossible d’obtenir la localisation.',
      permissionDenied:
        'Permission de localisation refusée. Veuillez activer les autorisations de localisation dans votre navigateur.',
      positionUnavailable: 'Les informations de localisation ne sont pas disponibles.',
      timeout: 'Le délai pour obtenir la localisation a expiré.',
      unsupported: 'Votre navigateur ne prend pas en charge la géolocalisation.',
    },
  },
  attendanceKiosk: {
    title: 'Kiosque · Présence',
    intro:
      'Recherchez votre nom et enregistrez votre entrée. À la fin de votre quart, enregistrez votre sortie.',
    greetings: {
      morning: 'Bonjour ☀️',
      afternoon: 'Bon après-midi ⛅',
      evening: 'Bonsoir 🌙',
    },
    messages: [
      'Avancez calmement et avec fierté. Vous allez bien.',
      'Votre effort fait la différence. Continuez ainsi.',
      'Chaque journée est une nouvelle occasion. Profitez-en.',
      'Votre travail compte. Merci pour votre engagement.',
      'Vous êtes une partie essentielle de l’équipe. Excellent travail.',
    ],
    checklist: {
      selectName: 'Sélectionnez votre nom',
      getLocation: 'Obtenez la localisation',
      takePhoto: 'Prenez une photo',
      checkIn: 'Entrée',
      checkOut: 'Sortie',
    },
    labels: {
      date: 'Date',
      search: 'Rechercher',
      employees: 'Employés',
      code: 'Code',
      photo: 'Photo',
      location: 'Localisation',
    },
    today: '(aujourd’hui)',
    searchPlaceholder: 'Nom ou code',
    noResults: 'Aucun résultat.',
    selectEmployee: 'Sélectionnez un employé',
    selectEmployeeHint: 'Utilisez la recherche ou la liste à gauche',
    noPhoto: 'Aucune photo',
    photoRequired: 'Requise pour pointer.',
    photoTaken: 'Photo prise',
    takePhoto: 'Prendre une photo',
    photoTip: 'Astuce : visage centré et bonne lumière.',
    noLocation: 'Aucune localisation',
    locationRequired: 'Requise pour pointer.',
    locationObtained: 'Localisation obtenue',
    getLocation: 'Obtenir la localisation',
    enableWhenReady: 'S’active lorsque la photo et la localisation sont disponibles.',
    register: 'Enregistrer',
    toggleTip: 'Astuce : bouton unique — alterne entrée/sortie selon le type sélectionné.',
    success: (employee: string, type: string, time: string) =>
      `Présence enregistrée avec succès\n\n${employee}\nType : ${type}\nHeure : ${time}`,
  },
  attendanceSchedules: {
    title: 'Configurer les horaires',
    filters: {
      search: 'Rechercher',
      searchPlaceholder: 'Nom ou code',
      unit: 'Unité',
      business: 'Entreprise',
      allUnits: 'Toutes',
      allBusinesses: 'Toutes',
      searchButton: 'Rechercher',
    },
    employees: {
      title: 'Employés',
      selected: 'Sélectionnés',
      code: 'Code',
      employee: 'Employé',
      department: 'Dépt.',
      loadError: 'Impossible de charger les employés',
    },
    schedule: {
      title: 'Horaire à appliquer',
      subtitle: 'S’appliquera de la même manière à toutes les personnes sélectionnées',
      clear: 'Effacer',
      mode: 'Mode',
      strict: 'Horaire strict',
      open: 'Horaire ouvert',
      modeHelp: 'Ouvert : pointage à toute heure. Strict : uniquement dans l’horaire configuré.',
      openEnabledTitle: 'Horaire ouvert activé',
      openEnabledBody:
        'Les employés peuvent pointer à tout moment. Il n’est pas nécessaire de configurer des horaires précis.',
      tolerance: 'Tolérance d’entrée',
      minutes: 'minutes',
      toleranceHelp: (minutes: number) =>
        `Les employés peuvent pointer jusqu’à ${minutes} minutes de retard sans pénalité.`,
      blockAfterToleranceTitle: 'Ne pas autoriser l’enregistrement après le délai de tolérance',
      blockAfterToleranceBody:
        'L’enregistrement sera bloqué si le délai de tolérance configuré est dépassé.',
      blockOutsideLocationTitle: 'Ne pas autoriser l’enregistrement hors de l’emplacement sélectionné',
      blockOutsideLocationBody: 'L’enregistrement sera autorisé uniquement depuis l’emplacement configuré.',
      allowedLocation: 'Emplacement autorisé',
      days: {
        mon: 'Lun',
        tue: 'Mar',
        wed: 'Mer',
        thu: 'Jeu',
        fri: 'Ven',
        sat: 'Sam',
        sun: 'Dim',
      },
      columns: {
        day: 'Jour',
        entry: 'Entrée',
        exit: 'Sortie',
        meal: 'Repas (min)',
        break: 'Pause',
      },
      availableLocations: {
        none: 'Aucun',
        hq: 'Bureau central - Monterrey',
        north: 'Succursale nord',
        south: 'Succursale sud',
        warehouse: 'Entrepôt principal',
        distribution: 'Centre de distribution',
      },
    },
    multiSelection: {
      title: 'Sélection multiple',
      body: (count: number) =>
        `Vous avez ${count} employés sélectionnés. L’horaire sera appliqué de la même manière à tous.`,
    },
    buttons: {
      cancel: 'Annuler',
      apply: 'Appliquer aux sélectionnés',
    },
    alerts: {
      selectAtLeastOne: 'Vous devez sélectionner au moins un employé.',
      success: (count: number, mode: string, toleranceText: string) =>
        `Horaires appliqués avec succès\n\nEmployés : ${count}\nMode : ${mode}${toleranceText}\n\nLes horaires ont été configurés correctement.`,
    },
  },
  attendanceCalendar: {
    title: 'Calendrier de présence',
    months: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    weekdays: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    legend: {
      entryRegistered: 'Entrée enregistrée',
      exitRegistered: 'Sortie enregistrée',
      currentDay: 'Jour actuel',
    },
    statusModalTitle: (day: number) => `Modifier le statut du jour ${day}`,
    systemRecord: 'Enregistrement du système',
    notEditable: 'Non modifiable',
    entry: 'Entrée',
    exit: 'Sortie',
    totalTime: 'Temps total',
    viewGoogleMaps: 'Voir dans Google Maps',
    manualUpdate: 'Modifier le statut manuellement :',
    buttons: {
      attendance: 'Marquer comme présence',
      absence: 'Marquer comme absence',
      tardy: 'Marquer comme retard',
      rest: 'Marquer comme repos',
    },
    statuses: {
      attendance: 'Présence',
      absence: 'Absence',
      tardy: 'Retard',
      rest: 'Repos',
      none: 'Aucun statut',
    },
    currentStatus: (label: string) => `Statut actuel : ${label}`,
    noStatusAssigned: 'Aucun statut attribué',
  },
};

const hrAttendancePt = {
  attendance: {
    title: 'Presença',
    subtitle: 'Registre sua entrada/saída com foto e localização.',
    viewRecords: 'Ver meus registros',
    markBlock: 'Marcar bloco',
    collaborator: 'Colaborador',
    photo: 'Foto',
    photoRequired: 'Obrigatória para registrar',
    takePhoto: 'Tirar foto',
    photoTaken: 'Foto tirada',
    photoTip: 'Dica: mantenha o rosto centralizado e com boa iluminação.',
    location: 'Localização',
    locationRequired: 'Obrigatória para registrar',
    getLocation: 'Obter localização',
    locationObtained: 'Localização obtida',
    noLocation: 'Sem localização',
    register: 'Registro',
    registerHint: 'Será habilitado quando houver foto + localização',
    entry: 'Entrada',
    exit: 'Saída',
    successEntry: (employee: string, time: string) => `Entrada registrada para ${employee} às ${time}.`,
    successExit: (employee: string, time: string) => `Saída registrada para ${employee} às ${time}.`,
  },
  control: {
    title: 'Controle',
    subtitle: 'Monitore a presença em tempo real e gerencie configurações.',
    registerLocations: 'Registrar locais',
    schedules: 'Horários',
    kiosk: 'Quiosque',
    kioskLink: 'Link do quiosque',
    kioskLinkCopied: 'Link do quiosque copiado com sucesso.',
    dailyAttendance: 'Presença do dia',
    entry: 'Entrada',
    exit: 'Saída',
    noRecord: 'Sem registro',
    location: 'Localização',
    attendanceCalendar: 'Calendário de presença',
  },
  attendanceLocationModal: {
    title: 'Registrar locais',
    banner:
      'Configure seus locais para que a tabela de presença mostre o nome do lugar em vez da latitude/longitude por proximidade. Você pode usar Aqui (GPS) ou colar um link do Google Maps para extrair coordenadas.',
    activeLocations: (count: number) => `Locais ativos: ${count}`,
    unsavedChanges: 'As alterações não são salvas até você pressionar Salvar.',
    noPendingChanges: 'Sem alterações pendentes',
    fields: {
      name: 'Nome',
      latitude: 'Latitude',
      longitude: 'Longitude',
      googleMapsLink: 'Link do Google Maps (opcional)',
      altitude: 'Altitude (opcional)',
      radius: 'Raio (m)',
    },
    placeholders: {
      name: 'Ex. Escritório',
      googleMapsLink: 'Cole aqui o link do Google Maps',
      altitude: 'm',
    },
    buttons: {
      extract: 'Extrair',
      here: 'Aqui',
      add: 'Adicionar',
      remove: 'Remover',
      load: 'Carregar',
      close: 'Fechar',
      save: 'Salvar',
    },
    table: {
      name: 'NOME',
      lat: 'LAT',
      lng: 'LNG',
      radius: 'RAIO',
      action: 'AÇÃO',
    },
    tip:
      'Dica: no Google Maps, compartilhe o local e cole o link aqui. Se o link for muito curto (maps.app.goo.gl), abra-o e copie a URL completa.',
    alerts: {
      requiredFields: 'Preencha Nome, Latitude, Longitude e Raio.',
      noLocation: 'Não foi possível obter a localização.',
      permissionDenied:
        'Permissão de localização negada. Ative as permissões de localização no navegador.',
      positionUnavailable: 'As informações de localização não estão disponíveis.',
      timeout: 'O tempo limite para obter a localização expirou.',
      unsupported: 'Seu navegador não oferece suporte à geolocalização.',
    },
  },
  attendanceKiosk: {
    title: 'Quiosque · Presença',
    intro:
      'Procure seu nome e registre sua entrada. Ao final do turno, registre sua saída.',
    greetings: {
      morning: 'Bom dia ☀️',
      afternoon: 'Boa tarde ⛅',
      evening: 'Boa noite 🌙',
    },
    messages: [
      'Faça com calma e orgulho. Você está indo bem.',
      'Seu esforço faz a diferença. Continue assim.',
      'Cada dia é uma nova oportunidade. Aproveite.',
      'Seu trabalho importa. Obrigado pela dedicação.',
      'Você é parte fundamental da equipe. Excelente trabalho.',
    ],
    checklist: {
      selectName: 'Selecione seu nome',
      getLocation: 'Obtenha localização',
      takePhoto: 'Tire foto',
      checkIn: 'Entrada',
      checkOut: 'Saída',
    },
    labels: {
      date: 'Data',
      search: 'Buscar',
      employees: 'Colaboradores',
      code: 'Código',
      photo: 'Foto',
      location: 'Localização',
    },
    today: '(hoje)',
    searchPlaceholder: 'Nome ou código',
    noResults: 'Sem resultados.',
    selectEmployee: 'Selecione um colaborador',
    selectEmployeeHint: 'Use a busca ou a lista à esquerda',
    noPhoto: 'Sem foto',
    photoRequired: 'Obrigatória para marcar.',
    photoTaken: 'Foto tirada',
    takePhoto: 'Tirar foto',
    photoTip: 'Dica: rosto centralizado e boa iluminação.',
    noLocation: 'Sem localização',
    locationRequired: 'Obrigatória para marcar.',
    locationObtained: 'Localização obtida',
    getLocation: 'Obter localização',
    enableWhenReady: 'Será habilitado quando houver foto + localização.',
    register: 'Registrar',
    toggleTip: 'Dica: botão único — alterna entrada/saída de acordo com o tipo selecionado.',
    success: (employee: string, type: string, time: string) =>
      `Presença registrada com sucesso\n\n${employee}\nTipo: ${type}\nHora: ${time}`,
  },
  attendanceSchedules: {
    title: 'Configurar horários',
    filters: {
      search: 'Buscar',
      searchPlaceholder: 'Nome ou código',
      unit: 'Unidade',
      business: 'Negócio',
      allUnits: 'Todas',
      allBusinesses: 'Todos',
      searchButton: 'Buscar',
    },
    employees: {
      title: 'Colaboradores',
      selected: 'Selecionados',
      code: 'Código',
      employee: 'Colaborador',
      department: 'Depto.',
      loadError: 'Não foi possível carregar os colaboradores',
    },
    schedule: {
      title: 'Horário a aplicar',
      subtitle: 'Será aplicado da mesma forma a todos os selecionados',
      clear: 'Limpar',
      mode: 'Modo',
      strict: 'Horário rígido',
      open: 'Horário aberto',
      modeHelp: 'Aberto: marca a qualquer hora. Rígido: somente dentro do horário configurado.',
      openEnabledTitle: 'Horário aberto ativado',
      openEnabledBody:
        'Os colaboradores poderão registrar em qualquer horário. Não é necessário configurar horários específicos.',
      tolerance: 'Tolerância de entrada',
      minutes: 'minutos',
      toleranceHelp: (minutes: number) =>
        `Os colaboradores poderão registrar entrada até ${minutes} minutos atrasados sem penalização.`,
      blockAfterToleranceTitle: 'Não permitir registro após o tempo de tolerância',
      blockAfterToleranceBody:
        'O registro será bloqueado se o tempo de tolerância configurado for ultrapassado.',
      blockOutsideLocationTitle: 'Não permitir registro fora da localização selecionada',
      blockOutsideLocationBody: 'O registro só poderá ser feito a partir da localização configurada.',
      allowedLocation: 'Localização permitida',
      days: {
        mon: 'Seg',
        tue: 'Ter',
        wed: 'Qua',
        thu: 'Qui',
        fri: 'Sex',
        sat: 'Sáb',
        sun: 'Dom',
      },
      columns: {
        day: 'Dia',
        entry: 'Entrada',
        exit: 'Saída',
        meal: 'Refeição (min)',
        break: 'Pausa',
      },
      availableLocations: {
        none: 'Nenhuma',
        hq: 'Escritório Central - Monterrey',
        north: 'Filial Norte',
        south: 'Filial Sul',
        warehouse: 'Armazém Principal',
        distribution: 'Centro de Distribuição',
      },
    },
    multiSelection: {
      title: 'Seleção múltipla',
      body: (count: number) =>
        `Você tem ${count} colaboradores selecionados. O horário será aplicado igualmente a todos.`,
    },
    buttons: {
      cancel: 'Cancelar',
      apply: 'Aplicar aos selecionados',
    },
    alerts: {
      selectAtLeastOne: 'Você deve selecionar pelo menos um colaborador.',
      success: (count: number, mode: string, toleranceText: string) =>
        `Horários aplicados com sucesso\n\nColaboradores: ${count}\nModo: ${mode}${toleranceText}\n\nOs horários foram configurados corretamente.`,
    },
  },
  attendanceCalendar: {
    title: 'Calendário de presença',
    months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    weekdays: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    legend: {
      entryRegistered: 'Entrada registrada',
      exitRegistered: 'Saída registrada',
      currentDay: 'Dia atual',
    },
    statusModalTitle: (day: number) => `Alterar status do dia ${day}`,
    systemRecord: 'Registro do sistema',
    notEditable: 'Não editável',
    entry: 'Entrada',
    exit: 'Saída',
    totalTime: 'Tempo total',
    viewGoogleMaps: 'Ver no Google Maps',
    manualUpdate: 'Alterar status manualmente:',
    buttons: {
      attendance: 'Marcar como presença',
      absence: 'Marcar como falta',
      tardy: 'Marcar como atraso',
      rest: 'Marcar como descanso',
    },
    statuses: {
      attendance: 'Presença',
      absence: 'Falta',
      tardy: 'Atraso',
      rest: 'Descanso',
      none: 'Sem status',
    },
    currentStatus: (label: string) => `Status atual: ${label}`,
    noStatusAssigned: 'Sem status atribuído',
  },
};

const hrAttendanceKo = {
  attendance: {
    title: '출석',
    subtitle: '사진과 위치로 출근/퇴근을 등록하세요.',
    viewRecords: '내 기록 보기',
    markBlock: '블록 표시',
    collaborator: '직원',
    photo: '사진',
    photoRequired: '등록하려면 필요합니다',
    takePhoto: '사진 촬영',
    photoTaken: '사진 촬영 완료',
    photoTip: '팁: 얼굴을 중앙에 두고 밝은 곳에서 촬영하세요.',
    location: '위치',
    locationRequired: '등록하려면 필요합니다',
    getLocation: '위치 가져오기',
    locationObtained: '위치 확인됨',
    noLocation: '위치 없음',
    register: '등록',
    registerHint: '사진과 위치가 있으면 활성화됩니다',
    entry: '출근',
    exit: '퇴근',
    successEntry: (employee: string, time: string) => `${employee}의 출근이 ${time}에 등록되었습니다.`,
    successExit: (employee: string, time: string) => `${employee}의 퇴근이 ${time}에 등록되었습니다.`,
  },
  control: {
    title: '관리',
    subtitle: '실시간으로 출석을 모니터링하고 설정을 관리합니다.',
    registerLocations: '위치 등록',
    schedules: '근무 일정',
    kiosk: '키오스크',
    kioskLink: '키오스크 링크',
    kioskLinkCopied: '키오스크 링크가 복사되었습니다.',
    dailyAttendance: '오늘의 출석',
    entry: '출근',
    exit: '퇴근',
    noRecord: '기록 없음',
    location: '위치',
    attendanceCalendar: '출석 달력',
  },
  attendanceLocationModal: {
    title: '위치 등록',
    banner:
      '출석 표에 위도/경도 대신 장소 이름이 표시되도록 위치를 설정하세요. 여기(GPS)를 사용하거나 Google Maps 링크를 붙여 좌표를 추출할 수 있습니다.',
    activeLocations: (count: number) => `활성 위치: ${count}`,
    unsavedChanges: '저장을 누르기 전까지 변경 사항은 저장되지 않습니다.',
    noPendingChanges: '대기 중인 변경 사항 없음',
    fields: {
      name: '이름',
      latitude: '위도',
      longitude: '경도',
      googleMapsLink: 'Google Maps 링크(선택)',
      altitude: '고도(선택)',
      radius: '반경(m)',
    },
    placeholders: {
      name: '예: 사무실',
      googleMapsLink: 'Google Maps 링크를 여기에 붙여 넣으세요',
      altitude: 'm',
    },
    buttons: {
      extract: '추출',
      here: '현재 위치',
      add: '추가',
      remove: '제거',
      load: '불러오기',
      close: '닫기',
      save: '저장',
    },
    table: {
      name: '이름',
      lat: '위도',
      lng: '경도',
      radius: '반경',
      action: '작업',
    },
    tip:
      '팁: Google Maps에서 장소를 공유한 뒤 링크를 여기에 붙여 넣으세요. 링크가 매우 짧으면(maps.app.goo.gl) 열어서 전체 URL을 복사하세요.',
    alerts: {
      requiredFields: '이름, 위도, 경도, 반경을 입력하세요.',
      noLocation: '위치를 가져올 수 없습니다.',
      permissionDenied: '위치 권한이 거부되었습니다. 브라우저에서 위치 권한을 허용하세요.',
      positionUnavailable: '위치 정보를 사용할 수 없습니다.',
      timeout: '위치 정보를 가져오는 시간이 초과되었습니다.',
      unsupported: '이 브라우저는 위치 정보를 지원하지 않습니다.',
    },
  },
  attendanceKiosk: {
    title: '키오스크 · 출석',
    intro: '이름을 검색하고 출근을 등록하세요. 근무가 끝나면 퇴근을 등록하세요.',
    greetings: {
      morning: '좋은 아침입니다 ☀️',
      afternoon: '좋은 오후입니다 ⛅',
      evening: '좋은 저녁입니다 🌙',
    },
    messages: [
      '차분하고 자랑스럽게 진행하세요. 잘하고 있습니다.',
      '당신의 노력은 차이를 만듭니다. 계속 힘내세요.',
      '매일은 새로운 기회입니다. 잘 활용해 보세요.',
      '당신의 일은 중요합니다. 헌신에 감사합니다.',
      '당신은 팀의 중요한 구성원입니다. 훌륭합니다.',
    ],
    checklist: {
      selectName: '이름 선택',
      getLocation: '위치 확인',
      takePhoto: '사진 촬영',
      checkIn: '출근',
      checkOut: '퇴근',
    },
    labels: {
      date: '날짜',
      search: '검색',
      employees: '직원',
      code: '코드',
      photo: '사진',
      location: '위치',
    },
    today: '(오늘)',
    searchPlaceholder: '이름 또는 코드',
    noResults: '검색 결과가 없습니다.',
    selectEmployee: '직원을 선택하세요',
    selectEmployeeHint: '검색창 또는 왼쪽 목록을 사용하세요',
    noPhoto: '사진 없음',
    photoRequired: '체크하려면 필요합니다.',
    photoTaken: '사진 촬영 완료',
    takePhoto: '사진 촬영',
    photoTip: '팁: 얼굴을 중앙에 두고 밝은 곳에서 촬영하세요.',
    noLocation: '위치 없음',
    locationRequired: '체크하려면 필요합니다.',
    locationObtained: '위치 확인됨',
    getLocation: '위치 가져오기',
    enableWhenReady: '사진과 위치가 있으면 활성화됩니다.',
    register: '등록',
    toggleTip: '팁: 단일 버튼으로 선택한 유형에 따라 출근/퇴근을 전환합니다.',
    success: (employee: string, type: string, time: string) =>
      `출석이 성공적으로 등록되었습니다\n\n${employee}\n유형: ${type}\n시간: ${time}`,
  },
  attendanceSchedules: {
    title: '근무 일정 설정',
    filters: {
      search: '검색',
      searchPlaceholder: '이름 또는 코드',
      unit: '유닛',
      business: '비즈니스',
      allUnits: '전체',
      allBusinesses: '전체',
      searchButton: '검색',
    },
    employees: {
      title: '직원',
      selected: '선택됨',
      code: '코드',
      employee: '직원',
      department: '부서',
      loadError: '직원을 불러올 수 없습니다',
    },
    schedule: {
      title: '적용할 일정',
      subtitle: '선택한 모든 직원에게 동일하게 적용됩니다',
      clear: '지우기',
      mode: '모드',
      strict: '엄격한 일정',
      open: '자유 일정',
      modeHelp: '자유: 아무 시간에나 체크 가능. 엄격: 설정된 시간 내에서만 체크 가능.',
      openEnabledTitle: '자유 일정 활성화',
      openEnabledBody: '직원은 아무 시간에나 등록할 수 있습니다. 특정 시간을 설정할 필요가 없습니다.',
      tolerance: '출근 허용 지연',
      minutes: '분',
      toleranceHelp: (minutes: number) => `직원은 최대 ${minutes}분 늦게 출근해도 불이익 없이 등록할 수 있습니다.`,
      blockAfterToleranceTitle: '허용 시간이 지난 후에는 등록 금지',
      blockAfterToleranceBody: '설정된 허용 시간을 넘기면 등록이 차단됩니다.',
      blockOutsideLocationTitle: '선택한 위치 밖에서는 등록 금지',
      blockOutsideLocationBody: '설정된 위치에서만 등록할 수 있습니다.',
      allowedLocation: '허용 위치',
      days: {
        mon: '월',
        tue: '화',
        wed: '수',
        thu: '목',
        fri: '금',
        sat: '토',
        sun: '일',
      },
      columns: {
        day: '요일',
        entry: '출근',
        exit: '퇴근',
        meal: '식사(분)',
        break: '휴식',
      },
      availableLocations: {
        none: '없음',
        hq: '중앙 사무실 - 몬테레이',
        north: '북부 지점',
        south: '남부 지점',
        warehouse: '주 창고',
        distribution: '물류 센터',
      },
    },
    multiSelection: {
      title: '다중 선택',
      body: (count: number) => `${count}명의 직원이 선택되었습니다. 일정은 모두에게 동일하게 적용됩니다.`,
    },
    buttons: {
      cancel: '취소',
      apply: '선택 항목에 적용',
    },
    alerts: {
      selectAtLeastOne: '최소 한 명의 직원을 선택해야 합니다.',
      success: (count: number, mode: string, toleranceText: string) =>
        `근무 일정이 성공적으로 적용되었습니다\n\n직원 수: ${count}\n모드: ${mode}${toleranceText}\n\n근무 일정이 올바르게 설정되었습니다.`,
    },
  },
  attendanceCalendar: {
    title: '출석 달력',
    months: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    weekdays: ['일', '월', '화', '수', '목', '금', '토'],
    legend: {
      entryRegistered: '출근 등록',
      exitRegistered: '퇴근 등록',
      currentDay: '오늘',
    },
    statusModalTitle: (day: number) => `${day}일 상태 변경`,
    systemRecord: '시스템 기록',
    notEditable: '수정 불가',
    entry: '출근',
    exit: '퇴근',
    totalTime: '총 시간',
    viewGoogleMaps: 'Google Maps에서 보기',
    manualUpdate: '상태 수동 변경:',
    buttons: {
      attendance: '출석으로 표시',
      absence: '결근으로 표시',
      tardy: '지각으로 표시',
      rest: '휴무로 표시',
    },
    statuses: {
      attendance: '출석',
      absence: '결근',
      tardy: '지각',
      rest: '휴무',
      none: '상태 없음',
    },
    currentStatus: (label: string) => `현재 상태: ${label}`,
    noStatusAssigned: '지정된 상태 없음',
  },
};

const hrAttendanceZh = {
  attendance: {
    title: '考勤',
    subtitle: '通过照片和位置登记上班/下班。',
    viewRecords: '查看我的记录',
    markBlock: '标记区块',
    collaborator: '员工',
    photo: '照片',
    photoRequired: '登记时必填',
    takePhoto: '拍照',
    photoTaken: '已拍照',
    photoTip: '提示：请保持脸部居中并确保光线充足。',
    location: '位置',
    locationRequired: '登记时必填',
    getLocation: '获取位置',
    locationObtained: '已获取位置',
    noLocation: '无位置',
    register: '登记',
    registerHint: '当照片和位置都可用时将启用',
    entry: '上班',
    exit: '下班',
    successEntry: (employee: string, time: string) => `${employee} 的上班已在 ${time} 记录。`,
    successExit: (employee: string, time: string) => `${employee} 的下班已在 ${time} 记录。`,
  },
  control: {
    title: '控制',
    subtitle: '实时监控考勤并管理配置。',
    registerLocations: '登记位置',
    schedules: '班次',
    kiosk: '自助终端',
    kioskLink: '终端链接',
    kioskLinkCopied: '终端链接已成功复制。',
    dailyAttendance: '今日考勤',
    entry: '上班',
    exit: '下班',
    noRecord: '无记录',
    location: '位置',
    attendanceCalendar: '考勤日历',
  },
  attendanceLocationModal: {
    title: '登记位置',
    banner:
      '配置位置后，考勤表将按距离显示地点名称而不是经纬度。你可以使用“这里”(GPS)或粘贴 Google Maps 链接来提取坐标。',
    activeLocations: (count: number) => `启用的位置：${count}`,
    unsavedChanges: '在点击保存之前，更改不会被保存。',
    noPendingChanges: '没有待保存的更改',
    fields: {
      name: '名称',
      latitude: '纬度',
      longitude: '经度',
      googleMapsLink: 'Google Maps 链接（可选）',
      altitude: '海拔（可选）',
      radius: '半径（米）',
    },
    placeholders: {
      name: '例如：办公室',
      googleMapsLink: '在此粘贴 Google Maps 链接',
      altitude: '米',
    },
    buttons: {
      extract: '提取',
      here: '这里',
      add: '添加',
      remove: '移除',
      load: '加载',
      close: '关闭',
      save: '保存',
    },
    table: {
      name: '名称',
      lat: '纬度',
      lng: '经度',
      radius: '半径',
      action: '操作',
    },
    tip:
      '提示：在 Google Maps 中共享地点并把链接粘贴到这里。如果链接很短（maps.app.goo.gl），请先打开它并复制完整 URL。',
    alerts: {
      requiredFields: '请填写名称、纬度、经度和半径。',
      noLocation: '无法获取位置。',
      permissionDenied: '位置权限被拒绝。请在浏览器中启用位置权限。',
      positionUnavailable: '位置信息不可用。',
      timeout: '获取位置超时。',
      unsupported: '你的浏览器不支持地理定位。',
    },
  },
  attendanceKiosk: {
    title: '终端 · 考勤',
    intro: '搜索你的姓名并登记上班。下班时再登记下班。',
    greetings: {
      morning: '早上好 ☀️',
      afternoon: '下午好 ⛅',
      evening: '晚上好 🌙',
    },
    messages: [
      '保持从容并为自己感到自豪。你做得很好。',
      '你的努力会带来不同。继续加油。',
      '每一天都是新的机会。好好把握。',
      '你的工作很重要。感谢你的付出。',
      '你是团队的重要一员。做得非常好。',
    ],
    checklist: {
      selectName: '选择你的姓名',
      getLocation: '获取位置',
      takePhoto: '拍照',
      checkIn: '上班',
      checkOut: '下班',
    },
    labels: {
      date: '日期',
      search: '搜索',
      employees: '员工',
      code: '代码',
      photo: '照片',
      location: '位置',
    },
    today: '（今天）',
    searchPlaceholder: '姓名或代码',
    noResults: '没有结果。',
    selectEmployee: '选择一名员工',
    selectEmployeeHint: '使用搜索框或左侧列表',
    noPhoto: '无照片',
    photoRequired: '打卡时需要',
    photoTaken: '已拍照',
    takePhoto: '拍照',
    photoTip: '提示：脸部居中并保持光线良好。',
    noLocation: '无位置',
    locationRequired: '打卡时需要',
    locationObtained: '已获取位置',
    getLocation: '获取位置',
    enableWhenReady: '当照片和位置都可用时将启用。',
    register: '登记',
    toggleTip: '提示：单一按钮会根据所选类型切换上班/下班。',
    success: (employee: string, type: string, time: string) =>
      `考勤登记成功\n\n${employee}\n类型：${type}\n时间：${time}`,
  },
  attendanceSchedules: {
    title: '配置班次',
    filters: {
      search: '搜索',
      searchPlaceholder: '姓名或代码',
      unit: '单位',
      business: '业务',
      allUnits: '全部',
      allBusinesses: '全部',
      searchButton: '搜索',
    },
    employees: {
      title: '员工',
      selected: '已选择',
      code: '代码',
      employee: '员工',
      department: '部门',
      loadError: '无法加载员工',
    },
    schedule: {
      title: '要应用的班次',
      subtitle: '将统一应用到所有已选择员工',
      clear: '清除',
      mode: '模式',
      strict: '严格班次',
      open: '开放班次',
      modeHelp: '开放：可在任意时间打卡。严格：只能在设定时间内打卡。',
      openEnabledTitle: '已启用开放班次',
      openEnabledBody: '员工可以在任意时间登记，无需配置具体时段。',
      tolerance: '上班容差',
      minutes: '分钟',
      toleranceHelp: (minutes: number) => `员工最多可迟到 ${minutes} 分钟而不受处罚。`,
      blockAfterToleranceTitle: '超过容差时间后不允许登记',
      blockAfterToleranceBody: '超过已配置的容差时间后将阻止登记。',
      blockOutsideLocationTitle: '不允许在所选位置之外登记',
      blockOutsideLocationBody: '仅允许在已配置的位置进行登记。',
      allowedLocation: '允许的位置',
      days: {
        mon: '周一',
        tue: '周二',
        wed: '周三',
        thu: '周四',
        fri: '周五',
        sat: '周六',
        sun: '周日',
      },
      columns: {
        day: '日期',
        entry: '上班',
        exit: '下班',
        meal: '用餐（分）',
        break: '休息',
      },
      availableLocations: {
        none: '无',
        hq: '中央办公室 - 蒙特雷',
        north: '北区分部',
        south: '南区分部',
        warehouse: '主仓库',
        distribution: '配送中心',
      },
    },
    multiSelection: {
      title: '多选',
      body: (count: number) => `你已选择 ${count} 名员工。班次将统一应用到所有人。`,
    },
    buttons: {
      cancel: '取消',
      apply: '应用到所选项',
    },
    alerts: {
      selectAtLeastOne: '至少需要选择一名员工。',
      success: (count: number, mode: string, toleranceText: string) =>
        `班次应用成功\n\n员工数：${count}\n模式：${mode}${toleranceText}\n\n班次已正确配置。`,
    },
  },
  attendanceCalendar: {
    title: '考勤日历',
    months: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    legend: {
      entryRegistered: '已登记上班',
      exitRegistered: '已登记下班',
      currentDay: '当前日期',
    },
    statusModalTitle: (day: number) => `修改第 ${day} 天状态`,
    systemRecord: '系统记录',
    notEditable: '不可修改',
    entry: '上班',
    exit: '下班',
    totalTime: '总时长',
    viewGoogleMaps: '在 Google Maps 中查看',
    manualUpdate: '手动修改状态：',
    buttons: {
      attendance: '标记为出勤',
      absence: '标记为缺勤',
      tardy: '标记为迟到',
      rest: '标记为休息',
    },
    statuses: {
      attendance: '出勤',
      absence: '缺勤',
      tardy: '迟到',
      rest: '休息',
      none: '无状态',
    },
    currentStatus: (label: string) => `当前状态：${label}`,
    noStatusAssigned: '未分配状态',
  },
};

const hrAssetsFr = {
  assets: {
    title: "Actifs de l'entreprise",
    subtitle: "Suivez les équipements, appareils et véhicules attribués",
    newAsset: 'Nouvel actif',
    loading: 'Chargement des actifs...',
    emptyState: 'Aucun actif ne correspond aux filtres actuels.',
    errors: {
      load: 'Impossible de charger les actifs.',
      save: "Impossible d'enregistrer l'actif.",
      details: "Impossible de charger les détails de l'actif.",
      status: "Impossible de mettre à jour le statut de l'actif.",
    },
    cards: {
      total: 'Total des actifs',
      assigned: 'Attribués',
      available: 'Disponibles',
      maintenance: 'En maintenance',
    },
    searchPlaceholder: 'Rechercher un actif...',
    filters: {
      allTypes: 'Tous les types',
      allStatuses: 'Tous les statuts',
      allUnits: 'Toutes les unités',
      computerEquipment: 'Équipement informatique',
      attendanceControl: 'Contrôle de présence',
      operation: 'Opérations',
      maintenance: 'Maintenance',
      available: 'Disponible',
      assigned: 'Attribué',
      inMaintenance: 'Maintenance',
      custody: 'Garde',
      inactive: 'Inactif',
    },
    statuses: {
      Asignado: 'Attribué',
      Mantenimiento: 'Maintenance',
      Resguardo: 'Garde',
      Disponible: 'Disponible',
      Inactivo: 'Inactif',
    },
    table: {
      id: 'ID',
      type: 'Type',
      asset: 'Actif',
      model: 'Modèle',
      serialNumber: 'Numéro de série',
      responsible: 'Responsable',
      unit: 'Unité',
      status: 'Statut',
      assignedAt: "Date d'attribution",
      value: 'Valeur',
      notes: 'Notes',
      actions: 'Actions',
    },
    columnPicker: {
      button: 'Colonnes',
      title: 'Colonnes visibles',
      subtitle: "Sélectionnez les colonnes d'actifs à afficher dans le tableau.",
      visibleCount: (visible: number, total: number) => `${visible} sur ${total} colonnes visibles`,
      selectAll: 'Tout sélectionner',
      reset: 'Réinitialiser',
      required: 'Colonne requise',
      cancel: 'Annuler',
      apply: 'Appliquer',
    },
    actionsMenu: {
      viewDetails: 'Voir les détails',
      edit: 'Modifier',
      delete: 'Supprimer',
      reassign: 'Réaffecter',
      maintenance: 'Maintenance',
      deactivate: 'Désactiver',
      moreActions: (assetName: string) => `Plus d’actions pour ${assetName}`,
    },
    actionAlerts: {
      details: "Détails de l'actif",
      reassignPending: 'Le flux de réaffectation sera connecté ici.',
      movedToMaintenance: (assetName: string) => `${assetName} a été placé en maintenance.`,
      deactivated: (assetName: string) => `${assetName} a été marqué comme inactif.`,
    },
    confirmDeactivate: {
      title: 'Désactiver un actif',
      description: "Cette action marquera l'actif comme inactif dans le tableau.",
      confirm: 'Désactiver',
      cancel: 'Annuler',
    },
    detailsModal: {
      title: "Détails de l'actif",
      subtitle: "Consultez la fiche complète de l'actif, son attribution et ses informations d'audit.",
      sections: {
        overview: 'Aperçu',
        assignment: 'Attribution',
        audit: 'Audit',
      },
      fields: {
        code: "Code de l'actif",
        type: 'Type',
        asset: 'Actif',
        model: 'Modèle',
        serialNumber: 'Numéro de série',
        responsible: 'Responsable',
        responsibleEmail: 'Courriel du responsable',
        unit: 'Unité',
        status: 'Statut',
        assignedAt: "Date d'attribution",
        value: 'Valeur',
        notes: 'Notes',
        createdBy: 'Créé par',
        createdAt: 'Créé le',
        updatedBy: 'Mis à jour par',
        updatedAt: 'Mis à jour le',
      },
      empty: {
        unassigned: 'Non attribué',
        noEmail: 'Sans courriel',
        noUnit: 'Sans unité',
        noNotes: 'Aucune note enregistrée',
        system: 'Système',
      },
      close: 'Fermer',
    },
    addNewAsset: {
      title: 'Nouvel actif',
      subtitle: "Enregistrez un nouvel actif de l'entreprise",
      editTitle: "Modifier l'actif",
      editSubtitle: "Mettez à jour l'actif sélectionné de l'entreprise",
      sections: {
        general: 'Informations générales',
        assignment: 'Attribution',
        valueDetails: 'Valeur et détails',
      },
      fields: {
        assetId: "ID de l'actif",
        assetType: "Type d'actif",
        assetName: "Nom de l'actif",
        model: 'Modèle',
        serialNumber: 'Numéro de série',
        responsible: 'Responsable',
        unit: 'Unité',
        status: 'Statut',
        assignedDate: "Date d'attribution",
        value: 'Valeur (USD)',
        notes: 'Notes supplémentaires',
      },
      placeholders: {
        assetId: 'Ex : ACT-001',
        assetName: 'Ex : MacBook Pro 16',
        model: 'Ex : M2 Pro',
        serialNumber: 'Ex : MRE-2023-9445',
        responsible: 'Nom du responsable',
        unit: 'Sélectionner une unité',
        status: 'Sélectionner un statut',
        value: 'Ex : $45,000',
        notes: "Informations supplémentaires sur l'actif...",
      },
      options: {
        laptop: 'Portable',
        attendanceTerminal: 'Terminal de présence',
        mobileDevice: 'Appareil mobile',
        maintenanceKit: 'Kit de maintenance',
        available: 'Disponible',
        assigned: 'Attribué',
        maintenance: 'Maintenance',
        custody: 'Garde',
        inactive: 'Inactif',
      },
      buttons: {
        cancel: 'Annuler',
        save: "Enregistrer l'actif",
        saveChanges: 'Enregistrer les modifications',
      },
      success: (assetName: string) => `${assetName} a été créé avec succès.`,
      successUpdated: (assetName: string) => `${assetName} a été mis à jour avec succès.`,
    },
  },
};

const hrAssetsPt = {
  assets: {
    title: 'Ativos da Empresa',
    subtitle: 'Acompanhe equipamentos, dispositivos e veículos atribuídos',
    newAsset: 'Novo ativo',
    loading: 'Carregando ativos...',
    emptyState: 'Nenhum ativo corresponde aos filtros atuais.',
    errors: {
      load: 'Não foi possível carregar os ativos.',
      save: 'Não foi possível salvar o ativo.',
      details: 'Não foi possível carregar os detalhes do ativo.',
      status: 'Não foi possível atualizar o status do ativo.',
    },
    cards: {
      total: 'Total de ativos',
      assigned: 'Atribuídos',
      available: 'Disponíveis',
      maintenance: 'Em manutenção',
    },
    searchPlaceholder: 'Buscar ativo...',
    filters: {
      allTypes: 'Todos os tipos',
      allStatuses: 'Todos os status',
      allUnits: 'Todas as unidades',
      computerEquipment: 'Equipamento de informática',
      attendanceControl: 'Controle de presença',
      operation: 'Operações',
      maintenance: 'Manutenção',
      available: 'Disponível',
      assigned: 'Atribuído',
      inMaintenance: 'Manutenção',
      custody: 'Custódia',
      inactive: 'Inativo',
    },
    statuses: {
      Asignado: 'Atribuído',
      Mantenimiento: 'Manutenção',
      Resguardo: 'Custódia',
      Disponible: 'Disponível',
      Inactivo: 'Inativo',
    },
    table: {
      id: 'ID',
      type: 'Tipo',
      asset: 'Ativo',
      model: 'Modelo',
      serialNumber: 'Número de série',
      responsible: 'Responsável',
      unit: 'Unidade',
      status: 'Status',
      assignedAt: 'Data de atribuição',
      value: 'Valor',
      notes: 'Notas',
      actions: 'Ações',
    },
    columnPicker: {
      button: 'Colunas',
      title: 'Colunas visíveis',
      subtitle: 'Selecione as colunas de ativos que deseja ver na tabela.',
      visibleCount: (visible: number, total: number) => `${visible} de ${total} colunas visíveis`,
      selectAll: 'Selecionar todas',
      reset: 'Restaurar',
      required: 'Coluna obrigatória',
      cancel: 'Cancelar',
      apply: 'Aplicar',
    },
    actionsMenu: {
      viewDetails: 'Ver detalhes',
      edit: 'Editar',
      delete: 'Excluir',
      reassign: 'Reatribuir',
      maintenance: 'Manutenção',
      deactivate: 'Desativar',
      moreActions: (assetName: string) => `Mais ações para ${assetName}`,
    },
    actionAlerts: {
      details: 'Detalhes do ativo',
      reassignPending: 'O fluxo de reatribuição será conectado aqui.',
      movedToMaintenance: (assetName: string) => `${assetName} foi movido para manutenção.`,
      deactivated: (assetName: string) => `${assetName} foi marcado como inativo.`,
    },
    confirmDeactivate: {
      title: 'Desativar ativo',
      description: 'Esta ação marcará o ativo como inativo na tabela.',
      confirm: 'Desativar',
      cancel: 'Cancelar',
    },
    detailsModal: {
      title: 'Detalhes do ativo',
      subtitle: 'Revise o registro completo do ativo, sua atribuição e seus dados de auditoria.',
      sections: {
        overview: 'Visão geral',
        assignment: 'Atribuição',
        audit: 'Auditoria',
      },
      fields: {
        code: 'Código do ativo',
        type: 'Tipo',
        asset: 'Ativo',
        model: 'Modelo',
        serialNumber: 'Número de série',
        responsible: 'Responsável',
        responsibleEmail: 'E-mail do responsável',
        unit: 'Unidade',
        status: 'Status',
        assignedAt: 'Data de atribuição',
        value: 'Valor',
        notes: 'Notas',
        createdBy: 'Criado por',
        createdAt: 'Criado em',
        updatedBy: 'Atualizado por',
        updatedAt: 'Atualizado em',
      },
      empty: {
        unassigned: 'Não atribuído',
        noEmail: 'Sem e-mail',
        noUnit: 'Sem unidade',
        noNotes: 'Sem notas registradas',
        system: 'Sistema',
      },
      close: 'Fechar',
    },
    addNewAsset: {
      title: 'Novo ativo',
      subtitle: 'Cadastre um novo ativo da empresa',
      editTitle: 'Editar ativo',
      editSubtitle: 'Atualize o ativo selecionado da empresa',
      sections: {
        general: 'Informações gerais',
        assignment: 'Atribuição',
        valueDetails: 'Valor e detalhes',
      },
      fields: {
        assetId: 'ID do ativo',
        assetType: 'Tipo de ativo',
        assetName: 'Nome do ativo',
        model: 'Modelo',
        serialNumber: 'Número de série',
        responsible: 'Responsável',
        unit: 'Unidade',
        status: 'Status',
        assignedDate: 'Data de atribuição',
        value: 'Valor (USD)',
        notes: 'Notas adicionais',
      },
      placeholders: {
        assetId: 'Ex.: ACT-001',
        assetName: 'Ex.: MacBook Pro 16',
        model: 'Ex.: M2 Pro',
        serialNumber: 'Ex.: MRE-2023-9445',
        responsible: 'Nome do responsável',
        unit: 'Selecionar unidade',
        status: 'Selecionar status',
        value: 'Ex.: $45,000',
        notes: 'Informações adicionais sobre o ativo...',
      },
      options: {
        laptop: 'Laptop',
        attendanceTerminal: 'Terminal de presença',
        mobileDevice: 'Dispositivo móvel',
        maintenanceKit: 'Kit de manutenção',
        available: 'Disponível',
        assigned: 'Atribuído',
        maintenance: 'Manutenção',
        custody: 'Custódia',
        inactive: 'Inativo',
      },
      buttons: {
        cancel: 'Cancelar',
        save: 'Salvar ativo',
        saveChanges: 'Salvar alterações',
      },
      success: (assetName: string) => `${assetName} foi criado com sucesso.`,
      successUpdated: (assetName: string) => `${assetName} foi atualizado com sucesso.`,
    },
  },
};

const hrAssetsKo = {
  assets: {
    title: '회사 자산',
    subtitle: '배정된 장비, 기기 및 차량을 추적합니다',
    newAsset: '새 자산',
    loading: '자산을 불러오는 중...',
    emptyState: '현재 필터와 일치하는 자산이 없습니다.',
    errors: {
      load: '자산을 불러올 수 없습니다.',
      save: '자산을 저장할 수 없습니다.',
      details: '자산 상세 정보를 불러올 수 없습니다.',
      status: '자산 상태를 업데이트할 수 없습니다.',
    },
    cards: {
      total: '총 자산',
      assigned: '배정됨',
      available: '사용 가능',
      maintenance: '유지보수 중',
    },
    searchPlaceholder: '자산 검색...',
    filters: {
      allTypes: '모든 유형',
      allStatuses: '모든 상태',
      allUnits: '모든 유닛',
      computerEquipment: '컴퓨터 장비',
      attendanceControl: '출석 제어',
      operation: '운영',
      maintenance: '유지보수',
      available: '사용 가능',
      assigned: '배정됨',
      inMaintenance: '유지보수',
      custody: '보관',
      inactive: '비활성',
    },
    statuses: {
      Asignado: '배정됨',
      Mantenimiento: '유지보수',
      Resguardo: '보관',
      Disponible: '사용 가능',
      Inactivo: '비활성',
    },
    table: {
      id: 'ID',
      type: '유형',
      asset: '자산',
      model: '모델',
      serialNumber: '일련번호',
      responsible: '담당자',
      unit: '유닛',
      status: '상태',
      assignedAt: '배정 날짜',
      value: '가치',
      notes: '메모',
      actions: '작업',
    },
    columnPicker: {
      button: '열',
      title: '표시할 열',
      subtitle: '자산 표에 표시할 열을 선택하세요.',
      visibleCount: (visible: number, total: number) => `${total}개 중 ${visible}개 열 표시`,
      selectAll: '모두 선택',
      reset: '초기화',
      required: '필수 열',
      cancel: '취소',
      apply: '적용',
    },
    actionsMenu: {
      viewDetails: '세부 정보 보기',
      edit: '수정',
      delete: '삭제',
      reassign: '재배정',
      maintenance: '유지보수',
      deactivate: '비활성화',
      moreActions: (assetName: string) => `${assetName}에 대한 추가 작업`,
    },
    actionAlerts: {
      details: '자산 세부 정보',
      reassignPending: '재배정 흐름이 여기에 연결됩니다.',
      movedToMaintenance: (assetName: string) => `${assetName}이(가) 유지보수 상태로 이동되었습니다.`,
      deactivated: (assetName: string) => `${assetName}이(가) 비활성 상태로 표시되었습니다.`,
    },
    confirmDeactivate: {
      title: '자산 비활성화',
      description: '이 작업은 표에서 자산을 비활성으로 표시합니다.',
      confirm: '비활성화',
      cancel: '취소',
    },
    detailsModal: {
      title: '자산 상세 정보',
      subtitle: '자산 전체 기록, 배정 정보, 감사 정보를 확인하세요.',
      sections: {
        overview: '개요',
        assignment: '배정',
        audit: '감사 기록',
      },
      fields: {
        code: '자산 코드',
        type: '유형',
        asset: '자산',
        model: '모델',
        serialNumber: '일련번호',
        responsible: '담당자',
        responsibleEmail: '담당자 이메일',
        unit: '유닛',
        status: '상태',
        assignedAt: '배정 날짜',
        value: '가치',
        notes: '메모',
        createdBy: '생성자',
        createdAt: '생성 일시',
        updatedBy: '수정자',
        updatedAt: '수정 일시',
      },
      empty: {
        unassigned: '미배정',
        noEmail: '이메일 없음',
        noUnit: '유닛 없음',
        noNotes: '등록된 메모 없음',
        system: '시스템',
      },
      close: '닫기',
    },
    addNewAsset: {
      title: '새 자산',
      subtitle: '회사에 새 자산을 등록합니다',
      editTitle: '자산 수정',
      editSubtitle: '선택한 회사 자산을 업데이트합니다',
      sections: {
        general: '일반 정보',
        assignment: '배정',
        valueDetails: '가치 및 세부 사항',
      },
      fields: {
        assetId: '자산 ID',
        assetType: '자산 유형',
        assetName: '자산 이름',
        model: '모델',
        serialNumber: '일련번호',
        responsible: '담당자',
        unit: '유닛',
        status: '상태',
        assignedDate: '배정 날짜',
        value: '가치 (USD)',
        notes: '추가 메모',
      },
      placeholders: {
        assetId: '예: ACT-001',
        assetName: '예: MacBook Pro 16',
        model: '예: M2 Pro',
        serialNumber: '예: MRE-2023-9445',
        responsible: '담당자 이름',
        unit: '유닛 선택',
        status: '상태 선택',
        value: '예: $45,000',
        notes: '자산에 대한 추가 정보...',
      },
      options: {
        laptop: '노트북',
        attendanceTerminal: '출석 단말기',
        mobileDevice: '모바일 기기',
        maintenanceKit: '유지보수 키트',
        available: '사용 가능',
        assigned: '배정됨',
        maintenance: '유지보수',
        custody: '보관',
        inactive: '비활성',
      },
      buttons: {
        cancel: '취소',
        save: '자산 저장',
        saveChanges: '변경 사항 저장',
      },
      success: (assetName: string) => `${assetName}이(가) 성공적으로 생성되었습니다.`,
      successUpdated: (assetName: string) => `${assetName}이(가) 성공적으로 업데이트되었습니다.`,
    },
  },
};

const hrAssetsZh = {
  assets: {
    title: '公司资产',
    subtitle: '跟踪已分配的设备、装置和车辆',
    newAsset: '新增资产',
    loading: '正在加载资产...',
    emptyState: '没有符合当前筛选条件的资产。',
    errors: {
      load: '无法加载资产。',
      save: '无法保存资产。',
      details: '无法加载资产详情。',
      status: '无法更新资产状态。',
    },
    cards: {
      total: '资产总数',
      assigned: '已分配',
      available: '可用',
      maintenance: '维护中',
    },
    searchPlaceholder: '搜索资产...',
    filters: {
      allTypes: '所有类型',
      allStatuses: '所有状态',
      allUnits: '所有单位',
      computerEquipment: '计算机设备',
      attendanceControl: '考勤设备',
      operation: '运营',
      maintenance: '维护',
      available: '可用',
      assigned: '已分配',
      inMaintenance: '维护中',
      custody: '保管中',
      inactive: '停用',
    },
    statuses: {
      Asignado: '已分配',
      Mantenimiento: '维护中',
      Resguardo: '保管中',
      Disponible: '可用',
      Inactivo: '停用',
    },
    table: {
      id: 'ID',
      type: '类型',
      asset: '资产',
      model: '型号',
      serialNumber: '序列号',
      responsible: '负责人',
      unit: '单位',
      status: '状态',
      assignedAt: '分配日期',
      value: '价值',
      notes: '备注',
      actions: '操作',
    },
    columnPicker: {
      button: '列',
      title: '可见列',
      subtitle: '选择要在资产表中显示的列。',
      visibleCount: (visible: number, total: number) => `${total} 列中显示 ${visible} 列`,
      selectAll: '全选',
      reset: '重置',
      required: '必选列',
      cancel: '取消',
      apply: '应用',
    },
    actionsMenu: {
      viewDetails: '查看详情',
      edit: '编辑',
      delete: '删除',
      reassign: '重新分配',
      maintenance: '维护',
      deactivate: '停用',
      moreActions: (assetName: string) => `${assetName} 的更多操作`,
    },
    actionAlerts: {
      details: '资产详情',
      reassignPending: '重新分配流程将在这里连接。',
      movedToMaintenance: (assetName: string) => `${assetName} 已转为维护状态。`,
      deactivated: (assetName: string) => `${assetName} 已标记为停用。`,
    },
    confirmDeactivate: {
      title: '停用资产',
      description: '此操作会在表格中将资产标记为停用。',
      confirm: '停用',
      cancel: '取消',
    },
    detailsModal: {
      title: '资产详情',
      subtitle: '查看完整的资产记录、分配信息和审计信息。',
      sections: {
        overview: '概览',
        assignment: '分配',
        audit: '审计记录',
      },
      fields: {
        code: '资产代码',
        type: '类型',
        asset: '资产',
        model: '型号',
        serialNumber: '序列号',
        responsible: '负责人',
        responsibleEmail: '负责人邮箱',
        unit: '单位',
        status: '状态',
        assignedAt: '分配日期',
        value: '价值',
        notes: '备注',
        createdBy: '创建人',
        createdAt: '创建时间',
        updatedBy: '更新人',
        updatedAt: '更新时间',
      },
      empty: {
        unassigned: '未分配',
        noEmail: '无邮箱',
        noUnit: '无单位',
        noNotes: '没有备注记录',
        system: '系统',
      },
      close: '关闭',
    },
    addNewAsset: {
      title: '新增资产',
      subtitle: '登记一个新的公司资产',
      editTitle: '编辑资产',
      editSubtitle: '更新所选公司资产',
      sections: {
        general: '基本信息',
        assignment: '分配',
        valueDetails: '价值与详情',
      },
      fields: {
        assetId: '资产 ID',
        assetType: '资产类型',
        assetName: '资产名称',
        model: '型号',
        serialNumber: '序列号',
        responsible: '负责人',
        unit: '单位',
        status: '状态',
        assignedDate: '分配日期',
        value: '价值 (USD)',
        notes: '附加说明',
      },
      placeholders: {
        assetId: '例如：ACT-001',
        assetName: '例如：MacBook Pro 16',
        model: '例如：M2 Pro',
        serialNumber: '例如：MRE-2023-9445',
        responsible: '负责人姓名',
        unit: '选择单位',
        status: '选择状态',
        value: '例如：$45,000',
        notes: '关于该资产的其他信息...',
      },
      options: {
        laptop: '笔记本电脑',
        attendanceTerminal: '考勤终端',
        mobileDevice: '移动设备',
        maintenanceKit: '维护工具包',
        available: '可用',
        assigned: '已分配',
        maintenance: '维护中',
        custody: '保管中',
        inactive: '停用',
      },
      buttons: {
        cancel: '取消',
        save: '保存资产',
        saveChanges: '保存更改',
      },
      success: (assetName: string) => `${assetName} 已成功创建。`,
      successUpdated: (assetName: string) => `${assetName} 已成功更新。`,
    },
  },
};

export const hrLanguages = {
  'es-MX': baseSpanish,
  'es-CO': baseSpanish,
  'en-US': baseEnglish,
  'en-CA': baseEnglish,
  'fr-CA': {
    ...baseEnglish,
    ...hrAttendanceFr,
    ...hrAssetsFr,
    shell: {
      title: 'Ressources Humaines',
      subtitle: 'Gérez les employés, la présence, la paie et plus encore.',
      back: 'Retour',
      tabs: {
        collaborators: 'Employés',
        attendance: 'Présence',
        control: 'Contrôle',
        payroll: 'Paie',
        announcements: 'Annonces',
        assets: 'Actifs',
        records: 'Dossiers',
        permissions: 'Permissions',
        incentives: 'Incentives',
        kpis: 'KPIs',
      },
    },
  },
  'pt-BR': {
    ...baseEnglish,
    ...hrAttendancePt,
    ...hrAssetsPt,
    shell: {
      title: 'Recursos Humanos',
      subtitle: 'Gerencie funcionários, presença, folha de pagamento e muito mais.',
      back: 'Voltar',
      tabs: {
        collaborators: 'Funcionários',
        attendance: 'Presença',
        control: 'Controle',
        payroll: 'Folha de pagamento',
        announcements: 'Comunicados',
        assets: 'Ativos',
        records: 'Registros',
        permissions: 'Permissões',
        incentives: 'Incentives',
        kpis: 'KPIs',
      },
    },
  },
  'ko-CA': {
    ...baseEnglish,
    ...hrAttendanceKo,
    ...hrAssetsKo,
    shell: {
      title: '인사 관리',
      subtitle: '직원, 출석, 급여 등을 관리합니다.',
      back: '뒤로',
      tabs: {
        collaborators: '직원',
        attendance: '출석',
        control: '관리',
        payroll: '급여',
        announcements: '공지',
        assets: '자산',
        records: '기록',
        permissions: '권한',
        incentives: 'Incentives',
        kpis: 'KPIs',
      },
    },
  },
  'zh-CA': {
    ...baseEnglish,
    ...hrAttendanceZh,
    ...hrAssetsZh,
    shell: {
      title: '人力资源',
      subtitle: '管理员工、考勤、薪资等内容。',
      back: '返回',
      tabs: {
        collaborators: '员工',
        attendance: '考勤',
        control: '控制',
        payroll: '薪资',
        announcements: '公告',
        assets: '资产',
        records: '记录',
        permissions: '权限',
        incentives: 'Incentives',
        kpis: 'KPIs',
      },
    },
  },
} as const;

export type HRLanguagePack = (typeof hrLanguages)['es-MX'];

export function useHRLanguage(): HRLanguagePack {
  const { currentLanguage } = useLanguage();
  return hrLanguages[currentLanguage.code as keyof typeof hrLanguages] ?? hrLanguages['es-MX'];
}
