import type { LearningCharacterId, LearningModeControl } from '../../../learningMode';
import type { PanelInicialGuidanceTabId } from './types';

type CharacterExamples = Record<LearningCharacterId, string>;

interface PanelControlSeed {
  id: string;
  emoji: string;
  kind: string;
  title: string;
  purpose: string;
  behavior: string;
  whenToUse: string;
  result: string;
  focus: string;
  examples: CharacterExamples;
}

const createControl = ({ focus, examples, ...control }: PanelControlSeed): LearningModeControl => ({
  ...control,
  tipByCharacter: {
    emily: `Convierte ${focus} en un estándar claro que puedas repetir al abrir otra cafetería o sumar responsables.`,
    juanito: `Usa ${focus} como una fuente verificable; si el dato vive solo en tu memoria, después no podrás compararlo ni corregirlo.`,
    camila: `Deja ${focus} visible en el sistema, aunque hoy el acuerdo funcione de palabra entre personas de confianza.`,
  },
  storyByCharacter: examples,
});

export const panelInicialLearningControls: Record<
  PanelInicialGuidanceTabId,
  readonly LearningModeControl[]
> = {
  profile: [
    createControl({
      id: 'profile-photo',
      emoji: '📷',
      kind: 'Control del perfil',
      title: 'Foto de perfil',
      purpose: 'Identifica visualmente a la persona responsable de la cuenta y de las acciones que realiza.',
      behavior: 'Permite cargar, reemplazar o retirar la imagen asociada con el usuario.',
      whenToUse: 'Úsalo al configurar la cuenta o cuando cambie la imagen institucional de la persona.',
      result: 'Reduce confusiones entre usuarios y hace más clara la responsabilidad de cada acción.',
      focus: 'la identificación de cada responsable',
      examples: {
        emily: 'Emily pide que cada gerente use una fotografía reconocible. Cuando revisa actividades de distintas cafeterías sabe inmediatamente quién está detrás de cada cuenta.',
        juanito: 'Juanito antes identificaba a las personas solo por correos parecidos. Una foto clara le ayuda a relacionar datos, decisiones y responsables sin revisar otras listas.',
        camila: 'Camila asigna una imagen distinta a cada usuario familiar. La cercanía ya no provoca que varias personas trabajen desde una cuenta compartida.',
      },
    }),
    createControl({
      id: 'identity-and-contact',
      emoji: '🪪',
      kind: 'Formulario y guardado',
      title: 'Datos personales y de contacto',
      purpose: 'Mantiene nombre, país, teléfonos y datos de contacto correctos para identificar al usuario.',
      behavior: 'Valida la información capturada y guarda los cambios en el expediente de la cuenta.',
      whenToUse: 'Úsalo al crear el perfil y cada vez que cambie un teléfono, país o dato de identidad.',
      result: 'Evita notificaciones perdidas y registros con responsables difíciles de localizar.',
      focus: 'los datos personales y de contacto',
      examples: {
        emily: 'Emily mantiene actualizado el teléfono de cada gerente regional. Si una cafetería necesita apoyo, el equipo encuentra a la persona correcta sin buscar en conversaciones antiguas.',
        juanito: 'Juanito registra teléfonos con el formato correcto y deja de guardar números sueltos en hojas de cálculo. Ahora sabe cuál dato es el vigente.',
        camila: 'Camila centraliza los teléfonos que antes estaban repartidos entre agendas familiares. La empresa puede contactar a cada responsable sin depender de quién tenga guardado el número.',
      },
    }),
    createControl({
      id: 'account-security',
      emoji: '🔐',
      kind: 'Función de seguridad',
      title: 'Contraseña y seguridad',
      purpose: 'Protege el acceso personal y evita que varias personas operen con credenciales compartidas.',
      behavior: 'Permite actualizar la contraseña y validar los requisitos antes de guardar el cambio.',
      whenToUse: 'Úsalo ante una sospecha de acceso, un cambio de responsable o como revisión preventiva.',
      result: 'Conserva trazabilidad sobre quién consulta o modifica información de la empresa.',
      focus: 'la seguridad individual de cada cuenta',
      examples: {
        emily: 'Emily cambia las credenciales cuando un responsable deja una sucursal. Así protege el estándar de operación sin interrumpir el trabajo del resto del equipo.',
        juanito: 'Juanito relaciona cada acceso con una sola persona. Si un dato cambia, puede investigar el registro correcto en vez de preguntar a toda la tienda.',
        camila: 'Camila reemplaza la contraseña que compartía la familia por accesos individuales. No es desconfianza: es claridad para cuidar el negocio.',
      },
    }),
    createControl({
      id: 'language-preferences',
      emoji: '🌐',
      kind: 'Preferencia de usuario',
      title: 'Idioma y preferencias',
      purpose: 'Adapta la experiencia del sistema al idioma y contexto de trabajo de la persona.',
      behavior: 'Guarda la preferencia y la utiliza en textos, formatos y comunicaciones compatibles.',
      whenToUse: 'Úsalo al incorporar usuarios de otra región o cuando cambie la preferencia personal.',
      result: 'Reduce errores de interpretación y facilita que cada persona use las herramientas correctamente.',
      focus: 'las preferencias personales de trabajo',
      examples: {
        emily: 'Emily configura el idioma adecuado para cada responsable y conserva una experiencia consistente cuando coordina operaciones en diferentes regiones.',
        juanito: 'Juanito selecciona el idioma y los formatos que entiende mejor su equipo. Así los datos se leen igual en todas las tiendas.',
        camila: 'Camila ajusta las preferencias de cada usuario para que aprender el sistema no se sienta como una barrera adicional para su familia y colaboradores.',
      },
    }),
  ],
  'business-structure': [
    createControl({
      id: 'business-identity',
      emoji: '🏢',
      kind: 'Configuración empresarial',
      title: 'Identidad de la empresa',
      purpose: 'Define nombre, industria, descripción, dirección y datos que identifican a la organización.',
      behavior: 'Guarda una referencia común que los demás módulos usan para entender el contexto operativo.',
      whenToUse: 'Úsalo al iniciar la configuración o cuando cambie la información legal u operativa principal.',
      result: 'Evita que cada módulo utilice nombres, direcciones o contextos diferentes para la misma empresa.',
      focus: 'la identidad oficial de la empresa',
      examples: {
        emily: 'Emily define una identidad central para su marca de cafeterías. Cada nueva sucursal parte del mismo nombre, industria y descripción de servicio.',
        juanito: 'Juanito concentra la información principal del grupo de supermercados. Sus reportes dejan de mezclar nombres abreviados o direcciones capturadas de distintas maneras.',
        camila: 'Camila formaliza los datos de la refaccionaria que antes solo conocía la familia. Proveedores y colaboradores comienzan a trabajar con la misma referencia.',
      },
    }),
    createControl({
      id: 'operation-type',
      emoji: '🧭',
      kind: 'Selector operativo',
      title: 'Tipo de operación',
      purpose: 'Indica cómo está organizada la empresa para que la estructura represente la realidad.',
      behavior: 'Ajusta las opciones de unidades y negocios según el modelo operativo seleccionado.',
      whenToUse: 'Úsalo antes de crear unidades, sucursales o negocios dependientes.',
      result: 'Evita construir una jerarquía que después no coincida con la forma real de operar.',
      focus: 'el modelo operativo de la empresa',
      examples: {
        emily: 'Emily define una operación con varias sucursales antes de registrar cafeterías. La estructura queda preparada para crecer sin improvisar jerarquías.',
        juanito: 'Juanito separa la organización administrativa de cada tienda. Esto le permite comparar números sin perder de vista dónde se genera cada resultado.',
        camila: 'Camila distingue la empresa principal de sus futuros puntos de venta. La expansión deja de ser una idea informal y adquiere una estructura concreta.',
      },
    }),
    createControl({
      id: 'manage-units',
      emoji: '🗂️',
      kind: 'Botones de estructura',
      title: 'Crear y editar unidades',
      purpose: 'Agrupa operaciones administrativas, regionales o funcionales bajo una estructura común.',
      behavior: 'Los botones de agregar y editar abren el formulario de la unidad; guardar confirma los datos y cancelar descarta el cambio.',
      whenToUse: 'Úsalo cuando necesites separar regiones, divisiones o áreas con administración propia.',
      result: 'Permite asignar personas, negocios y reportes al nivel correcto de la organización.',
      focus: 'las unidades organizacionales',
      examples: {
        emily: 'Emily crea unidades regionales para agrupar cafeterías. Puede comparar zonas y asignar responsables sin mezclar operaciones locales.',
        juanito: 'Juanito crea una unidad para administración y otra para operación comercial. Sus números ahora tienen un contexto organizacional claro.',
        camila: 'Camila crea unidades para administración y operación aunque hoy compartan edificio. Así comienza a delegar funciones con límites visibles.',
      },
    }),
    createControl({
      id: 'manage-businesses',
      emoji: '🏪',
      kind: 'Botones de estructura',
      title: 'Crear y editar negocios o sucursales',
      purpose: 'Registra cada operación concreta donde trabajan personas, se generan movimientos y se miden resultados.',
      behavior: 'Permite agregar, modificar y relacionar un negocio con su unidad correspondiente.',
      whenToUse: 'Úsalo al abrir una sucursal, separar una línea de negocio o corregir su asignación.',
      result: 'Hace posible filtrar colaboradores, gastos, ventas e indicadores por operación real.',
      focus: 'cada negocio y sucursal',
      examples: {
        emily: 'Emily registra cada cafetería como un negocio distinto. Cuando compara servicio, equipo o ventas sabe exactamente a qué sucursal pertenece cada dato.',
        juanito: 'Juanito separa sus supermercados por ubicación. Así identifica si una diferencia de inventario pertenece a una tienda específica y no al grupo completo.',
        camila: 'Camila registra la tienda y el almacén como operaciones relacionadas. Puede delegar responsabilidades sin perder la visión del negocio familiar.',
      },
    }),
    createControl({
      id: 'locations',
      emoji: '📍',
      kind: 'Configuración de ubicación',
      title: 'Dirección y coordenadas',
      purpose: 'Ubica físicamente la empresa, sus unidades y negocios para funciones que dependen del lugar.',
      behavior: 'Permite capturar dirección, buscar coordenadas o corregirlas manualmente antes de guardar.',
      whenToUse: 'Úsalo al configurar una sede y antes de activar asistencia, kioscos o servicios por ubicación.',
      result: 'Evita registros de asistencia o reportes vinculados con una ubicación incorrecta.',
      focus: 'las ubicaciones operativas',
      examples: {
        emily: 'Emily registra coordenadas exactas de cada cafetería antes de activar controles de asistencia. Los equipos marcan entrada donde realmente trabajan.',
        juanito: 'Juanito valida la dirección de cada supermercado para que reportes y kioscos no mezclen tiendas con nombres parecidos.',
        camila: 'Camila ubica correctamente tienda y almacén. Las entregas y responsabilidades dejan de depender de instrucciones informales.',
      },
    }),
    createControl({
      id: 'save-cancel-delete',
      emoji: '✅',
      kind: 'Controles de confirmación',
      title: 'Guardar, cancelar y eliminar',
      purpose: 'Confirma cambios válidos, descarta capturas accidentales o retira estructuras que ya no corresponden.',
      behavior: 'Guardar persiste la información, cancelar recupera el estado anterior y eliminar solicita confirmación antes de continuar.',
      whenToUse: 'Úsalos al terminar una edición y revisa dependencias antes de eliminar una unidad o negocio.',
      result: 'Protege la estructura contra cambios incompletos o eliminaciones accidentales.',
      focus: 'la confirmación de cambios estructurales',
      examples: {
        emily: 'Emily revisa la estructura antes de guardar y confirma eliminaciones solo cuando una sucursal ya fue cerrada y sus responsabilidades están reasignadas.',
        juanito: 'Juanito compara el estado anterior con el nuevo antes de confirmar. Si los datos no cuadran, cancela y revisa en lugar de guardar por impulso.',
        camila: 'Camila usa las confirmaciones para separar decisiones familiares de cambios operativos permanentes. Nada se elimina solo porque alguien lo comentó de palabra.',
      },
    }),
  ],
  'business-profile': [
    createControl({
      id: 'start-diagnosis',
      emoji: '🧩',
      kind: 'Diagnóstico empresarial',
      title: 'Iniciar o continuar diagnóstico',
      purpose: 'Evalúa la madurez de personas, procesos, productos y finanzas mediante preguntas estructuradas.',
      behavior: 'Abre el pilar seleccionado y conserva el avance para continuar después.',
      whenToUse: 'Úsalo al comenzar la implementación y periódicamente para medir cambios reales.',
      result: 'Convierte percepciones generales en prioridades concretas de mejora.',
      focus: 'el diagnóstico de madurez',
      examples: {
        emily: 'Emily completa un pilar a la vez antes de abrir otra cafetería. El diagnóstico le muestra qué estándar todavía depende demasiado de ella.',
        juanito: 'Juanito usa las respuestas para complementar sus indicadores financieros. Descubre problemas de personas y procesos que no aparecen directamente en una venta.',
        camila: 'Camila responde con honestidad aunque algunas prácticas familiares todavía sean informales. Así identifica por dónde profesionalizar sin perder la esencia del negocio.',
      },
    }),
    createControl({
      id: 'answer-navigation',
      emoji: '➡️',
      kind: 'Controles del cuestionario',
      title: 'Responder, avanzar y regresar',
      purpose: 'Registra cada respuesta y permite revisar preguntas sin perder el contexto del pilar.',
      behavior: 'Selecciona una opción y usa los botones anterior o siguiente para recorrer la evaluación.',
      whenToUse: 'Úsalos durante cada sesión de diagnóstico y corrige respuestas antes de completar el pilar.',
      result: 'Mantiene una evaluación ordenada y reduce respuestas omitidas o contradictorias.',
      focus: 'las respuestas del diagnóstico',
      examples: {
        emily: 'Emily revisa una respuesta cuando detecta que dos cafeterías operan de forma distinta. Ajusta la evaluación para reflejar el estándar real, no el ideal.',
        juanito: 'Juanito avanza pregunta por pregunta y vuelve cuando encuentra un dato que contradice su primera respuesta. Prefiere una lectura confiable a terminar rápido.',
        camila: 'Camila conversa con su equipo y corrige respuestas antes de avanzar. El diagnóstico deja de ser solo su percepción y representa mejor al negocio.',
      },
    }),
    createControl({
      id: 'complete-pillar',
      emoji: '🎯',
      kind: 'Botón de finalización',
      title: 'Guardar y completar un pilar',
      purpose: 'Consolida las respuestas y marca el bloque como listo para formar parte del reporte.',
      behavior: 'Valida que la sección tenga información suficiente y guarda su estado de avance o conclusión.',
      whenToUse: 'Úsalo después de revisar todas las respuestas del pilar.',
      result: 'Evita producir recomendaciones con secciones incompletas.',
      focus: 'el cierre de cada pilar',
      examples: {
        emily: 'Emily completa el pilar de Procesos solo cuando confirma que las sucursales aplican el mismo criterio. El resultado se convierte en una base para crecer.',
        juanito: 'Juanito verifica que todas las respuestas tengan evidencia antes de completar. Así el reporte no se apoya únicamente en intuiciones.',
        camila: 'Camila completa cada pilar después de acordar qué prácticas ya existen y cuáles siguen pendientes. La familia comparte una lectura común del negocio.',
      },
    }),
    createControl({
      id: 'print-diagnosis',
      emoji: '🖨️',
      kind: 'Botón de acción',
      title: 'Imprimir diagnóstico',
      purpose: 'Genera un reporte con resultados, señales y recomendaciones de madurez empresarial.',
      behavior: 'Prepara el documento con la información guardada y abre el flujo de impresión o exportación.',
      whenToUse: 'Úsalo cuando necesites revisar prioridades con socios, responsables o asesores.',
      result: 'Transforma el diagnóstico en una conversación de decisiones y seguimiento.',
      focus: 'el reporte de madurez',
      examples: {
        emily: 'Emily comparte el reporte con sus gerentes y convierte cada riesgo en una iniciativa para la siguiente etapa de expansión.',
        juanito: 'Juanito compara el reporte actual con revisiones anteriores. Observa si las mejoras operativas acompañan el crecimiento de sus números.',
        camila: 'Camila revisa el diagnóstico impreso con su familia. Las conversaciones dejan de depender de opiniones aisladas y se enfocan en prioridades visibles.',
      },
    }),
  ],
  consulting: [
    createControl({
      id: 'consulting-time-request',
      emoji: '📅',
      kind: 'Agenda de consultoría',
      title: 'Horario preferente y alternativa',
      purpose: 'Propone dos horarios posibles para coordinar una sesión de 50 minutos con el equipo de Índice.',
      behavior: 'Registra la fecha, hora y zona horaria; el equipo confirma por correo el espacio definitivo.',
      whenToUse: 'Úsalo cuando tengas un reto concreto o una decisión que requiera acompañamiento.',
      result: 'Evita intercambios innecesarios y conserva la solicitud visible dentro de la cuenta.',
      focus: 'la coordinación de la sesión de consultoría',
      examples: {
        emily: 'Emily propone dos horarios en los que puede participar su responsable de operación y recibe una confirmación clara para preparar la sesión.',
        juanito: 'Juanito registra su zona horaria y evita confundir la hora de la reunión cuando viaja entre ubicaciones.',
        camila: 'Camila elige un horario sin interrumpir la atención de la refaccionaria y conserva la solicitud dentro del sistema.',
      },
    }),
    createControl({
      id: 'consulting-context',
      emoji: '🧭',
      kind: 'Preparación de la sesión',
      title: 'Tema y contexto',
      purpose: 'Explica el reto, la decisión o el resultado que necesitas trabajar durante la consultoría.',
      behavior: 'Envía el tema y las notas junto con tus datos de contacto al equipo consultor.',
      whenToUse: 'Complétalo antes de solicitar la sesión para que la conversación empiece con contexto suficiente.',
      result: 'Permite dedicar los 50 minutos a tomar decisiones y no a reconstruir información básica.',
      focus: 'la preparación del objetivo de consultoría',
      examples: {
        emily: 'Emily describe la inconsistencia entre sucursales para que el consultor prepare preguntas sobre estandarización.',
        juanito: 'Juanito indica el indicador que quiere corregir y lleva la conversación directamente a causas y acciones.',
        camila: 'Camila explica el acuerdo familiar que necesita formalizar y llega a la sesión con una decisión concreta por resolver.',
      },
    }),
  ],
  'personal-performance': [
    createControl({
      id: 'start-performance-section',
      emoji: '🌱',
      kind: 'Evaluación personal',
      title: 'Iniciar o continuar una dimensión',
      purpose: 'Revisa hábitos de descanso, energía, claridad y sostenibilidad que influyen en la ejecución del líder.',
      behavior: 'Abre la dimensión seleccionada y recupera las respuestas guardadas anteriormente.',
      whenToUse: 'Úsalo para una revisión personal periódica o cuando notes desgaste en tus decisiones.',
      result: 'Hace visible si el crecimiento del negocio está dependiendo de un esfuerzo personal insostenible.',
      focus: 'los hábitos personales de liderazgo',
      examples: {
        emily: 'Emily revisa su energía antes de una etapa de expansión. Ajusta su agenda para seguir tomando decisiones estratégicas sin convertirse en el cuello de botella.',
        juanito: 'Juanito descubre que revisar números hasta tarde está afectando su claridad al día siguiente. Usa la evaluación para diseñar una rutina más consistente.',
        camila: 'Camila reconoce que resolver personalmente cada problema la está agotando. La evaluación le ayuda a identificar qué debe delegar.',
      },
    }),
    createControl({
      id: 'performance-navigation',
      emoji: '🧠',
      kind: 'Controles del cuestionario',
      title: 'Responder, avanzar y regresar',
      purpose: 'Registra respuestas personales y permite revisarlas antes de cerrar cada dimensión.',
      behavior: 'Selecciona una respuesta y usa los controles anterior, siguiente o volver a secciones.',
      whenToUse: 'Úsalos durante la evaluación y evita responder de forma automática.',
      result: 'Construye una lectura personal consistente en lugar de una impresión momentánea.',
      focus: 'la revisión consciente de cada respuesta',
      examples: {
        emily: 'Emily regresa a una pregunta cuando nota que su respuesta cambia según la sucursal. Identifica dónde necesita fortalecer a sus gerentes.',
        juanito: 'Juanito responde con la misma disciplina que utiliza al revisar un indicador: observa el periodo completo y no solo el día más reciente.',
        camila: 'Camila se da tiempo para distinguir entre ayudar al equipo y hacer el trabajo de todos. Esa reflexión cambia varias de sus respuestas.',
      },
    }),
    createControl({
      id: 'complete-performance',
      emoji: '✅',
      kind: 'Botón de finalización',
      title: 'Guardar y completar dimensión',
      purpose: 'Conserva el avance y marca una dimensión como lista para formar parte de la lectura final.',
      behavior: 'Valida las respuestas, guarda el estado y actualiza el progreso general.',
      whenToUse: 'Úsalo cuando hayas revisado todas las preguntas de la dimensión.',
      result: 'Permite comparar avances personales sin perder evaluaciones anteriores.',
      focus: 'el seguimiento del desempeño personal',
      examples: {
        emily: 'Emily completa cada dimensión y programa una nueva revisión después de delegar responsabilidades. Comprueba si el cambio mejora su capacidad de dirigir.',
        juanito: 'Juanito conserva resultados por periodo para observar tendencias personales, igual que hace con las ventas de sus tiendas.',
        camila: 'Camila termina la evaluación y elige un hábito concreto para dejar de absorber todos los pendientes de la refaccionaria.',
      },
    }),
    createControl({
      id: 'print-performance',
      emoji: '🖨️',
      kind: 'Botón de acción',
      title: 'Imprimir reporte personal',
      purpose: 'Genera una lectura estructurada de resultados y recomendaciones de desempeño.',
      behavior: 'Prepara el documento con las respuestas guardadas y abre el flujo de impresión o exportación.',
      whenToUse: 'Úsalo para definir compromisos personales o revisar avances con un coach o asesor.',
      result: 'Convierte la reflexión personal en acciones que sostienen el crecimiento de la empresa.',
      focus: 'el plan personal de mejora',
      examples: {
        emily: 'Emily usa el reporte para definir qué decisiones conservará y cuáles delegará a sus gerentes durante el siguiente trimestre.',
        juanito: 'Juanito traduce el reporte en dos hábitos medibles: horario de revisión y tiempo sin interrupciones para decisiones importantes.',
        camila: 'Camila comparte voluntariamente sus compromisos con un familiar de confianza para que delegar se convierta en una práctica real.',
      },
    }),
  ],
  users: [
    createControl({
      id: 'invite-user',
      emoji: '➕',
      kind: 'Botón de acción',
      title: 'Invitar usuario',
      purpose: 'Crea una invitación y prepara el acceso de una persona al espacio de trabajo.',
      behavior: 'Abre el formulario para asignar nombre, correo, rol, unidad, negocio, módulos y permisos iniciales.',
      whenToUse: 'Úsalo cuando una persona necesite operar directamente dentro de Índice.',
      result: 'Evita cuentas compartidas y deja claro quién puede realizar cada acción.',
      focus: 'el acceso individual de cada usuario',
      examples: {
        emily: 'Emily invita a cada gerente con su propio correo y permisos de sucursal. Puede delegar sin entregar acceso innecesario a toda la organización.',
        juanito: 'Juanito crea un usuario para cada encargado de tienda. Los movimientos dejan de aparecer bajo una cuenta genérica y los datos tienen responsable.',
        camila: 'Camila invita a familiares y vendedores por separado. La confianza permanece, pero las acciones ya no se mezclan en un solo acceso.',
      },
    }),
    createControl({
      id: 'user-search-filters',
      emoji: '🔎',
      kind: 'Herramientas de consulta',
      title: 'Buscar, filtrar y ordenar usuarios',
      purpose: 'Localiza personas por nombre, rol, estado o contexto empresarial.',
      behavior: 'La búsqueda y filtros reducen la tabla; los encabezados cambian el orden de lectura.',
      whenToUse: 'Úsalos antes de editar accesos, revisar invitaciones o limpiar usuarios inactivos.',
      result: 'Reduce errores al trabajar con listas extensas o personas con nombres similares.',
      focus: 'la consulta ordenada de usuarios',
      examples: {
        emily: 'Emily filtra gerentes activos antes de revisar permisos de una región. Trabaja sobre el grupo correcto sin recorrer todas las cafeterías.',
        juanito: 'Juanito ordena por tienda y estado para comparar cuentas activas contra su lista de responsables. Detecta accesos que ya no corresponden.',
        camila: 'Camila busca a una persona antes de cambiar sus permisos. Evita crear otra invitación solo porque no recordaba con qué correo estaba registrada.',
      },
    }),
    createControl({
      id: 'business-assignment',
      emoji: '🏪',
      kind: 'Asignación operativa',
      title: 'Asignar unidad y negocio',
      purpose: 'Relaciona al usuario con la parte de la empresa donde realmente trabaja.',
      behavior: 'Los selectores actualizan la unidad y el negocio permitidos según el alcance del administrador.',
      whenToUse: 'Úsalo al invitar, trasladar o cambiar la responsabilidad de una persona.',
      result: 'Mantiene datos, permisos y responsabilidades conectados con la operación correcta.',
      focus: 'la ubicación organizacional del usuario',
      examples: {
        emily: 'Emily asigna cada gerente a su región y cafetería. La información que consulta coincide con la operación que debe dirigir.',
        juanito: 'Juanito cambia a un encargado de tienda y actualiza su asignación. Sus reportes ya no mezclan movimientos de la ubicación anterior.',
        camila: 'Camila vincula a cada familiar con tienda, almacén o administración. Las responsabilidades dejan de depender de quién esté disponible ese día.',
      },
    }),
    createControl({
      id: 'module-access',
      emoji: '🧰',
      kind: 'Configuración de acceso',
      title: 'Asignar módulos',
      purpose: 'Define qué herramientas completas puede abrir cada usuario.',
      behavior: 'Permite seleccionar módulos dentro del alcance del administrador y guardar la nueva asignación.',
      whenToUse: 'Úsalo al incorporar a alguien o cuando cambie su responsabilidad.',
      result: 'Reduce exposición de información y evita que las personas trabajen en herramientas ajenas a su función.',
      focus: 'el acceso a módulos según responsabilidad',
      examples: {
        emily: 'Emily da acceso a RH y Procesos a sus gerentes, pero conserva Finanzas para los responsables autorizados. Cada rol ve lo necesario.',
        juanito: 'Juanito asigna Inventario al encargado de almacén y Ventas al responsable comercial. Los permisos siguen la estructura que usa para medir resultados.',
        camila: 'Camila deja de compartir acceso total con toda la familia. Cada persona recibe los módulos relacionados con su trabajo real.',
      },
    }),
    createControl({
      id: 'tab-permissions',
      emoji: '🛡️',
      kind: 'Configuración de permisos',
      title: 'Permisos por pestaña',
      purpose: 'Ajusta el acceso dentro de un módulo para separar funciones sensibles o especializadas.',
      behavior: 'El selector muestra las pestañas disponibles de los módulos asignados y guarda únicamente las autorizadas.',
      whenToUse: 'Úsalo cuando una persona necesita una parte del módulo, pero no todas sus funciones.',
      result: 'Aplica el principio de acceso necesario sin bloquear el trabajo cotidiano.',
      focus: 'los permisos detallados por función',
      examples: {
        emily: 'Emily permite a una gerente revisar asistencia, pero no modificar nómina. La operación avanza sin exponer información sensible.',
        juanito: 'Juanito autoriza inventario y reportes a un encargado, pero conserva configuraciones críticas. Cada permiso puede explicarse con una responsabilidad.',
        camila: 'Camila separa quién vende, quién administra usuarios y quién revisa finanzas. Los acuerdos familiares se convierten en límites operativos claros.',
      },
    }),
    createControl({
      id: 'invitation-actions',
      emoji: '✉️',
      kind: 'Acciones de invitación',
      title: 'Copiar enlace y reenviar invitación',
      purpose: 'Recupera una invitación pendiente sin crear usuarios duplicados.',
      behavior: 'Copia el enlace vigente o genera y envía nuevamente la invitación al correo registrado.',
      whenToUse: 'Úsalos cuando la persona no recibió, perdió o dejó vencer su acceso inicial.',
      result: 'Mantiene una sola identidad por persona y conserva su configuración previa.',
      focus: 'el seguimiento de invitaciones pendientes',
      examples: {
        emily: 'Emily reenvía la invitación a una gerente nueva en lugar de crear otra cuenta. Conserva los permisos y la sucursal que ya había preparado.',
        juanito: 'Juanito revisa el estado pendiente y reutiliza el mismo registro. Evita que dos cuentas alteren sus conteos de usuarios.',
        camila: 'Camila copia el enlace para ayudar a un familiar a terminar el registro, sin compartirle una contraseña genérica.',
      },
    }),
    createControl({
      id: 'remove-user',
      emoji: '🗑️',
      kind: 'Acción de seguridad',
      title: 'Retirar o eliminar acceso',
      purpose: 'Impide que una persona que ya no participa conserve acceso a la empresa.',
      behavior: 'Solicita confirmación y elimina la invitación o usuario según las reglas y protecciones del sistema.',
      whenToUse: 'Úsalo después de reasignar pendientes, documentos y responsabilidades de salida.',
      result: 'Cierra accesos oportunamente sin retirar por accidente a usuarios protegidos.',
      focus: 'el cierre responsable de accesos',
      examples: {
        emily: 'Emily retira el acceso de un responsable después de completar el traspaso de sucursal. Evita credenciales activas sin dueño operativo.',
        juanito: 'Juanito compara usuarios activos con su plantilla y elimina únicamente los registros confirmados. Sus conteos y accesos vuelven a coincidir.',
        camila: 'Camila documenta la salida y retira el acceso aunque exista una relación familiar. Protege la empresa sin convertir la decisión en un conflicto personal.',
      },
    }),
  ],
};
