CREATE TABLE IF NOT EXISTS finance_payable_kiosks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  provider_id BIGINT NULL,
  code VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  access_type VARCHAR(32) NOT NULL DEFAULT 'MIXED',
  public_access_token VARCHAR(128) NOT NULL,
  pin_hash VARCHAR(120) NOT NULL,
  currency_code VARCHAR(3) NOT NULL DEFAULT 'MXN',
  allow_provider_registration BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  UNIQUE KEY uq_finance_payable_kiosks_token (public_access_token),
  UNIQUE KEY uq_finance_payable_kiosks_company_code (company_id, code),
  KEY idx_finance_payable_kiosks_company_status (company_id, status),
  KEY idx_finance_payable_kiosks_unit (company_id, unit_id),
  KEY idx_finance_payable_kiosks_business (company_id, business_id),
  KEY idx_finance_payable_kiosks_provider (company_id, provider_id),
  CONSTRAINT fk_finance_payable_kiosks_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_payable_kiosks_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payable_kiosks_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payable_kiosks_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payable_kiosks_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payable_kiosks_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_payable_kiosks_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT chk_finance_payable_kiosks_access_type CHECK (access_type IN ('MIXED', 'PROVIDER', 'EMPLOYEE', 'PROVIDER_REGISTRATION'))
);
