CREATE TABLE IF NOT EXISTS finance_payable_kiosk_provider_access (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NOT NULL,
  kiosk_id BIGINT NOT NULL,
  provider_id BIGINT NOT NULL,
  pin_hash VARCHAR(120) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  failed_attempts INT NOT NULL DEFAULT 0,
  locked_until TIMESTAMP NULL,
  last_used_at TIMESTAMP NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP NULL,
  UNIQUE KEY uq_payable_kiosk_provider_access (kiosk_id, provider_id),
  KEY idx_payable_kiosk_provider_access_company (company_id, status),
  KEY idx_payable_kiosk_provider_access_provider (company_id, provider_id),
  CONSTRAINT fk_payable_kiosk_provider_access_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_payable_kiosk_provider_access_kiosk FOREIGN KEY (kiosk_id) REFERENCES finance_payable_kiosks(id) ON DELETE CASCADE,
  CONSTRAINT fk_payable_kiosk_provider_access_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE CASCADE,
  CONSTRAINT fk_payable_kiosk_provider_access_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_payable_kiosk_provider_access_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_payable_kiosk_provider_access_status CHECK (status IN ('ACTIVE', 'REVOKED'))
);
