CREATE TABLE `hr_assets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `asset_code` varchar(80) NOT NULL,
  `asset_type` varchar(50) NOT NULL,
  `name` varchar(160) NOT NULL,
  `model` varchar(160) DEFAULT NULL,
  `serial_number` varchar(160) DEFAULT NULL,
  `responsible_employee_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'available',
  `assigned_at` datetime DEFAULT NULL,
  `value_amount` decimal(12,2) DEFAULT NULL,
  `notes` text,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hr_assets_company_asset_code` (`company_id`,`asset_code`),
  UNIQUE KEY `uk_hr_assets_company_serial_number` (`company_id`,`serial_number`),
  KEY `idx_hr_assets_company_status` (`company_id`,`status`),
  KEY `idx_hr_assets_company_responsible` (`company_id`,`responsible_employee_id`),
  KEY `idx_hr_assets_company_unit` (`company_id`,`unit_id`),
  KEY `idx_hr_assets_company_type` (`company_id`,`asset_type`),
  KEY `idx_hr_assets_company_updated_at` (`company_id`,`updated_at`),
  CONSTRAINT `fk_hr_assets_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_assets_employee` FOREIGN KEY (`responsible_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_assets_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_assets_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_assets_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_hr_assets_status` CHECK (`status` IN ('available', 'assigned', 'maintenance', 'custody', 'inactive')),
  CONSTRAINT `chk_hr_assets_value_amount` CHECK (`value_amount` IS NULL OR `value_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `hr_asset_assignments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `asset_id` bigint NOT NULL,
  `responsible_employee_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `assignment_status` varchar(30) NOT NULL,
  `started_at` datetime NOT NULL,
  `ended_at` datetime DEFAULT NULL,
  `notes` text,
  `created_by_user_id` bigint DEFAULT NULL,
  `ended_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_asset_assignments_company_asset_started` (`company_id`,`asset_id`,`started_at`),
  KEY `idx_hr_asset_assignments_asset_ended` (`asset_id`,`ended_at`),
  KEY `idx_hr_asset_assignments_company_employee_started` (`company_id`,`responsible_employee_id`,`started_at`),
  CONSTRAINT `fk_hr_asset_assignments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_assignments_asset` FOREIGN KEY (`asset_id`) REFERENCES `hr_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_assignments_employee` FOREIGN KEY (`responsible_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_assignments_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_assignments_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_assignments_ended_by_user` FOREIGN KEY (`ended_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_hr_asset_assignments_status` CHECK (`assignment_status` IN ('assigned', 'custody'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `hr_asset_status_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `asset_id` bigint NOT NULL,
  `from_status` varchar(30) DEFAULT NULL,
  `to_status` varchar(30) NOT NULL,
  `change_reason` varchar(50) DEFAULT NULL,
  `notes` text,
  `changed_by_user_id` bigint DEFAULT NULL,
  `changed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_asset_status_history_company_asset_changed` (`company_id`,`asset_id`,`changed_at`),
  KEY `idx_hr_asset_status_history_company_to_status_changed` (`company_id`,`to_status`,`changed_at`),
  CONSTRAINT `fk_hr_asset_status_history_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_status_history_asset` FOREIGN KEY (`asset_id`) REFERENCES `hr_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_status_history_changed_by_user` FOREIGN KEY (`changed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_hr_asset_status_history_from_status` CHECK (`from_status` IS NULL OR `from_status` IN ('available', 'assigned', 'maintenance', 'custody', 'inactive')),
  CONSTRAINT `chk_hr_asset_status_history_to_status` CHECK (`to_status` IN ('available', 'assigned', 'maintenance', 'custody', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
