CREATE TABLE IF NOT EXISTS `sales_commission_rules` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `rule_code` varchar(40) NOT NULL,
  `name` varchar(180) NOT NULL,
  `user_id` varchar(80) DEFAULT NULL,
  `user_name` varchar(180) DEFAULT NULL,
  `product_id` varchar(80) DEFAULT NULL,
  `product_name` varchar(220) DEFAULT NULL,
  `category_id` varchar(80) DEFAULT NULL,
  `category_name` varchar(180) DEFAULT NULL,
  `commission_type` varchar(40) NOT NULL,
  `commission_value` decimal(15,4) NOT NULL DEFAULT 0.0000,
  `valid_from` date DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `priority` int NOT NULL DEFAULT 50,
  `notes` text DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_commission_rules_company_code` (`company_id`, `rule_code`),
  KEY `idx_sales_commission_rules_resolution` (`company_id`, `status`, `valid_from`, `valid_until`, `priority`),
  CONSTRAINT `fk_sales_commission_rules_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_commission_rules_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_commission_rules_updated_by` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
