CREATE TABLE IF NOT EXISTS `hr_employee_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `record_number` VARCHAR(32) NULL,
  `employee_id` BIGINT NOT NULL,
  `employee_name_snapshot` VARCHAR(160) NOT NULL,
  `employee_position_snapshot` VARCHAR(160) NULL,
  `employee_department_snapshot` VARCHAR(160) NULL,
  `employee_unit_id_snapshot` BIGINT NULL,
  `employee_unit_name_snapshot` VARCHAR(160) NULL,
  `employee_business_id_snapshot` BIGINT NULL,
  `employee_business_name_snapshot` VARCHAR(160) NULL,
  `record_type` VARCHAR(32) NOT NULL,
  `severity` VARCHAR(16) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `title` VARCHAR(160) NOT NULL,
  `description` TEXT NOT NULL,
  `actions_taken` TEXT NULL,
  `event_date` DATETIME NOT NULL,
  `reported_by_user_id` BIGINT NOT NULL,
  `reported_by_employee_id` BIGINT NULL,
  `reported_by_name_snapshot` VARCHAR(160) NOT NULL,
  `created_by_user_id` BIGINT NOT NULL,
  `updated_by_user_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_records_company_number` (`company_id`, `record_number`),
  KEY `idx_hr_employee_records_company_employee` (`company_id`, `employee_id`),
  KEY `idx_hr_employee_records_company_status` (`company_id`, `status`),
  KEY `idx_hr_employee_records_company_type` (`company_id`, `record_type`),
  KEY `idx_hr_employee_records_company_event_date` (`company_id`, `event_date`),
  KEY `idx_hr_employee_records_company_deleted` (`company_id`, `deleted_at`),
  CONSTRAINT `fk_hr_employee_records_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_records_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_records_reported_by_user` FOREIGN KEY (`reported_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_hr_employee_records_reported_by_employee` FOREIGN KEY (`reported_by_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_employee_records_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_hr_employee_records_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `hr_employee_record_witnesses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `record_id` BIGINT NOT NULL,
  `witness_employee_id` BIGINT NULL,
  `witness_name_snapshot` VARCHAR(160) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_employee_record_witnesses_record` (`record_id`),
  KEY `idx_hr_employee_record_witnesses_company` (`company_id`),
  CONSTRAINT `fk_hr_employee_record_witnesses_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_witnesses_record` FOREIGN KEY (`record_id`) REFERENCES `hr_employee_records` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_witnesses_employee` FOREIGN KEY (`witness_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `hr_employee_record_attachments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `record_id` BIGINT NOT NULL,
  `original_filename` VARCHAR(255) NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `size_bytes` BIGINT NOT NULL,
  `object_key` VARCHAR(512) NOT NULL,
  `uploaded_by_user_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_record_attachments_object_key` (`company_id`, `object_key`),
  KEY `idx_hr_employee_record_attachments_record` (`record_id`),
  KEY `idx_hr_employee_record_attachments_company_deleted` (`company_id`, `deleted_at`),
  CONSTRAINT `fk_hr_employee_record_attachments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_attachments_record` FOREIGN KEY (`record_id`) REFERENCES `hr_employee_records` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_attachments_uploaded_by_user` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `hr_employee_record_activity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `record_id` BIGINT NOT NULL,
  `activity_type` VARCHAR(32) NOT NULL,
  `from_status` VARCHAR(16) NULL,
  `to_status` VARCHAR(16) NULL,
  `note` TEXT NULL,
  `actor_user_id` BIGINT NOT NULL,
  `actor_name_snapshot` VARCHAR(160) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_employee_record_activity_record` (`record_id`),
  KEY `idx_hr_employee_record_activity_company` (`company_id`),
  CONSTRAINT `fk_hr_employee_record_activity_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_activity_record` FOREIGN KEY (`record_id`) REFERENCES `hr_employee_records` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_activity_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
