CREATE TABLE IF NOT EXISTS pos_discount_rules (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NULL,
  name VARCHAR(180) NOT NULL,
  description VARCHAR(600) NOT NULL,
  scope VARCHAR(24) NOT NULL,
  discount_type VARCHAR(24) NOT NULL,
  discount_value DECIMAL(19,4) NOT NULL,
  currency_code VARCHAR(3) NOT NULL DEFAULT 'MXN',
  starts_at TIMESTAMP NOT NULL,
  ends_at TIMESTAMP NOT NULL,
  minimum_amount DECIMAL(19,4) NULL,
  maximum_discount_amount DECIMAL(19,4) NULL,
  customer_type VARCHAR(24) NULL,
  product_id BIGINT NULL,
  category VARCHAR(160) NULL,
  requires_authorization BOOLEAN NOT NULL DEFAULT FALSE,
  stackable BOOLEAN NOT NULL DEFAULT FALSE,
  priority INT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  enabled_channels_json JSON NOT NULL,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_pos_discount_rules_company (company_id),
  KEY idx_pos_discount_rules_effective (company_id, status, starts_at, ends_at),
  KEY idx_pos_discount_rules_product (company_id, product_id),
  KEY idx_pos_discount_rules_scope (company_id, unit_id, business_id, warehouse_id),
  CONSTRAINT fk_pos_discount_rules_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_discount_rules_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_discount_rules_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_discount_rules_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_discount_rules_product FOREIGN KEY (product_id) REFERENCES sales_products(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_discount_rules_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_discount_rules_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_discount_rules_scope CHECK (scope IN ('PRODUCT', 'CATEGORY', 'CUSTOMER', 'ORDER', 'MANUAL')),
  CONSTRAINT chk_pos_discount_rules_type CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
  CONSTRAINT chk_pos_discount_rules_status CHECK (status IN ('ACTIVE', 'PAUSED', 'ARCHIVED')),
  CONSTRAINT chk_pos_discount_rules_value CHECK (
    discount_value > 0
    AND (discount_type <> 'PERCENTAGE' OR discount_value <= 100)
    AND ends_at >= starts_at
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_discount_applications (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  rule_id BIGINT NOT NULL,
  ticket_id BIGINT NOT NULL,
  ticket_item_id BIGINT NULL,
  discount_amount DECIMAL(19,4) NOT NULL,
  authorized_by_user_id BIGINT NULL,
  rule_snapshot_json JSON NOT NULL,
  created_by_user_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pos_discount_applications_ticket (company_id, ticket_id),
  KEY idx_pos_discount_applications_rule (company_id, rule_id),
  CONSTRAINT fk_pos_discount_applications_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_discount_applications_rule FOREIGN KEY (rule_id) REFERENCES pos_discount_rules(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_discount_applications_ticket FOREIGN KEY (ticket_id) REFERENCES pos_tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_discount_applications_item FOREIGN KEY (ticket_item_id) REFERENCES pos_ticket_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_discount_applications_authorizer FOREIGN KEY (authorized_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_discount_applications_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_discount_applications_amount CHECK (discount_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
