CREATE TABLE pos_restaurant_ecosystems (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    business_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    settlement_cash_register_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    currency_code VARCHAR(3) NOT NULL DEFAULT 'MXN',
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_pos_restaurant_ecosystem_code (company_id, code),
    KEY idx_pos_restaurant_ecosystem_scope (company_id, unit_id, business_id, status),
    KEY idx_pos_restaurant_ecosystem_register (company_id, settlement_cash_register_id),
    CONSTRAINT fk_pos_restaurant_ecosystem_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_ecosystem_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_ecosystem_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_ecosystem_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_ecosystem_register FOREIGN KEY (settlement_cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_ecosystem_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_ecosystem_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_pos_restaurant_ecosystem_status CHECK (status IN ('ACTIVE', 'DISABLED', 'REVOKED'))
);

CREATE TABLE pos_restaurant_areas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    ecosystem_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pos_restaurant_area_code (company_id, ecosystem_id, code),
    KEY idx_pos_restaurant_area_ecosystem (company_id, ecosystem_id, status, sort_order),
    CONSTRAINT fk_pos_restaurant_area_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_area_ecosystem FOREIGN KEY (ecosystem_id) REFERENCES pos_restaurant_ecosystems(id) ON DELETE RESTRICT,
    CONSTRAINT chk_pos_restaurant_area_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE pos_restaurant_tables (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    ecosystem_id BIGINT NOT NULL,
    area_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    capacity INT NOT NULL DEFAULT 4,
    operational_status VARCHAR(24) NOT NULL DEFAULT 'AVAILABLE',
    sort_order INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pos_restaurant_table_code (company_id, ecosystem_id, code),
    KEY idx_pos_restaurant_table_area (company_id, ecosystem_id, area_id, operational_status),
    CONSTRAINT fk_pos_restaurant_table_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_table_ecosystem FOREIGN KEY (ecosystem_id) REFERENCES pos_restaurant_ecosystems(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_table_area FOREIGN KEY (area_id) REFERENCES pos_restaurant_areas(id) ON DELETE RESTRICT,
    CONSTRAINT chk_pos_restaurant_table_capacity CHECK (capacity BETWEEN 1 AND 100),
    CONSTRAINT chk_pos_restaurant_table_status CHECK (operational_status IN ('AVAILABLE', 'OCCUPIED', 'CHECK_REQUESTED', 'CHECKOUT', 'CLEANING', 'BLOCKED'))
);

CREATE TABLE pos_restaurant_kiosks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    ecosystem_id BIGINT NOT NULL,
    kiosk_type VARCHAR(40) NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    area_id BIGINT NULL,
    kitchen_station_code VARCHAR(80) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    expires_at TIMESTAMP NULL,
    public_token_hint VARCHAR(16) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_pos_restaurant_kiosk_code (company_id, code),
    KEY idx_pos_restaurant_kiosk_ecosystem (company_id, ecosystem_id, kiosk_type, status),
    CONSTRAINT fk_pos_restaurant_kiosk_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_kiosk_ecosystem FOREIGN KEY (ecosystem_id) REFERENCES pos_restaurant_ecosystems(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_kiosk_area FOREIGN KEY (area_id) REFERENCES pos_restaurant_areas(id) ON DELETE SET NULL,
    CONSTRAINT fk_pos_restaurant_kiosk_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_kiosk_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_pos_restaurant_kiosk_type CHECK (kiosk_type IN ('waiter_station', 'table_order_center', 'kitchen_display')),
    CONSTRAINT chk_pos_restaurant_kiosk_status CHECK (status IN ('ACTIVE', 'DISABLED', 'REVOKED'))
);

CREATE TABLE pos_restaurant_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    ecosystem_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    opened_by_user_company_id BIGINT NOT NULL,
    responsible_user_company_id BIGINT NOT NULL,
    source_kiosk_id BIGINT NOT NULL,
    settlement_cash_register_id BIGINT NOT NULL,
    ticket_id BIGINT NULL,
    order_number VARCHAR(80) NOT NULL,
    guest_count INT NOT NULL DEFAULT 1,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    currency_code VARCHAR(3) NOT NULL,
    subtotal_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    claimed_by_user_id BIGINT NULL,
    claimed_at TIMESTAMP NULL,
    check_requested_at TIMESTAMP NULL,
    paid_at TIMESTAMP NULL,
    closed_at TIMESTAMP NULL,
    notes VARCHAR(1000) NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pos_restaurant_order_number (company_id, order_number),
    KEY idx_pos_restaurant_order_table (company_id, ecosystem_id, table_id, status),
    KEY idx_pos_restaurant_order_checkout (company_id, settlement_cash_register_id, status, check_requested_at),
    CONSTRAINT fk_pos_restaurant_order_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_order_ecosystem FOREIGN KEY (ecosystem_id) REFERENCES pos_restaurant_ecosystems(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_table FOREIGN KEY (table_id) REFERENCES pos_restaurant_tables(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_opened_by FOREIGN KEY (opened_by_user_company_id) REFERENCES user_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_responsible FOREIGN KEY (responsible_user_company_id) REFERENCES user_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_kiosk FOREIGN KEY (source_kiosk_id) REFERENCES pos_restaurant_kiosks(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_register FOREIGN KEY (settlement_cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_ticket FOREIGN KEY (ticket_id) REFERENCES pos_tickets(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_order_claimed_by FOREIGN KEY (claimed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_pos_restaurant_order_guests CHECK (guest_count BETWEEN 1 AND 1000),
    CONSTRAINT chk_pos_restaurant_order_status CHECK (status IN ('OPEN', 'IN_SERVICE', 'CHECK_REQUESTED', 'READY_FOR_CHECKOUT', 'CLAIMED_FOR_CHECKOUT', 'PAID', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE pos_restaurant_order_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    kitchen_station_code VARCHAR(80) NOT NULL DEFAULT 'GENERAL',
    sku_snapshot VARCHAR(120) NULL,
    product_name_snapshot VARCHAR(240) NOT NULL,
    quantity DECIMAL(19,4) NOT NULL,
    unit_price DECIMAL(19,4) NOT NULL,
    line_total_amount DECIMAL(19,4) NOT NULL,
    notes VARCHAR(1000) NULL,
    modifier_summary VARCHAR(1000) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    sort_order INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pos_restaurant_item_order (company_id, order_id, status, sort_order),
    KEY idx_pos_restaurant_item_kitchen (company_id, kitchen_station_code, status, created_at),
    CONSTRAINT fk_pos_restaurant_item_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_item_order FOREIGN KEY (order_id) REFERENCES pos_restaurant_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_item_product FOREIGN KEY (product_id) REFERENCES sales_products(id) ON DELETE RESTRICT,
    CONSTRAINT chk_pos_restaurant_item_values CHECK (quantity > 0 AND unit_price >= 0 AND line_total_amount >= 0),
    CONSTRAINT chk_pos_restaurant_item_status CHECK (status IN ('DRAFT', 'SENT', 'ACKNOWLEDGED', 'PREPARING', 'READY', 'SERVED', 'CANCELLED', 'VOIDED'))
);

CREATE TABLE pos_restaurant_order_rounds (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    sent_by_user_company_id BIGINT NOT NULL,
    source_kiosk_id BIGINT NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pos_restaurant_round_number (company_id, order_id, round_number),
    CONSTRAINT fk_pos_restaurant_round_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_round_order FOREIGN KEY (order_id) REFERENCES pos_restaurant_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_round_sent_by FOREIGN KEY (sent_by_user_company_id) REFERENCES user_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_round_kiosk FOREIGN KEY (source_kiosk_id) REFERENCES pos_restaurant_kiosks(id) ON DELETE RESTRICT
);

CREATE TABLE pos_restaurant_round_items (
    round_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    PRIMARY KEY (round_id, order_item_id),
    KEY idx_pos_restaurant_round_item_order_item (company_id, order_item_id),
    CONSTRAINT fk_pos_restaurant_round_item_round FOREIGN KEY (round_id) REFERENCES pos_restaurant_order_rounds(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_round_item_item FOREIGN KEY (order_item_id) REFERENCES pos_restaurant_order_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_round_item_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE pos_restaurant_order_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL,
    company_id BIGINT NOT NULL,
    ecosystem_id BIGINT NOT NULL,
    order_id BIGINT NULL,
    order_item_id BIGINT NULL,
    kiosk_definition_id BIGINT NULL,
    actor_user_company_id BIGINT NULL,
    actor_user_id BIGINT NULL,
    event_type VARCHAR(80) NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NULL,
    reason VARCHAR(500) NULL,
    snapshot_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pos_restaurant_event_id (event_id),
    KEY idx_pos_restaurant_event_order (company_id, order_id, created_at),
    KEY idx_pos_restaurant_event_ecosystem (company_id, ecosystem_id, created_at),
    CONSTRAINT fk_pos_restaurant_event_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_restaurant_event_ecosystem FOREIGN KEY (ecosystem_id) REFERENCES pos_restaurant_ecosystems(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_event_order FOREIGN KEY (order_id) REFERENCES pos_restaurant_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_event_item FOREIGN KEY (order_item_id) REFERENCES pos_restaurant_order_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_restaurant_event_kiosk FOREIGN KEY (kiosk_definition_id) REFERENCES kiosk_definitions(id) ON DELETE SET NULL,
    CONSTRAINT fk_pos_restaurant_event_actor_company FOREIGN KEY (actor_user_company_id) REFERENCES user_companies(id) ON DELETE SET NULL,
    CONSTRAINT fk_pos_restaurant_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
);
