CREATE TABLE IF NOT EXISTS training_exam_attempts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    program_code VARCHAR(80) NOT NULL,
    program_version VARCHAR(40) NOT NULL,
    exam_code VARCHAR(80) NOT NULL,
    attempt_number INT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    submitted_at TIMESTAMP(6) NULL,
    question_codes_json JSON NOT NULL,
    answers_json JSON NOT NULL,
    score INT NULL,
    total_questions INT NOT NULL,
    passed BOOLEAN NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_training_exam_attempt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_training_exam_attempt_user_exam (user_id, program_code, program_version, exam_code, started_at),
    INDEX idx_training_exam_attempt_status (status, expires_at)
);

CREATE TABLE IF NOT EXISTS training_certificates (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    program_code VARCHAR(80) NOT NULL,
    program_version VARCHAR(40) NOT NULL,
    folio VARCHAR(80) NOT NULL,
    verification_token VARCHAR(120) NOT NULL,
    final_score INT NOT NULL,
    total_questions INT NOT NULL,
    issued_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_training_certificate_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY uk_training_certificate_folio (folio),
    UNIQUE KEY uk_training_certificate_token (verification_token),
    UNIQUE KEY uk_training_certificate_user_program (user_id, program_code, program_version),
    INDEX idx_training_certificate_status_expiry (status, expires_at)
);
