CREATE TABLE IF NOT EXISTS pos_square_oauth_states (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  state_hash CHAR(64) NOT NULL,
  environment VARCHAR(24) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_oauth_state_hash (state_hash),
  KEY idx_pos_square_oauth_company_status (company_id, status, expires_at),
  CONSTRAINT fk_pos_square_oauth_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_oauth_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_square_oauth_status CHECK (status IN ('PENDING', 'CONSUMED', 'EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_connections (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  environment VARCHAR(24) NOT NULL,
  merchant_id VARCHAR(128) NOT NULL,
  access_token_protected TEXT NOT NULL,
  refresh_token_protected TEXT NULL,
  token_expires_at TIMESTAMP NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'CONNECTED',
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_connections_company_env (company_id, environment),
  KEY idx_pos_square_connections_merchant (environment, merchant_id),
  CONSTRAINT fk_pos_square_connections_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_connections_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_connections_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_square_connections_status CHECK (status IN ('CONNECTED', 'DISABLED', 'ERROR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_locations (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  square_location_id VARCHAR(128) NOT NULL,
  name VARCHAR(180) NOT NULL,
  currency_code VARCHAR(3) NULL,
  country_code VARCHAR(2) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  linked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_locations_company_square (company_id, square_location_id),
  CONSTRAINT fk_pos_square_locations_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_locations_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_locations_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_terminals (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  square_location_row_id BIGINT NOT NULL,
  square_device_code_id VARCHAR(128) NOT NULL,
  square_device_id VARCHAR(128) NULL,
  name VARCHAR(180) NOT NULL,
  pairing_code_hint VARCHAR(32) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'UNPAIRED',
  pair_by TIMESTAMP NULL,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_terminals_code (company_id, square_device_code_id),
  UNIQUE KEY uk_pos_square_terminals_device (company_id, square_device_id),
  KEY idx_pos_square_terminals_company_status (company_id, status),
  CONSTRAINT fk_pos_square_terminals_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_terminals_location FOREIGN KEY (square_location_row_id) REFERENCES pos_square_locations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_terminals_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_terminals_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_square_terminals_status CHECK (status IN ('UNPAIRED', 'PAIRED', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_register_terminals (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  terminal_id BIGINT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  assigned_by_user_id BIGINT NOT NULL,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  removed_at TIMESTAMP NULL,
  active_register_id BIGINT GENERATED ALWAYS AS (CASE WHEN active THEN cash_register_id ELSE NULL END) STORED,
  active_terminal_id BIGINT GENERATED ALWAYS AS (CASE WHEN active THEN terminal_id ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_assignment_register (company_id, active_register_id),
  UNIQUE KEY uk_pos_square_assignment_terminal (company_id, active_terminal_id),
  CONSTRAINT fk_pos_square_assignment_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_assignment_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_assignment_terminal FOREIGN KEY (terminal_id) REFERENCES pos_square_terminals(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_assignment_user FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_terminal_payment_intents (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  shift_id BIGINT NOT NULL,
  terminal_id BIGINT NOT NULL,
  square_location_id VARCHAR(128) NOT NULL,
  square_device_id VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(64) NOT NULL,
  square_checkout_id VARCHAR(128) NULL,
  square_payment_id VARCHAR(128) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'WAITING',
  amount DECIMAL(19,4) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  checkout_payload_sha256 CHAR(64) NOT NULL,
  checkout_request_json JSON NOT NULL,
  square_request_json JSON NULL,
  square_response_json JSON NULL,
  failure_code VARCHAR(80) NULL,
  failure_message VARCHAR(500) NULL,
  finalize_attempts INT NOT NULL DEFAULT 0,
  pos_ticket_id BIGINT NULL,
  created_by_user_id BIGINT NOT NULL,
  created_by_role VARCHAR(40) NOT NULL,
  scope_type VARCHAR(40) NOT NULL,
  scope_unit_id BIGINT NULL,
  scope_business_id BIGINT NULL,
  recoverable_register_id BIGINT GENERATED ALWAYS AS (CASE WHEN status IN ('WAITING', 'APPROVED', 'UNCERTAIN') AND pos_ticket_id IS NULL THEN cash_register_id ELSE NULL END) STORED,
  recoverable_shift_id BIGINT GENERATED ALWAYS AS (CASE WHEN status IN ('WAITING', 'APPROVED', 'UNCERTAIN') AND pos_ticket_id IS NULL THEN shift_id ELSE NULL END) STORED,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_intents_idempotency (company_id, idempotency_key),
  UNIQUE KEY uk_pos_square_intents_checkout (square_checkout_id),
  UNIQUE KEY uk_pos_square_intents_payment (square_payment_id),
  UNIQUE KEY uk_pos_square_intents_open_shift (company_id, recoverable_register_id, recoverable_shift_id),
  KEY idx_pos_square_intents_company_status (company_id, status, updated_at),
  KEY idx_pos_square_intents_register_shift (company_id, cash_register_id, shift_id),
  KEY idx_pos_square_intents_recovery (status, expires_at, updated_at),
  CONSTRAINT fk_pos_square_intents_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_intents_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_intents_shift FOREIGN KEY (shift_id) REFERENCES pos_shifts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_intents_terminal FOREIGN KEY (terminal_id) REFERENCES pos_square_terminals(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_square_intents_ticket FOREIGN KEY (pos_ticket_id) REFERENCES pos_tickets(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_square_intents_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_square_intents_status CHECK (status IN ('WAITING', 'APPROVED', 'DECLINED', 'CANCELLED', 'UNCERTAIN')),
  CONSTRAINT chk_pos_square_intents_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_audit_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  actor_user_id BIGINT NULL,
  cash_register_id BIGINT NULL,
  terminal_id BIGINT NULL,
  intent_id BIGINT NULL,
  event_type VARCHAR(80) NOT NULL,
  status VARCHAR(32) NOT NULL,
  message VARCHAR(500) NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pos_square_audit_company_created (company_id, created_at),
  KEY idx_pos_square_audit_intent (company_id, intent_id, created_at),
  CONSTRAINT fk_pos_square_audit_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_square_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_square_audit_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_square_audit_terminal FOREIGN KEY (terminal_id) REFERENCES pos_square_terminals(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_square_audit_intent FOREIGN KEY (intent_id) REFERENCES pos_square_terminal_payment_intents(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_square_webhook_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  square_event_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  environment VARCHAR(24) NOT NULL,
  merchant_id VARCHAR(128) NULL,
  object_id VARCHAR(128) NULL,
  payload_sha256 CHAR(64) NOT NULL,
  raw_payload JSON NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'RECEIVED',
  duplicate_count INT NOT NULL DEFAULT 0,
  company_id BIGINT NULL,
  intent_id BIGINT NULL,
  terminal_id BIGINT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMP NULL,
  last_error_message VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_square_webhook_event (square_event_id),
  KEY idx_pos_square_webhook_status (status, received_at),
  KEY idx_pos_square_webhook_company (company_id, received_at),
  CONSTRAINT fk_pos_square_webhook_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_square_webhook_intent FOREIGN KEY (intent_id) REFERENCES pos_square_terminal_payment_intents(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_square_webhook_terminal FOREIGN KEY (terminal_id) REFERENCES pos_square_terminals(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_square_webhook_status CHECK (status IN ('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
