CREATE TABLE IF NOT EXISTS pos_inventory_receipts (
  id bigint NOT NULL AUTO_INCREMENT,
  company_id bigint NOT NULL,
  receipt_number varchar(40) NOT NULL,
  unit_id bigint DEFAULT NULL,
  business_id bigint DEFAULT NULL,
  warehouse_id bigint NOT NULL,
  cash_register_id bigint NOT NULL,
  shift_id bigint NOT NULL,
  counterparty_name varchar(180) NOT NULL,
  payment_method varchar(20) NOT NULL,
  payment_account_id bigint DEFAULT NULL,
  total_amount decimal(15,2) NOT NULL,
  currency_code char(3) NOT NULL,
  payment_reference varchar(160) DEFAULT NULL,
  status varchar(24) NOT NULL DEFAULT 'POSTED',
  reversal_reason varchar(500) DEFAULT NULL,
  reversed_at datetime DEFAULT NULL,
  reversed_by_user_id bigint DEFAULT NULL,
  cash_movement_id bigint DEFAULT NULL,
  treasury_movement_id bigint DEFAULT NULL,
  created_by_user_id bigint NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata_json json DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_inventory_receipts_company_number (company_id, receipt_number),
  KEY idx_pos_inventory_receipts_company_shift (company_id, shift_id, created_at),
  CONSTRAINT fk_pos_inventory_receipts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_inventory_receipts_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id),
  CONSTRAINT fk_pos_inventory_receipts_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id),
  CONSTRAINT fk_pos_inventory_receipts_shift FOREIGN KEY (shift_id) REFERENCES pos_shifts(id),
  CONSTRAINT fk_pos_inventory_receipts_payment_account FOREIGN KEY (payment_account_id) REFERENCES finance_payment_accounts(id),
  CONSTRAINT fk_pos_inventory_receipts_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_pos_inventory_receipts_reversed_by FOREIGN KEY (reversed_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS pos_inventory_receipt_items (
  id bigint NOT NULL AUTO_INCREMENT,
  company_id bigint NOT NULL,
  receipt_id bigint NOT NULL,
  product_id bigint NOT NULL,
  product_name_snapshot varchar(220) NOT NULL,
  product_sku_snapshot varchar(120) DEFAULT NULL,
  inventory_unit varchar(32) NOT NULL,
  quantity decimal(15,3) NOT NULL,
  unit_cost decimal(15,4) NOT NULL,
  line_total decimal(15,2) NOT NULL,
  inventory_movement_id bigint DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pos_inventory_receipt_items_receipt (company_id, receipt_id),
  CONSTRAINT fk_pos_inventory_receipt_items_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_inventory_receipt_items_receipt FOREIGN KEY (receipt_id) REFERENCES pos_inventory_receipts(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_inventory_receipt_items_product FOREIGN KEY (product_id) REFERENCES sales_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

