-- Opt-in report schedules and immutable in-application report snapshots. No outbound delivery.
CREATE TABLE kpi_automated_report_rules (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  created_by_user_id BIGINT NOT NULL,
  title VARCHAR(140) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  report_type VARCHAR(24) NOT NULL,
  cadence VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  preferred_currency CHAR(3) NOT NULL,
  next_run_at TIMESTAMP NULL,
  last_run_at TIMESTAMP NULL,
  last_error_code VARCHAR(64) NULL,
  version INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_kpi_report_owner (company_id, created_by_user_id, id),
  KEY idx_kpi_report_due (status, next_run_at),
  CONSTRAINT fk_kpi_report_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_kpi_report_user FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_kpi_report_unit FOREIGN KEY (unit_id) REFERENCES units(id),
  CONSTRAINT fk_kpi_report_business FOREIGN KEY (business_id) REFERENCES businesses(id),
  CONSTRAINT chk_kpi_report_type CHECK (report_type IN ('EXECUTIVE', 'ACCOUNTING')),
  CONSTRAINT chk_kpi_report_cadence CHECK (cadence IN ('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY')),
  CONSTRAINT chk_kpi_report_status CHECK (status IN ('draft', 'ready', 'paused'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE kpi_automated_report_runs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  rule_id BIGINT NOT NULL,
  requested_by_user_id BIGINT NOT NULL,
  run_key VARCHAR(140) NOT NULL,
  report_type VARCHAR(24) NOT NULL,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  currency_code CHAR(3) NOT NULL,
  snapshot_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_kpi_report_run_key (company_id, rule_id, run_key),
  KEY idx_kpi_report_run_history (company_id, rule_id, id),
  CONSTRAINT fk_kpi_report_run_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_kpi_report_run_rule FOREIGN KEY (rule_id) REFERENCES kpi_automated_report_rules(id),
  CONSTRAINT fk_kpi_report_run_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
