CREATE TABLE company_payment_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_reference CHAR(32) NOT NULL,
    company_id BIGINT NOT NULL,
    kind VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    window_version INT NOT NULL DEFAULT 1,
    started_at TIMESTAMP(6) NOT NULL,
    deadline_at TIMESTAMP(6) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    payer_name VARCHAR(200) NOT NULL,
    payer_email VARCHAR(320) NOT NULL,
    amount_cents BIGINT NOT NULL,
    currency CHAR(3) NOT NULL,
    billing_interval VARCHAR(16) NULL,
    catalog_version_id BIGINT NULL,
    stripe_mode VARCHAR(8) NOT NULL,
    source_customer_id VARCHAR(255) NULL,
    source_subscription_id VARCHAR(255) NULL,
    quote_token CHAR(64) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    paid_at TIMESTAMP(6) NULL,
    next_check_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    active_company_id BIGINT GENERATED ALWAYS AS (CASE WHEN status = 'OPEN' THEN company_id ELSE NULL END) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uq_payment_request_reference (public_reference),
    UNIQUE KEY uq_payment_request_active_company (active_company_id),
    KEY idx_payment_request_due (status, deadline_at, id),
    KEY idx_payment_request_reconcile (status, next_check_at, id),
    KEY idx_payment_request_company (company_id, id),
    CONSTRAINT fk_payment_request_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_payment_request_catalog FOREIGN KEY (catalog_version_id) REFERENCES billing_catalog_versions(id),
    CONSTRAINT fk_payment_request_actor FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_payment_request_amount CHECK (amount_cents > 0),
    CONSTRAINT chk_payment_request_window CHECK (deadline_at > started_at AND window_version > 0),
    CONSTRAINT chk_payment_request_status CHECK (status IN ('OPEN', 'PAID')),
    CONSTRAINT chk_payment_request_kind CHECK (kind IN ('INVOICE', 'ACTIVATION'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE company_payment_request_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    window_version INT NOT NULL,
    actor_user_id BIGINT NULL,
    reason VARCHAR(1000) NOT NULL,
    deadline_at TIMESTAMP(6) NOT NULL,
    event_key CHAR(64) NOT NULL,
    request_fingerprint CHAR(64) NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_payment_request_event_key (event_key),
    KEY idx_payment_request_event_company (company_id, request_id, id),
    CONSTRAINT fk_payment_request_event_request FOREIGN KEY (request_id) REFERENCES company_payment_requests(id),
    CONSTRAINT fk_payment_request_event_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_payment_request_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE company_payment_request_deliveries (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    window_version INT NOT NULL,
    slot_index INT NOT NULL,
    channel VARCHAR(16) NOT NULL,
    recipient_user_id BIGINT NULL,
    recipient_user_company_id BIGINT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    scheduled_at TIMESTAMP(6) NOT NULL,
    next_attempt_at TIMESTAMP(6) NOT NULL,
    lease_token CHAR(32) NULL,
    lease_until TIMESTAMP(6) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    provider_reference VARCHAR(255) NULL,
    last_error VARCHAR(120) NULL,
    delivered_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_payment_request_delivery_slot (request_id, window_version, slot_index, channel),
    KEY idx_payment_request_delivery_due (status, next_attempt_at, lease_until),
    KEY idx_payment_request_delivery_company (company_id, request_id),
    CONSTRAINT fk_payment_request_delivery_request FOREIGN KEY (request_id) REFERENCES company_payment_requests(id),
    CONSTRAINT fk_payment_request_delivery_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_payment_request_delivery_user FOREIGN KEY (recipient_user_id) REFERENCES users(id),
    CONSTRAINT fk_payment_request_delivery_membership FOREIGN KEY (recipient_user_company_id) REFERENCES user_companies(id),
    CONSTRAINT chk_payment_request_delivery_slot CHECK (slot_index BETWEEN 0 AND 6),
    CONSTRAINT chk_payment_request_delivery_channel CHECK (channel IN ('EMAIL', 'IN_APP'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
