CREATE TABLE messaging_attachments (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
    company_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    sender_scope VARCHAR(20) NOT NULL,
    request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(60) NOT NULL,
    size_bytes BIGINT NOT NULL,
    upload_key VARCHAR(512) NOT NULL,
    stored_key VARCHAR(512) NULL,
    message_id BIGINT NULL,
    expires_at DATETIME(6) NOT NULL,
    staging_cleaned_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_messaging_attachment_request (conversation_id,sender_user_id,sender_scope,request_key),
    KEY ix_messaging_attachment_message (company_id,conversation_id,message_id),
    KEY ix_messaging_attachment_rate (sender_user_id,created_at),
    KEY ix_messaging_attachment_cleanup (staging_cleaned_at,expires_at),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (conversation_id) REFERENCES messaging_conversations(id),
    FOREIGN KEY (sender_user_id) REFERENCES users(id),
    FOREIGN KEY (message_id) REFERENCES messaging_messages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
