-- Reversible intake only. Business attachments remain in their existing owner tables.
CREATE TABLE ai_staged_files (
    id CHAR(36) NOT NULL PRIMARY KEY,
    access_token_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_company_id BIGINT NOT NULL,
    purpose VARCHAR(48) NOT NULL,
    target_id BIGINT NOT NULL,
    document_type VARCHAR(48) NULL,
    original_filename VARCHAR(180) NOT NULL,
    mime_type VARCHAR(80) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    bucket_name VARCHAR(120) NOT NULL,
    idempotency_key_hash CHAR(64) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'UPLOADING',
    attachment_id BIGINT NULL,
    expires_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    attached_at DATETIME(6) NULL,
    UNIQUE KEY uq_ai_file_intake (access_token_id, idempotency_key_hash),
    KEY ix_ai_file_cleanup (state, expires_at),
    KEY ix_ai_file_tenant (company_id, user_company_id, id),
    CONSTRAINT chk_ai_file_size CHECK (size_bytes > 0 AND size_bytes <= 10485760),
    CONSTRAINT chk_ai_file_state CHECK (state IN ('UPLOADING', 'STAGED', 'ATTACHED', 'EXPIRED'))
);
