CREATE TABLE IF NOT EXISTS `user_permission_requests` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `request_number` varchar(32) DEFAULT NULL,
  `user_company_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `user_name_snapshot` varchar(160) NOT NULL,
  `user_position_snapshot` varchar(160) DEFAULT NULL,
  `user_department_snapshot` varchar(160) DEFAULT NULL,
  `permission_type` varchar(32) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `requested_days` decimal(5,1) NOT NULL,
  `is_half_day` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `reason` text NOT NULL,
  `review_notes` text,
  `reviewed_by_user_id` bigint DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_by_user_id` bigint NOT NULL,
  `updated_by_user_id` bigint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_permission_requests_company_number` (`company_id`,`request_number`),
  KEY `idx_user_permission_requests_company_user` (`company_id`,`user_company_id`),
  KEY `idx_user_permission_requests_company_status` (`company_id`,`status`),
  KEY `idx_user_permission_requests_company_start_date` (`company_id`,`start_date`),
  KEY `idx_user_permission_requests_company_created_at` (`company_id`,`created_at`),
  KEY `fk_user_permission_requests_user` (`user_id`),
  KEY `fk_user_permission_requests_reviewed_by` (`reviewed_by_user_id`),
  KEY `fk_user_permission_requests_created_by` (`created_by_user_id`),
  KEY `fk_user_permission_requests_updated_by` (`updated_by_user_id`),
  CONSTRAINT `fk_user_permission_requests_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_permission_requests_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_user_permission_requests_reviewed_by` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_user_permission_requests_updated_by` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_user_permission_requests_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_permission_requests_user_company` FOREIGN KEY (`user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `user_permission_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `permission_request_id` bigint NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `mime_type` varchar(120) NOT NULL,
  `size_bytes` bigint NOT NULL DEFAULT '0',
  `object_key` varchar(255) NOT NULL,
  `uploaded_by_user_id` bigint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_permission_attachments_object_key` (`company_id`,`object_key`),
  KEY `idx_user_permission_attachments_request` (`permission_request_id`),
  KEY `idx_user_permission_attachments_company_deleted` (`company_id`,`deleted_at`),
  KEY `fk_user_permission_attachments_uploaded_by` (`uploaded_by_user_id`),
  CONSTRAINT `fk_user_permission_attachments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_permission_attachments_request` FOREIGN KEY (`permission_request_id`) REFERENCES `user_permission_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_permission_attachments_uploaded_by` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
