CREATE TABLE IF NOT EXISTS `sales_contacts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `unit_id` bigint DEFAULT NULL,
  `business_id` bigint DEFAULT NULL,
  `contact_code` varchar(40) NOT NULL,
  `company_name` varchar(220) NOT NULL,
  `contact_person` varchar(180) DEFAULT NULL,
  `phone` varchar(80) DEFAULT NULL,
  `email` varchar(220) DEFAULT NULL,
  `source` varchar(80) DEFAULT NULL,
  `status` varchar(60) NOT NULL DEFAULT 'active',
  `owner_user_company_id` bigint DEFAULT NULL,
  `owner_name` varchar(180) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `tags_json` json DEFAULT NULL,
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_contacts_company_code` (`company_id`, `contact_code`),
  KEY `idx_sales_contacts_company_status` (`company_id`, `status`),
  KEY `idx_sales_contacts_company_owner` (`company_id`, `owner_user_company_id`),
  KEY `idx_sales_contacts_company_unit` (`company_id`, `unit_id`),
  KEY `idx_sales_contacts_company_business` (`company_id`, `business_id`),
  CONSTRAINT `fk_sales_contacts_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_contacts_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contacts_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contacts_owner_user_company` FOREIGN KEY (`owner_user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contacts_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contacts_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_opportunities` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `contact_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `business_id` bigint DEFAULT NULL,
  `opportunity_code` varchar(40) NOT NULL,
  `opportunity_name` varchar(220) NOT NULL,
  `company_name` varchar(220) DEFAULT NULL,
  `contact_person` varchar(180) DEFAULT NULL,
  `phone` varchar(80) DEFAULT NULL,
  `email` varchar(220) DEFAULT NULL,
  `source` varchar(80) DEFAULT NULL,
  `stage` varchar(80) NOT NULL DEFAULT 'new',
  `temperature` varchar(40) DEFAULT NULL,
  `status` varchar(80) NOT NULL DEFAULT 'active',
  `owner_user_company_id` bigint DEFAULT NULL,
  `owner_name` varchar(180) DEFAULT NULL,
  `estimated_value` decimal(15,2) DEFAULT NULL,
  `currency` varchar(10) NOT NULL DEFAULT 'MXN',
  `probability_percent` int DEFAULT NULL,
  `expected_close_date` date DEFAULT NULL,
  `next_action` varchar(120) DEFAULT NULL,
  `next_action_at` datetime DEFAULT NULL,
  `last_contact_at` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_opportunities_company_code` (`company_id`, `opportunity_code`),
  KEY `idx_sales_opportunities_company_stage` (`company_id`, `stage`),
  KEY `idx_sales_opportunities_company_status` (`company_id`, `status`),
  KEY `idx_sales_opportunities_company_owner` (`company_id`, `owner_user_company_id`),
  KEY `idx_sales_opportunities_company_contact` (`company_id`, `contact_id`),
  KEY `idx_sales_opportunities_expected_close` (`company_id`, `expected_close_date`),
  KEY `idx_sales_opportunities_next_action` (`company_id`, `next_action_at`),
  CONSTRAINT `fk_sales_opportunities_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_opportunities_contact` FOREIGN KEY (`contact_id`) REFERENCES `sales_contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_opportunities_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_opportunities_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_opportunities_owner_user_company` FOREIGN KEY (`owner_user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_opportunities_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_opportunities_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_products` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `product_code` varchar(40) NOT NULL,
  `sku` varchar(80) DEFAULT NULL,
  `name` varchar(220) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `type` varchar(80) NOT NULL DEFAULT 'product',
  `price` decimal(15,2) DEFAULT NULL,
  `cost` decimal(15,2) DEFAULT NULL,
  `currency` varchar(10) NOT NULL DEFAULT 'MXN',
  `tax_category` varchar(80) DEFAULT NULL,
  `status` varchar(60) NOT NULL DEFAULT 'active',
  `visibility` varchar(80) NOT NULL DEFAULT 'commercial',
  `inventory_ready` tinyint(1) NOT NULL DEFAULT 0,
  `pos_ready` tinyint(1) NOT NULL DEFAULT 0,
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_products_company_code` (`company_id`, `product_code`),
  KEY `idx_sales_products_company_sku` (`company_id`, `sku`),
  KEY `idx_sales_products_company_category` (`company_id`, `category`),
  KEY `idx_sales_products_company_status` (`company_id`, `status`),
  CONSTRAINT `fk_sales_products_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_products_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_products_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_quotes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `contact_id` bigint DEFAULT NULL,
  `opportunity_id` bigint DEFAULT NULL,
  `quote_number` varchar(40) NOT NULL,
  `client_name` varchar(220) NOT NULL,
  `contact_person` varchar(180) DEFAULT NULL,
  `status` varchar(80) NOT NULL DEFAULT 'draft',
  `amount` decimal(15,2) DEFAULT NULL,
  `currency` varchar(10) NOT NULL DEFAULT 'MXN',
  `created_date` date DEFAULT NULL,
  `expiration_date` date DEFAULT NULL,
  `assigned_seller_user_company_id` bigint DEFAULT NULL,
  `assigned_seller_name` varchar(180) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `terms` text DEFAULT NULL,
  `connection_status` varchar(80) NOT NULL DEFAULT 'commercial_quote',
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_quotes_company_number` (`company_id`, `quote_number`),
  KEY `idx_sales_quotes_company_status` (`company_id`, `status`),
  KEY `idx_sales_quotes_company_contact` (`company_id`, `contact_id`),
  KEY `idx_sales_quotes_company_opportunity` (`company_id`, `opportunity_id`),
  KEY `idx_sales_quotes_expiration` (`company_id`, `expiration_date`),
  CONSTRAINT `fk_sales_quotes_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_quotes_contact` FOREIGN KEY (`contact_id`) REFERENCES `sales_contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_quotes_opportunity` FOREIGN KEY (`opportunity_id`) REFERENCES `sales_opportunities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_quotes_seller_user_company` FOREIGN KEY (`assigned_seller_user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_quotes_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_quotes_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_quote_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `quote_id` bigint NOT NULL,
  `product_id` bigint DEFAULT NULL,
  `section` varchar(160) DEFAULT NULL,
  `product_name` varchar(220) NOT NULL,
  `sku` varchar(80) DEFAULT NULL,
  `quantity` decimal(12,2) NOT NULL DEFAULT 1.00,
  `unit_price` decimal(15,2) NOT NULL DEFAULT 0.00,
  `discount_percent` decimal(6,2) NOT NULL DEFAULT 0.00,
  `tax_percent` decimal(6,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `sort_order` int NOT NULL DEFAULT 0,
  `metadata_json` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sales_quote_items_quote` (`company_id`, `quote_id`, `sort_order`),
  KEY `idx_sales_quote_items_product` (`company_id`, `product_id`),
  CONSTRAINT `fk_sales_quote_items_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_quote_items_quote` FOREIGN KEY (`quote_id`) REFERENCES `sales_quotes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_quote_items_product` FOREIGN KEY (`product_id`) REFERENCES `sales_products` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_post_sale_cases` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `contact_id` bigint DEFAULT NULL,
  `opportunity_id` bigint DEFAULT NULL,
  `quote_id` bigint DEFAULT NULL,
  `case_number` varchar(40) NOT NULL,
  `client_name` varchar(220) NOT NULL,
  `relation_type` varchar(80) NOT NULL DEFAULT 'one_time_customer',
  `post_sale_type` varchar(80) NOT NULL DEFAULT 'standard',
  `status` varchar(80) NOT NULL DEFAULT 'active',
  `owner_user_company_id` bigint DEFAULT NULL,
  `owner_name` varchar(180) DEFAULT NULL,
  `last_purchase_date` date DEFAULT NULL,
  `next_follow_up_date` date DEFAULT NULL,
  `renewal_date` date DEFAULT NULL,
  `lifetime_value` decimal(15,2) DEFAULT NULL,
  `currency` varchar(10) NOT NULL DEFAULT 'MXN',
  `risk_level` varchar(40) DEFAULT NULL,
  `lost_reason` varchar(80) DEFAULT NULL,
  `next_action` varchar(160) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `history_json` json DEFAULT NULL,
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_post_sale_company_case` (`company_id`, `case_number`),
  KEY `idx_sales_post_sale_company_status` (`company_id`, `status`),
  KEY `idx_sales_post_sale_company_relation` (`company_id`, `relation_type`),
  KEY `idx_sales_post_sale_follow_up` (`company_id`, `next_follow_up_date`),
  KEY `idx_sales_post_sale_renewal` (`company_id`, `renewal_date`),
  CONSTRAINT `fk_sales_post_sale_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_post_sale_contact` FOREIGN KEY (`contact_id`) REFERENCES `sales_contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_post_sale_opportunity` FOREIGN KEY (`opportunity_id`) REFERENCES `sales_opportunities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_post_sale_quote` FOREIGN KEY (`quote_id`) REFERENCES `sales_quotes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_post_sale_owner_user_company` FOREIGN KEY (`owner_user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_post_sale_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_post_sale_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_contracts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `contact_id` bigint DEFAULT NULL,
  `opportunity_id` bigint DEFAULT NULL,
  `quote_id` bigint DEFAULT NULL,
  `post_sale_case_id` bigint DEFAULT NULL,
  `contract_number` varchar(40) NOT NULL,
  `title` varchar(220) NOT NULL,
  `client_name` varchar(220) DEFAULT NULL,
  `contact_person` varchar(180) DEFAULT NULL,
  `contract_type` varchar(100) NOT NULL DEFAULT 'custom_contract',
  `status` varchar(80) NOT NULL DEFAULT 'draft',
  `signature_status` varchar(80) NOT NULL DEFAULT 'not_requested',
  `source` varchar(80) NOT NULL DEFAULT 'uploaded',
  `country` varchar(40) DEFAULT NULL,
  `owner_user_company_id` bigint DEFAULT NULL,
  `owner_name` varchar(180) DEFAULT NULL,
  `expiration_date` date DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `dynamic_fields_json` json DEFAULT NULL,
  `signature_request_json` json DEFAULT NULL,
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_contracts_company_number` (`company_id`, `contract_number`),
  KEY `idx_sales_contracts_company_status` (`company_id`, `status`),
  KEY `idx_sales_contracts_signature_status` (`company_id`, `signature_status`),
  KEY `idx_sales_contracts_expiration` (`company_id`, `expiration_date`),
  CONSTRAINT `fk_sales_contracts_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_contracts_contact` FOREIGN KEY (`contact_id`) REFERENCES `sales_contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contracts_opportunity` FOREIGN KEY (`opportunity_id`) REFERENCES `sales_opportunities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contracts_quote` FOREIGN KEY (`quote_id`) REFERENCES `sales_quotes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contracts_post_sale` FOREIGN KEY (`post_sale_case_id`) REFERENCES `sales_post_sale_cases` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contracts_owner_user_company` FOREIGN KEY (`owner_user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contracts_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_contracts_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `entity_type` varchar(80) NOT NULL,
  `entity_id` bigint NOT NULL,
  `file_name` varchar(260) NOT NULL,
  `file_kind` varchar(80) DEFAULT NULL,
  `file_status` varchar(80) DEFAULT NULL,
  `source` varchar(80) DEFAULT NULL,
  `object_key` varchar(512) DEFAULT NULL,
  `url` varchar(1024) DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sales_files_entity` (`company_id`, `entity_type`, `entity_id`),
  KEY `idx_sales_files_created_by` (`company_id`, `created_by_user_id`),
  CONSTRAINT `fk_sales_files_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_files_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
