CREATE TABLE IF NOT EXISTS finance_budgets (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  status VARCHAR(40) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_budgets_company_name_period (company_id, name, period_start, period_end),
  KEY idx_finance_budgets_company (company_id),
  KEY idx_finance_budgets_company_unit (company_id, unit_id),
  KEY idx_finance_budgets_company_business (company_id, business_id),
  KEY idx_finance_budgets_company_status (company_id, status),
  KEY idx_finance_budgets_company_period (company_id, period_start, period_end),
  KEY idx_finance_budgets_created_by (created_by_user_id),
  KEY idx_finance_budgets_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_budgets_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_budgets_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_budgets_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_budgets_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_budgets_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_budgets_status CHECK (status IN ('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_budget_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  budget_id BIGINT NOT NULL,
  name VARCHAR(160) NOT NULL,
  category_key VARCHAR(80) NULL,
  planned_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  committed_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  actual_expense_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  petty_cash_issued_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  petty_cash_settled_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  available_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  health_status VARCHAR(40) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_budget_lines_budget_name (budget_id, name),
  KEY idx_finance_budget_lines_company (company_id),
  KEY idx_finance_budget_lines_company_unit (company_id, unit_id),
  KEY idx_finance_budget_lines_company_business (company_id, business_id),
  KEY idx_finance_budget_lines_budget (budget_id),
  KEY idx_finance_budget_lines_health (company_id, health_status),
  KEY idx_finance_budget_lines_created_by (created_by_user_id),
  KEY idx_finance_budget_lines_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_budget_lines_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_budget_lines_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_budget_lines_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_budget_lines_budget FOREIGN KEY (budget_id) REFERENCES finance_budgets(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_budget_lines_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_budget_lines_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_budget_lines_health CHECK (health_status IN ('ON_TRACK', 'WARNING', 'EXCEEDED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_providers (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  name VARCHAR(180) NOT NULL,
  legal_name VARCHAR(220) NULL,
  tax_id VARCHAR(80) NULL,
  email VARCHAR(180) NULL,
  phone VARCHAR(60) NULL,
  status VARCHAR(40) NOT NULL,
  payment_terms_days INT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_providers_company_tax_id (company_id, tax_id),
  KEY idx_finance_providers_company (company_id),
  KEY idx_finance_providers_company_unit (company_id, unit_id),
  KEY idx_finance_providers_company_business (company_id, business_id),
  KEY idx_finance_providers_company_status (company_id, status),
  KEY idx_finance_providers_name (company_id, name),
  KEY idx_finance_providers_created_by (created_by_user_id),
  KEY idx_finance_providers_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_providers_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_providers_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_providers_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_providers_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_providers_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_providers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_payment_accounts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  name VARCHAR(160) NOT NULL,
  type VARCHAR(40) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  opening_balance DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  current_balance DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  status VARCHAR(40) NOT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_payment_accounts_company_name (company_id, name),
  KEY idx_finance_payment_accounts_company (company_id),
  KEY idx_finance_payment_accounts_company_unit (company_id, unit_id),
  KEY idx_finance_payment_accounts_company_business (company_id, business_id),
  KEY idx_finance_payment_accounts_company_type (company_id, type),
  KEY idx_finance_payment_accounts_company_status (company_id, status),
  KEY idx_finance_payment_accounts_created_by (created_by_user_id),
  KEY idx_finance_payment_accounts_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_payment_accounts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_payment_accounts_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payment_accounts_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payment_accounts_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_payment_accounts_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_payment_accounts_type CHECK (type IN ('CASH', 'BANK', 'CREDIT_CARD', 'PETTY_CASH')),
  CONSTRAINT chk_finance_payment_accounts_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_accounting_accounts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  code VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  group_key VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_accounting_accounts_company_code (company_id, code),
  KEY idx_finance_accounting_accounts_company (company_id),
  KEY idx_finance_accounting_accounts_company_unit (company_id, unit_id),
  KEY idx_finance_accounting_accounts_company_business (company_id, business_id),
  KEY idx_finance_accounting_accounts_group (company_id, group_key),
  KEY idx_finance_accounting_accounts_status (company_id, status),
  KEY idx_finance_accounting_accounts_created_by (created_by_user_id),
  KEY idx_finance_accounting_accounts_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_accounting_accounts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_accounting_accounts_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_accounting_accounts_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_accounting_accounts_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_accounting_accounts_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_accounting_accounts_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_expenses (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  folio VARCHAR(80) NOT NULL,
  provider_id BIGINT NULL,
  budget_line_id BIGINT NULL,
  accounting_account_id BIGINT NULL,
  payment_account_id BIGINT NULL,
  purchase_order_id BIGINT NULL,
  concept VARCHAR(220) NOT NULL,
  description TEXT NULL,
  expense_type VARCHAR(40) NOT NULL,
  subtotal_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  paid_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  balance_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL,
  expense_date DATE NOT NULL,
  due_date DATE NULL,
  payment_date DATE NULL,
  close_date DATE NULL,
  requested_by_user_id BIGINT NULL,
  approved_by_user_id BIGINT NULL,
  performed_by_user_id BIGINT NULL,
  status VARCHAR(40) NOT NULL,
  payment_status VARCHAR(40) NOT NULL,
  audit_status VARCHAR(40) NULL,
  attachment_count INT NOT NULL DEFAULT 0,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_expenses_company_folio (company_id, folio),
  KEY idx_finance_expenses_company (company_id),
  KEY idx_finance_expenses_company_unit (company_id, unit_id),
  KEY idx_finance_expenses_company_business (company_id, business_id),
  KEY idx_finance_expenses_status (company_id, status),
  KEY idx_finance_expenses_payment_status (company_id, payment_status),
  KEY idx_finance_expenses_expense_date (company_id, expense_date),
  KEY idx_finance_expenses_due_date (company_id, due_date),
  KEY idx_finance_expenses_payment_date (company_id, payment_date),
  KEY idx_finance_expenses_provider (provider_id),
  KEY idx_finance_expenses_budget_line (budget_line_id),
  KEY idx_finance_expenses_accounting_account (accounting_account_id),
  KEY idx_finance_expenses_payment_account (payment_account_id),
  KEY idx_finance_expenses_purchase_order (purchase_order_id),
  KEY idx_finance_expenses_requested_by (requested_by_user_id),
  KEY idx_finance_expenses_approved_by (approved_by_user_id),
  KEY idx_finance_expenses_performed_by (performed_by_user_id),
  KEY idx_finance_expenses_created_by (created_by_user_id),
  KEY idx_finance_expenses_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_expenses_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_expenses_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_budget_line FOREIGN KEY (budget_line_id) REFERENCES finance_budget_lines(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_accounting_account FOREIGN KEY (accounting_account_id) REFERENCES finance_accounting_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_payment_account FOREIGN KEY (payment_account_id) REFERENCES finance_payment_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_performed_by FOREIGN KEY (performed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_expenses_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_expenses_type CHECK (expense_type IN ('FIXED', 'VARIABLE')),
  CONSTRAINT chk_finance_expenses_status CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ORDERED', 'PARTIALLY_PAID', 'PAID', 'CLOSED', 'CANCELLED', 'REJECTED')),
  CONSTRAINT chk_finance_expenses_payment_status CHECK (payment_status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE')),
  CONSTRAINT chk_finance_expenses_attachment_count CHECK (attachment_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
