CREATE TABLE IF NOT EXISTS finance_petty_cash_funds (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  budget_id BIGINT NULL,
  budget_line_id BIGINT NULL,
  payment_account_id BIGINT NULL,
  funding_source_payment_account_id BIGINT NULL,
  responsible_user_id BIGINT NULL,
  name VARCHAR(180) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  limit_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  current_balance_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  cut_off_day INT NOT NULL DEFAULT 30,
  funding_source_name VARCHAR(180) NULL,
  funding_methods_json JSON NULL,
  spending_methods_json JSON NULL,
  kiosk_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  kiosk_uses_universal_pin BOOLEAN NOT NULL DEFAULT TRUE,
  kiosk_access_url VARCHAR(255) NULL,
  status VARCHAR(40) NOT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_petty_cash_funds_company_name (company_id, name),
  KEY idx_finance_petty_cash_funds_company (company_id),
  KEY idx_finance_petty_cash_funds_company_unit (company_id, unit_id),
  KEY idx_finance_petty_cash_funds_company_business (company_id, business_id),
  KEY idx_finance_petty_cash_funds_status (company_id, status),
  KEY idx_finance_petty_cash_funds_budget (budget_id),
  KEY idx_finance_petty_cash_funds_budget_line (budget_line_id),
  KEY idx_finance_petty_cash_funds_payment_account (payment_account_id),
  KEY idx_finance_petty_cash_funds_funding_source (funding_source_payment_account_id),
  KEY idx_finance_petty_cash_funds_responsible (responsible_user_id),
  KEY idx_finance_petty_cash_funds_created_by (created_by_user_id),
  KEY idx_finance_petty_cash_funds_updated_by (updated_by_user_id),
  CONSTRAINT fk_finance_petty_cash_funds_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_funds_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_budget FOREIGN KEY (budget_id) REFERENCES finance_budgets(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_budget_line FOREIGN KEY (budget_line_id) REFERENCES finance_budget_lines(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_payment_account FOREIGN KEY (payment_account_id) REFERENCES finance_payment_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_funding_source FOREIGN KEY (funding_source_payment_account_id) REFERENCES finance_payment_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_responsible FOREIGN KEY (responsible_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_funds_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_petty_cash_funds_status CHECK (status IN ('OPEN', 'LOW_BALANCE', 'NEEDS_RECONCILIATION', 'CLOSED')),
  CONSTRAINT chk_finance_petty_cash_funds_cut_off_day CHECK (cut_off_day BETWEEN 1 AND 31),
  CONSTRAINT chk_finance_petty_cash_funds_limit CHECK (limit_amount >= 0),
  CONSTRAINT chk_finance_petty_cash_funds_balance CHECK (current_balance_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_petty_cash_statements (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  petty_cash_fund_id BIGINT NOT NULL,
  folio VARCHAR(80) NOT NULL,
  period_key VARCHAR(20) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  cut_off_date DATE NOT NULL,
  opening_balance_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  assigned_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  additional_deposit_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  declared_closing_balance_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  estimated_usage_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  verified_expense_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  returned_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  shortage_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  carry_forward_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL,
  status VARCHAR(40) NOT NULL,
  responsible_user_id BIGINT NULL,
  reviewed_by_user_id BIGINT NULL,
  attachment_count INT NOT NULL DEFAULT 0,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_petty_cash_statements_fund_period (petty_cash_fund_id, period_key),
  UNIQUE KEY uq_finance_petty_cash_statements_company_folio (company_id, folio),
  KEY idx_finance_petty_cash_statements_company (company_id),
  KEY idx_finance_petty_cash_statements_status (company_id, status),
  KEY idx_finance_petty_cash_statements_period (company_id, period_start, period_end),
  KEY idx_finance_petty_cash_statements_responsible (responsible_user_id),
  KEY idx_finance_petty_cash_statements_reviewed_by (reviewed_by_user_id),
  CONSTRAINT fk_finance_petty_cash_statements_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_statements_fund FOREIGN KEY (petty_cash_fund_id) REFERENCES finance_petty_cash_funds(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_statements_responsible FOREIGN KEY (responsible_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_statements_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_statements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_statements_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_petty_cash_statements_status CHECK (status IN ('OPEN', 'CUT_PENDING', 'PARTIALLY_SETTLED', 'SETTLED', 'SHORTAGE', 'FORGIVEN_SHORTAGE', 'CHARGED_TO_EMPLOYEE', 'TRANSFERRED_TO_NEXT_CUT', 'CLOSED')),
  CONSTRAINT chk_finance_petty_cash_statements_attachment_count CHECK (attachment_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_petty_cash_movements (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  petty_cash_fund_id BIGINT NOT NULL,
  petty_cash_statement_id BIGINT NULL,
  from_payment_account_id BIGINT NULL,
  to_payment_account_id BIGINT NULL,
  type VARCHAR(40) NOT NULL,
  amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL,
  movement_date DATE NOT NULL,
  reference VARCHAR(220) NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_finance_petty_cash_movements_company (company_id),
  KEY idx_finance_petty_cash_movements_fund (petty_cash_fund_id),
  KEY idx_finance_petty_cash_movements_statement (petty_cash_statement_id),
  KEY idx_finance_petty_cash_movements_date (company_id, movement_date),
  KEY idx_finance_petty_cash_movements_type (company_id, type),
  KEY idx_finance_petty_cash_movements_from_account (from_payment_account_id),
  KEY idx_finance_petty_cash_movements_to_account (to_payment_account_id),
  CONSTRAINT fk_finance_petty_cash_movements_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_movements_fund FOREIGN KEY (petty_cash_fund_id) REFERENCES finance_petty_cash_funds(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_movements_statement FOREIGN KEY (petty_cash_statement_id) REFERENCES finance_petty_cash_statements(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_movements_from_account FOREIGN KEY (from_payment_account_id) REFERENCES finance_payment_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_movements_to_account FOREIGN KEY (to_payment_account_id) REFERENCES finance_payment_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_movements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_movements_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_petty_cash_movements_type CHECK (type IN ('INITIAL_FUNDING', 'ADDITIONAL_DEPOSIT', 'RETURN_TO_SOURCE', 'CARRY_FORWARD', 'SHORTAGE_ADJUSTMENT', 'FORGIVEN_SHORTAGE', 'EMPLOYEE_CHARGE')),
  CONSTRAINT chk_finance_petty_cash_movements_amount CHECK (amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_petty_cash_settlement_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  petty_cash_fund_id BIGINT NOT NULL,
  petty_cash_statement_id BIGINT NOT NULL,
  expense_id BIGINT NULL,
  provider_id BIGINT NULL,
  accounting_account_id BIGINT NULL,
  description VARCHAR(220) NOT NULL,
  receipt_reference VARCHAR(160) NULL,
  subtotal_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL,
  expense_date DATE NOT NULL,
  attachment_count INT NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_finance_petty_cash_settlement_lines_company (company_id),
  KEY idx_finance_petty_cash_settlement_lines_fund (petty_cash_fund_id),
  KEY idx_finance_petty_cash_settlement_lines_statement (petty_cash_statement_id),
  KEY idx_finance_petty_cash_settlement_lines_provider (provider_id),
  KEY idx_finance_petty_cash_settlement_lines_accounting (accounting_account_id),
  KEY idx_finance_petty_cash_settlement_lines_expense (expense_id),
  KEY idx_finance_petty_cash_settlement_lines_status (company_id, status),
  CONSTRAINT fk_finance_petty_cash_settlement_lines_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_fund FOREIGN KEY (petty_cash_fund_id) REFERENCES finance_petty_cash_funds(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_statement FOREIGN KEY (petty_cash_statement_id) REFERENCES finance_petty_cash_statements(id) ON DELETE CASCADE,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_expense FOREIGN KEY (expense_id) REFERENCES finance_expenses(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_accounting FOREIGN KEY (accounting_account_id) REFERENCES finance_accounting_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_petty_cash_settlement_lines_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_petty_cash_settlement_lines_status CHECK (status IN ('DRAFT', 'RECEIPT_ATTACHED', 'VALIDATED', 'EXPENSE_CREATED', 'REJECTED')),
  CONSTRAINT chk_finance_petty_cash_settlement_lines_amounts CHECK (subtotal_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0),
  CONSTRAINT chk_finance_petty_cash_settlement_lines_attachment_count CHECK (attachment_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
