CREATE TABLE IF NOT EXISTS `sales_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `contact_id` bigint DEFAULT NULL,
  `opportunity_id` bigint DEFAULT NULL,
  `quote_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `business_id` bigint DEFAULT NULL,
  `seller_user_company_id` bigint DEFAULT NULL,
  `sale_number` varchar(40) NOT NULL,
  `quote_reference` varchar(80) DEFAULT NULL,
  `sale_document_reference` varchar(80) DEFAULT NULL,
  `customer_name` varchar(220) NOT NULL,
  `seller_name` varchar(180) DEFAULT NULL,
  `sale_date` date DEFAULT NULL,
  `total_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `subtotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `discount_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `tax_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `margin_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `currency` varchar(10) NOT NULL DEFAULT 'MXN',
  `payment_method` varchar(80) DEFAULT NULL,
  `payment_reference` varchar(120) DEFAULT NULL,
  `payment_evidence_status` varchar(80) NOT NULL DEFAULT 'missing',
  `commercial_status` varchar(80) NOT NULL DEFAULT 'pending_validation',
  `finance_status` varchar(80) NOT NULL DEFAULT 'pending',
  `inventory_status` varchar(80) NOT NULL DEFAULT 'pending',
  `delivery_status` varchar(80) NOT NULL DEFAULT 'pending',
  `commission_status` varchar(80) NOT NULL DEFAULT 'pending',
  `inventory_movement_status` varchar(80) NOT NULL DEFAULT 'not_generated',
  `inventory_movement_reference` varchar(120) DEFAULT NULL,
  `commission_rate` decimal(6,2) NOT NULL DEFAULT 0.00,
  `commission_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `commission_notes` text DEFAULT NULL,
  `sale_lines_json` json DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `custom_fields_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_records_company_number` (`company_id`, `sale_number`),
  KEY `idx_sales_records_company_date` (`company_id`, `sale_date`),
  KEY `idx_sales_records_company_contact` (`company_id`, `contact_id`),
  KEY `idx_sales_records_company_quote` (`company_id`, `quote_id`),
  KEY `idx_sales_records_company_unit` (`company_id`, `unit_id`),
  KEY `idx_sales_records_company_business` (`company_id`, `business_id`),
  KEY `idx_sales_records_finance_status` (`company_id`, `finance_status`),
  KEY `idx_sales_records_inventory_status` (`company_id`, `inventory_status`),
  CONSTRAINT `fk_sales_records_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_records_contact` FOREIGN KEY (`contact_id`) REFERENCES `sales_contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_opportunity` FOREIGN KEY (`opportunity_id`) REFERENCES `sales_opportunities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_quote` FOREIGN KEY (`quote_id`) REFERENCES `sales_quotes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_seller_user_company` FOREIGN KEY (`seller_user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_records_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
