CREATE TABLE IF NOT EXISTS `sales_inventory_warehouses` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `warehouse_code` varchar(40) NOT NULL,
  `name` varchar(180) NOT NULL,
  `type` varchar(80) NOT NULL DEFAULT 'businessWarehouse',
  `business_unit_id` varchar(80) DEFAULT NULL,
  `business_unit_name` varchar(180) DEFAULT NULL,
  `business_id` varchar(80) DEFAULT NULL,
  `business_name` varchar(180) DEFAULT NULL,
  `jurisdiction` varchar(180) DEFAULT NULL,
  `responsible_user_id` varchar(80) DEFAULT NULL,
  `responsible_name` varchar(180) DEFAULT NULL,
  `address_note` text DEFAULT NULL,
  `status` varchar(40) NOT NULL DEFAULT 'active',
  `last_movement_at` date DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_inventory_warehouses_company_code` (`company_id`, `warehouse_code`),
  KEY `idx_sales_inventory_warehouses_company_status` (`company_id`, `status`),
  KEY `idx_sales_inventory_warehouses_company_unit` (`company_id`, `business_unit_id`),
  KEY `idx_sales_inventory_warehouses_company_business` (`company_id`, `business_id`),
  CONSTRAINT `fk_sales_inventory_warehouses_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_inventory_warehouses_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_inventory_warehouses_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_inventory_balances` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `balance_code` varchar(40) NOT NULL,
  `product_id` bigint NOT NULL,
  `warehouse_id` bigint NOT NULL,
  `warehouse_name` varchar(180) NOT NULL,
  `available_quantity` decimal(15,2) NOT NULL DEFAULT 0.00,
  `reserved_quantity` decimal(15,2) NOT NULL DEFAULT 0.00,
  `minimum_quantity` decimal(15,2) NOT NULL DEFAULT 0.00,
  `unit_cost` decimal(15,2) NOT NULL DEFAULT 0.00,
  `uses_inventory` tinyint(1) NOT NULL DEFAULT 0,
  `business_unit_id` varchar(80) DEFAULT NULL,
  `business_unit_name` varchar(180) DEFAULT NULL,
  `business_id` varchar(80) DEFAULT NULL,
  `business_name` varchar(180) DEFAULT NULL,
  `last_movement_at` date DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_inventory_balances_product_warehouse` (`company_id`, `product_id`, `warehouse_id`),
  UNIQUE KEY `uk_sales_inventory_balances_company_code` (`company_id`, `balance_code`),
  KEY `idx_sales_inventory_balances_company_product` (`company_id`, `product_id`),
  KEY `idx_sales_inventory_balances_company_warehouse` (`company_id`, `warehouse_id`),
  CONSTRAINT `fk_sales_inventory_balances_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_inventory_balances_product` FOREIGN KEY (`product_id`) REFERENCES `sales_products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_inventory_balances_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `sales_inventory_warehouses` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_inventory_balances_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_inventory_balances_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sales_inventory_movements` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `movement_number` varchar(40) NOT NULL,
  `group_id` varchar(40) DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_name` varchar(220) NOT NULL,
  `product_sku` varchar(80) DEFAULT NULL,
  `product_image_url` text DEFAULT NULL,
  `product_image_alt` varchar(220) DEFAULT NULL,
  `variant_label` varchar(160) DEFAULT NULL,
  `movement_type` varchar(80) NOT NULL,
  `quantity` decimal(15,2) NOT NULL DEFAULT 0.00,
  `unit_cost` decimal(15,2) DEFAULT NULL,
  `from_warehouse_id` bigint DEFAULT NULL,
  `from_warehouse_name` varchar(180) DEFAULT NULL,
  `to_warehouse_id` bigint DEFAULT NULL,
  `to_warehouse_name` varchar(180) DEFAULT NULL,
  `supplier_name` varchar(180) DEFAULT NULL,
  `business_unit_id` varchar(80) DEFAULT NULL,
  `business_unit_name` varchar(180) DEFAULT NULL,
  `business_id` varchar(80) DEFAULT NULL,
  `business_name` varchar(180) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `reference` varchar(120) DEFAULT NULL,
  `responsible_name` varchar(180) DEFAULT NULL,
  `movement_date` date NOT NULL,
  `status` varchar(40) NOT NULL DEFAULT 'draft',
  `attachments_json` json DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_inventory_movements_company_number` (`company_id`, `movement_number`, `id`),
  KEY `idx_sales_inventory_movements_company_date` (`company_id`, `movement_date`),
  KEY `idx_sales_inventory_movements_company_product` (`company_id`, `product_id`),
  KEY `idx_sales_inventory_movements_company_status` (`company_id`, `status`),
  KEY `idx_sales_inventory_movements_from_warehouse` (`company_id`, `from_warehouse_id`),
  KEY `idx_sales_inventory_movements_to_warehouse` (`company_id`, `to_warehouse_id`),
  CONSTRAINT `fk_sales_inventory_movements_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_inventory_movements_product` FOREIGN KEY (`product_id`) REFERENCES `sales_products` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_inventory_movements_from_warehouse` FOREIGN KEY (`from_warehouse_id`) REFERENCES `sales_inventory_warehouses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_inventory_movements_to_warehouse` FOREIGN KEY (`to_warehouse_id`) REFERENCES `sales_inventory_warehouses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_inventory_movements_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_inventory_movements_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
