CREATE TABLE IF NOT EXISTS pos_cash_registers (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  status VARCHAR(32) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT NULL,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  active_code VARCHAR(64) GENERATED ALWAYS AS (
    CASE WHEN deleted_at IS NULL THEN code ELSE NULL END
  ) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_cash_registers_company_active_code (company_id, active_code),
  KEY idx_pos_cash_registers_company (company_id),
  KEY idx_pos_cash_registers_unit (unit_id),
  KEY idx_pos_cash_registers_business (business_id),
  KEY idx_pos_cash_registers_warehouse (warehouse_id),
  KEY idx_pos_cash_registers_status (company_id, status),
  KEY idx_pos_cash_registers_deleted (deleted_at),
  CONSTRAINT fk_pos_cash_registers_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_cash_registers_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_cash_registers_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_cash_registers_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_registers_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_registers_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_cash_registers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_shifts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  opened_by_user_id BIGINT NOT NULL,
  closed_by_user_id BIGINT NULL,
  status VARCHAR(32) NOT NULL,
  opening_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  expected_cash_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  counted_cash_amount DECIMAL(19,4) NULL,
  over_short_amount DECIMAL(19,4) NULL,
  currency_code VARCHAR(3) NOT NULL,
  opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP NULL,
  opening_note TEXT NULL,
  closing_note TEXT NULL,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  open_register_id BIGINT GENERATED ALWAYS AS (
    CASE WHEN deleted_at IS NULL AND status IN ('OPEN', 'CLOSING') THEN cash_register_id ELSE NULL END
  ) STORED,
  open_user_id BIGINT GENERATED ALWAYS AS (
    CASE WHEN deleted_at IS NULL AND status IN ('OPEN', 'CLOSING') THEN opened_by_user_id ELSE NULL END
  ) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_shifts_company_open_register (company_id, open_register_id),
  UNIQUE KEY uk_pos_shifts_company_open_user (company_id, open_user_id),
  KEY idx_pos_shifts_company (company_id),
  KEY idx_pos_shifts_unit (unit_id),
  KEY idx_pos_shifts_business (business_id),
  KEY idx_pos_shifts_warehouse (warehouse_id),
  KEY idx_pos_shifts_cash_register (cash_register_id),
  KEY idx_pos_shifts_opened_by (opened_by_user_id),
  KEY idx_pos_shifts_status (company_id, status),
  KEY idx_pos_shifts_opened_at (company_id, opened_at),
  KEY idx_pos_shifts_deleted (deleted_at),
  CONSTRAINT fk_pos_shifts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_shifts_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_shifts_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_shifts_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_shifts_cash_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_shifts_opened_by FOREIGN KEY (opened_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_shifts_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_shifts_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_shifts_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_shifts_status CHECK (status IN ('OPEN', 'CLOSING', 'CLOSED', 'CANCELLED')),
  CONSTRAINT chk_pos_shifts_amounts CHECK (
    opening_amount >= 0
    AND expected_cash_amount >= 0
    AND (counted_cash_amount IS NULL OR counted_cash_amount >= 0)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
