CREATE TABLE IF NOT EXISTS pos_tickets (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  shift_id BIGINT NOT NULL,
  customer_id BIGINT NULL,
  sales_record_id BIGINT NULL,
  ticket_number VARCHAR(80) NOT NULL,
  status VARCHAR(32) NOT NULL,
  channel VARCHAR(32) NOT NULL DEFAULT 'POS',
  currency_code VARCHAR(3) NOT NULL,
  subtotal_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  discount_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  paid_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  balance_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  customer_name_snapshot VARCHAR(220) NULL,
  customer_tax_id_snapshot VARCHAR(80) NULL,
  notes TEXT NULL,
  completed_at TIMESTAMP NULL,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  version BIGINT NOT NULL DEFAULT 0,
  custom_fields_json JSON NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_tickets_company_number (company_id, ticket_number),
  KEY idx_pos_tickets_company (company_id),
  KEY idx_pos_tickets_warehouse (warehouse_id),
  KEY idx_pos_tickets_cash_register (cash_register_id),
  KEY idx_pos_tickets_shift (shift_id),
  KEY idx_pos_tickets_customer (customer_id),
  KEY idx_pos_tickets_ticket_number (company_id, ticket_number),
  KEY idx_pos_tickets_status (company_id, status),
  KEY idx_pos_tickets_completed_at (company_id, completed_at),
  KEY idx_pos_tickets_deleted_at (deleted_at),
  CONSTRAINT fk_pos_tickets_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_tickets_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_tickets_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_tickets_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_tickets_cash_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_tickets_shift FOREIGN KEY (shift_id) REFERENCES pos_shifts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_tickets_customer FOREIGN KEY (customer_id) REFERENCES sales_contacts(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_tickets_sales_record FOREIGN KEY (sales_record_id) REFERENCES sales_records(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_tickets_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_tickets_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_tickets_status CHECK (status IN ('COMPLETED', 'CANCELLED')),
  CONSTRAINT chk_pos_tickets_amounts CHECK (
    subtotal_amount >= 0
    AND discount_amount >= 0
    AND tax_amount >= 0
    AND total_amount >= 0
    AND paid_amount >= 0
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_ticket_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  ticket_id BIGINT NOT NULL,
  product_id BIGINT NULL,
  sku_snapshot VARCHAR(120) NULL,
  product_name_snapshot VARCHAR(240) NOT NULL,
  product_type_snapshot VARCHAR(40) NULL,
  quantity DECIMAL(19,4) NOT NULL,
  unit_price DECIMAL(19,4) NOT NULL,
  discount_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  line_total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pos_ticket_items_company (company_id),
  KEY idx_pos_ticket_items_ticket (ticket_id),
  KEY idx_pos_ticket_items_product (company_id, product_id),
  CONSTRAINT fk_pos_ticket_items_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_ticket_items_ticket FOREIGN KEY (ticket_id) REFERENCES pos_tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_ticket_items_product FOREIGN KEY (product_id) REFERENCES sales_products(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_ticket_items_amounts CHECK (
    quantity > 0
    AND unit_price >= 0
    AND discount_amount >= 0
    AND tax_amount >= 0
    AND line_total_amount >= 0
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_payments (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  ticket_id BIGINT NOT NULL,
  shift_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  payment_method VARCHAR(32) NOT NULL,
  payment_account_id BIGINT NULL,
  amount DECIMAL(19,4) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  reference VARCHAR(160) NULL,
  status VARCHAR(32) NOT NULL,
  paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id BIGINT NOT NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_pos_payments_company (company_id),
  KEY idx_pos_payments_ticket (ticket_id),
  KEY idx_pos_payments_shift (shift_id),
  KEY idx_pos_payments_cash_register (cash_register_id),
  KEY idx_pos_payments_method (company_id, payment_method),
  KEY idx_pos_payments_status (company_id, status),
  CONSTRAINT fk_pos_payments_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_payments_ticket FOREIGN KEY (ticket_id) REFERENCES pos_tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_payments_shift FOREIGN KEY (shift_id) REFERENCES pos_shifts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_payments_cash_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_payments_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_payments_method CHECK (payment_method IN ('CASH', 'CARD', 'TRANSFER', 'WALLET', 'CREDIT')),
  CONSTRAINT chk_pos_payments_status CHECK (status IN ('CAPTURED', 'VOIDED')),
  CONSTRAINT chk_pos_payments_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
