CREATE TABLE IF NOT EXISTS pos_cash_movements (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  shift_id BIGINT NOT NULL,
  movement_type VARCHAR(32) NOT NULL,
  amount DECIMAL(19,4) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  reason TEXT NOT NULL,
  reference VARCHAR(160) NULL,
  created_by_user_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_pos_cash_movements_company_shift (company_id, shift_id),
  KEY idx_pos_cash_movements_register (cash_register_id),
  KEY idx_pos_cash_movements_type (company_id, movement_type),
  KEY idx_pos_cash_movements_created_at (company_id, created_at),
  CONSTRAINT fk_pos_cash_movements_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_cash_movements_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_cash_movements_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_cash_movements_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_movements_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_movements_shift FOREIGN KEY (shift_id) REFERENCES pos_shifts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_movements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_cash_movements_type CHECK (movement_type IN ('CASH_IN', 'CASH_OUT', 'SAFE_DROP', 'CORRECTION')),
  CONSTRAINT chk_pos_cash_movements_amount CHECK (amount <> 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_cash_closings (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NOT NULL,
  cash_register_id BIGINT NOT NULL,
  shift_id BIGINT NOT NULL,
  opening_cash_amount DECIMAL(19,4) NOT NULL,
  cash_sales_amount DECIMAL(19,4) NOT NULL,
  cash_in_amount DECIMAL(19,4) NOT NULL,
  cash_out_amount DECIMAL(19,4) NOT NULL,
  safe_drop_amount DECIMAL(19,4) NOT NULL,
  correction_amount DECIMAL(19,4) NOT NULL,
  expected_cash_amount DECIMAL(19,4) NOT NULL,
  counted_cash_amount DECIMAL(19,4) NOT NULL,
  over_short_amount DECIMAL(19,4) NOT NULL,
  total_sales_amount DECIMAL(19,4) NOT NULL,
  total_refunds_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tickets_count INT NOT NULL DEFAULT 0,
  payments_summary_json JSON NULL,
  notes TEXT NULL,
  closed_by_user_id BIGINT NOT NULL,
  closed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_cash_closings_shift (company_id, shift_id),
  KEY idx_pos_cash_closings_register (cash_register_id),
  KEY idx_pos_cash_closings_closed_at (company_id, closed_at),
  CONSTRAINT fk_pos_cash_closings_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_cash_closings_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_cash_closings_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_cash_closings_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_closings_register FOREIGN KEY (cash_register_id) REFERENCES pos_cash_registers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_closings_shift FOREIGN KEY (shift_id) REFERENCES pos_shifts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_cash_closings_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
