CREATE TABLE IF NOT EXISTS pos_product_suppliers (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  provider_id BIGINT NOT NULL,
  provider_sku VARCHAR(120) NULL,
  cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL DEFAULT 'MXN',
  lead_time_days INT NULL,
  minimum_order_quantity DECIMAL(19,4) NOT NULL DEFAULT 1.0000,
  is_preferred TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  created_by_user_id BIGINT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_product_suppliers_product_provider (company_id, product_id, provider_id),
  KEY idx_pos_product_suppliers_product (company_id, product_id),
  KEY idx_pos_product_suppliers_provider (company_id, provider_id),
  CONSTRAINT fk_pos_product_suppliers_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_product_suppliers_product FOREIGN KEY (product_id) REFERENCES sales_products(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_product_suppliers_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_product_suppliers_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_product_suppliers_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_product_suppliers_amounts CHECK (cost_amount >= 0 AND minimum_order_quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_purchase_orders (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  unit_id BIGINT NULL,
  business_id BIGINT NULL,
  warehouse_id BIGINT NOT NULL,
  provider_id BIGINT NOT NULL,
  folio VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  subtotal_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  expected_date DATE NULL,
  ordered_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  sent_at TIMESTAMP NULL,
  received_at TIMESTAMP NULL,
  cancelled_at TIMESTAMP NULL,
  notes TEXT NULL,
  created_by_user_id BIGINT NOT NULL,
  updated_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_purchase_orders_company_folio (company_id, folio),
  KEY idx_pos_purchase_orders_company_status (company_id, status),
  KEY idx_pos_purchase_orders_provider (company_id, provider_id),
  KEY idx_pos_purchase_orders_warehouse (company_id, warehouse_id),
  KEY idx_pos_purchase_orders_expected (company_id, expected_date),
  CONSTRAINT fk_pos_purchase_orders_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_orders_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_purchase_orders_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_purchase_orders_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_purchase_orders_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_purchase_orders_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_purchase_orders_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_purchase_orders_status CHECK (status IN ('DRAFT', 'REQUESTED', 'APPROVED', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
  CONSTRAINT chk_pos_purchase_orders_amounts CHECK (subtotal_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_purchase_order_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  purchase_order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  sku_snapshot VARCHAR(120) NULL,
  product_name_snapshot VARCHAR(240) NOT NULL,
  quantity DECIMAL(19,4) NOT NULL,
  received_quantity DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  unit_cost_amount DECIMAL(19,4) NOT NULL,
  tax_rate DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  line_subtotal_amount DECIMAL(19,4) NOT NULL,
  line_tax_amount DECIMAL(19,4) NOT NULL,
  line_total_amount DECIMAL(19,4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_pos_purchase_order_items_order (company_id, purchase_order_id),
  KEY idx_pos_purchase_order_items_product (company_id, product_id),
  CONSTRAINT fk_pos_purchase_order_items_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_order_items_order FOREIGN KEY (purchase_order_id) REFERENCES pos_purchase_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_order_items_product FOREIGN KEY (product_id) REFERENCES sales_products(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_purchase_order_items_amounts CHECK (
    quantity > 0 AND received_quantity >= 0 AND unit_cost_amount >= 0
    AND line_subtotal_amount >= 0 AND line_tax_amount >= 0 AND line_total_amount >= 0
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_purchase_receipts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  purchase_order_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  receipt_number VARCHAR(80) NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  received_by_user_id BIGINT NOT NULL,
  notes TEXT NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_purchase_receipts_company_number (company_id, receipt_number),
  KEY idx_pos_purchase_receipts_order (company_id, purchase_order_id),
  KEY idx_pos_purchase_receipts_warehouse (company_id, warehouse_id),
  CONSTRAINT fk_pos_purchase_receipts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_receipts_order FOREIGN KEY (purchase_order_id) REFERENCES pos_purchase_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_receipts_warehouse FOREIGN KEY (warehouse_id) REFERENCES sales_inventory_warehouses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_purchase_receipts_received_by FOREIGN KEY (received_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_purchase_receipt_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  receipt_id BIGINT NOT NULL,
  purchase_order_item_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity_received DECIMAL(19,4) NOT NULL,
  unit_cost_amount DECIMAL(19,4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_pos_purchase_receipt_items_receipt (company_id, receipt_id),
  KEY idx_pos_purchase_receipt_items_product (company_id, product_id),
  CONSTRAINT fk_pos_purchase_receipt_items_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_receipt_items_receipt FOREIGN KEY (receipt_id) REFERENCES pos_purchase_receipts(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_purchase_receipt_items_order_item FOREIGN KEY (purchase_order_item_id) REFERENCES pos_purchase_order_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_purchase_receipt_items_product FOREIGN KEY (product_id) REFERENCES sales_products(id) ON DELETE RESTRICT,
  CONSTRAINT chk_pos_purchase_receipt_items_quantity CHECK (quantity_received > 0 AND unit_cost_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_supplier_invoices (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id BIGINT NOT NULL,
  provider_id BIGINT NOT NULL,
  purchase_order_id BIGINT NULL,
  invoice_number VARCHAR(120) NOT NULL,
  invoice_date DATE NULL,
  due_date DATE NULL,
  subtotal_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  total_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  currency_code VARCHAR(3) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'SUBMITTED',
  document_url TEXT NULL,
  notes TEXT NULL,
  submitted_by_name VARCHAR(180) NULL,
  reviewed_by_user_id BIGINT NULL,
  reviewed_at TIMESTAMP NULL,
  review_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pos_supplier_invoices_provider_number (company_id, provider_id, invoice_number),
  KEY idx_pos_supplier_invoices_company_status (company_id, status),
  KEY idx_pos_supplier_invoices_provider (company_id, provider_id),
  KEY idx_pos_supplier_invoices_order (company_id, purchase_order_id),
  CONSTRAINT fk_pos_supplier_invoices_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pos_supplier_invoices_provider FOREIGN KEY (provider_id) REFERENCES finance_providers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pos_supplier_invoices_order FOREIGN KEY (purchase_order_id) REFERENCES pos_purchase_orders(id) ON DELETE SET NULL,
  CONSTRAINT fk_pos_supplier_invoices_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_pos_supplier_invoices_status CHECK (status IN ('SUBMITTED', 'MATCHED', 'APPROVED_FOR_PAYMENT', 'REJECTED')),
  CONSTRAINT chk_pos_supplier_invoices_amounts CHECK (subtotal_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
