export const endpoints = {
  auth: {
    login: '/api/v1/auth/login',
    demoLogin: '/api/v1/auth/demo-login',
    publicDemos: '/api/v1/auth/public-demos',
    loginOtpVerify: '/api/v1/auth/login/otp/verify',
    loginOtpResend: '/api/v1/auth/login/otp/resend',
    register: '/api/v1/auth/register',
    csrf: '/api/v1/auth/csrf',
    signupTrial: '/api/v1/auth/signup/trial',
    logout: '/api/v1/auth/logout',
    me: '/api/v1/auth/me',
    company: '/api/v1/auth/company',
    managedCompanies: '/api/v1/auth/managed-companies',
    managedCompany: '/api/v1/auth/managed-company',
    passwordReset: '/api/v1/auth/password-reset',
  },
  billingSignup: {
    config: '/api/v1/billing/signup/config',
    emailVerificationStart: '/api/v1/billing/signup/email-verification/start',
    emailVerificationResend: '/api/v1/billing/signup/email-verification/resend',
    emailVerificationVerify: '/api/v1/billing/signup/email-verification/verify',
    checkout: '/api/v1/billing/signup/checkout',
    status: '/api/v1/billing/signup/status',
  },
  billingRecovery: {
    snapshot: '/api/v1/billing/recovery',
    portal: '/api/v1/billing/recovery/portal',
  },
  billingStorage: {
    snapshot: '/api/v1/billing/storage',
  },
  platform: {
    context: '/api/v1/platform/context',
  },
  platformAdmin: {
    context: '/api/v1/platform-admin/context',
    overview: '/api/v1/platform-admin/overview',
    companies: '/api/v1/platform-admin/companies',
    billing: '/api/v1/platform-admin/billing',
    catalog: '/api/v1/platform-admin/catalog',
    modules: '/api/v1/platform-admin/modules',
    audit: '/api/v1/platform-admin/audit',
    systemTickets: '/api/v1/platform-admin/system-tickets',
  },
  distributorPortal: {
    context: '/api/v1/distributor-portal/context',
    contractsAccess: '/api/v1/distributor-portal/contracts-access',
    catalog: '/api/v1/distributor-portal/catalog',
    companies: '/api/v1/distributor-portal/companies',
    consulting: '/api/v1/distributor-portal/consulting',
    systemTickets: '/api/v1/distributor-portal/system-tickets',
  },
  notifications: {
    list: '/api/v1/notifications',
    readAll: '/api/v1/notifications/read-all',
  },
  workspaceState: {
    base: '/api/v1/workspace-state',
  },
  billing: {
    subscription: '/api/v1/billing/subscription',
    cancelSubscription: '/api/v1/billing/subscription/cancel',
    resumeSubscription: '/api/v1/billing/subscription/resume',
    portal: '/api/v1/billing/subscription/portal',
    selection: '/api/v1/billing/subscription/selection',
    selectionPreview: '/api/v1/billing/subscription/selection/preview',
    activate: '/api/v1/billing/subscription/activate',
    invoices: '/api/v1/billing/subscription/invoices',
    seats: '/api/v1/billing/seats',
  },
  kioskCenter: {
    kiosks: '/api/v2/kiosk-center/kiosks',
  },
  kpis: {
    executivePanel: '/api/v1/kpis/executive-panel',
  },
  invitations: {
    base: '/api/v1/invitations',
  },
  dashboard: {
    modules: '/api/v1/modules',
    units: '/api/v1/org/units',
    businesses: '/api/v1/org/businesses',
  },
  configCenter: {
    currentUser: '/api/v1/config-center/current-user',
    users: '/api/v1/config-center/users',
    updateUser: '/api/v1/config-center/users',
    inviteUser: '/api/v1/config-center/users/invite',
    resendInvitation: '/api/v1/config-center/users/invitations',
    empresa: '/api/v1/config-center/company',
    config: '/api/v1/config-center/config',
    saveConfig: '/api/v1/config-center/business-structure',
    saveEmpresa: '/api/v1/config-center/company',
    locationCoordinateExtraction: '/api/v1/config-center/locations/extract-coordinates',
    saveCurrentUser: '/api/v1/config-center/current-user',
    currentUserAvatarPresignUpload: '/api/v1/config-center/current-user/avatar/presign-upload',
  },
  humanResources: {
    hrUsersList: '/api/v1/hr/users',
    hrUserCreate: '/api/v1/hr/users',
    hrUserDetails: '/api/v1/hr/users',
    hrUserUpdate: '/api/v1/hr/users',
    hrUserDelete: '/api/v1/hr/users',
    hrUserTerminate: '/api/v1/hr/users',
    hrUserDocuments: '/api/v1/hr/users',
    attendanceDashboard: '/api/v1/hr/attendance/dashboard',
    attendanceSelfDashboard: '/api/v1/hr/attendance/me/dashboard',
    attendanceControlOverview: '/api/v1/hr/attendance/control-overview',
    attendanceLocations: '/api/v1/hr/attendance/locations',
    attendanceLocationCoordinateExtraction: '/api/v1/hr/attendance/locations/extract-coordinates',
    attendanceScheduleTemplates: '/api/v1/hr/attendance/schedule-templates',
    attendanceScheduleCandidates: '/api/v1/hr/attendance/schedule-candidates',
    attendanceScheduleAssignmentsBulk: '/api/v1/hr/attendance/schedule-assignments/bulk',
    attendanceWorkSiteAssignmentsBulk: '/api/v1/hr/attendance/work-site-assignments/bulk',
    attendanceWorkAssignmentsClear: '/api/v1/hr/attendance/work-assignments/clear',
    attendanceKioskDevices: '/api/v1/hr/attendance/kiosk-devices',
    attendanceKioskDeviceRotateToken: '/api/v1/hr/attendance/kiosk-devices',
    attendanceAccessProfiles: '/api/v1/hr/attendance/access-profiles',
    attendanceAccessMethods: '/api/v1/hr/attendance/access-methods',
    attendancePublicKiosk: '/api/v1/hr/attendance/public-kiosk',
    attendanceCalendar: '/api/v1/hr/attendance/users',
    attendanceSelfCalendar: '/api/v1/hr/attendance/me/calendar',
    attendanceMediaPresignUpload: '/api/v1/hr/attendance/media/presign-upload',
    attendanceSelfMediaPresignUpload: '/api/v1/hr/attendance/me/media/presign-upload',
    attendanceFaceVerificationSessions: '/api/v1/hr/attendance/face-verification-sessions',
    attendanceSelfFaceVerificationSessions: '/api/v1/hr/attendance/me/face-verification-sessions',
    attendanceKioskEvents: '/api/v1/hr/attendance/kiosk-events',
    attendanceSelfKioskEvents: '/api/v1/hr/attendance/me/kiosk-events',
    attendanceDailyRecords: '/api/v1/hr/attendance/daily-records',
    attendanceSelfDailyRecords: '/api/v1/hr/attendance/me/daily-records',
    faceEnrollmentSessions: '/api/v1/hr/face/enrollment-sessions',
    faceEnrollments: '/api/v1/hr/face/enrollments',
    announcementsList: '/api/v1/hr/announcements',
    announcementsCreate: '/api/v1/hr/announcements',
    announcementsAudienceOptions: '/api/v1/hr/announcements/audience-options',
    recordsList: '/api/v1/hr/records',
    recordsCreate: '/api/v1/hr/records',
    recordDetails: '/api/v1/hr/records',
    recordUpdate: '/api/v1/hr/records',
    recordDelete: '/api/v1/hr/records',
    recordAttachments: '/api/v1/hr/records',
    permissionsList: '/api/v1/hr/permissions',
    permissionsDetails: '/api/v1/hr/permissions',
    permissionsApprove: '/api/v1/hr/permissions',
    permissionsReject: '/api/v1/hr/permissions',
    permissionsMeList: '/api/v1/hr/permissions/me',
    permissionsMeDetails: '/api/v1/hr/permissions/me',
    permissionsMeCreate: '/api/v1/hr/permissions/me',
    permissionsMeDelete: '/api/v1/hr/permissions/me',
    permissionsMeAttachments: '/api/v1/hr/permissions/me',
    incentivesList: '/api/v1/hr/incentives',
    incentivesCreate: '/api/v1/hr/incentives',
    incentivesDelete: '/api/v1/hr/incentives',
    payrollOverview: '/api/v1/hr/payroll/overview',
    payrollPreferences: '/api/v1/hr/payroll/preferences',
    payrollRuns: '/api/v1/hr/payroll/runs',
    payrollColombia: '/api/v1/hr/payroll/colombia',
    payrollGovernmentReporting: '/api/v1/hr/payroll/government-reporting',
  },
  sales: {
    base: '/api/v1/sales',
    context: '/api/v1/sales/context',
    kpis: '/api/v1/sales/kpis',
  },
} as const;
