export const endpoints = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    me: '/api/v1/auth/me',
  },
  dashboard: {
    modules: '/api/v1/modules',
    units: '/api/v1/org/units',
    businesses: '/api/v1/org/businesses',
  },
  configCenter: {
    currentUser: '/api/v1/config-center/current-user',
    users: '/api/v1/config-center/users',
    updateUser: '/api/v1/config-center/users',
    inviteUser: '/api/v1/config-center/users/invite',
    resendInvitation: '/api/v1/config-center/users/invitations',
    empresa: '/api/v1/config-center/company',
    config: '/api/v1/config-center/config',
    saveConfig: '/api/v1/config-center/business-structure',
    saveEmpresa: '/api/v1/config-center/company',
    saveCurrentUser: '/api/v1/config-center/current-user',
  },
  humanResources: {
    employeesList: '/api/v1/hr/employees',
    employeeCreate: '/api/v1/hr/employees',
    employeeDetails: '/api/v1/hr/employees',
    employeeUpdate: '/api/v1/hr/employees',
    employeeDelete: '/api/v1/hr/employees',
    employeeTerminate: '/api/v1/hr/employees',
    employeeDocuments: '/api/v1/hr/employees',
    attendanceDashboard: '/api/v1/hr/attendance/dashboard',
    attendanceSelfDashboard: '/api/v1/hr/attendance/me/dashboard',
    attendanceControlOverview: '/api/v1/hr/attendance/control-overview',
    attendanceLocations: '/api/v1/hr/attendance/locations',
    attendanceScheduleTemplates: '/api/v1/hr/attendance/schedule-templates',
    attendanceScheduleAssignmentsBulk: '/api/v1/hr/attendance/schedule-assignments/bulk',
    attendanceKioskDevices: '/api/v1/hr/attendance/kiosk-devices',
    attendanceKioskDeviceRotateToken: '/api/v1/hr/attendance/kiosk-devices',
    attendanceAccessProfiles: '/api/v1/hr/attendance/access-profiles',
    attendanceAccessMethods: '/api/v1/hr/attendance/access-methods',
    attendancePublicKiosk: '/api/v1/hr/attendance/public-kiosk',
    attendanceCalendar: '/api/v1/hr/attendance/employees',
    attendanceSelfCalendar: '/api/v1/hr/attendance/me/calendar',
    attendanceMediaPresignUpload: '/api/v1/hr/attendance/media/presign-upload',
    attendanceSelfMediaPresignUpload: '/api/v1/hr/attendance/me/media/presign-upload',
    attendanceFaceVerificationSessions: '/api/v1/hr/attendance/face-verification-sessions',
    attendanceSelfFaceVerificationSessions: '/api/v1/hr/attendance/me/face-verification-sessions',
    attendanceKioskEvents: '/api/v1/hr/attendance/kiosk-events',
    attendanceSelfKioskEvents: '/api/v1/hr/attendance/me/kiosk-events',
    attendanceDailyRecords: '/api/v1/hr/attendance/daily-records',
    attendanceSelfDailyRecords: '/api/v1/hr/attendance/me/daily-records',
    faceEnrollmentSessions: '/api/v1/hr/face/enrollment-sessions',
    faceEnrollments: '/api/v1/hr/face/enrollments',
    announcementsList: '/api/v1/hr/announcements',
    announcementsCreate: '/api/v1/hr/announcements',
    recordsList: '/api/v1/hr/records',
    recordsCreate: '/api/v1/hr/records',
    recordDetails: '/api/v1/hr/records',
    recordUpdate: '/api/v1/hr/records',
    recordDelete: '/api/v1/hr/records',
    recordAttachments: '/api/v1/hr/records',
    payrollOverview: '/api/v1/hr/payroll/overview',
    payrollPreferences: '/api/v1/hr/payroll/preferences',
    payrollRuns: '/api/v1/hr/payroll/runs',
  },
} as const;
