import type { RecordsTranslations } from '../translations';
import type { EmployeeRecord } from '../types/records.types';

const sanitizeFileName = (value: string) => (
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'record'
);

const getRecordPdfCopy = (locale: string) => {
  if (locale.startsWith('es')) {
    return {
      brand: 'Índice ERP',
      title: 'Acta de Recursos Humanos',
      generatedAt: 'Fecha de emisión',
      overview: 'Resumen del acta',
      followUp: 'Seguimiento',
      signatures: 'Firmas de conocimiento',
      employeeSignature: 'Colaborador',
      reportedBySignature: 'Responsable que reporta',
      signature: 'Firma',
      footer: 'Documento generado por Índice ERP para control interno de Recursos Humanos.',
    };
  }

  if (locale.startsWith('pt')) {
    return {
      brand: 'Índice ERP',
      title: 'Registro de Recursos Humanos',
      generatedAt: 'Data de emissão',
      overview: 'Resumo do registro',
      followUp: 'Acompanhamento',
      signatures: 'Assinaturas de ciência',
      employeeSignature: 'Colaborador',
      reportedBySignature: 'Responsável pelo relato',
      signature: 'Assinatura',
      footer: 'Documento gerado pelo Índice ERP para controle interno de Recursos Humanos.',
    };
  }

  if (locale.startsWith('fr')) {
    return {
      brand: 'Índice ERP',
      title: 'Dossier de Ressources Humaines',
      generatedAt: "Date d'émission",
      overview: 'Résumé du dossier',
      followUp: 'Suivi',
      signatures: 'Signatures de prise de connaissance',
      employeeSignature: 'Employé',
      reportedBySignature: 'Responsable déclarant',
      signature: 'Signature',
      footer: 'Document généré par Índice ERP pour le contrôle interne des Ressources Humaines.',
    };
  }

  return {
    brand: 'Índice ERP',
    title: 'Human Resources Record',
    generatedAt: 'Issue date',
    overview: 'Record summary',
    followUp: 'Follow-up',
    signatures: 'Acknowledgement signatures',
    employeeSignature: 'Employee',
    reportedBySignature: 'Reporting manager',
    signature: 'Signature',
    footer: 'Document generated by Índice ERP for internal Human Resources control.',
  };
};

const addSection = (
  doc: import('jspdf').jsPDF,
  title: string,
  rows: Array<[string, string]>,
  startY: number,
) => {
  const left = 18;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxValueWidth = pageWidth - 84;
  let y = startY;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(title, left, y);
  y += 8;

  rows.forEach(([label, value]) => {
    if (!value.trim()) {
      return;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(label.toUpperCase(), left, y);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    const lines = doc.splitTextToSize(value, maxValueWidth);
    doc.text(lines, 74, y);
    y += Math.max(7, lines.length * 5 + 2);
  });

  return y + 3;
};

export async function downloadRecordPdf(
  record: EmployeeRecord,
  copy: RecordsTranslations,
  locale: string,
) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pdfCopy = getRecordPdfCopy(locale);
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const left = 18;
  const contentWidth = pageWidth - left * 2;
  const issuedAt = new Intl.DateTimeFormat(locale, {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date());
  const recordNumber = record.recordNumber || copy.pdf.recordNumber(record.id);

  doc.setFillColor(89, 195, 165);
  doc.rect(0, 0, pageWidth, 31, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(pdfCopy.title, left, 17);
  doc.setFontSize(10);
  doc.text(pdfCopy.brand, pageWidth - left, 17, { align: 'right' });

  let y = 43;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text(record.title, left, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(`${recordNumber} · ${pdfCopy.generatedAt}: ${issuedAt}`, left, y);
  y += 11;

  y = addSection(
    doc,
    pdfCopy.overview,
    [
      [copy.pdf.employee, `${record.user.name}${record.user.position ? ` - ${record.user.position}` : ''}`],
      [copy.pdf.reportedBy, record.reportedBy.name],
      [copy.pdf.eventDate, new Date(record.eventDate).toLocaleString(locale)],
      [copy.pdf.type, copy.types[record.type]],
      [copy.pdf.severity, record.severity ? copy.severity[record.severity] : copy.pdf.notAvailable],
      [copy.pdf.status, copy.status[record.status]],
    ],
    y,
  );

  y = addSection(
    doc,
    pdfCopy.followUp,
    [
      [copy.pdf.description, record.description],
      [copy.pdf.actionsTaken, record.actionsTaken || copy.pdf.notAvailable],
      [copy.pdf.witnesses, record.witnesses?.length ? record.witnesses.join(', ') : copy.pdf.notAvailable],
      [copy.pdf.attachments, record.attachments?.length ? record.attachments.map((attachment) => attachment.name).join(', ') : copy.pdf.notAvailable],
    ],
    y,
  );

  if (y > pageHeight - 78) {
    doc.addPage();
    y = 24;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(pdfCopy.signatures, left, y);
  y += 24;

  const signatureWidth = (contentWidth - 12) / 2;
  [
    { label: pdfCopy.employeeSignature, name: record.user.name, x: left },
    { label: pdfCopy.reportedBySignature, name: record.reportedBy.name, x: left + signatureWidth + 12 },
  ].forEach((signature) => {
    doc.setDrawColor(148, 163, 184);
    doc.line(signature.x, y, signature.x + signatureWidth, y);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(signature.label, signature.x, y + 7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(signature.name, signature.x, y + 13, { maxWidth: signatureWidth });
    doc.text(pdfCopy.signature, signature.x, y + 19);
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(pdfCopy.footer, left, pageHeight - 14);
  doc.text(recordNumber, pageWidth - left, pageHeight - 14, { align: 'right' });

  doc.save(`${sanitizeFileName(recordNumber || record.title)}.pdf`);
}
