import { getHumanEngineLanguage, type HumanEngineLanguage } from './localization';
import type { HumanTagId, AggregatedHumanTag } from './types';

type HumanTagCatalogEntry = Pick<
  AggregatedHumanTag,
  'category' | 'dimension' | 'label' | 'operationalRisk' | 'recommendedAction'
>;

export const HUMAN_TAG_CATALOG: Record<HumanTagId, HumanTagCatalogEntry> = {
  fatiga_acumulada: {
    category: 'risk',
    dimension: 'recovery',
    label: 'Fatiga acumulada',
    operationalRisk: 'La persona puede seguir ejecutando, pero con menor margen de recuperacion entre ciclos de trabajo.',
    recommendedAction: 'Reducir una fuente de carga secundaria y proteger un bloque real de recuperacion esta semana.',
  },
  claridad_degradada: {
    category: 'symptom',
    dimension: 'executive',
    label: 'Claridad ejecutiva degradada',
    operationalRisk: 'Las decisiones pueden volverse mas lentas, reactivas o inconsistentes bajo presion.',
    recommendedAction: 'Mover decisiones relevantes al bloque de mayor energia y definir criterios por escrito.',
  },
  productividad_por_presion: {
    category: 'risk',
    dimension: 'sustainability',
    label: 'Productividad basada en presion',
    operationalRisk: 'El rendimiento depende de urgencia, disciplina o tension, no de un sistema sostenible.',
    recommendedAction: 'Instalar un ritmo operativo que cierre el dia antes de que la urgencia sea el unico motor.',
  },
  sobrecarga_constante: {
    category: 'risk',
    dimension: 'cognitive',
    label: 'Sobrecarga cognitiva',
    operationalRisk: 'La mente opera como sistema de seguimiento y empieza a perder precision ejecutiva.',
    recommendedAction: 'Descargar pendientes en una lista unica y elegir tres decisiones que no deben vivir en memoria.',
  },
  dificultad_desconexion: {
    category: 'constraint',
    dimension: 'recovery',
    label: 'Dificultad de desconexion',
    operationalRisk: 'El trabajo sigue activo mentalmente fuera del horario y bloquea recuperacion real.',
    recommendedAction: 'Crear un cierre diario con pendientes, primer paso de manana y apagado de notificaciones.',
  },
  rutina_no_sostenible: {
    category: 'risk',
    dimension: 'sustainability',
    label: 'Rutina no sostenible',
    operationalRisk: 'La rutina actual puede funcionar por periodos cortos, pero se debilita cuando aumenta la carga.',
    recommendedAction: 'Eliminar o delegar un compromiso no esencial antes de agregar nuevas exigencias.',
  },
  energia_inestable: {
    category: 'symptom',
    dimension: 'energy',
    label: 'Energia inestable',
    operationalRisk: 'El dia depende de picos de energia y produce variacion en foco, humor y avance.',
    recommendedAction: 'Fijar una comida, agua y pausa de movimiento como sistema base de energia.',
  },
  baja_recuperacion: {
    category: 'risk',
    dimension: 'recovery',
    label: 'Baja recuperacion',
    operationalRisk: 'La recuperacion no compensa la carga y vuelve fragil cualquier mejora de productividad.',
    recommendedAction: 'Proteger hora de cierre nocturno y medir energia al despertar durante siete dias.',
  },
  tension_cognitiva: {
    category: 'symptom',
    dimension: 'cognitive',
    label: 'Tension cognitiva',
    operationalRisk: 'La tension mental consume energia antes de que el trabajo empiece formalmente.',
    recommendedAction: 'Separar preocupaciones en controlables, delegables y pendientes de decision.',
  },
  dependencia_voluntad: {
    category: 'dependency',
    dimension: 'sustainability',
    label: 'Dependencia de voluntad',
    operationalRisk: 'El sistema personal exige demasiada fuerza individual para sostener resultados.',
    recommendedAction: 'Convertir una decision repetida en regla simple para no resolverla todos los dias.',
  },
  sedentarismo_operativo: {
    category: 'constraint',
    dimension: 'energy',
    label: 'Sedentarismo operativo',
    operationalRisk: 'El cuerpo entra en modo pasivo y la mente pierde frescura en bloques largos de trabajo.',
    recommendedAction: 'Insertar pausas activas de tres minutos entre reuniones o bloques exigentes.',
  },
  limites_debiles: {
    category: 'constraint',
    dimension: 'sustainability',
    label: 'Limites laborales debiles',
    operationalRisk: 'El trabajo ocupa espacios de recuperacion y vuelve normal operar sin cierre.',
    recommendedAction: 'Definir una hora limite para trabajo operativo y una excepcion clara para urgencias reales.',
  },
  recuperacion_fragmentada: {
    category: 'symptom',
    dimension: 'recovery',
    label: 'Recuperacion fragmentada',
    operationalRisk: 'El descanso se interrumpe y reduce recuperacion aunque el total de horas parezca aceptable.',
    recommendedAction: 'Reducir estimulos nocturnos y registrar que interrumpe mas el descanso.',
  },
  trabajo_nocturno: {
    category: 'constraint',
    dimension: 'recovery',
    label: 'Trabajo nocturno',
    operationalRisk: 'El sistema nervioso sigue activo cuando deberia entrar en recuperacion.',
    recommendedAction: 'Reservar trabajo nocturno solo para emergencias y mover decisiones al dia siguiente.',
  },
  ansiedad_responsabilidades: {
    category: 'symptom',
    dimension: 'cognitive',
    label: 'Ansiedad por responsabilidades',
    operationalRisk: 'La preocupacion sostenida drena energia incluso cuando no se esta ejecutando.',
    recommendedAction: 'Convertir responsabilidades abiertas en decisiones, delegaciones o siguientes pasos visibles.',
  },
  degradacion_ejecutiva: {
    category: 'risk',
    dimension: 'executive',
    label: 'Degradacion ejecutiva',
    operationalRisk: 'La calidad de decision puede caer antes de que caiga el volumen de trabajo.',
    recommendedAction: 'Reducir contexto abierto y tomar decisiones importantes con criterios escritos.',
  },
  riesgo_burnout: {
    category: 'risk',
    dimension: 'sustainability',
    label: 'Riesgo de burnout',
    operationalRisk: 'El desgaste puede empezar a afectar continuidad, criterio y capacidad de recuperacion.',
    recommendedAction: 'Bajar carga secundaria y crear una revision semanal de energia, limites y recuperacion.',
  },
  dependencia_presencia: {
    category: 'dependency',
    dimension: 'sustainability',
    label: 'Dependencia de presencia constante',
    operationalRisk: 'La operacion personal no escala si todo requiere disponibilidad continua.',
    recommendedAction: 'Documentar una rutina repetida que pueda ejecutarse sin presencia directa.',
  },
  pausas_insuficientes: {
    category: 'constraint',
    dimension: 'recovery',
    label: 'Pausas insuficientes',
    operationalRisk: 'La falta de pausas reduce claridad y aumenta errores al final de la jornada.',
    recommendedAction: 'Bloquear dos pausas breves no negociables entre bloques de mayor demanda.',
  },
  trabajo_extendido: {
    category: 'constraint',
    dimension: 'sustainability',
    label: 'Semana laboral extendida',
    operationalRisk: 'La semana consume dias de recuperacion y normaliza operar con deuda de energia.',
    recommendedAction: 'Proteger al menos medio dia sin tareas operativas.',
  },
  carga_sin_recuperacion: {
    category: 'risk',
    dimension: 'recovery',
    label: 'Carga sin recuperacion proporcional',
    operationalRisk: 'Los dias exigentes dejan residuo de cansancio que se acumula en la semana siguiente.',
    recommendedAction: 'Despues de dias pesados, reducir compromisos secundarios y cerrar con descarga operativa.',
  },
  combustible_fisico_bajo: {
    category: 'constraint',
    dimension: 'energy',
    label: 'Combustible fisico bajo',
    operationalRisk: 'La energia base no sostiene el nivel de decision y ejecucion requerido.',
    recommendedAction: 'Asegurar dos comidas completas, agua visible y una opcion de respaldo para dias cargados.',
  },
  pantallas_nocturnas: {
    category: 'constraint',
    dimension: 'recovery',
    label: 'Estimulo nocturno alto',
    operationalRisk: 'El cierre mental se retrasa y el descanso empieza con la mente en modo trabajo.',
    recommendedAction: 'Cambiar los ultimos 30 minutos por preparacion del dia siguiente o lectura ligera.',
  },
  culpa_descanso: {
    category: 'constraint',
    dimension: 'sustainability',
    label: 'Culpa al descansar',
    operationalRisk: 'La recuperacion se percibe como costo y no como parte del sistema de rendimiento.',
    recommendedAction: 'Tratar descanso como bloque operativo protegido, no como premio posterior.',
  },
  recuperacion_mental_baja: {
    category: 'symptom',
    dimension: 'recovery',
    label: 'Recuperacion mental baja',
    operationalRisk: 'La mente no termina de salir del modo resolucion y reduce descanso real.',
    recommendedAction: 'Instalar un ritual de salida: cerrar tablero, anotar pendientes y apagar alertas.',
  },
  energia_estable: {
    category: 'capacity',
    dimension: 'energy',
    label: 'Energia estable',
    operationalRisk: 'La energia fisica ayuda a sostener ejecucion, pero puede estar compensando otras fricciones.',
    recommendedAction: 'Proteger los habitos que sostienen energia antes de ajustar carga mental.',
  },
  recuperacion_estable: {
    category: 'capacity',
    dimension: 'recovery',
    label: 'Recuperacion estable',
    operationalRisk: 'La recuperacion actual es una fortaleza que debe protegerse al aumentar responsabilidades.',
    recommendedAction: 'Mantener horarios y cierres que ya funcionan durante semanas de mayor presion.',
  },
  claridad_operativa: {
    category: 'capacity',
    dimension: 'executive',
    label: 'Claridad operativa',
    operationalRisk: 'La claridad es un activo operativo que puede deteriorarse si se acumula contexto abierto.',
    recommendedAction: 'Usar criterios escritos para preservar calidad de decision bajo carga.',
  },
  limites_saludables: {
    category: 'capacity',
    dimension: 'sustainability',
    label: 'Limites saludables',
    operationalRisk: 'Los limites actuales sostienen continuidad; perderlos aumentaria dependencia de esfuerzo.',
    recommendedAction: 'Conservar limites antes de aceptar nuevas demandas o responsabilidades.',
  },
  resiliencia_funcional: {
    category: 'capacity',
    dimension: 'sustainability',
    label: 'Resiliencia funcional',
    operationalRisk: 'La persona tiene capacidad de sostener exigencia, pero debe evitar convertirla en deuda.',
    recommendedAction: 'Mantener solo habitos que puedan sostenerse sin aumentar presion.',
  },
};

type HumanTagLocalizedCopy = Pick<HumanTagCatalogEntry, 'label' | 'operationalRisk' | 'recommendedAction'>;

const GENERIC_TAG_COPY: Record<Exclude<HumanEngineLanguage, 'es' | 'en'>, Pick<HumanTagCatalogEntry, 'operationalRisk' | 'recommendedAction'>> = {
  fr: {
    operationalRisk: 'Ce signal peut limiter la capacité opérationnelle personnelle si la charge augmente.',
    recommendedAction: 'Installer un ajustement simple, visible et soutenable pendant sept jours avant d’ajouter une nouvelle exigence.',
  },
  pt: {
    operationalRisk: 'Este sinal pode limitar a capacidade operacional pessoal se a carga aumentar.',
    recommendedAction: 'Instale um ajuste simples, visível e sustentável por sete dias antes de adicionar uma nova exigência.',
  },
  ko: {
    operationalRisk: '업무 부담이 커지면 이 신호는 개인 운영 역량을 제한할 수 있습니다.',
    recommendedAction: '새로운 요구를 추가하기 전에 7일 동안 유지 가능한 단순하고 보이는 조정을 먼저 설치하세요.',
  },
  zh: {
    operationalRisk: '如果工作负荷继续增加，这个信号可能会限制个人运营能力。',
    recommendedAction: '先建立一个简单、可见、可持续 7 天的调整，再增加新的要求。',
  },
};

const TAG_LABEL_TRANSLATIONS: Record<Exclude<HumanEngineLanguage, 'es'>, Record<HumanTagId, string>> = {
  en: {
    fatiga_acumulada: 'Accumulated fatigue',
    claridad_degradada: 'Degraded executive clarity',
    productividad_por_presion: 'Pressure-based productivity',
    sobrecarga_constante: 'Cognitive overload',
    dificultad_desconexion: 'Difficulty disconnecting',
    rutina_no_sostenible: 'Unsustainable routine',
    energia_inestable: 'Unstable energy',
    baja_recuperacion: 'Low recovery',
    tension_cognitiva: 'Cognitive tension',
    dependencia_voluntad: 'Willpower dependency',
    sedentarismo_operativo: 'Operational sedentarism',
    limites_debiles: 'Weak work boundaries',
    recuperacion_fragmentada: 'Fragmented recovery',
    trabajo_nocturno: 'Late-night work',
    ansiedad_responsabilidades: 'Responsibility anxiety',
    degradacion_ejecutiva: 'Executive degradation',
    riesgo_burnout: 'Burnout risk',
    dependencia_presencia: 'Constant-presence dependency',
    pausas_insuficientes: 'Insufficient breaks',
    trabajo_extendido: 'Extended workweek',
    carga_sin_recuperacion: 'Load without proportional recovery',
    combustible_fisico_bajo: 'Low physical fuel',
    pantallas_nocturnas: 'High nighttime stimulation',
    culpa_descanso: 'Rest guilt',
    recuperacion_mental_baja: 'Low mental recovery',
    energia_estable: 'Stable energy',
    recuperacion_estable: 'Stable recovery',
    claridad_operativa: 'Operating clarity',
    limites_saludables: 'Healthy boundaries',
    resiliencia_funcional: 'Functional resilience',
  },
  fr: {
    fatiga_acumulada: 'Fatigue accumulée',
    claridad_degradada: 'Clarté exécutive dégradée',
    productividad_por_presion: 'Productivité fondée sur la pression',
    sobrecarga_constante: 'Surcharge cognitive',
    dificultad_desconexion: 'Difficulté à déconnecter',
    rutina_no_sostenible: 'Routine non soutenable',
    energia_inestable: 'Énergie instable',
    baja_recuperacion: 'Récupération faible',
    tension_cognitiva: 'Tension cognitive',
    dependencia_voluntad: 'Dépendance à la volonté',
    sedentarismo_operativo: 'Sédentarité opérationnelle',
    limites_debiles: 'Limites de travail faibles',
    recuperacion_fragmentada: 'Récupération fragmentée',
    trabajo_nocturno: 'Travail nocturne',
    ansiedad_responsabilidades: 'Anxiété liée aux responsabilités',
    degradacion_ejecutiva: 'Dégradation exécutive',
    riesgo_burnout: 'Risque d’épuisement',
    dependencia_presencia: 'Dépendance à la présence constante',
    pausas_insuficientes: 'Pauses insuffisantes',
    trabajo_extendido: 'Semaine de travail prolongée',
    carga_sin_recuperacion: 'Charge sans récupération proportionnelle',
    combustible_fisico_bajo: 'Carburant physique insuffisant',
    pantallas_nocturnas: 'Stimulation nocturne élevée',
    culpa_descanso: 'Culpabilité liée au repos',
    recuperacion_mental_baja: 'Récupération mentale faible',
    energia_estable: 'Énergie stable',
    recuperacion_estable: 'Récupération stable',
    claridad_operativa: 'Clarté opérationnelle',
    limites_saludables: 'Limites saines',
    resiliencia_funcional: 'Résilience fonctionnelle',
  },
  pt: {
    fatiga_acumulada: 'Fadiga acumulada',
    claridad_degradada: 'Clareza executiva degradada',
    productividad_por_presion: 'Produtividade baseada em pressão',
    sobrecarga_constante: 'Sobrecarga cognitiva',
    dificultad_desconexion: 'Dificuldade de desconexão',
    rutina_no_sostenible: 'Rotina não sustentável',
    energia_inestable: 'Energia instável',
    baja_recuperacion: 'Baixa recuperação',
    tension_cognitiva: 'Tensão cognitiva',
    dependencia_voluntad: 'Dependência de força de vontade',
    sedentarismo_operativo: 'Sedentarismo operacional',
    limites_debiles: 'Limites de trabalho frágeis',
    recuperacion_fragmentada: 'Recuperação fragmentada',
    trabajo_nocturno: 'Trabalho noturno',
    ansiedad_responsabilidades: 'Ansiedade por responsabilidades',
    degradacion_ejecutiva: 'Degradação executiva',
    riesgo_burnout: 'Risco de burnout',
    dependencia_presencia: 'Dependência de presença constante',
    pausas_insuficientes: 'Pausas insuficientes',
    trabajo_extendido: 'Semana de trabalho estendida',
    carga_sin_recuperacion: 'Carga sem recuperação proporcional',
    combustible_fisico_bajo: 'Baixo combustível físico',
    pantallas_nocturnas: 'Alta estimulação noturna',
    culpa_descanso: 'Culpa ao descansar',
    recuperacion_mental_baja: 'Baixa recuperação mental',
    energia_estable: 'Energia estável',
    recuperacion_estable: 'Recuperação estável',
    claridad_operativa: 'Clareza operacional',
    limites_saludables: 'Limites saudáveis',
    resiliencia_funcional: 'Resiliência funcional',
  },
  ko: {
    fatiga_acumulada: '누적 피로',
    claridad_degradada: '저하된 실행 명료성',
    productividad_por_presion: '압박 기반 생산성',
    sobrecarga_constante: '인지 과부하',
    dificultad_desconexion: '업무 차단의 어려움',
    rutina_no_sostenible: '지속 가능하지 않은 루틴',
    energia_inestable: '불안정한 에너지',
    baja_recuperacion: '낮은 회복',
    tension_cognitiva: '인지적 긴장',
    dependencia_voluntad: '의지력 의존',
    sedentarismo_operativo: '운영상의 좌식 패턴',
    limites_debiles: '약한 업무 경계',
    recuperacion_fragmentada: '분절된 회복',
    trabajo_nocturno: '야간 업무',
    ansiedad_responsabilidades: '책임에 대한 불안',
    degradacion_ejecutiva: '실행 기능 저하',
    riesgo_burnout: '번아웃 위험',
    dependencia_presencia: '상시 존재 의존',
    pausas_insuficientes: '부족한 휴식',
    trabajo_extendido: '연장된 근무 주간',
    carga_sin_recuperacion: '회복에 비해 높은 부하',
    combustible_fisico_bajo: '낮은 신체 에너지 기반',
    pantallas_nocturnas: '높은 야간 자극',
    culpa_descanso: '휴식에 대한 죄책감',
    recuperacion_mental_baja: '낮은 정신적 회복',
    energia_estable: '안정적인 에너지',
    recuperacion_estable: '안정적인 회복',
    claridad_operativa: '운영 명료성',
    limites_saludables: '건강한 경계',
    resiliencia_funcional: '기능적 회복탄력성',
  },
  zh: {
    fatiga_acumulada: '累积疲劳',
    claridad_degradada: '执行清晰度下降',
    productividad_por_presion: '压力驱动的生产力',
    sobrecarga_constante: '认知过载',
    dificultad_desconexion: '难以断开工作',
    rutina_no_sostenible: '不可持续的日常节奏',
    energia_inestable: '能量不稳定',
    baja_recuperacion: '恢复不足',
    tension_cognitiva: '认知紧张',
    dependencia_voluntad: '意志力依赖',
    sedentarismo_operativo: '运营性久坐',
    limites_debiles: '工作边界薄弱',
    recuperacion_fragmentada: '碎片化恢复',
    trabajo_nocturno: '夜间工作',
    ansiedad_responsabilidades: '责任焦虑',
    degradacion_ejecutiva: '执行能力下降',
    riesgo_burnout: '倦怠风险',
    dependencia_presencia: '持续在场依赖',
    pausas_insuficientes: '休息不足',
    trabajo_extendido: '延长的工作周',
    carga_sin_recuperacion: '负荷与恢复不匹配',
    combustible_fisico_bajo: '身体能量基础不足',
    pantallas_nocturnas: '夜间刺激过高',
    culpa_descanso: '休息内疚感',
    recuperacion_mental_baja: '心理恢复不足',
    energia_estable: '能量稳定',
    recuperacion_estable: '恢复稳定',
    claridad_operativa: '运营清晰度',
    limites_saludables: '健康边界',
    resiliencia_funcional: '功能性韧性',
  },
};

const EN_TAG_COPY_OVERRIDES: Partial<Record<HumanTagId, HumanTagLocalizedCopy>> = {
  fatiga_acumulada: {
    label: TAG_LABEL_TRANSLATIONS.en.fatiga_acumulada,
    operationalRisk: 'The person may keep executing, but with less recovery margin between work cycles.',
    recommendedAction: 'Reduce one secondary load source and protect one real recovery block this week.',
  },
  claridad_degradada: {
    label: TAG_LABEL_TRANSLATIONS.en.claridad_degradada,
    operationalRisk: 'Decisions may become slower, more reactive, or inconsistent under pressure.',
    recommendedAction: 'Move relevant decisions to the highest-energy block and define criteria in writing.',
  },
  productividad_por_presion: {
    label: TAG_LABEL_TRANSLATIONS.en.productividad_por_presion,
    operationalRisk: 'Performance depends on urgency, discipline, or tension instead of a sustainable system.',
    recommendedAction: 'Install an operating rhythm that closes the day before urgency becomes the only engine.',
  },
  sobrecarga_constante: {
    label: TAG_LABEL_TRANSLATIONS.en.sobrecarga_constante,
    operationalRisk: 'The mind becomes the tracking system and starts losing executive precision.',
    recommendedAction: 'Unload pending work into one list and choose three decisions that should not live in memory.',
  },
  dificultad_desconexion: {
    label: TAG_LABEL_TRANSLATIONS.en.dificultad_desconexion,
    operationalRisk: 'Work remains mentally active after hours and blocks real recovery.',
    recommendedAction: 'Create a daily shutdown with pending items, tomorrow’s first step, and notifications off.',
  },
  rutina_no_sostenible: {
    label: TAG_LABEL_TRANSLATIONS.en.rutina_no_sostenible,
    operationalRisk: 'The current routine may work briefly, but weakens when load increases.',
    recommendedAction: 'Remove or delegate one non-essential commitment before adding new demands.',
  },
  energia_inestable: {
    label: TAG_LABEL_TRANSLATIONS.en.energia_inestable,
    operationalRisk: 'The day depends on energy spikes and creates variation in focus, mood, and progress.',
    recommendedAction: 'Fix one meal, water, and a movement break as the base energy system.',
  },
  baja_recuperacion: {
    label: TAG_LABEL_TRANSLATIONS.en.baja_recuperacion,
    operationalRisk: 'Recovery does not compensate load and makes any productivity improvement fragile.',
    recommendedAction: 'Protect a nighttime shutdown hour and track morning energy for seven days.',
  },
  dependencia_presencia: {
    label: TAG_LABEL_TRANSLATIONS.en.dependencia_presencia,
    operationalRisk: 'The personal operation does not scale if everything requires continuous availability.',
    recommendedAction: 'Document one repeated routine that can move without direct presence.',
  },
  riesgo_burnout: {
    label: TAG_LABEL_TRANSLATIONS.en.riesgo_burnout,
    operationalRisk: 'Wear may start affecting continuity, judgment, and recovery capacity.',
    recommendedAction: 'Lower secondary load and create a weekly review of energy, boundaries, and recovery.',
  },
};

export const getHumanTagCatalog = (locale: string): Record<HumanTagId, HumanTagCatalogEntry> => {
  const language = getHumanEngineLanguage(locale);

  if (language === 'es') {
    return HUMAN_TAG_CATALOG;
  }

  const genericCopy = language === 'en'
    ? undefined
    : GENERIC_TAG_COPY[language];

  return (Object.keys(HUMAN_TAG_CATALOG) as HumanTagId[]).reduce<Record<HumanTagId, HumanTagCatalogEntry>>((result, tagId) => {
    const baseEntry = HUMAN_TAG_CATALOG[tagId];
    const translatedLabel = TAG_LABEL_TRANSLATIONS[language][tagId];
    const englishOverride = language === 'en' ? EN_TAG_COPY_OVERRIDES[tagId] : undefined;

    result[tagId] = {
      ...baseEntry,
      ...(genericCopy ?? {}),
      ...(englishOverride ?? {}),
      label: englishOverride?.label ?? translatedLabel,
    };

    return result;
  }, {} as Record<HumanTagId, HumanTagCatalogEntry>);
};
