import type { PointOfSaleLocale } from '../../translations';

const en = {
  title: 'Square payment recovery', help: 'Resolve this payment before charging again or choosing another method.', refresh: 'Refresh', recover: 'Recover payment', retry: 'Retry original request', cancel: 'Cancel payment', intent: 'Payment', notSent: 'not sent to Square yet', loading: 'Verifying Square payments…', loadError: 'Square recovery payments could not be loaded.', lookupError: 'The original Square request could not be verified. Keep it blocked and try again.', cancelError: 'The Square payment could not be cancelled.', differentDraft: 'The pending Square request belongs to a different sale. Restore that sale before retrying.', waiting: 'Payment request sent to Square Terminal. Waiting for the customer…', approved: 'Square payment approved and POS sale completed.', finalizing: 'Square approved the card. Completing the POS sale…', refundedReleased: 'Square confirms the payment was fully refunded. This register is released.', declined: 'Square Terminal declined the payment.', cancelled: 'Square Terminal payment was cancelled.', uncertain: 'Square payment is uncertain. Recover it before charging again.', timeout: 'Local wait ended. Verifying the payment with the backend…', recovering: 'Recovering the Square payment through the backend…', linked: 'Square payment and its POS receipt were recovered.', pending: 'Square Terminal payment is not approved yet.', recoveryError: 'Square Terminal payment could not be recovered.', fullCard: 'Square Terminal supports one full card payment for the current ticket.', chargeError: 'The Square Terminal payment could not be completed.', blocked: 'Resolve the pending Square payment before registering another payment.', blockedCharge: 'Resolve the pending Square payment before starting a new charge.', blockedSale: 'Resolve the pending Square payment before completing this sale.', blockedCash: 'Resolve the pending Square payment before registering cash.',
};
export type SquareTerminalRecoveryCopy = { [K in keyof typeof en]: string };
const es: SquareTerminalRecoveryCopy = {
  title: 'Recuperación de pagos Square', help: 'Resuelve este pago antes de volver a cobrar o elegir otro método.', refresh: 'Actualizar', recover: 'Recuperar pago', retry: 'Reintentar solicitud original', cancel: 'Cancelar pago', intent: 'Pago', notSent: 'aún no enviado a Square', loading: 'Verificando pagos Square…', loadError: 'No se pudieron cargar los pagos Square pendientes.', lookupError: 'No se pudo verificar la solicitud Square original. Mantenla bloqueada e inténtalo de nuevo.', cancelError: 'No se pudo cancelar el pago Square.', differentDraft: 'La solicitud Square pendiente pertenece a otra venta. Restaura esa venta antes de reintentar.', waiting: 'Solicitud enviada a Square Terminal. Esperando al cliente…', approved: 'Pago Square aprobado y venta POS completada.', finalizing: 'Square aprobó la tarjeta. Completando la venta POS…', refundedReleased: 'Square confirma que el pago fue reembolsado por completo. La caja queda liberada.', declined: 'Square Terminal rechazó el pago.', cancelled: 'Se canceló el pago Square Terminal.', uncertain: 'El resultado del pago Square es incierto. Recupéralo antes de volver a cobrar.', timeout: 'Terminó la espera local. Verificando el pago con el servidor…', recovering: 'Recuperando el pago Square mediante el servidor…', linked: 'Se recuperaron el pago Square y su comprobante POS.', pending: 'El pago Square Terminal aún no está aprobado.', recoveryError: 'No se pudo recuperar el pago Square Terminal.', fullCard: 'Square Terminal admite un pago completo con tarjeta para el ticket actual.', chargeError: 'No se pudo completar el pago con Square Terminal.', blocked: 'Resuelve el pago Square pendiente antes de registrar otro pago.', blockedCharge: 'Resuelve el pago Square pendiente antes de iniciar otro cobro.', blockedSale: 'Resuelve el pago Square pendiente antes de completar esta venta.', blockedCash: 'Resuelve el pago Square pendiente antes de registrar efectivo.',
};
const fr: SquareTerminalRecoveryCopy = {
  title: 'Récupération des paiements Square', help: 'Résolvez ce paiement avant de facturer à nouveau ou de changer de méthode.', refresh: 'Actualiser', recover: 'Récupérer le paiement', retry: 'Réessayer la demande initiale', cancel: 'Annuler le paiement', intent: 'Paiement', notSent: 'pas encore envoyé à Square', loading: 'Vérification des paiements Square…', loadError: 'Impossible de charger les paiements Square à récupérer.', lookupError: 'La demande Square initiale n’a pas pu être vérifiée. Gardez-la bloquée et réessayez.', cancelError: 'Le paiement Square n’a pas pu être annulé.', differentDraft: 'La demande Square en attente appartient à une autre vente. Restaurez cette vente avant de réessayer.', waiting: 'Demande envoyée au terminal Square. En attente du client…', approved: 'Paiement Square approuvé et vente POS terminée.', finalizing: 'Square a approuvé la carte. Finalisation de la vente POS…', refundedReleased: 'Square confirme le remboursement intégral du paiement. La caisse est libérée.', declined: 'Le terminal Square a refusé le paiement.', cancelled: 'Le paiement Square Terminal a été annulé.', uncertain: 'Le résultat du paiement Square est incertain. Récupérez-le avant de facturer à nouveau.', timeout: 'L’attente locale est terminée. Vérification auprès du serveur…', recovering: 'Récupération du paiement Square par le serveur…', linked: 'Le paiement Square et son reçu POS ont été récupérés.', pending: 'Le paiement Square Terminal n’est pas encore approuvé.', recoveryError: 'Le paiement Square Terminal n’a pas pu être récupéré.', fullCard: 'Square Terminal accepte un paiement intégral par carte pour le ticket actuel.', chargeError: 'Le paiement Square Terminal n’a pas pu être effectué.', blocked: 'Résolvez le paiement Square en attente avant d’enregistrer un autre paiement.', blockedCharge: 'Résolvez le paiement Square en attente avant une nouvelle facturation.', blockedSale: 'Résolvez le paiement Square en attente avant de terminer cette vente.', blockedCash: 'Résolvez le paiement Square en attente avant d’enregistrer des espèces.',
};
const pt: SquareTerminalRecoveryCopy = {
  title: 'Recuperação de pagamentos Square', help: 'Resolva este pagamento antes de cobrar novamente ou escolher outro método.', refresh: 'Atualizar', recover: 'Recuperar pagamento', retry: 'Repetir solicitação original', cancel: 'Cancelar pagamento', intent: 'Pagamento', notSent: 'ainda não enviado à Square', loading: 'Verificando pagamentos Square…', loadError: 'Não foi possível carregar os pagamentos Square pendentes.', lookupError: 'Não foi possível verificar a solicitação Square original. Mantenha-a bloqueada e tente novamente.', cancelError: 'Não foi possível cancelar o pagamento Square.', differentDraft: 'A solicitação Square pendente pertence a outra venda. Restaure essa venda antes de tentar novamente.', waiting: 'Solicitação enviada ao Square Terminal. Aguardando o cliente…', approved: 'Pagamento Square aprovado e venda POS concluída.', finalizing: 'A Square aprovou o cartão. Concluindo a venda POS…', refundedReleased: 'A Square confirmou o reembolso total. O caixa foi liberado.', declined: 'O Square Terminal recusou o pagamento.', cancelled: 'O pagamento Square Terminal foi cancelado.', uncertain: 'O resultado do pagamento Square é incerto. Recupere-o antes de cobrar novamente.', timeout: 'A espera local terminou. Verificando o pagamento no servidor…', recovering: 'Recuperando o pagamento Square pelo servidor…', linked: 'O pagamento Square e o recibo POS foram recuperados.', pending: 'O pagamento Square Terminal ainda não foi aprovado.', recoveryError: 'Não foi possível recuperar o pagamento Square Terminal.', fullCard: 'O Square Terminal aceita um pagamento integral por cartão no ticket atual.', chargeError: 'Não foi possível concluir o pagamento Square Terminal.', blocked: 'Resolva o pagamento Square pendente antes de registrar outro pagamento.', blockedCharge: 'Resolva o pagamento Square pendente antes de iniciar outra cobrança.', blockedSale: 'Resolva o pagamento Square pendente antes de concluir esta venda.', blockedCash: 'Resolva o pagamento Square pendente antes de registrar dinheiro.',
};
const ko: SquareTerminalRecoveryCopy = {
  title: 'Square 결제 복구', help: '다시 결제하거나 다른 방법을 선택하기 전에 이 결제를 해결하세요.', refresh: '새로 고침', recover: '결제 복구', retry: '원래 요청 다시 시도', cancel: '결제 취소', intent: '결제', notSent: '아직 Square로 전송되지 않음', loading: 'Square 결제 확인 중…', loadError: '복구할 Square 결제를 불러오지 못했습니다.', lookupError: '원래 Square 요청을 확인하지 못했습니다. 차단 상태를 유지하고 다시 시도하세요.', cancelError: 'Square 결제를 취소하지 못했습니다.', differentDraft: '대기 중인 Square 요청은 다른 판매에 속합니다. 다시 시도하기 전에 해당 판매를 복원하세요.', waiting: 'Square Terminal로 요청을 보냈습니다. 고객을 기다리는 중…', approved: 'Square 결제가 승인되고 POS 판매가 완료되었습니다.', finalizing: 'Square가 카드를 승인했습니다. POS 판매를 완료하는 중…', refundedReleased: 'Square에서 전액 환불을 확인했습니다. 계산대 차단이 해제되었습니다.', declined: 'Square Terminal이 결제를 거부했습니다.', cancelled: 'Square Terminal 결제가 취소되었습니다.', uncertain: 'Square 결제 결과를 알 수 없습니다. 다시 결제하기 전에 복구하세요.', timeout: '로컬 대기가 끝났습니다. 서버에서 결제를 확인하는 중…', recovering: '서버를 통해 Square 결제를 복구하는 중…', linked: 'Square 결제와 POS 영수증을 복구했습니다.', pending: 'Square Terminal 결제가 아직 승인되지 않았습니다.', recoveryError: 'Square Terminal 결제를 복구하지 못했습니다.', fullCard: 'Square Terminal은 현재 티켓의 카드 전액 결제 한 건을 지원합니다.', chargeError: 'Square Terminal 결제를 완료하지 못했습니다.', blocked: '다른 결제를 등록하기 전에 대기 중인 Square 결제를 해결하세요.', blockedCharge: '새 결제를 시작하기 전에 대기 중인 Square 결제를 해결하세요.', blockedSale: '이 판매를 완료하기 전에 대기 중인 Square 결제를 해결하세요.', blockedCash: '현금을 등록하기 전에 대기 중인 Square 결제를 해결하세요.',
};
const zh: SquareTerminalRecoveryCopy = {
  title: 'Square 付款恢复', help: '再次收费或选择其他方式前，请先处理此付款。', refresh: '刷新', recover: '恢复付款', retry: '重试原始请求', cancel: '取消付款', intent: '付款', notSent: '尚未发送到 Square', loading: '正在核实 Square 付款…', loadError: '无法加载待恢复的 Square 付款。', lookupError: '无法核实原始 Square 请求。请保持阻止状态并重试。', cancelError: '无法取消 Square 付款。', differentDraft: '待处理的 Square 请求属于另一笔销售。重试前请恢复该销售。', waiting: '请求已发送到 Square Terminal。正在等待客户…', approved: 'Square 付款已批准，POS 销售已完成。', finalizing: 'Square 已批准银行卡。正在完成 POS 销售…', refundedReleased: 'Square 已确认全额退款，收银台现已解除占用。', declined: 'Square Terminal 已拒绝付款。', cancelled: 'Square Terminal 付款已取消。', uncertain: 'Square 付款结果不确定。再次收费前请恢复付款。', timeout: '本地等待已结束。正在通过服务器核实付款…', recovering: '正在通过服务器恢复 Square 付款…', linked: '已恢复 Square 付款及其 POS 收据。', pending: 'Square Terminal 付款尚未批准。', recoveryError: '无法恢复 Square Terminal 付款。', fullCard: 'Square Terminal 支持当前票据的一笔全额银行卡付款。', chargeError: '无法完成 Square Terminal 付款。', blocked: '登记其他付款前，请先处理待完成的 Square 付款。', blockedCharge: '开始新的收费前，请先处理待完成的 Square 付款。', blockedSale: '完成此销售前，请先处理待完成的 Square 付款。', blockedCash: '登记现金前，请先处理待完成的 Square 付款。',
};
export const squareTerminalRecoveryCopyByLocale: Record<PointOfSaleLocale, SquareTerminalRecoveryCopy> = {
  'en-CA': en, 'en-US': en, 'es-MX': es, 'es-CO': es,
  'fr-CA': fr, 'pt-BR': pt, 'ko-CA': ko, 'zh-CA': zh,
};
