export const esMXIncentiveForm = {
  title: 'Agregar incentivo', description: 'Registra una percepción que se aplicará a la siguiente corrida.', saving: 'Guardando…', save: 'Guardar incentivo', cancel: 'Cancelar', allEmployeesSummary: 'Se aplicará a todo el personal activo.', selectedEmployeesSummary: (count: number) => `${count} colaboradores seleccionados.`, incentiveSection: 'Incentivo', name: 'Nombre del incentivo', namePlaceholder: 'Ej. Bono por puntualidad', status: 'Estado', statuses: { active: 'Activo', scheduled: 'Programado', paused: 'Pausado' }, amount: 'Monto', amountPlaceholder: 'Ej. 1500', currency: 'Divisa', effectiveDate: 'Fecha de aplicación', descriptionLabel: 'Concepto', descriptionPlaceholder: 'Detalle interno del incentivo', employees: 'Colaboradores', allActiveEmployees: 'Todo el personal activo', searchPlaceholder: 'Buscar colaborador, puesto o unidad', noPosition: 'Sin puesto', noUnit: 'Sin unidad',
} as const;

export const frCAIncentiveForm = {
  title: 'Ajouter un incitatif', description: 'Enregistrez une rémunération qui sera appliquée à la prochaine paie.', saving: 'Enregistrement…', save: 'Enregistrer l’incitatif', cancel: 'Annuler', allEmployeesSummary: 'Il sera appliqué à tous les employés actifs.', selectedEmployeesSummary: (count: number) => `${count} employés sélectionnés.`, incentiveSection: 'Incitatif', name: 'Nom de l’incitatif', namePlaceholder: 'Ex. Prime d’assiduité', status: 'Statut', statuses: { active: 'Actif', scheduled: 'Planifié', paused: 'En pause' }, amount: 'Montant', amountPlaceholder: 'Ex. 1500', currency: 'Devise', effectiveDate: 'Date d’application', descriptionLabel: 'Description', descriptionPlaceholder: 'Détails internes de l’incitatif', employees: 'Employés', allActiveEmployees: 'Tous les employés actifs', searchPlaceholder: 'Rechercher un employé, un poste ou une unité', noPosition: 'Aucun poste', noUnit: 'Aucune unité',
} as const;

export const ptBRIncentiveForm = {
  title: 'Adicionar incentivo', description: 'Registre um provento que será aplicado à próxima folha.', saving: 'Salvando…', save: 'Salvar incentivo', cancel: 'Cancelar', allEmployeesSummary: 'Será aplicado a todos os colaboradores ativos.', selectedEmployeesSummary: (count: number) => `${count} colaboradores selecionados.`, incentiveSection: 'Incentivo', name: 'Nome do incentivo', namePlaceholder: 'Ex.: Bônus de pontualidade', status: 'Status', statuses: { active: 'Ativo', scheduled: 'Programado', paused: 'Pausado' }, amount: 'Valor', amountPlaceholder: 'Ex.: 1500', currency: 'Moeda', effectiveDate: 'Data de aplicação', descriptionLabel: 'Descrição', descriptionPlaceholder: 'Detalhe interno do incentivo', employees: 'Colaboradores', allActiveEmployees: 'Todos os colaboradores ativos', searchPlaceholder: 'Buscar colaborador, cargo ou unidade', noPosition: 'Sem cargo', noUnit: 'Sem unidade',
} as const;

export const koCAIncentiveForm = {
  title: '인센티브 추가', description: '다음 급여 실행에 적용할 수당을 등록합니다.', saving: '저장 중…', save: '인센티브 저장', cancel: '취소', allEmployeesSummary: '모든 활성 직원에게 적용됩니다.', selectedEmployeesSummary: (count: number) => `직원 ${count}명 선택됨.`, incentiveSection: '인센티브', name: '인센티브 이름', namePlaceholder: '예: 출근 보너스', status: '상태', statuses: { active: '활성', scheduled: '예약됨', paused: '일시 중지' }, amount: '금액', amountPlaceholder: '예: 1500', currency: '통화', effectiveDate: '적용일', descriptionLabel: '설명', descriptionPlaceholder: '인센티브 내부 세부 정보', employees: '직원', allActiveEmployees: '모든 활성 직원', searchPlaceholder: '직원, 직책 또는 단위 검색', noPosition: '직책 없음', noUnit: '단위 없음',
} as const;

export const zhCAIncentiveForm = {
  title: '添加激励', description: '记录将在下一次工资运行中应用的收入项目。', saving: '正在保存…', save: '保存激励', cancel: '取消', allEmployeesSummary: '将应用于所有在职员工。', selectedEmployeesSummary: (count: number) => `已选择 ${count} 名员工。`, incentiveSection: '激励', name: '激励名称', namePlaceholder: '例如：全勤奖', status: '状态', statuses: { active: '启用', scheduled: '已计划', paused: '已暂停' }, amount: '金额', amountPlaceholder: '例如：1500', currency: '币种', effectiveDate: '应用日期', descriptionLabel: '说明', descriptionPlaceholder: '激励内部说明', employees: '员工', allActiveEmployees: '所有在职员工', searchPlaceholder: '搜索员工、职位或单位', noPosition: '无职位', noUnit: '无单位',
} as const;
